### ISSUE TITLE
Support for secrets in fluent-bit config

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10018]
**Description**

At the moment there is no simple way to have the passwords for the http/elasticsearch or even extra config to be stored in a secret.

Fluent-bit provides a nice way of using placeholders in the config which will get replaced at runtime by environment variables, see https://docs.fluentbit.io/manual/administration/configuring-fluent-bit/variables

To avoid having specific solutions to the http/es plugins only and instead have a generic approach, I suggest the following idea:

1. Introduce config options to specify secret pairs:
```
conf:
  secrets:
    MY_ES_PASSWD: "1234!"
    MY_HTTP_PASSWD: "321r"
    MY_EXTRA_PASSWD: "321r"
```
2. Use them in your config in the fluent-bit style:
```
  backend:
    es:
      http_user: "myUserName"
      http_passwd: "${MY_ES_PASSWD}"
    http:
      http_user: "myUserName"
      http_passwd: "${MY_HTTP_PASSWD}"
  extra: |
    [OUTPUT]
        Name              http
        Match             *
        HTTP_User        myUserName
        HTTP_Passwd      ${MY_EXTRA_PASSWD}
```
3. Render all secret pairs into one new kubernetes secret
```
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: logging-flluent-bit-config
data:
    MY_ES_PASSWD: xxx
    MY_HTTP_PASSWD: xxx
    MY_EXTRA_PASSWD: xxx
```
4. Mount that secret as env variables into the daemonset:
```
spec:
  containers:
  - name: fluent-bit
    image: xxx
    env:
      - name: MY_ES_PASSWD
        valueFrom:
          secretKeyRef:
            name: logging-flluent-bit-config
            key: MY_ES_PASSWD
      - name: SECRET_PASSWORD
        valueFrom:
          secretKeyRef:
            name: logging-flluent-bit-config
            key: MY_HTTP_PASSWD
      - name: MY_EXTRA_PASSWD
        valueFrom:
          secretKeyRef:
            name: logging-flluent-bit-config
            key: MY_EXTRA_PASSWD
```

With that you can easily populate secrets as env variables into the fluent-bit container and just use them as values in your config.

**Reasons**
Secrets should only be stored in kubernetes secrets

**Attachments**
