### ISSUE TITLE
Redesign of fluent-bit configuration improving usabilities of shipped logs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10089]
**Description**

Major goal of the logging component is to ship logs of system and workload components to different logging backends in a way that they are most queryable in that backend.
A challenge with kyma is the heterogenousy of log formats. Every workload (or system component) is logging in a different format. Using the kubernetes filter, it will parse JSON documents only on-demand (so you can mix plain text and JSON). However, shipping the differnet log types to a stack like ELK, different JSON formats are even a bigger problem as the JSON attribute types must be of the same type for an successful indexing.
With that, by default JSON documents should not be parsed and shipped as plain text log to the different backend systems as we simply cannot give any guarantees on the formats.

That situation we can improve by introducing a well-defined best practice log format and giving a chance to workloads to be conform to that format. Having then an additional filter applied in fluent-bit will enable us to send well-formed logs for known applications to the backend, while everything else gets shipped as plain text.
That should be the case for system components. A custom workload should have the chance to participate in that as well but also to define easy it's own format and enable shipping for it.

In order to achieve it the current fluent-bit chart needs a redesign as it is not flexible enough. Further points with current config approach is:
- Not all features of the standard plugins are configurable via values.yaml
- You can mix-match the output plugins via the tags to different inputs, but there is no flexibility on having various inputs nor filter combinations (only way to introduce custom inputs or filters is via one extra.conf, sometimes you want to have multiple even)
- The kubernetes filter plugin should be configured differently dependent on the output and/or input

Goal:
- come up with a new config format which is flexible to configure (fixing the points above) but brings a very good default out-of-the-box
- The default should cover already the discussed option to process and ship logs coming from workloads with a well-defined format
- The config should not be dependent on the "overrides" limitation, assume full values.yaml expressiveness as planned to be introduced soon

**Reasons**

**Attachments**

**Comment by suleymanakbas91** [comment]
With https://github.com/kyma-project/kyma/pull/10284, I've refactored the chart and made it very similar to the upstream chart. I've also added new configuration options (config.parsers.additional, config.filters.additional, etc.) to enable passing extra configuration options to each part of the config file. 

As an example, I pass this overrides file to a Kyma installation: 

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    installer: overrides
    component: logging
    kyma-project.io/installation: ""
  name: logging-overrides
  namespace: kyma-installer
data:
  fluent-bit.config.parsers.additional: |
    [PARSER]
        Name                service-manager-proxy
        Format              regex
        Regex               time="(?<time>[^ ]*)" level=(?<level>[^ ]*) msg="(?<msg>[^ ].*)" component="(?<component>[^ ].*)" correlation_id=(?<correlation_id>[^ ].*) 
  fluent-bit.config.filters.additional: |
    [FILTER]
        Name                parser
        Match               loki.*service-manager-proxy*
        Key_Name            log
        Parser              service-manager-proxy
        Reserve_Data        True
```

It introduces a custom Parser I created for Service Manager Proxy logs and a filter which applies the parser to the Pods with the name `service-manager-proxy`. 

As a result, all the field of the logs are parsed correctly:

![Screenshot 2021-01-07 at 13 36 28](https://user-images.githubusercontent.com/5543238/103893356-7e37f600-50ed-11eb-83de-fc10b61d07c8.png)
