### ISSUE TITLE
APIRule does not re-check conflicting virtualservices 

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#10146]
**Description**
I created an APIRule on a subdomain which was already taken by a virtualservice resource.
The resulting status of the APIRule was very understandable like that:

```
status:
  APIRuleStatus:
    code: ERROR
    desc: 'Validation error: Attribute ".spec.service.host": This host is occupied
      by another Virtual Service'
  accessRuleStatus:
    code: SKIPPED
  lastProcessedTime: "2020-12-06T09:08:14Z"
  observedGeneration: 1
  virtualServiceStatus:
    code: SKIPPED
```
So I deleted the existing virtualservice as I simply forgot about it. Now I would expect that the APIRule gets healthy. Instead it stays like that forever.

**Expected result**
APIRule gets healthy after conflicting virtualservice got resolved.

**Actual result**
APIRule stays in the same status and does not get effective

**Steps to reproduce**
Have an virtualservice with the same subdomain before you create an APIRule

**Troubleshooting**
Re-create the APIRule after the virtualservice got deleted
