### ISSUE TITLE
Console backend needs ingress certificate from apiserver-proxy

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#10246]
**Description**

**Expected result**
Console backend does not require an ingress certificate from apiserver-proxy to work.

**Actual result**
Certificate is expected and components startup fails.

**Steps to reproduce**
- Create a k3d cluster.
- Install kyma with the following overrides:
```yaml
global:
  isLocalEnv: false
  ingress:
    domainName: local.kyma.dev
  environment:
    gardener: false
  domainName: local.kyma.dev
```

**Troubleshooting**
worked around it by adding the following chart to the installation (although this should not be done this way):
https://github.com/kyma-incubator/local-kyma/tree/main/ingress-dns-cert
