### ISSUE TITLE
Core: requires certificate from apiserver-proxy on k3d

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#10249]
**Description**
The core component requires a certificate issued by the `apiserver-proxy` which should not be mandatory.
The relevant part of the chart expects certificate information given as global values:
```yaml
{{ if not .Values.global.environment.gardener }}
apiVersion: v1
data:
  "key": {{ .Values.global.ingress.tlsKey }}
  "cert": {{ .Values.global.ingress.tlsCrt }}
kind: Secret
metadata:
  name: {{ .Values.global.istio.gateway.name }}-certs
  namespace: istio-system
type: Opaque
{{ end }}
```
The error displayed is as follows:
```
Error deploying core: Error: Failed to install core within the configured time. Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: unknown object type "nil" in Secret.data.key
```

**Expected result**
Core component installs on k3d without problems.

**Actual result**
The before described error appears.

**Steps to reproduce**
- Create a k3d cluster.
- Install kyma with the following overrides:
```yaml
global:
  isLocalEnv: false
  ingress:
    domainName: local.kyma.dev
  environment:
    gardener: false
  domainName: local.kyma.dev
```

**Troubleshooting**
worked around it by adding the following chart to the installation (although this should not be done this way):
https://github.com/kyma-incubator/local-kyma/tree/main/ingress-dns-cert
