### ISSUE TITLE
API Rule with mutators section set to Allow does not work

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#10322]
**Description**

According to the current `API Gateway` documentation in order to expose a service by creating an `APIRule CR` we can make use of an yaml example that is presented in this section - https://kyma-project.io/docs/components/api-gateway#tutorials-expose-a-service
Unfortunately, it turns out that if you set an `Allow` in mutators section then `APIRule` will not be applied properly and results in _Resource not found_ error after trying to access the exposed resource.

Found in the latest Kyma v1.18 release.

**Expected result**

- including `mutators` section with `Allow` set should not crash `API Rule`
- hint in documentation should be present to inform not to use `mutators` section when using `Allow` access strategy

**Actual result**

For now such error is presented:
```{"error":{"code":404,"status":"Not Found","request":"(code)","message":"The requested resource could not be found"}}```

**Steps to reproduce**

Try to apply a new API Rule using following schema: (example is being taken straight from docs, please check the link above)
```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: httpbin
spec:
  service:
    host: httpbin.$DOMAIN
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: allow
      mutators:
        - handler: allow
    - path: /post
      methods: ["POST"]
      accessStrategies:
        - handler: allow
      mutators:
        - handler: allow
```

**Troubleshooting**

It looks like `Allow` access strategy is not being supported by the Oathkeeper under the hood - it does not recognise 
Removing `mutators` section completely makes the API Rule work. On basis of example present before, this should work:
```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: httpbin
spec:
  service:
    host: httpbin.$DOMAIN
    name: httpbin
    port: 8000
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: allow
    - path: /post
      methods: ["POST"]
      accessStrategies:
        - handler: allow
```
