### ISSUE TITLE
Function UI: secrets not visible with the key

### ISSUE THREAD

**Issue by tehret77** [kyma-project/kyma#10394]
**Description**

When open a function the assigned secrets are not visible with the key (not the secret itself).

**Expected result**
In Kyma version 1.10 the key of the secret was shown in the list of environment variables and I expected to see the same behaviour in newer versions.

**Actual result**
The key value of a secret is not shown in the environment variables list.

**Steps to reproduce**

create a crd of kind function.serverless.kyma-project.io

```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    app: <some name>
    version: <some version>
  name: <some name>
  namespace: <some namespace>
spec:
  env:
  - name: SOME_SECRET_USED_IN_FUNCTION
    valueFrom:
      secretKeyRef:
        key: function_secret
        name: secret_key
  maxReplicas: 1
  minReplicas: 1
  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 100Mi
  runtime: nodejs10
  source: <>
```
