### ISSUE TITLE
Path in APIRule CRD does not accept /(slash)

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10460]
**Description**

Tha path is using this regex(`pattern: ^/([0-9a-zA-Z./*]+)`) which does not accept `/`. 

The change happened in this [PR](https://github.com/sayanh/kyma/commit/50bbaa55c69e5e46dcecf994ac90dafefee41c05#diff-1cae59d645bf61139d7e56b721b92f865d4a2d064e08026f5598adf8963b26c4L436)

**Expected result**

The path should accept slash in the path.

**Actual result**

Sample API Rule which fails:
```

apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: test
  namespace: test
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
  - accessStrategies:
    - handler: oauth2_introspection
    methods:
    - POST
    - OPTIONS
    path: "/"
  service:
    host: web-7rsedmimr7.berkan-skr-beb-test.test.kyma-project.dev
    name: test
    namespace: test
    port: 80
EOF

The APIRule "test" is invalid: spec.rules.path: Invalid value: "": spec.rules.path in body should match '^/([0-9a-zA-Z./*]+)'
```
