### ISSUE TITLE
Function deployment not ready in gke-upgrade tests

### ISSUE THREAD

**Issue by tgorgol** [kyma-project/kyma#10731]
**Description**

Sometimes the Function Deployment exceeds the progression timeout in `execute-serverlessupgradetest` test (part of `post-master-kyma-gke-upgrade` job) which results in a failed test run.

Example prow job logs: https://storage.googleapis.com/kyma-prow-logs/logs/post-master-kyma-gke-upgrade/1364190741638680576/build-log.txt

Error:

```yaml
Deployment e2e-upgrade-fnc-fm9j6 failed with condition: 
- type: Available
  status: "False"
  lastupdatetime: "2021-02-23T13:10:42Z"
  lasttransitiontime: "2021-02-23T13:10:42Z"
  reason: MinimumReplicasUnavailable
  message: Deployment does not have minimum availability.
- type: Progressing
  status: "False"
  lastupdatetime: "2021-02-23T13:20:43Z"
  lasttransitiontime: "2021-02-23T13:20:43Z"
  reason: ProgressDeadlineExceeded
  message: ReplicaSet "e2e-upgrade-fnc-fm9j6-68cc6b477" has timed out progressing.
```
GCP logs: https://cloudlogging.app.goo.gl/VbV2ZuJpxun1JFKr9

**Expected result**

Function Deployment should be ready and the test should succeed.

**Actual result**

Deployment failed.
