### ISSUE TITLE
Add security context for ORY deployments

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#10790]
**Description**

Define security context for all ORY compoenents:
```
securityContext:
  allowPrivilegeEscalation: false
  privileged: false
  runAsGroup: 65534
  runAsNonRoot: true
  runAsUser: 65534
```  

**Reasons**

Kyma should not run privileges containers

**Attachments**

see https://github.tools.sap/kyma/backlog/issues/1197
