### ISSUE TITLE
Report the actual cleaned event-type list in the Kyma Subscription custom resource

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#10814]
**Description**

The Eventing controllers (eventing-controller-nats and eventing-controller), are  creating NATS Subjects and Webhooks (respectively) with clean names (more info: https://github.com/kyma-project/kyma/issues/10218). 

**Subscription**

```yaml
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: somename
  namespace: somenamespace
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: somesource
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.my-first-app.order.created.v1
    - eventSource:
        property: source
        type: exact
        value: somesource
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.my-second-app.order.updated.v1
  protocol: "any"
  protocolsettings: {}
  sink: http://someservice.somenamespace.svc.cluster.local
```

**Ideas**

- Report the actual cleaned event-type list in the Kyma Subscription status sub-resource.
