### ISSUE TITLE
Same event types in multiple filters in a single subscription is broken 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#10936]
**Description**

When there are multiple event.types with same value in a single subscription, the system behaves strangely.
Currently, the system assumes that there are unique event-types in the filters array of a subscription, which may not be the case.

**Expected result**

No matter how many times the event types are repeated in a subscription, the event should be delivered once and when the subscription is deleted the consequent events should not reach the subscriber.

**Actual result**

- An event is delivered multiple times for a single occurence.
- Deletion of the complete subscription does not mean deletion of each nats subscription.

**Steps to reproduce**
 - create a NATS based cluster

- Sample subscription to reproduce the issue:
```
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: function-amazing-tomasz1-subscription
  namespace: testme
spec:
  filter:
    dialect: NATS100
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.test.order.created.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.test.order.created.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.test.order.created.v1
  protocol: NATS
  protocolsettings:
    exemptHandshake: true
    qos: AT-LEAST-ONCE
    webhookAuth:
      clientId: ""
      clientSecret: ""
      grantType: ""
      tokenUrl: ""
      type: ""
  sink: http://function-amazing-tomasz1.testme.svc.cluster.local
status:
  conditions:
  - lastTransitionTime: "2021-03-22T00:45:02Z"
    reason: NATS Subscription active
    status: "True"
    type: Subscription active
  emsSubscriptionStatus: {}
  ready: true
```
- Delete the subscription

**Troubleshooting**

- Kyma version `b6598d2c7949d3a71f92d69738aa085027f1864f`
