### ISSUE TITLE
Prometheus PVC name too long, longer than 63 characters

### ISSUE THREAD

**Issue by bbroniewski** [kyma-project/kyma#11018]
**Description**

During installation of Kyma in version 1.20 when prometheus is requesting PV, provisioning is failing because of too long name used in pvc.

```shell
name: prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0
```

**System**
-Ubuntu Server 20.04
-On-premise
-Kernel version 5.4.0-70-generic
-Kyma 1.20
-Openebs cStor

**Expected result**
PVC name should be shorter not having "prometheus" repeated 4 times.

**Actual result**
PVC name is too long causing fail of PV provisioning.

**Steps to reproduce**

Start kyma installation in version 1.20.

**Troubleshooting**
```shell
kubectl -n openebs describe cstorvolumeconfig pvc-6bf18bf2-e29c-48c1-917b-c4414f88fa51
Warning  Provisioning  2m28s (x87 over 37m)  cstorvolumeclaim-controller  CStorVolume.cstor.openebs.io "pvc-6bf18bf2-e29c-48c1-917b-c4414f88fa51" is invalid: metadata.labels: Invalid value: "prometheus-monitoring-prometheus-db-prometheus-monitoring-prometheus-0": must be no more than 63 characters
```

**Comment by bbroniewski** [comment]
Is it Openebs architecture issue, because they are using name in labels? How can I fix that? I found possible solution wih modification of values.yaml:
```yaml
prometheus:
  prometheusSpec:
    replicas: 1
    storageSpec:
      volumeClaimTemplate:
        metadata:
          name: data
        spec:
```

Is it possible to adjust it during the installation or I need to restart installation after values.yaml modification?

**Comment by tobiscr** [comment]
@rakesh-garimella : can you please have a look. THX in advance!

**Comment by rakesh-garimella** [comment]
Hi @bbroniewski this is a known issue check [here](https://github.com/helm/charts/issues/13170)

you can leverage the override files as mentioned [here](https://kyma-project.io/docs/components/tracing/#troubleshooting-jaeger-shows-only-a-few-traces-create-an-override) and one can use it while installing as following
```
kyma install --override {OVERRIDE_FILE_PATH}
```

an example override you can try is following
```yaml
apiVersion: v1
data:
  prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata.name: data
kind: ConfigMap
metadata:
  labels:
    component: monitoring
    installer: overrides
  name: monitoring-overrides
  namespace: kyma-installer
```

For the upgrade you can use the same file then
```
kyma upgrade --override {OVERRIDE_FILE_PATH}
```
Although in this case you would need to delete the previous PVC and the statefuls set as its a known issue

**Comment by bbroniewski** [comment]
Hi, thank you.

I fixed it using config map:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: monitoring
    kyma-project.io/installation: ""
data:
  prometheus.prometheusSpec.storageSpec.volumeClaimTemplate.metadata.name: "data"
```
