### ISSUE TITLE
Installation refactoring caused critical issue with missing ResourceQuota and LimitRange for kyma-system namespace

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1105]
found by: https://github.com/kyma-project/kyma/issues/814

**Issue:**
When refactoring/removing cluster-prerequisites, RQ and LR for kyma-system was moved to core helm chart/release. Then introducing:
```
spec:
  version: "__VERSION__"
  url: "__URL__"
  components: 
    - name: "cluster-essentials"
      namespace: "kyma-system"
    - name: "istio"
      namespace: "istio-system"
    - name: "prometheus-operator"
      namespace: "kyma-system"
    - name: "provision-bundles"
    - name: "dex"
      namespace: "kyma-system"
    - name: "core"
      namespace: "kyma-system"
    - name: "remote-environments"
      namespace: "kyma-integration"
      release: "ec-default"
    - name: "remote-environments"
      namespace: "kyma-integration"
      release: "hmc-default"
```
Caused that in our current kyma installation setup, all helm releases for kyma-system before core don't have RQ and LR provided.

**Solution**:
Move kyma-system RQ and LR to "cluster-essentials" chart.
