### ISSUE TITLE
Script to connect a local grafana to a kyma cluster

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#11103]
**Description**
Instead of deploying Grafana to every cluster, you could have an instance running on demand locally and connect it via port-forwarding is to setup a local grafana and connect it to a cluster via port-forwarding.

Let's do a spike proofing the idea.

AC:
- Have a script or something else which will download/install/startup a grafana instance local
- Grafana has two datasources for prometheus and loki configured
- The datasources are using current kubeconfig to connect to a cluster (via port-forwarding)
- You can explore the logs and metrics

**Reasons**

**Attachments**

**Comment by rakesh-garimella** [comment]
Following steps needs to be followed:
```
curl -O https://dl.grafana.com/oss/release/grafana-7.5.4.darwin-amd64.tar.gz
tar -zxvf grafana-7.5.4.darwin-amd64.tar.gz

# Copy the datasource file
cp datasource.yaml conf/provisioning/datasources
# Enable autonomous mode
export GF_AUTH_ANONYMOUS_ENABLED="true"
# Change role to Admin
export GF_AUTH_ANONYMOUS_ORG_ROLE="Admin"

# start the binary
./bin/grafana-server web
```

The `datasource.yaml` can be following:
```
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Loki
  - name: Prometheus

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: "http://127.0.0.1:3100"
    jsonData:
      maxLines: 1000
  - name: Prometheus
    type: prometheus
    access: proxy
    url: "http://127.0.0.1:9090/"
    isDefault: true

```
