### ISSUE TITLE
Fix Velero tutorial

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-project/kyma#11129]
**Description**

[This tutorial](https://kyma-project.io/docs/root/kyma#tutorials-restore-resources-using-velero) actually aimed to show how to take backup using Velero, but the title and the introduction are misleadingly saying it is for restoring. Also, there have been many new versions of Velero CLI since we wrote this doc, so the commands may not be up-to-date. We should go through the tutorial and fix the misleading parts.

We can also consider providing instructions for both taking backup and restoring from backup.

**Comment by suleymanakbas91** [comment]
Another point is that, there is already VolumeSnapshotClass deployed on Gardener clusters by default. So, we can delete that part from the tutorial. These default classes are not annotated as default though. That's why we need to specify the class name in the VolumeSnapshot definition like this:

```yaml
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshot
metadata:
  name: snapshot
spec:
  volumeSnapshotClassName: default
  source:
    persistentVolumeClaimName: {PVC_NAME}
```
