### ISSUE TITLE
CORS allowMethods missing methods configured in API rule

### ISSUE THREAD

**Issue by SVendittelli** [kyma-project/kyma#11126]
**Description**

After configuring an API rule with a PATCH method, browser PATCH requests would fail due to CORS error:  `PATCH is not allowed by Access-Control-Allow-Methods in preflight response`. Further investigation revealed that the associated istio virtual-service configuration was missing the `PATCH` in the `allowMethods` array.

```yaml
spec:
  ...
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      # Note the missing PATCH here
      allowOrigins:
      - regex: .*
    match:
    - uri:
        regex: /v1/.*
  ...
```

Adding this manually resolved the issue. Note it needed to be manually added to all of the relevant paths.

**Expected result**

Expected that the methods configured in the API rule would be allowed by CORS in the virtual service.

**Actual result**

The configured methods were missing from the vs.

**Steps to reproduce**

1. Create a service pointing to a deployment that will accept a patch request
2. Configure an API rule for that service which accepts the PATCH method
3. Make a PATCH request from a browser and observe the request is blocked due to CORS policy

**Troubleshooting**

GET, POST, PUT, and DELETE calls were all successful but PATCH calls were blocked.
