### ISSUE TITLE
alertmanager component secret override functionality does not allow custom alertmanager.yaml file

### ISSUE THREAD

**Issue by dapus123** [kyma-project/kyma#11147]
**Description**

If user wants to add a custom secret configuration for alertmanager.yaml as below example:
```
apiVersion: v1
kind: Secret
metadata:
 name: monitoring-config-overrides
 namespace: kyma-installer
 labels:
    kyma-project.io/installation: ""
    installer: overrides
    component: monitoring
type: Opaque
stringData:
  alertmanager.yaml: |-
    global:
      resolve_timeout: 5m
      # The smarthost and SMTP sender used for mail notifications.
      ...
      etc all user would want 
      ...
```

**Reasons**

configuring smtp and different receivers, routes, rules on single one place

**Comment by a-thaler** [comment]
Hi @dapus123,

your description is a bit confusing as it seems you are missing up deploying a secret for the alertmanager and configuring overrides for the monitoring component.
So mainly you want to have a custom alertmanager setup. This you can configure via kyma overrides for the monitoring chart. So you could try to set specific setting from this block: https://github.com/kyma-project/kyma/blob/bc4ba16a8452aa40144d78bdf85afcff3e677967/resources/monitoring/values.yaml#L184 Here, you will face soon limitations as the overrides are not supporting arrays.

So indeed the better way is to provide your own alertmanager config. For that you can configure to bring your own secret by setting this flag: https://github.com/kyma-project/kyma/blob/bc4ba16a8452aa40144d78bdf85afcff3e677967/resources/monitoring/values.yaml#L416
Then you can just deploy your own secret using the correct name. But that secret would not require any override labelling.

Summarized, configure an override:
```
apiVersion: v1
kind: ConfigMap
metadata:
 name: monitoring-config-overrides
 namespace: kyma-installer
 labels:
    kyma-project.io/installation: ""
    installer: overrides
    component: monitoring
data:
  alertmanager.alertmanagerSpec.useExistingSecret: true
```

Then deploy your custom secret for the alertmanager:
```
apiVersion: v1
kind: Secret
metadata:
 name: alertmanager-monitoring-alertmanager
 namespace: kyma-system
 labels:
    app: monitoring-alertmanager
type: Opaque
stringData:
  alertmanager.yaml: |-
...
```
