### ISSUE TITLE
Unify labels logic between the Kyma Cli and the Console

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#11155]
**Description**

There is a different meaning of labels between the console and the Kyma Cli and this should be unified. Labels provided using console UI are added to the `metadata.labels` map (which are propagated to the deployment, building job and service) but labels provided using the cli are added to the `spec.labels` (which are propagated to the pod)

**Example**

**1. Function with labels created using the console:**
![Screenshot 2021-04-20 at 15 36 43](https://user-images.githubusercontent.com/28900355/115407191-1d41b300-a1f0-11eb-9df1-53f24cebc9a4.png)

**2. Sync this function using Cli and add other labels (we can't see previously added labels here):**
![Screenshot 2021-04-20 at 15 38 20](https://user-images.githubusercontent.com/28900355/115407221-229efd80-a1f0-11eb-8520-d1cb4131dd5b.png)

**3. This same function after update using cli:**
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    consoleanotherlabel: "2"
    consolelabel: "1"
<...>
spec:
  labels:
    clianotherlabel: "2"
    clilabel: "1"
<...>
```
