### ISSUE TITLE
Strange reconcile() error in BEB Subscription Controller

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11166]
**Description**

During the tests on Eventing/BEB using the new unified controller from https://github.com/kyma-project/kyma/pull/11156 ,
the following error regarding the removing of finalizers happened:

```yaml
{
   "level": "error",
   "ts": 1.61902042E9,
   "logger": "controller",
   "msg": "Reconciler error",
   "reconcilerGroup": "eventing.kyma-project.io",
   "reconcilerKind": "Subscription",
   "controller": "subscription",
   "name": "test",
   "namespace": "themue-test",
   "error": "error while removing Finalizer with name: eventing.kyma-project.io: Operation cannot be fulfilled on subscriptions.eventing.kyma-project.io \"test\": StorageError: invalid object, Code: 4, Key: /registry/eventing.kyma-project.io/subscriptions/themue-test/test, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e788ff19-2351-41fd-8f5c-3109d7a4e6b1, UID in object meta: ",
   "errorVerbose": "Operation cannot be fulfilled on subscriptions.eventing.kyma-project.io \"test\": StorageError: invalid object, Code: 4, Key: /registry/eventing.kyma-project.io/subscriptions/themue-test/test, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: e788ff19-2351-41fd-8f5c-3109d7a4e6b1, UID in object meta: \nerror while removing Finalizer with name: eventing.kyma-project.io\ngithub.com/kyma-project/kyma/components/eventing-controller/reconciler/subscription.(*Reconciler).removeFinalizer\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/reconciler/subscription/reconciler.go:941\ngithub.com/kyma-project/kyma/components/eventing-controller/reconciler/subscription.(*Reconciler).Reconcile\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/reconciler/subscription/reconciler.go:166\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:235\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1373",
   "stacktrace": "github.com/go-logr/zapr.(*zapLogger).Error\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/github.com/go-logr/zapr/zapr.go:132\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:237\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:209\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:188\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155\nk8s.io/apimachinery/pkg/util/wait.BackoffUntil\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156\nk8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\nk8s.io/apimachinery/pkg/util/wait.Until\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90"
}
```
