### ISSUE TITLE
Failed to create namespace `kyma-integration` during Upgrade

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#11469]
**Description**
When upgrading Kyma using the `alpha deploy` command, the upgrade fails due to the reason it cannot create the namespace `kyma-integration`. 

**Expected result**
Upgrade succeeds without any problems.

**Actual result**
Upgrade failed since the namespace `kyma-integration` is not able to be created, thus some resources which are bound to this namespace cannot be created.
This scenario comes up if you install/upgrade Kyma with components that are not installed in the `kyma-integration` namespace.
```
Error deploying prerequisite: cluster-essentials: Error: Failed to deploy cluster-essentials within the configured time. Error: failed to create resource: namespaces "kyma-integration" not found
Error: Error deploying prerequisite: cluster-essentials: Error: Failed to deploy cluster-essentials within the configured time. Error: failed to create resource: namespaces "kyma-integration" not found
```

**Steps to reproduce**
- Kyma components file:
```
defaultNamespace: kyma-system
prerequisites:
  - name: "cluster-essentials"
  - name: "istio"
    namespace: "istio-system"
  - name: "certificates"
    namespace: "istio-system"
components:
  - name: "logging"
  ```

- Provision cluster on k3s
` ./bin/kyma-darwin alpha provision k3s`
- Deploy kyma which local sources:
` ./bin/kyma-darwin alpha deploy --source=local`
- Upgrade kyma which local sources:
` ./bin/kyma-darwin alpha deploy --source=local`

**Troubleshooting**
