### ISSUE TITLE
Pod cluster-essentials-migrate-xxx gets stuck in ContainerCreating

### ISSUE THREAD

**Issue by jeremyharisch** [kyma-project/kyma#11471]
**Description**
When upgrading a kyma cluster, the following pod remains in Status ContainerCreating: `cluster-essentials-migrate-xxx`

**Expected result**
The pod gets status `ready`.

**Actual result**
The pod stays in status `ContainerCreating`.
The output of the pod:
```
Unable to attach or mount volumes: unmounted volumes=[cert], unattached volumes=[cluster-essentials-migrate-ac-certs-token-sqb7b cert]: timed out waiting for the condition MountVolume.SetUp failed for volume "cert" : secret "connector-service-app-ca" not found
```

**Steps to reproduce**
components.yaml file which was used:
```
defaultNamespace: kyma-system
prerequisites:
  - name: "cluster-essentials"
  - name: "istio"
    namespace: "istio-system"
  - name: "certificates"
    namespace: "istio-system"
components:
  - name: "logging"
```
- Provision cluster on k3s
` ./bin/kyma-darwin alpha provision k3s`
- Deploy kyma which local sources:
` ./bin/kyma-darwin alpha deploy --source=local`
- Create namespace `kyma-integration`, this is due to [this](https://github.com/kyma-project/kyma/issues/11469)
- Upgrade kyma which local sources:
` ./bin/kyma-darwin alpha deploy --source=local`

**Troubleshooting**
