### ISSUE TITLE
Kyma does not disable mTLS as the documentation and the comment suggest

### ISSUE THREAD

**Issue by oliver-goetz** [kyma-project/kyma#11478]
The quoted destination rule does not disable mTLS for the kubernetes API server as the [documentation](https://kyma-project.io/docs/components/service-mesh#details-istio-setup-in-kyma-kyma-specific-configuration) and the comment of the rule suggest

https://github.com/kyma-project/kyma/blob/53d9ec73d2a7b528554771e6e4aee88715054ae4/resources/istio/files/destination-rules.yaml#L2-L13

A working rule could look like...
```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-server
  namespace: istio-system 
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
```

**Comment by oliver-goetz** [comment]
The following rule would be better because it avoids this `istioctl analyze` error message
```
Error [IST0128] (DestinationRule api-server.istio-system) DestinationRule istio-system/api-server in namespace istio-system has TLS mode set to SIMPLE but no caCertificates are set to validate server identity for host: kubernetes.default.svc.cluster.local
```


```yaml
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: api-server
  namespace: istio-system 
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    tls:
      mode: SIMPLE
      caCertificates: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
