### ISSUE TITLE
api-controller allows an API to be created with wrong issuer

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#1156]
**Description**

You can create an API via `api-controller` with `issuer` in broken format and authentication policy will be created, which will result in constant 401s. Currently, `issuer` can be in the non-URL or email format for given api definition.

When you create api with incorrect issuer, service will be secured but the origin authentication fails constantly.

**Expected result**

When an issuer is provided in the wrong format, authentication policy is not created for given api.

**Actual result**

Authentication policy is created

**Steps to reproduce**

Apply sample api
```
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:
  labels:
    example: http-db-service
  name: http-db-service
spec:
  authentication:
  - type: JWT
    jwt:
      jwksUri: http://dex-service.kyma-system:5556/keys
      issuer: imateapot
  hostname: http-db-service.kyma.local
  service:
    name: http-db-service
    port: 8017
```

**Troubleshooting**
