### ISSUE TITLE
Missing production profile in the new generated "eventing-publisher-proxy" deployment

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11604]
**Description**

In a production environment, the new "eventing-publisher-proxy" generated by "eventing-controller" doesn't contain the production profile values.

**Expected result**

```
  publisherProxy:
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 400m
        memory: 256Mi
```
**Actual result**
the "resurces" are:
```
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
```

**Steps to reproduce**

Install a SKR using "main" and check the generated eventing-publisher-proxy"  deployment.

**Troubleshooting**
