### ISSUE TITLE
kyma alpha provision k3s reports 80 and 443 ports in use

### ISSUE THREAD

**Issue by Kiddinglife** [kyma-project/kyma#11615]
**Description**
```
jakez@pop-os:~/Desktop/kyma-setup$ kyma alpha provision k3s --verbose
Executed command:
  k3d version
with output:
  k3d version v4.4.6
k3s version v1.21.1-k3s1 (default)
Extracted K3d version: '4.4.6'
Executed command:
  k3d cluster list
with output:
  NAME   SERVERS   AGENTS   LOADBALANCER
Executed command:
  k3d cluster list -o json
with output:
  []
K3d cluster list JSON: '[]
'K3d cluster 'kyma' does not exist2021-07-02T17:21:21.552+1000  INFO    step/log.go:62  Port 80 or 443 are already in use. Please stop the allocating service and try again.
Error: Port 80 or 443 are already in use
```
error log says the ports 80 and 443 are in use but they are actualluy not used at all.
```
jakez@pop-os:~/Desktop/kyma-setup$ sudo netstat -tulpn | grep :80
jakez@pop-os:~/Desktop/kyma-setup$ sudo netstat -tulpn | grep :443
```

```
jakez@pop-os:~/Desktop/kyma-setup$ uname -a
Linux pop-os 5.11.0-7620-generic #21~1624379747~21.04~3abeff8-Ubuntu SMP Wed Jun 23 02:34:03 UTC  x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by elchead** [comment]
@Kiddinglife Have you tried using sudo?
For linux, root access is required to reserve port 80.

The output should have been improved in a past PR  (https://github.com/kyma-project/cli/pull/893)
Which version of kyma are you using?

**Comment by johgoe** [comment]
We had the same issue with k8s in windows wsl but could fix it with the following config: 
SERVER0_IP is replaced `export SERVER0_IP=$(docker inspect -f '{{index .NetworkSettings.Networks "kyma" "IPAddress"}}' /k3d-kyma-server-0)`

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: installation-config-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    kyma-project.io/installation: ""
data:
  global.isLocalEnv: "false"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: apiserver-proxy-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: apiserver-proxy
    kyma-project.io/installation: ""
data:
  global.isLocalEnv: "true"
  global.minikubeIP: "SERVER0_IP"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-kubeconfig-service-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: iam-kubeconfig-service
    kyma-project.io/installation: ""
data:
  global.isLocalEnv: "true"
  global.minikubeIP: "SERVER0_IP"
```
If isLocalEnv is true iam-kubeconfig-service and apiserver-proxy use 8443 instead of 443 and has no conflict with istio gateway port 443 on a single node deployment. 
The minikubeIP value is only required because the helm  chart does allow to enable isLocalEnv without enabling hostAliases for dex which would not be required for k8s.
