### ISSUE TITLE
Unable to subscribe to EMS events

### ISSUE THREAD

**Issue by m00g3n** [kyma-project/kyma#11647]
**Description**

Unable to subscribe to EMS events due to invalid `GrantType`.

```
{"level":"ERROR","timestamp":"2021-07-08T07:28:29Z","logger":"controller-runtime.manager.controller.beb-subscription-controller","caller":"controller/controller.go:302","message":"Reconciler error","context":{"name":"function-practical-filip5","namespace":"testing","error":"invalid GrantType: "}}
```

**Expected result**

EMS Subscription creation should succeed.

**Actual result**

EMS Subscription creation fails.

**Steps to reproduce**

 
1. Create testing namespace: `kubectl create ns testing`
2. Create `eventing-backend` secret in testing namespace.
3. Create function `kyma init function --namespace testing --name testfn`
4. Add subscription to `config.yaml` file:
```
subscriptions:
    - name: testfn
      protocol: ""
      filter:
        dialect: ""
        filters:
            - eventSource:
                property: source
                type: exact
                value: ""
              eventType:
                property: type
                type: exact
                value: test
```
5. Apply function `kyma apply function`

**Troubleshooting**
