### ISSUE TITLE
api-server-proxy does not consider service account RBAC for nonResourceURLs

### ISSUE THREAD

**Issue by oliver-goetz** [kyma-project/kyma#11664]
**Description**

When using [Kyma API server proxy](https://github.com/kyma-project/kyma/tree/main/components/apiserver-proxy) RBAC for service accounts are not taken into account when accessing nonResourceURLs. When a service account token is valid api-server-proxy is forwarding the request to upstream no matter what RBAC says.
However, [kube-rbac-proxy](https://github.com/brancz/kube-rbac-proxy) is considering them. According to README I expect them to habe the same behavior.

This is my test case:

```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
  namespace: api-proxy-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyma-apiserver-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-apiserver-proxy
subjects:
- kind: ServiceAccount
  name: httpbin
  namespace: api-proxy-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-apiserver-proxy
rules:
- apiGroups: ["authentication.k8s.io"]
  resources:
  - tokenreviews
  verbs: ["create"]
- apiGroups: ["authorization.k8s.io"]
  resources:
  - subjectaccessreviews
  verbs: ["create"]
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: api-proxy-test
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 8000
    targetPort: 8080
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: api-proxy-test
  name: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
      - name: kyma-apiserver-proxy
        image: eu.gcr.io/kyma-project/apiserver-proxy:e386863b
        # image: quay.io/brancz/kube-rbac-proxy:v0.10.0
        args:
        - "--insecure-listen-address=0.0.0.0:8080"
        - "--upstream=http://127.0.0.1:80/"
        - "--logtostderr=true"
        - "--v=7"
        ports:
        - containerPort: 8080
          name: http
        securityContext:
          allowPrivilegeEscalation: false
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  namespace: api-proxy-test
  name: httpbin
spec:
  hosts:
  - httpbin.domain.local
  gateways:
  - kyma-system/kyma-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8000
        host: httpbin
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: httpbin-anything
rules:
- nonResourceURLs: ["/anything"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: httpbin-anything
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: httpbin-anything
subjects:
- kind: ServiceAccount
  name: access-tester
  namespace: api-proxy-test
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: access-tester
  namespace: api-proxy-test
```

**Expected result**

Assuming you use the Bearer token of `access-tester` service account this should happen according to ClusterRole `httpbin-anyting`:

- Accessing https://httpbin.domain.local/anything should return HTTP code 200
- Accessing https://httpbin.domain.local should return HTTP code 403

**Actual result**

Both endpoints return HTTP 200.

**Steps to reproduce**

Apply my test case configuration and curl the endpoints I mentioned before.

Then test again with the image of `kube-rbac-proxy` you find as comment in my example configuration. When you curl again you will see the expected result.

**Troubleshooting**
