### ISSUE TITLE
Functions are not triggered after upgrading from Kyma 1.x to 2.x (with BEB backend)

### ISSUE THREAD

**Issue by marcobebway** [kyma-project/kyma#11709]
**Description**

Functions are not triggered after upgrading from Kyma 1.x to 2.x (if Eventing backend is BEB).

**Expected result**

Functions should be triggered successfully.

**Steps to reproduce**

1. Provision a Kyma 1.x cluster.
1. Switch Eventing backend to BEB.
1. Create 10 functions.
1. Verify Event Publishing/Receiving is working.
1. Upgrade cluster to Kyma 2.x.
1. Publish Events.
1. Events should be delivered to all functions.

**Troubleshooting**

The subscriptions (which does not work) had one of the following statuses:

```yaml
status:
  apiRuleName: webhook-xxbrd
  conditions:
  - lastTransitionTime: "2021-07-20T11:46:44Z"
    reason: APIRule status ready
    status: "True"
    type: APIRule status
  - lastTransitionTime: "2021-07-20T09:14:01Z"
    reason: BEB Subscription created
    status: "True"
    type: Subscribed
  - lastTransitionTime: "2021-07-20T09:56:05Z"
    reason: BEB Subscription active
    status: "True"
    type: Subscription active
  emsSubscriptionStatus:
    lastFailedDelivery: "2021-07-20T11:45:30.581Z"
    lastFailedDeliveryReason: 'Access Token endpoint response code: 401'
    subscriptionStatus: Active
  emshash: 4329666562095247213
  ev2hash: 1194936211214380872
  externalSink: https://web-zj4bnenubp.mb-beb3.kymatunas.shoot.canary.k8s-hana.ondemand.com/
  ready: true
```

```yaml
status:
  apiRuleName: webhook-4g72b
  conditions:
  - lastTransitionTime: "2021-07-20T10:14:20Z"
    reason: APIRule status ready
    status: "True"
    type: APIRule status
  - lastTransitionTime: "2021-07-20T09:13:17Z"
    reason: BEB Subscription created
    status: "True"
    type: Subscribed
  - lastTransitionTime: "2021-07-20T10:14:19Z"
    reason: BEB Subscription not active
    status: "False"
    type: Subscription active
  emsSubscriptionStatus:
    lastSuccessfulDelivery: "2021-07-20T10:12:52.501Z"
    subscriptionStatus: Paused
    subscriptionStatusReason: Paused as the number of webhooks has exceeded the max limit
  emshash: 3671634937697129051
  ev2hash: -5711747950443215567
  externalSink: https://web-zyb8mjv3hu.mb-beb3.kymatunas.shoot.canary.k8s-hana.ondemand.com/
  failedActivation: "2021-07-20T10:14:19Z"
  ready: false
```

**Observation**

- BEB complained about reaching the allowed quota of 10 subscriptions, although only 8 were created.
