### ISSUE TITLE
The "multiplexer" eventing pattern doesn't work with the NATS backend

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#11719]
**Description**

If two subscriptions are registered to the same filter, the event should be delivered to both subscriptions.
This is working for BEB but is not working for NATS

**Expected result**

**Actual result**

**Steps to reproduce**

To reproduce it, register two subscriptions having the same filter, but different names:
```
cat << EOF | k apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: test
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.test.svc.cluster.local
EOF
```
and
```
cat << EOF | k apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp-1
  namespace: test
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://anothertest.anothertest.svc.cluster.local
EOF
```
For BEB, the function receives two events, corresponding to the two subscriptions
For NATS only one subscriber receives the message.

**Troubleshooting**
