### ISSUE TITLE
Verify setting up of tracing sampling

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#11727]
**Description**
The purpose of this test is to verify if the trace sampling can be modified by setting of overrides

**Test Steps**
1. Follow the  steps for override as mentioned [here](https://kyma-project.io/docs/components/tracing/#troubleshooting-jaeger-shows-only-a-few-traces-create-an-override) but use sampling to 100
2. Verify if the override is set properly by executing following command
`kubectl get istiooperators.install.istio.io -n istio-system installed-state -oyaml | less`
and verify following is present
```
 meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata: {}
      tracing:
        sampling: 100
```
For Kyma 2
1. Create a file `tracing.yaml` and enter following
```
istio:
  kyma_istio_operator: |-
    apiVersion: install.istio.io/v1alpha1
    kind: IstioOperator
    metadata:
      namespace: istio-system
    spec:
      meshConfig:
        defaultConfig:
          tracing:
            sampling: 100
```

2. apply the override by using following command
```
kyma alpha deploy -f tracing.yaml --component istio@istio-system
```
3. Verify if the override is set properly by executing following command
`kubectl get istiooperators.install.istio.io -n istio-system installed-state -oyaml | less`
and verify following is present
```
 meshConfig:
    accessLogFile: /dev/stdout
    defaultConfig:
      proxyMetadata: {}
      tracing:
        sampling: 100
```
