### ISSUE TITLE
Eventing on managed Kyma: Send external events to event-publisher-proxy

### ISSUE THREAD

**Issue by skye0402** [kyma-project/kyma#11961]
**Description**

It should be possible to use NATS eventing from the internet and not only from the Kyma cluster. On managed Kyma no applications can be created. Also the Kyma namespaces are no-go areas. Token requests likewise don't work.
There is no known way to send an event from outside except through creating an API rule for the event-publisher proxy. @sayanh did this for me on managed Kyma and it works.

**Reasons**

For example an action in SAP IoT sends an alert (event) to Kyma. Serverless functions that subscribed to the event react on this event. In principle for the same reasons why NATS is used for internal eventing.
The alternative would be an API rule to the serverless function but that is not eventing.

**Attachments**

Yaml that allowed the eventing from namespace `kyma-system`:
```
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: event-publisher-proxy-rule
  namespace: kyma-system
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: eventing-event-publisher-proxy
    port: 80
    host: eventing-publisher
  rules:
    - path: /.*
      methods: ["*"]
      accessStrategies:
      - handler: allow
```
