### ISSUE TITLE
APIRule and Host header override

### ISSUE THREAD

**Issue by szymon-nex** [kyma-project/kyma#11978]
**Description**

Seems that APIRule pointing to service removes original HTTP  `Host` header and replaces it with local hostname of k8s service. This can change destination application behavior ex. generate different and not valid callbacks. I use KYMA available on SAP BTP platform but seems that this problem is not platform related.

**Expected result**

I would expect to receive the same HTTP `Host` header in backed application as in user request

```
GET / HTTP/1.1
host: test-expose.<cluster>.kyma-stage.shoot.live.k8s-hana.ondemand.com
user-agent: curl/7.68.0
accept: */*
x-envoy-attempt-count: 1
x-envoy-external-address: <ip>
x-forwarded-for: <ip>, 127.0.0.6
x-forwarded-proto: https
x-request-id: 18ac9af3-e49b-4c24-8991-61f9b9a24cc7
accept-encoding: gzip
```

**Actual result**

```
GET / HTTP/1.1
host: test-service.monitoring.svc.cluster.local:80  <--- service local cluster hostname
user-agent: curl/7.68.0
accept: */*
x-envoy-attempt-count: 1
x-envoy-external-address: <ip>
x-forwarded-for: <ip>, 127.0.0.6
x-forwarded-proto: https
x-request-id: 18ac9af3-e49b-4c24-8991-61f9b9a24cc7
accept-encoding: gzip
```

**Steps to reproduce**

Deploy sample application with service and APIRule:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: "test-pod-label"
  template:
    metadata:
      labels:
        apps: "test-pod-label"
    spec:
      containers:
        - name: test
          image: "alpine:latest"
          command: [ "nc", "-l", "-p", "3001" ]
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: test-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    apps: "test-pod-label"

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: test-expose
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - path: /.*
      accessStrategies:
        - config: {}
          handler: noop
      methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
  service:
    host: test-expose
    name: test-service
    port: 80
```

Call remote exposed URL
```
curl  https://test-expose.<cluster>.kyma-stage.shoot.live.k8s-hana.ondemand.com
```

Watch application logs stdout

```
kubectl logs -f test-deployment-<xxx>-<yyy>
```

**Troubleshooting**
