### ISSUE TITLE
fluent-bit config field 'removeKeys' can not be overridden. 

### ISSUE THREAD

**Issue by 4kills** [kyma-project/kyma#12077]
**Description**

It is not possible to override [this field](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/values.yaml#L242) (`removeKeys`) of the fluent-bit `values.yaml`. 

The field value is applied [here](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/templates/configmap.yaml#L124) by [this function](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/templates/_helpers.tpl#L65). 

It is not possible to override this because [the function](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/templates/_helpers.tpl#L65) expects a **yaml list** (it crashes if you provide a string), but when you try to apply the override via `kyma install -s {CUR_VER} -o logging-overrides.yaml` with a **yaml list**, this error occurs:
```console
abc@efg:~/some_path/logging$ kyma install -s 1.24.4 -o logging-overrides.yaml
2021/09/09 15:03:28 Failed to get XML: status error: 403
- Cluster type determined
  Installing Kyma in version '1.24.4'
X Preparing installation
Error: unable to load the configurations: error: failed to parse configurations: failed to convert yaml to configuration: failed to decode resource: v1.ConfigMap.Data: ReadString: expects " or n, but found [, error found in #10 byte of ...|oveKeys":["dummyIgno|..., bigger context ...|luent-bit.config.outputs.loki.config.removeKeys":["dummyIgnore123","dummyIgnore234"]},"kind":"Config|...
```
because naturally a config map resource in kubernetes must not contain data fields with array-type values (only string and boolean are permitted, I believe). 

With the original `values.yaml` it works, because helm doesn't impose any such requirements and fills in the template before creating the resource in the cluster, but overriding values via `kyma upgrade|install` of course first tries to create the resource in the cluster. 

Kyma version 1.24.4

---

**Possible fix** 

I believe this can be fixed easily by providing a comma-separated list as string in the initial `values.yaml` (which would otherwise be created during `helm install|upgrade` by [the helper function](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/templates/_helpers.tpl#L65) ) and remove that helper function altogether. Then users could override `removeKeys` with a string constituting a comma-separated list as well. 

---

**Steps to reproduce**

1. Try applying my very simple overrides file via `kyma upgrade -s 1.24.4 -o logging-overrides.yaml`:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: logging-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: logging
    kyma-project.io/installation: ""
data:
  fluent-bit.config.outputs.loki.config.removeKeys:
    - dummyIgnore123
    - dummyIgnore234
```
2. Receive the error mentioned above.

If you try to provide a string instead, the kyma installation will crash when trying to `helm install` the logging component. 

---

**Troubleshooting**

Unfortunately no workaround. I tried creating the entire fluent-bit loki [OUTPUT] config via the `values.yaml additional` field found [here](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/values.yaml#L342) from scratch, but then I have to disable [the loki [OUTPUT] configuration](https://github.com/kyma-project/kyma/blob/33d08542b2338beb7a836200f855ac71891abc21/resources/logging/charts/fluent-bit/values.yaml#L232) so there aren't 2 [OUTPUT]s for loki, but then the [label map](https://github.com/kyma-project/kyma/blob/8dc1b9c744953d38035b2875be39a5348d95eb94/resources/logging/charts/fluent-bit/templates/configmap.yaml#L268) won't be generated, which I need as well.

** Last words

I know this issue seems minor, but I need to be able to override the `removeKeys` field.

**Comment by a-thaler** [comment]
Hi @4kills, I fully agree, the main effect of the helper is that you cannot override anymore. I removed it in linked PR. We don't need to stay compatible as anyway no one was able to override it.

As a workaround you can disable the loki output fully and define a custom loki output via the "config.outputs.additional" field.

That uglyness of the override mechanism will not be present anymore with the kyma 2 story.

**Comment by a-thaler** [comment]
Ah sorry, reading your last words again and see the problem with the workaround, will think once more about a workaround

**Comment by a-thaler** [comment]
A not so nice way is to keep the default loki output active but match it to a non-existing tag, so that there will be no input connected. So setting "config.outputs.loki.match" to some value. Then the labelMap will still be generated and could be used in your additional output definition.

**Comment by 4kills** [comment]
Yea I think I might do that, thank you @a-thaler  :). 
Another problem with the `labelMap` is that it is only overridable regarding the names of the labels but it is not extendible: It is not possible to add additional fields for the same reason as for `removeKeys`: the `kyma upgrade` command (or rather k8s) doesn't allow non-string/non-boolean values for fields. So if I want to expand the labelMap by the `chart` label like this: 
```yaml 
  fluent-bit.config.outputs.loki.config.labelMap:
    kubernetes:
      namespace_name: namespace
      labels:
        app: app
        chart: chart # <--- This is NOT possible
        release: release
        "serverless.kyma-project.io/function-name": function
        "serverless.kyma-project.io/uuid": functionUID
      host: node
      container_name: container
      pod_name: pod
    stream: stream
  ```
That also doesn't work due to the more or less same error as above: 

```console
abc@efg:~/some_path/logging$ kyma upgrade -s 1.24.4 -o logging-overrides.yaml
- Cluster info read
  No migration guide available for upgrade from version '1.24.4' to version '1.24.4'
  Upgrading Kyma from version '1.24.4' to version '1.24.4'
X Preparing Upgrade
Error: unable to load the configurations: error: failed to parse configurations: failed to convert yaml to configuration: failed to decode resource: v1.ConfigMap.Data: ReadString: expects " or n, but found {, error found in #10 byte of ...|abelMap":{"kubernete|..., bigger context ...|"fluent-bit.config.outputs.loki.config.labelMap":{"kubernetes":{"container_name":"container","host":|...
```

This actually might be a separate issue, but at least I am able to override the labelMap.json manually (- which of course is a bit of a pain but I hope kyma 2 will make that much easier).
