### ISSUE TITLE
applications.applicationconnector.kyma-project.io is forbidden

### ISSUE THREAD

**Issue by coderjinhui** [kyma-project/kyma#12080]
Hi,

I meet the problem when I create a new application with documentation: https://kyma-project.io/docs/1.24/components/application-connector#tutorials-create-a-new-application

**Description**
I create the application following the documentation step by step. But it throw the error in console.

**Expected result**
Create the application successfully

**Actual result**
Shows the error `Error from server (Forbidden): error when creating "application.yaml": applications.applicationconnector.kyma-project.io is forbidden: User "xxx@xxx.com" cannot create resource "applications" in API group "applicationconnector.kyma-project.io" at the cluster scope`

**Steps to reproduce**
1. create the `application.yaml` file with following content
```yaml
apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: fnTriggerApp
spec:
  description: it is fnTriggerApp
  labels:
    region: us
    kind: production
```
2. run the command
```bash
kubectl apply -f application.yaml
```
3. then will show the error
![image](https://user-images.githubusercontent.com/16981410/132824302-14fc03b4-a288-4e51-8727-997b8a9c4242.png)
