### ISSUE TITLE
Proxy the `X-Forwarded-*` headers in Application Gateway and Central Application Gateway

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#12190]
**Description**

The compliant proxy should handle and forward the 

- `X-Forwarded-For`,
- `X-Forwarded-Proto`,
- `X-Forwarded-Host`

headers for the purpose of checking credibility of request source. However, the Application Gateway and Central Application Gateway proxies just remove them.

We should design a strategy of correct handling of those headers to provide world quality proxy.

**In code**

https://github.com/kyma-project/kyma/blob/main/components/application-gateway/internal/proxy/proxyfactory.go#L97-L102
https://github.com/kyma-project/kyma/blob/main/components/central-application-gateway/internal/proxy/reverseproxy.go#L80-L85

**Sources**
https://en.wikipedia.org/wiki/X-Forwarded-For
https://sekurak.pl/naglowek-x-forwarded-for-problemy-bezpieczenstwa/

**Comment by cnvergence** [comment]
We had a similar task to look into the subject of forwarding the host-header by default in Istio. I will drop some research on that here, so you may use it in the future.

The major concern is about support for the different Cloud providers and network topologies, specifically their types of LoadBalancers, so with the Network Load Balancers (TCP/UDP) to properly extract real Client IP we will need to patch the Istio-ingressgateway service:
`kubectl patch svc istio-ingressgateway -n istio-system -p ‘{“spec”:{“externalTrafficPolicy”:“Local”}}’`

Changing it by default will preserve the client source IP and avoids a second hop for LoadBalancer and Nodeport type services, but risks potentially imbalanced traffic spreading. 
We also had discussed this on this [PR](https://github.com/kyma-project/kyma/pull/11006/) for supporting getting Client-IP in AWS.

Also, this can always be a potential vector for XFF spoofing attacks, each deployment should have configured remote IP addresses in Istio so that we will only trust X-Forwarded-For headers from trusted [sources](https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#ip-based-allow-list-and-deny-list).

This setting can be enabled by specifying numTrustedProxies, which is the number of trusted proxies deployed in front of the Istio gateway proxy so that the client address can be extracted correctly. Following the docs having cloud-based Load Balancer and a reverse proxy in front of Istio gateway, should set the numTrustedProxies to 2. This is will work right away with HTTP/HTTPS Cloud Load Balancers in front of Kyma.

The worst case will be the external Load Balancer that uses the PROXY protocol, like AWS Classic ELB.
With that, we need to apply EnvoyFilter
```
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: proxy-protocol
  namespace: istio-system
spec:
  configPatches:
  - applyTo: LISTENER
    patch:
      operation: MERGE
      value:
        listener_filters:
        - name: envoy.listener.proxy_protocol
        - name: envoy.listener.tls_inspector
  workloadSelector:
    labels:
      istio: ingressgateway
```
which is actively in development and is considered experimental. Istio claims that it doesn’t support the proxy protocol and it can be enabled only with the EnvoyFilter API and should be used at your own risk.

**Useful links**
- Example latest XFF Spoofing CVE in gin-gonic/gin library: https://nvd.nist.gov/vuln/detail/CVE-2020-28483
- Configuring gateway network topology: https://istio.io/latest/docs/ops/configuration/traffic-management/network-topologies/
- Source IP address settings: https://istio.io/latest/docs/tasks/security/authorization/authz-ingress/#source-ip-address-of-the-original-client
- Istio issue for sanitizing XFF headers: https://github.com/istio/istio/issues/7679
