### ISSUE TITLE
Expose the real event-type used by the backend into subscription status

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12240]
**Description**
The configurable "event-type-prefix"  could change the real event type used by the eventing backend
For example, having an EMPTY even-type-prefix and a filter defined in a susbcription
```
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.commerce.order.created.v1
```
generates a REAL event type on the backend: 
```
sap.kymacustomcommerce.order.created.v1
```
Of course, the user want to publish an event to the filter defined in the subscription:
```
curl -v -X POST \
    -H "Content-Type: application/cloudevents+json" \
    --data @<(<<EOF
    {
        "specversion": "1.0",
        "source": "",
        "type": "sap.kyma.custom.commerce.order.created.v1",
        "eventtypeversion": "v1",
        "id": "A234-1234-1234",
        "data" : "{\"foo\":\"bar\"}",
        "datacontenttype":"application/json"
    }
EOF
    ) \
    http://localhost:8081/publish
```
Cause we are changing and hidden the real event type used by the backend, the subscriber will not receive the event.

We should expose the real even type used by the backend in the status of the subscription, as a hint for the publisher.
In our case  this should be:
```
sap.kymacustomcommerce.order.created.v1
```
