### ISSUE TITLE
Ensure sidecar injection in existing workloads after changing strategy to disabled-by-default

### ISSUE THREAD

**Issue by mjakobczyk** [kyma-project/kyma#12337]
**Description**

In Kyma 2.0 Istio will not offer automatic sidecar injection feature. As a result, sidecars will be present only in these workloads that customer manually mark.

**Reasons**

As a result of changing the default behaviour we need to ensure that workloads that existed on the k8s cluster before migration from Kyma 1.X to Kyma 2.0 will have the injection policy preserved.

**Attachments**

Have a look at Istio docs about [Controlling the injection policy](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy).
See: https://github.com/kyma-project/kyma/issues/11637

**Comment by mjakobczyk** [comment]
**Current findings:**
As a part of Istio installation there is a `MutatingWebhookConfiguration` called `istio-sidecar-injector` created. It basically contains 4 webhooks:
- `rev.namespace.sidecar-injector.istio.io`
- `rev.object.sidecar-injector.istio.io`
- `namespace.sidecar-injector.istio.io`
- `object.sidecar-injector.istio.io`

As a part of our enabled-by-default Istio sidecar injection policy we provide a configuration for one additional webhook called `auto.sidecar-injector.istio.io`:
```yaml
  sidecarInjectorWebhook:
    enableNamespacesByDefault: true
    objectSelector:
      autoInject: true
      enabled: false
    rewriteAppHTTPProbe: true
```

If we want to disable sidecars injection by default we could get rid of this webhook completely.
