### ISSUE TITLE
Changes to annotations and labels will not be reverted by the reconciler

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12499]
**Description**

A user can break eventing in the cluster without reconciler being able to restore the cluster to a working state by adding annotations such as
```
sidecar.istio.io/inject: "false"
```

**Expected result**

Reconciler should revert these changes

**Actual result**

The changes still exist after reconciliation 

**Steps to reproduce**

modify the eventing-controller deployment:
add
```yaml
template:
  metadata:
    annotations:
      sidecar.istio.io/inject: "false"
```

rerun the reconciler

**Troubleshooting**
