### ISSUE TITLE
Kyma 2.0 creating function error

### ISSUE THREAD

**Issue by ghost** [kyma-project/kyma#12502]
**Description**

Kyma main was installed in an AWS Gardener cluster with the "reconciler" running locally: 
```
go run ./cmd/mothership/main.go local
```
Kyma was installed and is running, but the  creation of a new function failed.
"describe pod" returns:
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  29m                   default-scheduler  Successfully assigned test/test-vtcsq-5d7cf55fb5-qh5tt to ip-10-250-2-255.eu-central-1.compute.internal
  Normal   Pulled     29m                   kubelet            Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.11.2-distroless" already present on machine
  Normal   Created    29m                   kubelet            Created container istio-init
  Normal   Started    29m                   kubelet            Started container istio-init
  Normal   Pulled     29m                   kubelet            Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.11.2-distroless" already present on machine
  Normal   Created    29m                   kubelet            Created container istio-proxy
  Normal   Started    29m                   kubelet            Started container istio-proxy
  Normal   Pulling    28m (x3 over 29m)     kubelet            Pulling image "registry.kyma.example.com/test-test:fe599ba5aa446a9a5c607a4c9192d042c7955946d61ff1f812012643b267d72d"
  Warning  Failed     28m (x3 over 29m)     kubelet            Failed to pull image "registry.kyma.example.com/test-test:fe599ba5aa446a9a5c607a4c9192d042c7955946d61ff1f812012643b267d72d": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry.kyma.example.com/v2/": dial tcp: lookup registry.kyma.example.com: no such host
  Warning  Failed     28m (x3 over 29m)     kubelet            Error: ErrImagePull
  Warning  Failed     28m (x5 over 29m)     kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m4s (x113 over 29m)  kubelet            Back-off pulling image "registry.kyma.example.com/test-test:fe599ba5aa446a9a5c607a4c9192d042c7955946d61ff1f812012643b267d72d"
```
The function's build step was ok:
```
NAME                          READY   STATUS             RESTARTS   AGE
test-build-45bvn-xnlzg        0/1     Completed          0          53m
test-vtcsq-5d7cf55fb5-qh5tt   1/2     ImagePullBackOff   0          53m
```

**Steps to reproduce**
1. create a "test" ns:
```
k create ns test
```
2. create a function in the "test" ns:
```
cat << EOF | k apply -f -
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  generation: 2
  name: test
  namespace: test
spec:
  buildResources:
    limits:
      cpu: 1700m
      memory: 1700Mi
    requests:
      cpu: 1100m
      memory: 1100Mi
  deps: "{ \n  \"name\": \"test\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
    {}\n}"
  maxReplicas: 5
  minReplicas: 1
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  runtime: nodejs12
  source: "module.exports = { \n  main: function (event, context) {\n    console.log(event.data);\n
    \   return \"Hello World!\";\n  }\n}"
EOF
```
