### ISSUE TITLE
Deletion of oauth2client breaks eventing in EventMesh mode

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12516]
**Description**
If a user deletes the oauth2client our controller does not 
* either recreate the oauth2 client
* set subscription status ready to false

If the oauth2client gets recreated by the reconciler our controller still does not work as the clientcredentials in BEB mode have not been updated

**Expected behaviour**

* controller should own the oauth2client and watch it. 
* If recreation of the oauth2client happens then all subscriptions need to be updated.
* upgrade flow must still work: #11709

**finding**
* subscriptions were ready all the time even though they did not work
* restarting the controller did not fix the broken state even though now the secret did exist again
* fixing was possible by switching eventing to nats and then back to BEB  (switching to nats triggers a cleanup on BEB)

**Comment by radufa** [comment]
**manual fix**
* wait till a new mother-reconciler call was done. This will generate a new "outh2clients/eventing-controller" and corresponding a new "secrets/eventing-controller-beb-oauth2"
* delete eventing-controller pod (restarting it). It will redeploy the subscriptions on EventMesh, using the new WebHookAuth.

**Comment by radufa** [comment]
Extract from eventing-controller log file if "outh2clients/eventing-controller" was deleted:
```
{"level":"ERROR","timestamp":"2021-11-02T14:10:18Z","logger":"controller-runtime.manager.controller.secret","caller":"controller/controller.go:304","message":"Reconciler error","context":{"reconciler group":"","reconciler kind":"Secret","name":"any","namespace":"kyma-system","error":"get secret failed namespace:kyma-system name:eventing-controller-beb-oauth2: Secret \"eventing-controller-beb-oauth2\" not found","errorVerbose":"Secret \"eventing-controller-beb-oauth2\" not found\nget secret failed namespace:kyma-system name:eventing-controller-beb-oauth2\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).getOAuth2ClientCredentials\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:628\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).reconcileBEBBackend\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:220\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).Reconcile\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:131\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}}
{"level":"ERROR","timestamp":"2021-11-02T14:11:40Z","logger":"controller-runtime.manager.controller.secret","caller":"controller/controller.go:304","message":"Reconciler error","context":{"reconciler group":"","reconciler kind":"Secret","name":"any","namespace":"kyma-system","error":"get secret failed namespace:kyma-system name:eventing-controller-beb-oauth2: Secret \"eventing-controller-beb-oauth2\" not found","errorVerbose":"Secret \"eventing-controller-beb-oauth2\" not found\nget secret failed namespace:kyma-system name:eventing-controller-beb-oauth2\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).getOAuth2ClientCredentials\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:628\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).reconcileBEBBackend\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:220\ngithub.com/kyma-project/kyma/components/eventing-controller/controllers/backend.(*Reconciler).Reconcile\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/backend/reconciler.go:131\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:298\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:253\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/src/github.com/kyma-project/kyma/components/eventing-controller/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:214\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1371"}}
```
The backend status continues to be ready:
```
% k -n kyma-system get eventingbackend
NAME               BACKEND   EVENTINGREADY   SUBSCRIPTIONCONTROLLERREADY   PUBLISHERPROXYREADY
eventing-backend   BEB       true            true                          true
```
The subscriptions are ready too (this is wrong):
```
k -n test get subscriptions
NAME    READY   AGE
test    true    115m
test1   true    104m
```
But the status of a subscription is correct:
```
status:
  apiRuleName: webhook-w9vm2
  conditions:
  - lastTransitionTime: "2021-11-02T14:19:01Z"
    reason: APIRule status ready
    status: "True"
    type: APIRule status
  - lastTransitionTime: "2021-11-02T12:29:05Z"
    message: BEB-subscription-name=test8e4b6f0485deb037060b4057392c0179347b346e
    reason: BEB Subscription created
    status: "True"
    type: Subscribed
  - lastTransitionTime: "2021-11-02T13:59:27Z"
    reason: BEB Subscription active
    status: "True"
    type: Subscription active
  emsSubscriptionStatus:
    lastFailedDelivery: "2021-11-02T14:15:41.807Z"
    lastFailedDeliveryReason: 'Webhook endpoint response code: 401'
    lastSuccessfulDelivery: "2021-11-02T13:59:36.409Z"
    subscriptionStatus: Active
  emshash: 837367044952984149
  ev2hash: -1938463347287219310
  externalSink: https://web-8ytgtdv45t.rf-t1.kymatunas.shoot.canary.k8s-hana.ondemand.com/
  ready: true
```
