### ISSUE TITLE
eventing-controller is in CrashLoopBackOff after deleting eventing-controller-token secret

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#12551]
**Steps to reproduce**

1. I created gardener GCP cluster, and installed Kyma (main-d91237f9dfc3ae9e40ae64363fbba84430000410) using reconciler.
2. Create namespace (`kubectl create namespace test`) and create a subscription using:
```
cat << EOF | k apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: test
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.test.svc.cluster.local
EOF
```
3. Delete `eventing-controller-token` secret from `kyma-system` namespace.
```
kubectl delete secret -n kyma-system eventing-controller-token-4zc4k
```

4. Delete the subscription:
```
kubectl delete subscription -n test test-noapp
```

5. The `eventing-controller` pod will now get into`CrashLoopBackOff` state.
6. Reconcile the kyma cluster using reconciler.
7. The `eventing-controller` pod will still be in `CrashLoopBackOff` state.

**Expected result**
The `eventing-controller` should use the new eventing-controller-token secret.

**Actual result**
The `eventing-controller` pod is in `CrashLoopBackOff` state.

**Troubleshooting**

```
eventing-controller-77bd956bf9-mdksz                              2/3     CrashLoopBackOff   6          17m
```

Logs from eventing-controller pod:
```
{"level":"ERROR","timestamp":"2021-11-05T13:44:20Z","caller":"cache/reflector.go:138","message":"sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1.Deployment: failed to list *v1.Deployment: Unauthorized\n","context":{}}
{"level":"ERROR","timestamp":"2021-11-05T13:44:34Z","caller":"cache/reflector.go:138","message":"sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1.Pod: failed to list *v1.Pod: Unauthorized\n","context":{}}
{"level":"ERROR","timestamp":"2021-11-05T13:44:40Z","caller":"cache/reflector.go:138","message":"sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1alpha1.EventingBackend: failed to list *v1alpha1.EventingBackend: Unauthorized\n","context":{}}
{"level":"ERROR","timestamp":"2021-11-05T13:44:40Z","caller":"cache/reflector.go:138","message":"sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1.Secret: failed to list *v1.Secret: Unauthorized\n","context":{}}
{"level":"ERROR","timestamp":"2021-11-05T13:44:46Z","caller":"cache/reflector.go:138","message":"k8s.io/client-go/dynamic/dynamicinformer/informer.go:91: Failed to watch *unstructured.Unstructured: failed to list *unstructured.Unstructured: Unauthorized\n","context":{}}
{"level":"ERROR","timestamp":"2021-11-05T13:44:57Z","caller":"cache/reflector.go:138","message":"sigs.k8s.io/controller-runtime/pkg/cache/internal/informers_map.go:245: Failed to watch *v1alpha1.Subscription: failed to list *v1alpha1.Subscription: Unauthorized\n","context":{}}
```
