### ISSUE TITLE
Upgrade of ory component fails due to wrong type of `secrets.cookie` config

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12641]
**Description**

When upgrading kyma installation ory-hydra component crashes:
```
The configuration contains values or keys which are invalid:
secrets.cookie: <nil>
                ^-- expected array, but got null

time=2021-11-18T12:33:02Z level=fatal msg=Unable to instantiate configuration. audience=application error=map[message:I[#/secrets/cookie] S[#/properties/secrets/properties/cookie/type] expected array, but got null] service_name=ORY Hydra service_version=v1.10.7
```
The ory-hydra-credentials secret content looks like this:
```
apiVersion: v1
kind: Secret
data:
  dsn: bWVtb3J5
  secretsCookie: ""
  secretsSystem: bEx0Yk01TlV0bnctZWYyMWpZNVVSWTJ0Sk5ObG41Y19FWl9ReEZtSGxhZz0=
```

**Expected result**

Secret format matches hydra expectations.

**Steps to reproduce**
I can't right now :(

I did `kyma deploy` some time ago. Now I tried it again and it failed.

When I deleted the secret it was regenerated and deployment succeeded.
