### ISSUE TITLE
ORY gcloud overides fail

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#12722]
**Description**

Installation of ORY component with gcloud postgres DB, **passed as overrides** fail.

**Expected result**

ORY installation succeeds with pod `ory-gcloud-sqlproxy-xxx` created successfully

**Actual result**

ORY installation fails and pod `ory-gcloud-sqlproxy-xxx` is not created

**Steps to reproduce**

- Create a local file `overrides.yaml` and add the modified production profile from ORY that includes atleast the following settings:
 ```yaml
global:
  ory:
    hydra:
      persistence:
        enabled: true
        postgresql:
          enabled: false
        gcloud:
          enabled: true
          saJson: |
            {
               ...
            }
        user: testuser
        password: testpwd
        dbUrl: ory-gcloud-sqlproxy.kyma-system:3306
        dbName: hydra
        dbType: postgres
gcloud-sqlproxy:
  cloudsql:
    instance:
      instanceName: xyz
      project: sap-se-cx-kyma-xxx
      region: europe-west3
      port: 3306
  rbac:
    create: true
  extraArgs:
    log_debug_stdout: true
    term_timeout: 30s
  podAnnotations:
    sidecar.istio.io/inject: "false"
  # Must be in-sync with hydra.hydra.config.existingSecret
  existingSecret: "ory-hydra-credentials"
  existingSecretKey: "gcp-sa.json"
```
- Install kyma using the command: `kyma deploy --profile production -f overrides.yaml`

**Troubleshooting**

It is clear that the overrides are updated **partially** since the dsn is updated with the gcloud-postgres value as shown here:
```sh
➜  kubectl get secret ory-hydra-credentials -o go-template='{{index .data "dsn"}}' | base64 -d
   postgres://testuser:testpwd@ory-gcloud-sqlproxy.kyma-system:3306/hydra?sslmode=disable&max_conn_lifetime=10s%                                                                                           
```

The creation of the pod `ory-gcloud-sqlproxy-xxx` is not triggered and hence the connection to gcloud-postgres DB is not established.
