### ISSUE TITLE
Kyma 2.0 breaks eventing subscriptions

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12810]
After upgrade from 1.24.8 to 2.0.0 the eventing-controller shows errors

kubectl logs -f -n kyma-system eventing-controller-7869d484b6-gg568

```
{"level":"ERROR","timestamp":"2021-12-07T21:21:06Z","logger":"nats-subscription-reconciler","caller":"nats/reconciler.go:186","message":"sink URL validation failed","context":{"kind":"Subscription","version":3,"namespace":"mynamespace","name":"search-service-recreate","error":"sink does not contain suffix: svc.cluster.local in the URL"}}
```

my subscription looks like

kubectl get subscriptions.eventing.kyma-project.io -o yaml -n mynamespace search-service-recreate 

```
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  finalizers:
  - eventing.kyma-project.io
  name: search-service-recreate
  namespace: mxspf
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.searchservice.collection.recreate.v1
  protocol: ""
  protocolsettings: {}
  sink: http://search-service.mynamespace.svc.cluster.local:8080/recreate
status:
  conditions:
  - lastTransitionTime: "2021-12-07T21:21:06Z"
    message: 'sink does not contain suffix: svc.cluster.local in the URL'
    reason: NATS Subscription active
    status: "False"
    type: Subscription active
  emsSubscriptionStatus: {}
  ready: false
```

Follow up:

- [x] https://github.com/kyma-project/kyma/issues/12812.
