### ISSUE TITLE
Specify NATS cluster label and cluster name for production profile

### ISSUE THREAD

**Issue by radufa** [kyma-project/kyma#12866]
**Description**
For NATS production profile, the distribution of pods / nodes is controlled by the "pod affinity rule" defined in:
https://github.com/kyma-project/kyma/blob/main/resources/eventing/charts/nats/values.yaml#L144
```
# Affinity for pod assignment
# ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity:
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchLabels:
              nats_cluster: eventing-nats
          topologyKey: kubernetes.io/hostname
        weight: 100
```
As a consequence, a NATS instance must have the label
```
nats_cluster: eventing-nats
```
defined. 
Also each NATS instance should have the same cluster name "eventing-nats" instead of the host name.
```
[7] 2021/12/14 02:09:22.758355 [INF] Starting nats-server
[7] 2021/12/14 02:09:22.758421 [INF]   Version:  2.6.5
[7] 2021/12/14 02:09:22.758425 [INF]   Git:      [ea48105]
[7] 2021/12/14 02:09:22.758428 [INF]   Name:     eventing-nats-0
[7] 2021/12/14 02:09:22.758432 [INF]   ID:       NBC5TLIVT7I6SGJ76ONC367U5BQ4RVAJ4RHRMCU7M7RRRWZ3QUUDH5IV
[7] 2021/12/14 02:09:22.758436 [INF] Using configuration file: /etc/nats-config/nats.conf
[7] 2021/12/14 02:09:22.759937 [INF] Starting http monitor on 0.0.0.0:8222
[7] 2021/12/14 02:09:22.760025 [INF] Listening for client connections on 0.0.0.0:4222
[7] 2021/12/14 02:09:22.760281 [INF] Server is ready
[7] 2021/12/14 02:09:22.760306 [INF] Cluster name is t8uPxuz226MxE0fODNCLnt
[7] 2021/12/14 02:09:22.760309 [WRN] Cluster name was dynamically generated, consider setting one
[7] 2021/12/14 02:09:22.760335 [INF] Listening for route connections on 0.0.0.0:6222
[7] 2021/12/14 02:09:22.772927 [ERR] Error trying to connect to route (attempt 1): lookup for host "eventing-nats-2.eventing-nats.kyma-system.svc.cluster.local": lookup eventing-nats-2.eventing-nats.kyma-system.svc.cluster.local on 10.223.240.10:53: no such host
```
It should avoid the "split brain" running mode of NATS cluster, see: https://github.com/kyma-project/kyma/issues/12825
