### ISSUE TITLE
Reconciler of kyma cli is not very transparent

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#12960]
From a administrative view installing a cluster with a command line tool without seeing what the changes will be feels not very trustful. For that reason we are looking for an alternative way to install kyma.

Currently we think about replacing Kyma CLI deploy with ArgoCD.
ArgoCD can track Git Repositories and helm repositories.
In git different kind of imstallation types like helm template or kustomize are supported.
ArgoCD applications can organized hierarchically.
Depending on the configuration changes are synchronized automatically or manually. 
It's also possible to show the diffs before you synchronize.

Did you ever think about deploying kyma with a  tool like argo cd instead of cli.
We think it could be possible at the moment but what are the direction of the reconciler? Are there any plans to move more functionalities from the charts to cli? This will destroy our plans to try argo cd for more transparency for our azure aks installations.

It also enables us not to develop only serverless applications with kyma but also deploy standard applications with a own chart

**Comment by johgoe** [comment]
A first looks like it could work

![grafik](https://user-images.githubusercontent.com/1584475/147952618-0191833e-dc4b-4f4f-884a-af9b99c749c0.png)

e.g. application spec:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-configuration
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  project: kyma
  source:
    helm:
      values: |-
        meshConfig:
          accessLogFile: ""

        helmValues:
          global:
            logging:
              level: all:warn
            proxy:
              resources:
                requests:
                  cpu: 150m
                  memory: 128Mi
                limits:
                  cpu: 500m
                  memory: 1024Mi

        components:
          ingressGateways:
            enabled: true
            config:
              hpaSpec:
                maxReplicas: 10
                minReplicas: 3
                metrics:
                  - resource:
                      name: cpu
                      targetAverageUtilization: 80
                    type: Resource
                  - resource:
                      name: memory
                      targetAverageUtilization: 80
                    type: Resource
              resources:
                limits:
                  cpu: 2000m
                  memory: 1024Mi
                requests:
                  cpu: 100m
                  memory: 128Mi
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - istio-ingressgateway
                      topologyKey: "kubernetes.io/hostname"

          pilot:
            enabled: true
            config:
              hpaSpec:
                maxReplicas: 5
                minReplicas: 2
              affinity:
                podAntiAffinity:
                  preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchExpressions:
                        - key: app
                          operator: In
                          values:
                          - istiod
                      topologyKey: "kubernetes.io/hostname"
    path: resources/istio-configuration
    repoURL: https://github.com/kyma-project/kyma
    targetRevision: 2.0.0
```

The values have to be added manually because argo cd can't detect profile-production.yaml because the argo cd naming convention for values-files is values-*.yaml so only values-production.yaml would work for choosing a prepared values profile.
