### ISSUE TITLE
Receiving quota limitation on istio-ingressgateway

### ISSUE THREAD

**Issue by nexus49** [kyma-project/kyma#1332]
I am seeing a quota limitation on the isto-ingressgateway deployment:

Environment GKE

```
kc get deploy -n istio-system istio-ingressgateway -oyaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  [..]
  name: istio-ingressgateway
  namespace: istio-system
    [..]
spec:
  progressDeadlineSeconds: 600
  replicas: 2
    [..]
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    [..]
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-10-16T12:02:19Z
    lastUpdateTime: 2018-10-16T12:02:40Z
    message: ReplicaSet "istio-ingressgateway-85758b8fb" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: 2018-10-16T12:35:05Z
    lastUpdateTime: 2018-10-16T12:35:05Z
    message: 'pods "istio-ingressgateway-85758b8fb-rqz84" is forbidden: exceeded quota:
      kyma-default, requested: requests.memory=128Mi, used: requests.memory=1952Mi,
      limited: requests.memory=2Gi'
    reason: FailedCreate
    status: "True"
    type: ReplicaFailure
  - lastTransitionTime: 2018-10-17T11:56:56Z
    lastUpdateTime: 2018-10-17T11:56:56Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
```
