### ISSUE TITLE
Sink Validation behaviour is different in NATS and BEB

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#13354]
**Description**

If the sink validation fails in NATS, the `ready` status of the kyma subscription becomes `false`, but for BEB - the `ready` status remains `true` (if it was previously true)

**Expected result**

The subscription exhibits similar behaviour with both NATS and BEB backends

**Actual result**

NATS and BEB show different behaviours

**Steps to reproduce**

- Create a valid subscription as below with NATS backend

```
cat << EOF | kubectl apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: test
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.test.svc.cluster.local
EOF
```

- Once the subscription is active, edit the existing subscription and change the sink value to `test.test.svc.cluster.local`
- The ready status is now false
- Repeat the same steps with BEB backend. In this case the ready status of the subscription remains true.

**Troubleshooting**
