### ISSUE TITLE
Serverless functions creates too many spans after reaching it using event

### ISSUE THREAD

**Issue by pPrecel** [kyma-project/kyma#13599]
**Description**

Function reached by an event generates one more span than reached by for example HTTP request using the ApiRule or other service. We have to investigate why it's caused by and if it's the desired result.

**Expected result**

Function hit by HTTP request using the ApiRule:
<img width="1680" alt="Screenshot 2022-03-09 at 19 26 21" src="https://user-images.githubusercontent.com/28900355/157660692-43636416-536a-4e3e-b39e-24a2d7b624b6.png">

**Actual result**

Function hit by the CloudEvent (in-cluster):
<img width="1680" alt="Screenshot 2022-03-09 at 19 28 17" src="https://user-images.githubusercontent.com/28900355/157660775-60dc0729-361e-4e79-a89f-8d4be2bf69f8.png">
> **NOTE:** there is one more (second brown) span

**Steps to reproduce**

1. Generate workspace:

```bash
kyma init function  
```

2. Modify the` config.yaml` file to:

```yaml
name: fs-function
namespace: default
runtime: nodejs14
source:
    sourceType: inline
apiRules:
- rules:
    - methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - HEAD
subscriptions:
- filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.nonexistingapp.order.created.v1
```

3. Modify the `handler.js` file to:

```javascript
const axios = require('axios');
var XMLHttpRequest = require("xmlhttprequest").XMLHttpRequest;

module.exports = {
    main: function (event, context) {

        axios("http://www.google.com/")
            // Unhandled promise rejections are deprecated
            .catch((err) => {
                if (err.response) {

                console.log("not ok", err.response.status)
                }
            });

        var oReq = new XMLHttpRequest();
        oReq.open("GET", "http://www.google.com/");
        oReq.send();
       
        
        return 'Hello Serverless'
    }
}
```

4. Modify the `package.json` file to:

```json
{
  "name": "function-exciting-rafal8",
  "version": "0.0.1",
  "dependencies": {
    "@opentelemetry/api": "^0.18.0",
    "xmlhttprequest": "^1.8.0",
    "axios": "^0.26.0"
  }
}

```

5. Apply function:

```bash
kyma apply function
```

6. Reach function from outside of the cluster:

```bash
export url=$(kubectl get apirule fs-function -ojsonpath='{ .spec.service.host }')
curl --header "X-B3-Sampled: 1" "https://$url/" 
```

7. Reach function from inside of the cluster by an event:

```bash
kubectl run --rm -i --tty --image ubuntu my-shell

root@my-shell:/# apt update && apt install curl --yes
root@my-shell:/#  curl -k -i \
                      --data @<(cat <<EOF
                      {
                          "source": "kyma",
                          "specversion": "1.0",
                          "eventtypeversion": "v1",
                          "data": {"orderCode":"3211213"},
                          "datacontenttype": "application/json",
                          "id": "759815c3-b142-48f2-bf18-c6502dc0998f",
                          "type": "sap.kyma.custom.nonexistingapp.order.created.v1"
                      }
                  EOF
                      ) \
                      -H "X-B3-Sampled: 1" \
                      -H "Content-Type: application/cloudevents+json" \
                      "http://eventing-event-publisher-proxy.kyma-system/publish"
```

8. Open Jaeger UI and compare results:

```bash
kubectl -n kyma-system port-forward svc/tracing-jaeger-query 16686:16686
```
