### ISSUE TITLE
OOM of prometheus on frequest restarts of pods - envoy metrics pollution

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13659]
**Description**
In a scenario with frequent restarts or creation of pods like when having cronjobs in place, the "prometheus-istio-server" runs into OOMs very fast and the main prometheus problems gets increasing memory footrpint as well. Increasing memory will not fix the root problem and results in deferred crashes.

**Expected result**
Not changing the communication topology but just having restarting pods should increase the footprint of the prometheus-istio-server and the main prometheus in a minimal way

**Actual result**
Memory consumption increases heavily for both prometheuses as amount of active timeseries increases

**Steps to reproduce**
Scale out an application to 30 replicase and restart rollout the app. Watch the amount of timeseries for the prometheus instance

**Troubleshooting**

**Comment by a-thaler** [comment]
Analyses show that the "envoy_" metrics exposed and collected are really huge. In a scenario with 200 pods which are all getting restarted 3 times, 50% of the amount of timeseries in the prometheus-istio-server is caused by envoy metrics.
These metrics are all pod specific and are not getting aggregated further to some more higher level like done with the istio metrics.
Nothing in the default kyma setup is based on these metrics, so not collecting these metrics by default will give bring a big improvement here.
As the envoys metrics are not getting aggregated anyway, there is no need to get them collected by the dedicated prometheus-istio-server. We should give simple instructions on how to collect these metrics via a servicemonitor definition and just drop them from the default setup.

Here the footprint with current setup
<img width="1716" alt="initial-grafana" src="https://user-images.githubusercontent.com/7479371/158857423-61b3f1d0-12ed-449a-823e-fefdd5c3e926.png">

Here the same test run with dropped envoy metrics
<img width="1721" alt="envoy-grafana" src="https://user-images.githubusercontent.com/7479371/158851495-7adace63-2af8-4a4c-b2ac-5148c613414d.png">

A way to enable the envoy metrics scraping on demand is to place such podmonitor:
```


apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-sidecars
spec:
  selector:
    matchLabels:
      security.istio.io/tlsMode: 'istio'
  podMetricsEndpoints:
    - port: http-envoy-prom
      path: /stats/prometheus

```
