### ISSUE TITLE
Derive subscriber endpoint from the subscription custom resource 

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#1367]
### Description
Currently, the subscriber endpoint has to be provided in the custom resource definition as a fully qualified URL

```yaml
apiVersion: eventing.kyma.cx/v1alpha1
kind: Subscription
metadata:
  name: example-subscription
  labels:
    example: event-bus
spec:
  endpoint: http://event-email-service.stage:3000/v1/events/register
  ...
```

This approach has two issues:
1. It makes it difficult to create a template project for a sample subscriber since the endpoint has to be somehow changed based on in which Kyma environment the subscription and subscriber have been created.
1. The event-activation can be circumvented as one can still create a subscription in Kyma environment `env1` and can provide an endpoint that delivers events in Kyma environment `env2`.

### Hint
The subscription custom resource already contains information about the Kyma environment. Using this and minimal information that is not coupled with the Kyma environment, it should be possible to derive the endpoint URL.

> **Note**: Consider the possibility of providing multiple ways of specifying endpoint based on various different protocols. This could be helpful in the future.

```
endpoint URL = Subscription Namespace + Minimal independent information about the subscriber service.
```
> **Note** : Align with automatix.

### AC:
- [ ] There is a design with pros and cons about the approach to derive the endpoint URL.
- [ ] The Subscription Custom Resource definition has been changed
- [ ] Endpoint in subscription CR does not provide namespace while describing endpoint details.
- [ ] Documentation and examples have been modified
- [ ] E2E tests have been modified accordingly.
