### ISSUE TITLE
Subscribing to events

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#13797]
As a user of kyma eventing i want to be able to subscribe to events by specifying only the information i really want to filter events by.

For me this means:
* an event sent by a connected application can be specified in a filter by specifying:
	* the application it was initially sent from
	* the `businessobject.operation.version` contained in my original event
* an event sent from within the cluster:
	* `businessobject.operation.version`
	* internal source of the event (name of the lambda eg, or some user configurable identifier)
* an event not sent using the eventpublisher.
	* a full eventtype that adheres to the backend the subscription is working on. This will allow me to subscribe to events that are not sent using kyma, but are directly sent to the eg the event mesh.

**Comment by FriedrichWilken** [comment]
Let's say you want to create a subscription like this, where would the info mentioned before go?

```
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: goldfish-testing
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.goldfish-testing.svc.cluster.local
EOF
```

**Comment by k15r** [comment]
One important thing to know about the current state of the subscription is, that it was modelled based on the EventMesh subscription definition. If do not expose that one to the customer, but just use it internally for subscriptions on EventMesh we can change our subscription crd:
```
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: goldfish-testing
spec:
  filter:
    filters:
    - sourceType: connectedApp
      source: <application>
      eventType: <eventType>
    - sourceType: internal
      source: <internalsource>|optional
      eventType: <eventType>
    - sourceType: external
      eventType: <full event type>
      source: <externalSource>
  sink: http://test.goldfish-testing.svc.cluster.local
```

Obviously not all backends will support the external Source (eg Nats Jetstream)
