### ISSUE TITLE
Application Gateway mTLS-OAuth flow

### ISSUE THREAD

**Issue by janmedrek** [kyma-project/kyma#13970]
**Description**

We need to provide support for mTLS-secured OAuth token fetch. Right now we handle the fetch with regular client credentials: Client ID and the Client Secret. In some cases instead of using string secret, the token fetch API is secured with mTLS traffic.

We could utilize Application CR to store information about such Auth:
```
credentials:
            authenticationUrl: https://{BASE-APPLICATION-URL}/authorizationserver/oauth/token
            secretName: {SECRET-NAME}
            type: OAuth-mTLS
```

And then in the secret (perhaps we should separate the private key from the certificate instead of keeping it in one block):
```
...
data:
  clientId: aGVsbG90aGVyZQo=
  clientSecret: {BASE64-ENCODED-KEY+CERT}
...
```
or
```
...
data:
  clientId: aGVsbG90aGVyZQo=
  certificate: {BASE64-ENCODED-CERT}
  key: {BASE64-ENCODED-KEY}
...
```

**Reasons**

There are more and more systems in the cloud environment using [OAuth 2.0 Mutual-TLS Client Authentication](https://datatracker.ietf.org/doc/html/rfc8705). We need to provide a way to integrate the Application Gateway with that flow.

**Acceptance Criteria**
- [ ] ~~Application CR enhanced to store OAuth-mTLS credentials~~
- [x] Application Gateway can handle OAuth Mutual-TLS Client Authentication
- [x] Documentation updated to reflect new way of fetching OAuth token
- [x] Clean up data model to remove deprecated `commonName` field
