### ISSUE TITLE
Investigate and design new Eventing-Backend CRD to include eventing-backend type and configs

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#14129]
Keep in mind that this ticket is part of [this issue](https://github.com/kyma-project/kyma/issues/13800).
- [x] Define a new eventing-backend CRD.
    - [x] Check what configs we need to move to the eventing-backend CRD.
    - [x] Remember to keep the new CRD flexible for [Multiple active backends](https://github.com/kyma-project/kyma/issues/13798).
    - [x] Investigate where the backend CR validation should take place? (api-server or reconciler?)
       - Example: Check how Knative did it?

Some example spec/configs to consider:
- [x] Enable specifying the eventing backend type to be used (e.g. eventingbackend.Spec.Type=nats)
- [x] Allow specifying config on the eventingbackend CRD
  - [x] Beb secrets (e.g. eventingbackend.Spec.Config.Beb.secretRef=<name of secret>)
  - [x] Nats config options such as default limit, default maximum inflight (needs to be set by eventing controller who reads the eventing backend CR for the active backend)
     - Note: Currently we have the configs in eventing-controller charts and in subscription CR. (For example maximum inflight is included in subscription CRD, we can define the defaults for them in the new eventingbackend CRD.)

**Comment by FriedrichWilken** [comment]
Keep in mind that this ticket is part of [this issue](https://github.com/kyma-project/kyma/issues/13800).
- [x] Define a new eventing-backend CRD.
```yaml
apiVersion: eventing.kyma-project.io/v1alpha1
kind: EventingBackend
metadata:
  name: any
  namespace: any
  labels:
    kyma-project.io/eventing: backend
spec:
  type: "nats"
  config:
  - maxInFlightMessages: 10
status:
  backendType: nats
  conditions:
  - lastTransitionTime: "2022-05-06T08:35:11Z"
    reason: Backend ready
    status: "True"
    type: Backend Ready
  - lastTransitionTime: "2022-05-06T08:35:11Z"
    reason: Publisher proxy deployment ready
    status: "True"
    type: Publisher Proxy Ready
  - lastTransitionTime: "2022-05-06T08:35:11Z"
    reason: Subscription controller started
    status: "True"
    type: Subscription Controller Ready
  eventingReady: true
```

- [x] Check what configs we need to move to the eventing-backend CRD.
    - Due to the generic approach we came up with, there is no need to decide on single configs here.
- [x] Remember to keep the new CRD flexible for [Multiple active backends](https://github.com/kyma-project/kyma/issues/13798).
    - The proposed CRD would allow to have multiple backend instances of the same or different backend type.
- [X] Investigate where the backend CR validation should take place? (api-server or reconciler?)
   - `ValidatingAdmissionWebhook`

Some example spec/configs to consider:
- [x] Enable specifying the eventing backend type to be used (e.g. eventingbackend.Spec.Type=nats)
```yaml
...
 spec:
  type: "nats"
...
```
- [x] Allow specifying config on the eventingbackend CRD
```yaml
...
spec:
  config:
  - maxInFlightMessages: 10
...
```
  - [x] Beb secrets (e.g. eventingbackend.Spec.Config.Beb.secretRef=<name of secret>)
```yaml
...
spec:
  config:
  - bebSecret: foo
...
```
  - [x] Nats config options such as default limit, default maximum inflight (needs to be set by eventing controller who reads the eventing backend CR for the active backend)
  - [
     - Note: Currently we have the configs in eventing-controller charts and in subscription CR. (For example maximum inflight is included in subscription CRD, we can define the defaults for them in the new eventingbackend CRD.)
