### ISSUE TITLE
[Telemetry Operator] de-dotting filter support + docu for http output

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14310]
**Description**
For integration with ElasticSearch/OpenSearch you will face at some point the typical problem of de-dotting. Fluent Bit provides a dedot option as part of the ElasticSearch output plugin. Unfortunately, when integrating via a log shipper in-between like fluentd, then that option is not available. A filter is required to apply the dedot modifications to log records.

As workaround a lua script is available, see also: https://github.com/fluent/fluent-bit/issues/1134

After considerations of https://github.com/kyma-project/community/pull/675/files, an option is needed on the "http" output to support dedotting. The operator will translate that settings into an aditional filter definition at the last element of the filter chain.

```YAML
  output: #only one output, no output should fail validation
    http: # enables http output
      Dedot: false # new flag resulting in a lua filter as last element in filter chain, default false as typically not used in http
      Host: # next 3 attributes should be configurable by static value and valueFrom incl. secret rotation
        value: "icke.com"
        valueFrom: ...
      HTTP_User:
        value: "icke.com"
        valueFrom: ...
      HTTP_Password:
        value: "icke.com"
        valueFrom: ...
      URI: /customindex/kyma
```
**Criteria**
- Support dedotting via a lua filter (provide pre-bundled script file)
- Add a new option to the "http" output which is false by default
- Enabling the option will add the lua filter as last element to the chain and all logs of the pipeline are getting the dedot logic applied
- Documentation for the http output is available and describes dedotting flag
