### ISSUE TITLE
Ory Hydra pods in initialising state block rolling update

### ISSUE THREAD

**Issue by barchw** [kyma-project/kyma#14356]
**Description**

Ory Hydra containers with wrong persistence credentials configuration (e. g. wrong password) stay in initialising state because of wait-for-db. Reconciling again with correct config doesn't replace initialising pods.

Problem is present both on `evaluation` and `production` profile

**Related issues**
Follow up of: https://github.com/kyma-project/kyma/issues/14238

**Expected result**

Rolling update proceeds successfully with old pods being replaced by new with new configuration

**Actual result**

Badly configured pods stay in initialising state and no new pods are created

**Steps to reproduce**

1. Deploy Ory in production profile with correct configuration (e. g. default with postgres DB)
2. Change persistence settings in `values.yaml` and `profile-production.yaml` to wrong one:
``` yaml
global:
  ory:
    hydra:
      persistence:
        enabled: true
        postgresql:
          enabled: false
        gcloud:
          enabled: false
        user: "wronguser"
        password: "wrongpassword"
        dbUrl: "wrongurl"
        dbName: "wrongdb"
        dbType: "wrongdbtype"
```
3. Redeploy ory with new config on production profile
```
└─[$] <> kgpon kyma-system | grep ory
ory-hydra-6889fdb58c-65ntl                                        2/2     Running    0          11m
ory-hydra-6889fdb58c-ncdd4                                        2/2     Running    0          10m
ory-hydra-c497c6477-lnctt                                         0/2     Init:0/3   0          8m51s
ory-hydra-maester-7db9799d4b-h26mm                                2/2     Running    0          18m
ory-oathkeeper-5d74cbf9-7ssl8                                     3/3     Running    0          18m
ory-oathkeeper-5d74cbf9-dn5fr                                     3/3     Running    0          17m
ory-oathkeeper-5d74cbf9-g8cqj                                     3/3     Running    0          18m
ory-oathkeeper-5d74cbf9-plxq8                                     3/3     Running    0          18m
ory-postgresql-0                                                  1/1     Running    0          130m
```
4. Revert config to correct one and redeploy

**Troubleshooting**

The issue might be caused by Hydra rolling update strategy set to `maxUnavailable: "0%"`
```yaml
deployment:
    strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: "50%"
        maxUnavailable: "0%"
```

**Workaround**

Manually deleting the initialising pods will allow the update to proceed
