### ISSUE TITLE
[POC] expose multiple svc under same virtual host

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#14421]
**Description**

Expose [httpbin](https://github.com/istio/istio/tree/master/samples/httpbin) and [helloworld](https://github.com/istio/istio/tree/master/samples/helloworld) apps provided by Istio under same virtual host. Create step by step tutorial providing example yamls.
To expose  both svc use [Istio VS](https://istio.io/latest/docs/reference/config/networking/virtual-service/) and [ORY oathkeeper rules](https://www.ory.sh/docs/oathkeeper/api-access-rules). Istio VS should point to ORY oathkeeper svc. ORY oathkeeper rules are pointing to respective httpbin and helloworld apps. Resources created under the hood by api-gateway should be treated as a starting point.

AC:
- [x] Istio VS pointing to ORY oathkeeper created
- [x] ORY Oathkeeper rule created for httpbin
- [x] ORY Oathkeeper rule created for helloworld
- [x] apps deployed to different ns
- [x] httpbin headers exposed under `https://istio-POC.${DOMAIN}/httbin/headers`
- [x] helloworld hello exposed under `https://istio-POC.${DOMAIN}/helloworld/hello`

**Reasons**

**Attachments**

https://github.com/kyma-project/kyma/issues/9936

**Comment by barchw** [comment]
Steps to achieve goal of POC:

1. Kyma was deployed on profile evaluation
``` bash
kyma deploy -s main
```
2. Created two namespaces for httpbin and helloworld applications
``` bash
kubectl create ns httpbin
kubectl create ns hello-world
```
3. Deployed httpbin and helloworld apps
### httpbin.yaml
``` yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: httpbin
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
  namespace: httpbin
  labels:
    app: httpbin
    service: httpbin
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: httpbin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin
  namespace: httpbin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpbin
      version: v1
  template:
    metadata:
      labels:
        app: httpbin
        version: v1
    spec:
      serviceAccountName: httpbin
      containers:
      - image: docker.io/kennethreitz/httpbin
        imagePullPolicy: IfNotPresent
        name: httpbin
        ports:
        - containerPort: 80
```
### helloworld.yaml
``` yaml
apiVersion: v1
kind: Service
metadata:
  name: helloworld
  namespace: hello-world
  labels:
    app: helloworld
    service: helloworld
spec:
  ports:
  - port: 80
    targetPort: 5000
    name: http
  selector:
    app: helloworld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v1
  namespace: hello-world
  labels:
    app: helloworld
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloworld
      version: v1
  template:
    metadata:
      labels:
        app: helloworld
        version: v1
    spec:
      containers:
      - name: helloworld
        image: docker.io/istio/examples-helloworld-v1
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: IfNotPresent #Always
        ports:
        - containerPort: 5000
```
4. Created VS pointing to ory oathkeeper proxy on paths /httpbin/headers and /helloworld/hello
### vs.yaml
``` yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: poc-vs
  namespace: httpbin
spec:
  gateways:
  - kyma-system/kyma-gateway
  hosts:
  - istio-POC.{{ .Values.global.ingress.domainName }}
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /httpbin/headers
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - X-Broker-API-Version
      allowMethods: ["GET", "PUT", "POST"]
      allowOrigins:
      - regex: ".*"
    match:
    - uri:
        regex: /helloworld/hello
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
```
5. Created ORY oathkeeper rules stripping the paths to only the second part of the path ("/headers" for httpbin) and pointing upstream to desired service
### ory-helloworld-rule.yaml
``` yaml
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: helloworld-rule
spec:
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  match:
    methods:
      - GET
      - PUT
      - POST
    url: <http|https>://istio-POC.{{ domainName }}<(:(80|443))?></helloworld/hello>
  upstream:
    url: http://helloworld.hello-world.svc.cluster.local:80
    #Strip path removes "/helloworld" from the path
    stripPath: "/helloworld"
```
### ory-httpbin-rule.yaml
``` yaml
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-rule
spec:
  authenticators:
  - handler: noop
  authorizer:
    handler: allow
  match:
    methods:
      - GET
      - PUT
      - POST
    url: <http|https>://istio-POC.{{ domainName }}<(:(80|443))?></httpbin/headers>
  upstream:
    url: http://httpbin.httpbin.svc.cluster.local:80
    #Strip path removes "/httpbin" from the path
    stripPath: "/httpbin"
```
6. Curling both endpoints now results with success
``` bash
 curl -ik -X GET https://istio-POC.$KYMA_DOMAIN/helloworld/hello
```
``` zsh
└─[$] <> curl -ik -X GET https://istio-POC.bc-ory.goatz.shoot.canary.k8s-hana.ondemand.com/helloworld/hello
HTTP/2 200 
content-length: 60
content-type: text/html; charset=utf-8
date: Fri, 01 Jul 2022 09:18:18 GMT
server: istio-envoy
x-envoy-upstream-service-time: 148

Hello version: v1, instance: helloworld-v1-776f57d5f6-m5w69
```
``` bash
curl -ik -X GET https://istio-POC.$KYMA_DOMAIN/httpbin/headers
```
``` zsh
HTTP/2 200 
access-control-allow-credentials: true
access-control-allow-origin: *
content-length: 604
content-type: application/json
date: Fri, 01 Jul 2022 09:20:06 GMT
server: istio-envoy
x-envoy-upstream-service-time: 16

{
  "headers": {
    "Accept": "*/*", 
    "Accept-Encoding": "gzip", 
    "Host": "httpbin.httpbin.svc.cluster.local:80", 
    "User-Agent": "curl/7.79.1", 
    "X-B3-Parentspanid": "58085320f2e9acc0", 
    "X-B3-Sampled": "0", 
    "X-B3-Spanid": "f37ab47c219c07b9", 
    "X-B3-Traceid": "37762d53f884d27d463d4fa14a7e42bb", 
    "X-Envoy-Attempt-Count": "1", 
    "X-Forwarded-Client-Cert": "By=spiffe://cluster.local/ns/httpbin/sa/httpbin;Hash=892f623faa4af64a548ecb1b9326d0952e76f900ee20513d1245d45bffbe8ae2;Subject=\"\";URI=spiffe://cluster.local/ns/kyma-system/sa/oathkeeper-maester-account"
  }
}
```
