### ISSUE TITLE
HA Evaluation of Jetstream

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14451]
Followup to #14111 
In order to fulfil the HA requirements of kyma we need to test the following scenario:
- NATS Jetstream cluster must be configured with proper POD Antiaffinity Rules (Spread across as many nodes as possible)
- bringing down one node (k8s cluster node) must not disrupt event publishing / dispatching workflow

**Comment by mfaizanse** [comment]
```
affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  nats_cluster: eventing-nats
              topologyKey: kubernetes.io/hostname
            weight: 100
```
