### ISSUE TITLE
The service instance redis pod is taking too long to be deleted

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#1447]
**Description**
Sometimes the `service instance` redis pod is taking too long to be deleted. Thus resulting in `kubeless-test` namespace not getting deleted. This happens sporadically on when kubeless test is executed on minikube.

**Expected result**
The `kubeless-test` namespace should be deleted.

**Actual result**

The `redis service instance pod` is not deleted and thus the `kubeless-test` namespace is still left causing the helm test `kubeless-test` to fail.

**Steps to reproduce**

I could reproduce it locally running on minikube by executing following yaml
```yaml
# NOTE: The Role, ServiceAccount, and RoleBinding are created once during installation and not removed after (or recreated before) each test. This is a limitation of Helm: it can only create a Pod during testing.
# (This applies to Helm 2.7.2.)
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: test-{{ template "fullname" . }}
  labels:
    helm-chart-test: "true"
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "get", "list"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["create", "delete", "get", "list", "patch"]
- apiGroups: [""]
  resources: ["services", "services/proxy", "configmaps", "pods/log", "replicationcontrollers"]
  verbs: ["get", "list"]
- apiGroups: ["kubeless.io"]
  resources: ["functions"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["servicecatalog.k8s.io"]
  resources: ["serviceinstances", "servicebindings"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["servicecatalog.kyma.cx"]
  resources: ["servicebindingusages"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["eventing.kyma.cx"]
  resources: ["subscriptions"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["gateway.kyma.cx"]
  resources: ["apis"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["applicationconnector.kyma-project.io"]
  resources: ["eventactivations"]
  verbs: ["create", "delete", "get", "list"]
- apiGroups: ["networking.istio.io"]
  resources: ["virtualservices"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments", "replicasets", "statefulsets"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["cronjobs"]
  verbs: ["get", "list"]
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list"]


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-core-kubeless
  labels:
    helm-chart-test: "true"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: test-core-kubeless
  labels:
    helm-chart-test: "true"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: test-core-kubeless
subjects:
- kind: ServiceAccount
  name: test-core-kubeless
  namespace: kyma-system
---
apiVersion: v1
kind: Pod
metadata:
  name: test-kubeless
  namespace: kyma-system
  labels:
    helm-chart-test: "true"
  annotations:
    helm.sh/hook: test-success
spec:
  serviceAccount: "test-core-kubeless"
  containers:
  - name: test-kubeless
    image: eu.gcr.io/kyma-project/develop/kubeless-test-client:73e18620
    volumeMounts:
    - name: k8syaml
      mountPath: /k8syaml
    env:
    - name: KUBELESS_NAMESPACE
      value: kyma-system
    - name: KUBELESS_CONFIG
      value: core-kubeless-config
    - name: DOMAIN_NAME
      value: "kyma.local"
    #command: [ "/bin/sh", "-c", "while true; do sleep 30; done;" ]
  volumes:
    - name: k8syaml
      configMap: 
        name: test-core-kubeless-config
        items:
          - key: k8sYaml
            path: k8s.yaml
          - key: svcBindLambdaYaml
            path: svcbind-lambda.yaml
  restartPolicy: Never
```

**Troubleshooting**

Some info:

```
k get all -n kubeless-test
NAME                                                                 READY     STATUS        RESTARTS   AGE
po/hb-redis-micro-6655f2a5-d917-11e8-a143-0242ac110027-redis-9n8td   0/1       Terminating   0          42m
```

Logs from `catalog-controller`
```
{"level":"info","log":{"message":"started handling request","method":"DELETE","remote":"172.17.0.36:48712","request":"/v2/service_instances/6655f2a5-d917-11e8-a143-0242ac110027?accepts_incomplete=true\u0026plan_id=a6078798-70a1-4674-af94-ab9664d36a54\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","time":"2018-10-26T12:06:57.398Z"}}
{"level":"info","log":{"action":"deprovision","message":"action response","resp:async":true,"resp:operation:id":"01CTR4AD6FC3H0QCYFKBKMQGJW","service":"server","time":"2018-10-26T12:06:57.503Z"}}
{"level":"info","log":{"message":"completed handling request","method":"DELETE","remote":"172.17.0.36:48712","request":"/v2/service_instances/6655f2a5-d917-11e8-a143-0242ac110027?accepts_incomplete=true\u0026plan_id=a6078798-70a1-4674-af94-ab9664d36a54\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","size":63,"status":202,"time":"2018-10-26T12:06:57.503Z","took":104767235}}
{"level":"info","log":{"message":"Deleting chart with release name [hb-redis-micro-6655f2a5-d917-11e8-a143-0242ac110027]","purge":true,"service":"helm_client","time":"2018-10-26T12:06:57.506Z"}}
{"level":"info","log":{"message":"started handling request","method":"GET","remote":"172.17.0.36:48712","request":"/v2/service_instances/6655f2a5-d917-11e8-a143-0242ac110027/last_operation?operation=01CTR4AD6FC3H0QCYFKBKMQGJW\u0026plan_id=a6078798-70a1-4674-af94-ab9664d36a54\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","time":"2018-10-26T12:06:58.589Z"}}
{"level":"info","log":{"action":"getLastOperation","instance:id":"6655f2a5-d917-11e8-a143-0242ac110027","message":"action response","operation:id":"01CTR4AD6FC3H0QCYFKBKMQGJW","resp:operation:desc":"deprovisioning succeeded","resp:operation:state":"succeeded","service":"server","time":"2018-10-26T12:06:58.59Z"}}
{"level":"info","log":{"message":"completed handling request","method":"GET","remote":"172.17.0.36:48712","request":"/v2/service_instances/6655f2a5-d917-11e8-a143-0242ac110027/last_operation?operation=01CTR4AD6FC3H0QCYFKBKMQGJW\u0026plan_id=a6078798-70a1-4674-af94-ab9664d36a54\u0026service_id=a2257daa-0e26-4c61-a68d-8a7453c1b767","size":62,"status":200,"time":"2018-10-26T12:06:58.59Z","took":1508361}}
{"level":"info","log":{"message":"started handling request","method":"GET","remote":"127.0.0.1:50664","request":"/statusz","time":"2018-10-26T12:06:59.734Z"}}
{"level":"info","log":{"message":"completed handling request","method":"GET","remote":"127.0.0.1:50664","request":"/statusz","size":2,"status":200,"time":"2018-10-26T12:06:59.735Z","took":144238}}
```

```
k get serviceinstance -n kubeless-test
No resources found.
```

```
k get deployment -n kubeless-test
No resources found.
```
