### ISSUE TITLE
[Telemetry Operator] Extract parsers into dedicated CRD

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14554]
**Description**
As outlined in https://github.com/kyma-project/community/pull/675 the parsers a re central configuration element and should not be defined per pipeline. Instead they should be defined in an individual CRD.

```YAML
kind: LogParser # cluster scope
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: multiline-custom-regex
spec:
  parser: # Name is rejected as it gets generated out of resource name
          # Will be registered as parser to be used in annotations or in a pipeline via a custom parser filter
      |
        Format regex
        Regex ^(?<INT>[^ ]+) (?<FLOAT>[^ ]+) (?<BOOL>[^ ]+) (?<STRING>.+)$
```

**Criteria**
- Have a dedicated CRD for parsers
- No parsers or multilineParser section in LogPipeline anymore
- When defining a parser in the CRD, the user can reference it in  an annotation and it gets applied. Also the user can use it in a custom parser filter of a pipeline
- Activate typical multilineParsers out of the box as we will not have them configurable for now
- Example is present in operator/config/examples folder
