### ISSUE TITLE
[Telemetry Operator] Add http output with minimal attribute set

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14557]
**Description**
Introduce an output definition for pushing logs using the http output plugin, also see https://github.com/kyma-project/community/pull/675/files. Settings for a typical OpenSearch integration are needed:
- host - value and valueFrom support needed
- http_User - value and valueFrom support needed
- http_Passwd  - value and valueFrom support needed
- uri: value

All other values need meaningful defaults like having TLS switched on

For now the valueFrom must support the secretKeyRef notation only

```YAML
  output: #only one output, no output should fail validation
    http: # enables http output
      Host: # next 3 attributes should be configurable by static value and valueFrom incl. secret rotation
        value: "icke.com"
        valueFrom: ...
      HTTP_User:
        value: "icke"
        valueFrom:
          secretKeyRef:
            name: my-elastic-credentials
            namespace: default
            key: ES_USER
      HTTP_Password:
        value: "icke.com"
        valueFrom: ...
      URI: /customindex/kyma
```

**Criterias**
- defining an output of type "http" is possible
- users can inject values from secrets
- default setup is using TLS
- integration tests with in-cluster HTTP backend
