### ISSUE TITLE
[Telemetry Operator] Refactor secretRefs

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14558]
**Description**
As outlined in https://github.com/kyma-project/community/pull/675 the secretRefs attribute needs to be transformed into a "variables" attribute. Hereby, an explicit key mapping is required by design.

The minimal scope should cover that API:
```YAML
  variables: # env variables to be used in custom plugins
    - name: myEnv2
      valueFrom:
        secretKeyRef:
          name: my-elastic-credentials
          namespace: default
          key: ES_ENDPOINT
```

**Criterias**
- API is formulated as proposed
- User can provide secrets to a custom plugin config
- variables names must be global unique, if not, a validation fails with a nice error message pointing to the conflicting variables (incl. name of pipeline)
- examples are adjusted
