### ISSUE TITLE
[Telemetry Operator] Support for podLabels selection on application input

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14563]
**Description**
Besides the selection of namespaces and containers to process application logs from, users need a way to select specific workloads on an input. According to https://github.com/kyma-project/community/pull/675/files a "podLabels" selector is needed as well as a "excludePodLabels" selector so that users can select workload based on label expresseions:
```YAML
input:
  application:
    podLabels: # generates a "grep" filter as a first element in the chain selecting logs by the "kubernetes" attributes
      - app: icke1
        managedBy: Ben
      - app: icke2
    excludePodLabels:
      - app: chris
```
**Update**
After investigating the ticket we have found that with normal grep filter we can only perform a Logical AND (by performing multiple `greps`). Logical OR is not possible with grep filter. To proceed further we should investigate further into following:
1. If we can achieve logical OR and AND using `lua`
2. Also we should investigate the performance with multiple `greps` and with `lua`

The selectors will be translated into filter definitions to be placed as first elements in the generated filter chain.

**Criterias**
- On an "application" input, users can select and exclude pods by providing typical selector expressions
- There can be multiple selector expressions (for realising OR logic) consisting of a struct (realising the AND logic)
- Logs not matching the selectors will be dropped
- Logs matching the exclude-selectors will be dropped
- Both kind of selectors can be used in parallel
- tests
