### ISSUE TITLE
[Telemetry Operator] Add input section for application logs with filters for rewrite_tag

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14564]
**Description**
According to https://github.com/kyma-project/community/pull/675/files a new root section for defining a single input is needed. Here, you can select a type of input and configure the different types with more details. 

Furthermore the namespace and container selectors are required, which will result into a rule expression for the related rewrite_tag filter.

```YAML
  input: # singular, different inputs require different pipelines and output configs
    application: # maps to central tail pipeline, dealing with the actual application logs
      namespaces: [] # generates the rule for the rewrite_tag assigned to every pipeline
      excludeNamespaces: []
      containers: []
      excludeContainers: []
```

**Criterias**
- the input section is optional, by default "application" type is selected without any selector
- all input types can be configured simultaneous (no exclusive or) as the used type will be selected by the "type" selector
- namespaces and containers selected or excluded need to be evaluated already on the rewrite_tag so that unnecessary logs can be dropped here already
- the selectors do not support wildcards for now
- include and exclude expressions cannot be used in parallel, validation should fail with appropriate validation message
- the defaults should not collect any logs from Kyma and Kubernetes system components
- the defaults should not collect any logs from fluentbit containers

**Comment by lindnerby** [comment]
Introduced an extra flag to `includeSystemNamespaces` within the application input to include system namespaces `kyma-system`, `kyma-integration`, `istio-system` and `kube-system` that are excluded by default when applying a logpipeline. Flag is overriden by explicitly defining exluded or included namespaces.

**Comment by lindnerby** [comment]
Adapted the API and documentation accordingly after feedback to match the following structure:
```
input:
  application:
    namespaces:
      include:
      exclude:
      system:
    containers:
      include:
      exclude:
```
