### ISSUE TITLE
[Telemetry Operator] add loki output plugin

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14560]
**Description**
In order to have loki integrated by default, the loki output needs to be supported by default, see also https://github.com/kyma-project/community/pull/675/files. For that a new output definition needs to be added with a minimal attribute set

```YAML
  output:
    grafana-loki:
      Url:
        value: "http://logging-loki:3100/loki/api/v1/push"
      Labels:
        "job": "telemetry-fluent-bit"
      RemoveKeys: ["kubernetes", "stream"]
      LabelMap:
        "kubernetes":
          "container_name": "container"
          "host": "node"
          "labels":
            "app": "app"
            "app.kubernetes.io/component": "component"
            "app.kubernetes.io/name": "app"
            "serverless.kyma-project.io/function-name": "function"
          "namespace_name": "namespace"
          "pod_name": "pod"
        "stream": "stream"
```

**Criterias**
- a new output is available for configuration
- all attributes are covered which are needed for the typical kyma integration scenario
- adjust examples
- adjust the logging component to use the new supported output
