### ISSUE TITLE
[Telemetry Operator] add filter for including/excluding logs based on attributes

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#14561]
**Description**

Users need a way to filter logs in regards to concrete values in the payload, like filtering for logs belonging to a specific tenant.
According to https://github.com/kyma-project/community/pull/675/files a new filter is needed which allows to include or exclude logs, translating to a "grep" filter definition.

The syntax for the keys should support simple attribute selection but also nested attribute selection. Here, we either use the same notation as fluentbit via record accessors or introduce an own syntax.

```YAML
  filters: # list of filters, order is important
    - include: # maps to "grep" filter, drops lines where attribute will not match the regexp
        key: tenant
        regexp: icke
    - exclude: # maps to "grep" filter, drops lines where attribute will not match the regexp
        key: severity
        regexp: debug
```

**Criterias:**
- User can select logs (drop logs which are not fitting) by matching the values of attributes
- Attributes can be nested
- Users can deselect logs by matching the values of attributes
- tests
