### ISSUE TITLE
Allow multiple Hostnames for istio-gateway

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#14648]
Currently https://github.com/kyma-project/kyma/blob/main/resources/istio-resources/templates/gateway.yaml allows only a single domain like 

`*.mydomain.com`

from the helm parameter global.domainName.

In our case we want to support to listen to 

www.mydomain.com and mydomain.com to host our service. Currently mydomain.com is not possible because only subdomains are supported.

The easiest way would be to add a second host for the istio gateway (and of cause providing a TLS Certificate which supports both domains).

The gateway spec should then look like

```
spec:
  selector:
    app: istio-ingressgateway
    istio: ingressgateway
  servers:
  - hosts:
    - '*.mydomain.com'
    - mydomain.com
    port:
      name: https
      number: 443
      protocol: HTTPS
```

From my point of view a new additional helm parameter to add additional gateways domains
