### ISSUE TITLE
Improve the configuring interface of Istio component helm chart

### ISSUE THREAD

**Issue by cnvergence** [kyma-project/kyma#14857]
**Description**

Currently, we are providing way to configure Istio Operator values using different keys, eg `.Values.components.ingressGateways` or `.Values.helmValues.global`.
It can be not confusing to users, so we should unify all of the IstioOperator [options](https://istio.io/latest/docs/reference/config/istio.operator.v1alpha1/) under `.Values.istioOperator` key.

**Reasons**

Provide simpler configuration interface in our Helm chart

**Comment by rufreakde** [comment]
Also working on this right now and finding something like this is very cumbersome...
```yaml
        - name: values.istio.helmValues.global.proxy.logging.level
          value: "none"
        - name: values.istio.meshConfig.accessLogFile
          value: ""
```
