### ISSUE TITLE
Spike: Evaluate Buildpack / Build System for Functions

### ISSUE THREAD

**Issue by joek** [kyma-project/kyma#1493]

**Comment by k15r** [comment]
I played a bit with knative, and used the kubeless runtime containers as a base for the function.
https://github.com/k15r/knative-node
The function is still stored in a config map. The problem with this is that the knative guys do not like to put information that should be versioned into a config map, as it currently cannot be versioned .
But as we currently already use a config map for storing the function, and as the image will persist the function i went that road.
https://github.com/k15r/knative-node

**Comment by sayanh** [comment]
As I continued on Korbinian's work, here's what I achieved:

### Concept
- The function is stored in a configmap along with the dependencies.

- The `Dockerfile` for function container image is also stored in a configmap. This removes the dependency on any form of git repo.

-  Host a docker repository inside Kyma cluster to remove any dependency on external docker repo. Having said that, using an external docker repository is also possible.

### Steps to be followed:

- Storing the function in a configmap here.
```yaml
cat << EOF | kubectl apply -n stage -f -
apiVersion: v1
data:
  handler: handler.main
  handler.js: |-
    'use strict';
      const _ = require('lodash');
      module.exports = {
          main: (event, context) => {
              _.assign(event.data, {date: new Date().toTimeString()});
              return JSON.stringify(event.data);
          },
      };
  package.json: |-
    {
      "name": "hellowithdeps",
      "version": "0.0.1",
      "dependencies": {
        "end-of-stream": "^1.4.1",
        "from2": "^2.3.0",
        "lodash": "^4.17.5"
      }
    }
kind: ConfigMap
metadata:
  labels:
    function: bla
  name: bla-knative
EOF
```

- The `Dockerfile` for function container image is also stored in a configmap. This removes the dependency on any form of external git repo.
```yaml
cat << EOF | kubectl apply -n stage -f -
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    function: bla
  name: bla-dockerfile
data:
  Dockerfile: |-
    FROM kubeless/nodejs@sha256:5c3c21cf29231f25a0d7d2669c6f18c686894bf44e975fcbbbb420c6d045f7e7
    USER root
    RUN export KUBELESS_INSTALL_VOLUME='/kubeless' && \
        mkdir /kubeless && \
        cp /src/handler.js /kubeless && \
        cp /src/package.json /kubeless && \
        /kubeless-npm-install.sh
    USER 1000
EOF
```

- Host a docker registry inside Kyma cluster in namespace `kyma-system`

```bash
#### Publicly exposing docker registry
echo "$(minikube ip) docker-reg.kyma.local" | sudo tee -a /etc/hosts
#### Publicly exposing docker registry
minikube ssh 'echo "127.0.0.1 docker-reg.kyma.local" | sudo tee -a /etc/hosts'
```

```yaml
#### Creating docker registry resources
cat << EOF | kubectl -n kyma-system apply -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker-registry
data:
  registry-config.yml: |
    version: 0.1
    log:
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      filesystem:
        rootdirectory: /var/lib/registry
    http:
      addr: :5000
      headers:
        X-Content-Type-Options: [nosniff]
    auth:
      htpasswd:
        realm: basic-realm
        path: /auth/htpasswd
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
---
apiVersion: v1
kind: Secret
metadata:
  name: docker-registry
type: Opaque
data:
  HTPASSWD: YWRtaW46JDJ5JDA1JHJwWHlibVNIMWhEV2VFYjJJUHg5aS5ENmh0MVZjMVBob3YyUnlXSEQzOFdEM1EvYlQ3em8uCgo=
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
  labels:
    app: docker-reg
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: docker-reg
---
apiVersion: apps/v1
kind: Deployment  ####  Can be a Statefulset as well
metadata:
  name: docker-reg
  labels:
    app: docker-reg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-reg
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: docker-reg
    spec:
      volumes:
        - name: config
          configMap:
            name: docker-registry
            items:
              - key: registry-config.yml
                path: config.yml
        - name: htpasswd
          secret:
            secretName: docker-registry
            items:
            - key: HTPASSWD
              path: htpasswd
        - name: storage
          emptyDir: {}
      containers:
        - name: docker-registry
          image: registry:2.6.2
          resources:
            limits:
              memory: 2G
            requests:
              memory: 32Mi
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          volumeMounts:
            - name: config
              mountPath: /etc/docker/registry
              readOnly: true
            - name: htpasswd
              mountPath: /auth
              readOnly: true
            - name: storage #### Can be a PersistentVolumeClaim
              mountPath: /var/lib/registry
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  labels:
    app: docker-registry
  name: docker-registry
  namespace: kyma-system
spec:
  gateways:
  - kyma-gateway
  hosts:
  - docker-reg.kyma.local
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: docker-registry
        port:
          number: 5000
EOF
```

- Creating secrets related to the docker-registry in an `istio-enabled=true` namespace, `stage`.
Turns out the `ResourceQuota` and `LimitRange` for this namespace is too less for a Knative build. Hence deleting them for now(can be increased as well):

```bash
kubectl -n stage delete resourcequotas kyma-default
kubectl -n stage delete limitranges kyma-default
```

```yaml
cat << EOF | kubectl -n stage apply -f -
## Secret used by build
apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass-new
  annotations:
    build.knative.dev/docker-0: http://docker-registry.kyma-system.svc.cluster.local:5000/
type: kubernetes.io/basic-auth
data:
  # Use 'echo -n "username" | base64' to generate this string
  username: YWRtaW4=
  # Use 'echo -n "password" | base64' to generate this string
  password: YWRtaW4xMjM=
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-bot-new
secrets:
- name: basic-user-pass-new
---
## Secret used by revision
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkb2NrZXItcmVnLmt5bWEubG9jYWwiOnsiVXNlcm5hbWUiOiJhZG1pbiIsIlBhc3N3b3JkIjoiYWRtaW4xMjMiLCJFbWFpbCI6IiJ9fX0=
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: pull-regcred
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-regcred
imagePullSecrets:
- name: pull-regcred
EOF
```

- Recreating Knative serving controller with DNS mapping for `docker-reg.kyma.local`
```yaml
#### Replace minikube ip in line 320
minikube_ip=$(minikube ip)
deployment=$(cat << EOF
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  name: controller
  namespace: knative-serving
  selfLink: /apis/extensions/v1beta1/namespaces/knative-serving/deployments/controller
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: controller
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
      creationTimestamp: null
      labels:
        app: controller
    spec:
      hostAliases:
      - ip: "${minikube_ip}" ### Replace with your minikube ip
        hostnames:
        - "docker-reg.kyma.local"
      containers:
      - image: gcr.io/knative-releases/github.com/knative/serving/cmd/controller@sha256:455c17eed5d0472ffbba26d77e029598bbcb42d612da20efe9820f91b9f1aedd
        imagePullPolicy: IfNotPresent
        name: controller
        ports:
        - containerPort: 9090
          name: metrics
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config-logging
          name: config-logging
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: controller
      serviceAccountName: controller
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: config-logging
        name: config-logging
status: {}
EOF
)
echo $deployment | kubectl apply -f -
```

- Create Serving resource with images pointing to the locally situated docker-registry
```yaml
cat << EOF | kubectl -n stage apply -f -
apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: helloworld-nodejs
spec:
  runLatest:
    configuration:
      build:
        serviceAccountName: build-bot-new
        steps:
        - name: build-and-push
          image: gcr.io/kaniko-project/executor
          args:
          - --dockerfile=/workspace/Dockerfile
          - --skip-tls-verify  ### If mTLS is enabled, this can be ommited 
          - --destination=docker-registry.kyma-system.svc.cluster.local:5000/knative-node:v1
          - --verbosity=warn
          volumeMounts:
          - name: bla-dockerfile-vol
            mountPath: /workspace
          - name: bla-deps
            mountPath: /src
        volumes:
        - name: bla-dockerfile-vol
          configMap:
            defaultMode: 420
            name: bla-dockerfile
        - name: bla-deps
          configMap:
            defaultMode: 420
            name: bla-knative
      revisionTemplate:
        spec:
          serviceAccountName: pull-regcred
          container:
            image: docker-reg.kyma.local/knative-node:v1
            env:
            - name: FUNC_HANDLER
              value: main
            - name: MOD_NAME
              value: handler
            - name: FUNC_TIMEOUT
              value: "180"
            - name: FUNC_RUNTIME
              value: nodejs8
            - name: FUNC_MEMORY_LIMIT
              value: 128Mi
            - name: FUNC_PORT
              value: "8080"
            - name: NODE_PATH
              value: "\$(KUBELESS_INSTALL_VOLUME)/node_modules"
EOF
```

- Test the function is working
```bash
curl -v -H "Host: helloworld-nodejs.stage.example.com" http://$(minikube ip):$(kubectl get svc knative-ingressgateway --namespace istio-system --output 'jsonpath={.spec.ports[?(@.port==80)].nodePort}')
```
