### ISSUE TITLE
Check Nats Jetstream clustering setup

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#14962]
## Description

Investigate our clustering setup for NATS. 
During an issue investigation we noticed, that the NATS Server itself reported to be healthy, but the Jetstream Server part (within the NATS server) was not responding. This rendered the entire eventing setup unusable.

## Acceptance
- [x] verify that NATS Server and the Jetstream part within both are setup correctly to form a cluster over all existing NATS Server nodes
- [x] streams created on Jetstream must have replicas on all server nodes
- [x] server nodes must be distributed across the kubernetes cluster, spanning multiple availability zones 

Questions:

- do we need to setup 5 server nodes in order to allow an outage on an entire availability zone?
- 3 availability zones / 3 cluster nodes : how does it affect performance?

**Comment by k15r** [comment]
TB: 3d

**Comment by friedrichwilken** [comment]
- [ ] verify that NATS Server and the Jetstream part within both are setup correctly to form a cluster over all existing NATS 
-> yes, this looks to be setup properly:
	```yaml
	affinity:
	    podAntiAffinity: #looks for other pods that need to be avoided
	        preferredDuringSchedulingIgnoredDuringExecution: #prefered is weaker then required
			- podAffinityTerm: #look for setup of pod
				labelSelector: # looks for labels
			        matchLabels: #labels that match exactly
						nats_cluster: eventing-nats 
				topologyKey: kubernetes.io/hostname ## for one replica for each zone
            weight: 100 # 0-100 value for preferredDuring... to weight against other preference rules
	```


- [ ] streams created on Jetstream must have replicas on all server nodes
```shell
Information for Stream sap created 2022-08-08T19:39:58+02:00

Configuration:

             Subjects: kyma.>
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 3
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: eventing-nats
               Leader: eventing-nats-1
              Replica: eventing-nats-0, current, seen 0.42s ago
              Replica: eventing-nats-2, current, seen 0.41s ago

```
- [ ] server nodes must be distributed across the kubernetes cluster, spanning multiple availability zones 
on a system with 3 zones and 3 nodes for each zone (for a total of 9 nodes)
```bash
NAME                                                     STATUS   ROLES    AGE    VERSION
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-89hj5   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-kgfxg   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-lx6fb   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-s5rlt   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-zpnfl   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-bv5vg   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-jct6v   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-wgswk   Ready    <none>   123m   v1.21.14
```
(note the `z1` to `z3` in the name to mark each zone) there are three clusters, as described in the `statefulset`
```shell
NAME                                                     READY   STATUS    RESTARTS   AGE
eventing-nats-0                                          3/3     Running   0          113m
eventing-nats-1                                          3/3     Running   0          112m
eventing-nats-2                                          3/3     Running   0          111m  
```
where `eventing-nats-0` exists on a node 
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-jct6v
```
that exists in `eastus-3`
```yaml
labels:
	...
    topology.disk.csi.azure.com/zone: eastus-3
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-3
```
while `eventing-node-1` exists on node
```shell
  nodeName: shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-89hj5
```
that exists in `eastus-2`
```yaml
labels:
	...
    topology.disk.csi.azure.com/zone: eastus-2
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-2
```
finally `eventing-node-2` exists on node
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt
```
that exists in `eastus-1`
```yaml
labels:
	...
    topology.disk.csi.azure.com/zone: eastus-1
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-1
```
**So all three nats-server pods exist in different zones**

When the labels of the last mentioned node, `shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt`, gets changed from
```yaml 
topology.kubernetes.io/zone: eastus-1
```
to 
```yaml
topology.kubernetes.io/zone: eastus-2
```
(which seams to be not reconciled for at least 2 minutes)
the `eventing-node-2` stays on node
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt
```
when deleting the pod it gets recreated on 
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-zpnfl
```
that exists in zone 
```yaml
labels:
    ...
    topology.disk.csi.azure.com/zone: eastus-1
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-1
```
**Changing the zone label of the node, on that the pod exists will not trigger a reconciliation on a different node in the expected zone. Deletion of the aforementioned pod will lead to a recreation of the pod in the expected zone.**

Changing the hostname label from:
```yaml
kubernetes.io/hostname: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-zpnfl
```
to
```yaml
kubernetes.io/hostname: shoot--kymatunas--fw-mzone-worker-k5pdi-z2-7cbc4-zpnfl
```
will also not trigger a recreation of the pod.

**Comment by friedrichwilken** [comment]
- [ ] streams created on Jetstream must have replicas on all server nodes.
First, there is some ambiguity here about the expression "server node" since there are not only `k8s server nodes` but also `NATS server nodes`. Please be more precise if the context is "NATS on k8s".

On a system with 3 zones and 3 nodes for each zone (for a total of 9 nodes) on a `production` cluster the NATS setup looked like this.
```shell
Information for Stream sap created 2022-08-08T19:39:58+02:00

Configuration:

             Subjects: kyma.>
     Acknowledgements: true
            Retention: File - Interest
             Replicas: 3
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: eventing-nats
               Leader: eventing-nats-1
              Replica: eventing-nats-0, current, seen 0.42s ago
              Replica: eventing-nats-2, current, seen 0.41s ago
```
So there are three NATS server in the k8s-cluster.

The k8s-cluster has these nine k8s-nodes. Note the `z1` to `z3` part of the k8s-node's names that corresponds with the `zone`s 1 to 3.

```bash
NAME                                                     STATUS   ROLES    AGE    VERSION
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-89hj5   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-kgfxg   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-lx6fb   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-s5rlt   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-zpnfl   Ready    <none>   123m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-bv5vg   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-jct6v   Ready    <none>   122m   v1.21.14
shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-wgswk   Ready    <none>   123m   v1.21.14
```

There are three `eventing-nats-` pods, as described in the `statefulset`
```shell
NAME                                                     READY   STATUS    RESTARTS   AGE
eventing-nats-0                                          3/3     Running   0          113m
eventing-nats-1                                          3/3     Running   0          112m
eventing-nats-2                                          3/3     Running   0          111m  
```

where `eventing-nats-0` was scheduled on k8s-node
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-jct6v
```
that exists in `eastus-3` aka `z3`
```yaml
labels:
    ...
    kubernetes.io/hostname: shoot--kymatunas--fw-mzone-worker-oljl5-z3-6cc78-jct6v
    ...
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-3
```


while `eventing-node-1` was
```shell
  nodeName: shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-89hj5
```
that exists in `eastus-2` aka `z2`
```yaml
labels:
    ...
    kubernetes.io/hostname: shoot--kymatunas--fw-mzone-worker-fcunz-z2-9f4b5-89hj5
    ...
    topology.disk.csi.azure.com/zone: eastus-2
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-2
```


finally `eventing-node-2` exists on node
```yaml
nodeName: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt
```
that exists in `eastus-1` aka `z1`
```yaml
labels:
    ...
    kubernetes.io/hostname: shoot--kymatunas--fw-mzone-worker-k5pdi-z1-7cbc4-qq7tt
    ...
    topology.disk.csi.azure.com/zone: eastus-1
    topology.kubernetes.io/region: eastus
    topology.kubernetes.io/zone: eastus-1
```

**So all three nats-server pods have been scheduled on different k8s-nodes and in different zones**

**Question: Are they all in different zones by chance?**

When changing the labels of the k8s-nodes `kubernetes.io/hostname` or `topology.kubernetes.io/zone` get changed the pods do not get rescheduled as expected by the affinity rule (the `IgnoredDuringExecution` part in `preferredDuringSchedulingIgnoredDuringExecution`). 

Changing the `zone` label on a k8s-node to create a constellation where 2 pod where in the same zone and then deleting one of these pods lead to the pod getting scheduled on a different k8s-node within a different zone, so all there nodes where in different zones again. ** Question: was this by chance? **

The same behaviour was observed after changing the `hostname` label to duplicate the the hostname, which was expected considering the affinity rules.
