### ISSUE TITLE
[v1a1->v1a2] invalid minReplicas

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15004]
After conversion minReplicas has value from maxReplicas.

input:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-007-1
  namespace: default
spec:
  minReplicas: 2
  maxReplicas: 3
  runtime: python39
  source: |-
    def main(event, context):
        return "hello world"
```
result (minReplicas==3 !):
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-007-1
  [...]
spec:
  maxReplicas: 3
  minReplicas: 3
  [...]
status:
  [...]
```

I am using kyma taken from main on August 2.
For conversion I use command `kubectl apply -f input.yaml`.

**Related issues**
https://github.com/kyma-project/kyma/issues/14593
