### ISSUE TITLE
[v1a1->v1a2] unexpected min/maxReplicas

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15005]
When we `apply` function in version `v1alpha2` we get default `min/maxReplicas` in result. It's different behavior from `v1alpha1`.

input:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-2
  namespace: default
spec:
  runtime: python39
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
```
result (default `min/maxReplicas`):
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-2
  [...]
spec:
  maxReplicas: 1
  minReplicas: 1
  [...]
status:
  [...]
```

The same with `v1alpha1`
input:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-001-1
  namespace: default
spec:
  runtime: python39
  source: |-
    def main(event, context):
        return "hello world"
```
result (without `min/maxReplicas`):
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-1
  [...]
spec:
  resourceConfiguration:
    build:
      resources: {}
    function:
      resources: {}
  runtime: python39
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
  template: {}
status:
  [...]
```

I am using kyma taken from main on August 2.
For conversion I use command `kubectl apply -f input.yaml`.

**Related issues**
https://github.com/kyma-project/kyma/issues/14593
