### ISSUE TITLE
[v1a1->v1a2] empty resources

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15003]
After conversion we have empty resource configuration. Expected (probably) are default values.

input:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-001-1
  namespace: default
spec:
  runtime: python39
  source: |-
    def main(event, context):
        return "hello world"
```
result:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-1
  [...]
spec:
  resourceConfiguration:
    build:
      resources: {}
    function:
      resources: {}
  [...]
status:
  [...]
```

The same in v1alpha2:
input:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-2
  namespace: default
spec:
  runtime: python39
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
```
result (contains default resourceConfiguration.function.resources):
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-2
  [...]
spec:
  resourceConfiguration:
    build:
      resources: {}
    function:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
  [...]
status:
  [...]
```

I am using kyma taken from main on August 2.
For conversion I use command `kubectl apply -f input.yaml`.

**Related issues**
https://github.com/kyma-project/kyma/issues/14593
