### ISSUE TITLE
Invalid function spec is passed to the control loop but it should be rejected at validation time

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15015]
When we have validation in `v1alpha2` but we haven't it in `v1alpha1` we can do `kubectl apply -f 009-1-resources.yaml` without errors.
Later we see function without status (the same like in #15013).

input:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-009-1
  namespace: default
spec:
  resources:
    limits:
      cpu: 1
      memory: 2
    requests:
      cpu: 3
      memory: 4
  runtime: python39
  source: |-
    def main(event, context):
        return "hello world"
```
`kubectl logs -n kyma-system serverless-ctrl-mngr-cc5fddc8f-crbx5 | grep function-009-1` shows:
```
{"level":"WARN","timestamp":"2022-08-04T11:24:32Z","logger":"controllers.function","caller":"serverless/fsm.go:135","message":"while updating function status: admission webhook \"validation.webhook.serverless.kyma-project.io\" denied the request: validation failed: [invalid function resources: [spec.resourceConfiguration.function.resources.requests.memory(4) should be higher than minimal value (16Mi) spec.resourceConfiguration.function.resources.limits.cpu(1) should be higher than spec.resourceConfiguration.function.resources.requests.cpu(3) spec.resourceConfiguration.function.resources.limits.memory(2) should be higher than spec.resourceConfiguration.function.resources.requests.memory(4) spec.resourceConfiguration.function.resources.limits.memory(2) should be higher than minimal value (16Mi)]]","context":{"kind":"Function","name":"function-009-1","namespace":"default","version":1}}
```

I am using kyma taken from main on August 2.
