### ISSUE TITLE
[v1a1->v1a2] why spec.source.inline.dependencies is required

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15013]
Why spec.source.inline.dependencies (`v1alpha2`) is required? 
This field looks like a good candidate for optional. Corresponding field in `v1alpha1` is optional.

input:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-001-2
  namespace: default
spec:
  runtime: python39
  source:
    inline:
      source: |-
        def main(event, context):
            return "hello world"
```
`kubectl apply -f 001-2-simple-wo-deps.yaml` shows:
```
error: error validating "001-2-simple-wo-deps.yaml": error validating data: ValidationError(Function.spec.source.inline): missing required field "dependencies" in io.kyma-project.serverless.v1alpha2.Function.spec.source.inline; if you choose to ignore these errors, turn validation off with --validate=false
```

I am using kyma taken from main on August 2.
For conversion I use command `kubectl apply -f input.yaml`.
