### ISSUE TITLE
[v1a1->v1a2] Function with runtimeImageOverride don't work

### ISSUE THREAD

**Issue by anoipm** [kyma-project/kyma#15017]
I tried run function with `runtimeImageOverride`. I have error `Minimum replcas not available for deployment function-013-2-rz8ww` and I can't localize any informatiion about what went wrong. 

input:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-013-2
  namespace: default
spec:
  runtimeImageOverride: "python:3.9.13-slim-bullseye"
  runtime: python39
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
```
result:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-013-2
  [...]
spec:
  [...]
  runtime: python39
  runtimeImageOverride: python:3.9.13-slim-bullseye
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
  template: {}
status:
  conditions:
  - lastTransitionTime: "2022-08-04T13:05:47Z"
    message: Minimum replcas not available for deployment function-013-2-rz8ww
    reason: MinReplicasNotAvailable
    status: Unknown
    type: Running
  - lastTransitionTime: "2022-08-04T13:05:46Z"
    message: Job function-013-2-build-zvxs9 finished
    reason: JobFinished
    status: "True"
    type: BuildReady
  - lastTransitionTime: "2022-08-04T13:05:30Z"
    message: 'Updated ConfigMap: "function-013-2-m9f2w"'
    reason: ConfigMapUpdated
    status: "True"
    type: ConfigurationReady
  runtime: python39
  runtimeImageOverride: python:3.9.13-slim-bullseye
```

`kubectl get pod` shows:
```
NAME                                    READY   STATUS             RESTARTS   AGE
function-013-2-build-zvxs9-5qlq8        0/1     Completed          0          20h
function-013-2-rz8ww-5c678d6b7f-ln75s   0/1     CrashLoopBackOff   99         20h
```

`kubectl logs function-013-2-rz8ww-5c678d6b7f-ln75s` shows nothing.

I am using kyma taken from main on August 2.
For conversion I use command `kubectl apply -f input.yaml`.

**Comment by kwiatekus** [comment]
The custom image you use must fulfill the prerequisites documented here
https://kyma-project.io/docs/kyma/main/05-technical-reference/svls-08-function-specification#override-runtime-image

Try this one, and it will work

```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: function-013-2
  namespace: default
spec:
  runtimeImageOverride: "kwiatekus/python-runtime-debian:latest"
  runtime: python39
  source:
    inline:
      dependencies: ""
      source: |-
        def main(event, context):
            return "hello world"
```
