### ISSUE TITLE
ssh git url is not parsed correctly by function controller

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15065]
**Description**
Function controler fail to reconcile git functions with ssh url format

**Attachments**
```
{"level":"WARN","timestamp":"2022-08-10T07:55:05Z","logger":"controllers.function","caller":"serverless/fsm.go:135","message":"while updating function status: admission webhook \"validation.webhook.serverless.kyma-project.io\" denied the request: validation failed: [invalid source.gitRepository.URL value: parse \"git@ssh.dev.azure.com:v3/kyma-wookiee/kyma-function/azure-devops-sample-function\": invalid URI for request]","context":{"kind":"Function","name":"fun4-azure-devops-node-ssh","namespace":"default","version":2}}
```

```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: GitRepository
metadata:
...
  name: azure-devops-ssh
  namespace: default
...
spec:
  auth:
    secretName: azure-repo-ssh-key
    type: key
  url: >-
    git@ssh.dev.azure.com:v3/kyma-wookiee/kyma-function/azure-devops-sample-function
```
