### ISSUE TITLE
Defaulting webhook denies requests with empty build resources config

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15082]
**Description**

**Steps to reproduce**

Apply the following function:
```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: bug
  namespace: default
spec:
  maxReplicas: 5
  minReplicas: 1
  resourceConfiguration:
    build:
      resources: {}
    function:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
  runtime: nodejs14
  source:
    inline:
      dependencies: "{ \n  \"name\": \"blaaa\",\n  \"version\": \"1.0.0\",\n  \"dependencies\":
        {}\n}"
      source: "module.exports = { \n  main: function (event, context) {\n    return
        \"Hello World!\";\n  }\n}"
  template: {}
```

Go to Kyma UI try and edit it's resources ( i.e change min replicas )

You will see and error originating from defaulting webhook

![Image](https://user-images.githubusercontent.com/6783567/184118263-6bfcf2a6-6a24-443c-a041-116738ace9f6.png)
