### ISSUE TITLE
[Telemetry Operator] Bad default handling in LogPipeline resource

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15134]
**Description**
Creating a LogPipeline resource on the APIServer is defaulting several attributes to an empty map. That behaviour is not expected and not common.

For example, creating a resource like that:
```
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: icke1
spec:
  output:
    custom: |
      Name               stdout
```

and then calling `k get logpipeline icke1 -oyaml` will return:
```

apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  XXX (not relevant here)
spec:
  output:
    custom: |
      Name               stdout
    grafana-loki:
      url:
        valueFrom:
          secretKeyRef: {}
    http:
      host:
        valueFrom:
          secretKeyRef: {}
      password:
        valueFrom:
          secretKeyRef: {}
      tls: {}
      user:
        valueFrom:
          secretKeyRef: {}
```

I expect that only the spec attributes are defined which I defined in the create statement
