### ISSUE TITLE
Profile is not propagaded during conversion v1alpha1 -> v1alpha2 

### ISSUE THREAD

**Issue by dbadura** [kyma-project/kyma#15288]
**Description**
Conversion webhook doesn't propagade profile during conversion from v1alpha1 to v1alpha2

**Expected result**
The profile will be correctly propagaded.

**Actual result**
The profile is not propagaded.

**Steps to reproduce**
Create v1alpha1 function:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: function-001-v1
  labels:
    "serverless.kyma-project.io/function-resources-preset": L
spec:
  deps: ""
  source: |-
      def main(event, context):
          return "hello world"
```

**Troubleshooting**

Here is `TODO` which mention this problem in code: 
https://github.com/kyma-project/kyma/blob/main/components/function-controller/internal/webhook/conversion_webhook.go#L181

**Comment by kwiatekus** [comment]
We need to deprecate the label. Labels should be used only for searching.
Preset value should end up in preset field of the build configuration spec.

In case of conversion v1alpha1->v1alpha2:
 - the label value should be moved to the spec field

In the v1alpha2 defaulting webhook:
 - if the label exists but the spec filed not, than the value from label should be moved to the spec
 - the build and function resources (cpu, memory) should be configured according to the preset value

**Comment by anoipm** [comment]
TODO:
- [ ] conversion `build-resources-preset` (v1a1) to `resourceConfiguration.build.profile` (v1a2),
- [ ] conversion `resourceConfiguration.build.profile` (v1a2) to `build-resources-preset` (v1a1),
- [ ] conversion `function-resources-preset` (v1a1) to `resourceConfiguration.function.profile` (v1a2),
- [ ] conversion `resourceConfiguration.function.profile` (v1a2) to `function-resources-preset` (v1a1),
- [ ] investigation what to do with `replicas-preset` (v1a1),
- [ ] fix documentation incostistency between preset values in docs/05-technical-reference/svls-09-available-presets.md and resources/serverless/charts/webhook/values.yaml for "slow" in "buildJob",
- [ ] change documentation about presets (dedicated fields instead of labels),
- [ ] ...

**Comment by kwiatekus** [comment]
It looks to me that the actual build/runtime resources are not controlled by the `spec.resourceConfiguration.function|build.profile`

I see that that field is properly populated via conversion and defaulting, but when I edit the field (from `XL` to `S`), nothing happens. The resources (`request` and `limits`) remain the same.

```
spec:
  resourceConfiguration:
    function:
      profile: S
      resources:
        limits:
          cpu: 1600m //< --- this still corresponds to XL
          memory: 2Gi //< --- this still corresponds to XL
        requests:
          cpu: 800m //< --- this still corresponds to XL
          memory: 1Gi //< --- this still corresponds to XL
```
