### ISSUE TITLE
[Telemetry Operator] Loki URL is a ValueType, but secrets are not supported

### ISSUE THREAD

**Issue by skhalash** [kyma-project/kyma#15320]
**Description**

The `grafana-loki` output plugin has an URL field, which is of type `ValueType`. It is either a string value or a reference to a value in a Kuberenetes secret. It should work the same way as HTTP output host, user, and password. However secret support for the Loki output has been never implemented.

```yaml
  output:
    grafana-loki:
      labels:
        job: telemetry-fluent-bit
      removeKeys:
      - kubernetes
      - stream
      url:
        value: http://logging-loki:3100/loki/api/v1/push
        valueFrom:
          secretKeyRef: {}
```

Actually, there was no need for Loki URL to be of type `ValueType`, it could have been a plain `string`. However, changing it back to `string` will be a breaking change. That's why it's just easier to add secret support for it and in general, make it easy for an output plugin to define a new field of type `ValueType`. Currently, this logic is scattered across multiple places.

**Expected result**

If a field supports secrets according to the API, it should actually work.

**Actual result**

Loki URL only supports strings, but not secrets.

**Steps to reproduce**

**Troubleshooting**
