### ISSUE TITLE
validation.webhook.serverless.kyma-project.io does not allow for  gardener hibernation

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15394]
**Description**
I see clusters which are installed from main having warnings from gardener:
"Your hibernation schedule may not have any effect: ValidatingWebhookConfiguration "validation.webhook.serverless.kyma-project.io" is problematic and was remediated by Gardener (please check its annotations for details)."

 Please  check that our webhooks are excluding the kube-system namespace.

 - I.e for [this](https://dashboard.garden.canary.k8s.ondemand.com/namespace/garden-wookiee/shoots/demo-rec/) cluster

**Attachments**

![Image](https://user-images.githubusercontent.com/6783567/188905036-ad28322a-a854-4bbd-86c5-83a3951f5182.png)

**Comment by pPrecel** [comment]
Webhook's annotation:

```
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation.webhook.serverless.kyma-project.io
  annotations:
    gardener.cloud/warning: |-
      ATTENTION: This webhook configuration has been modified by Gardener since it does not follow the best practices recommended by Kubernetes (https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#best-practices-and-warnings) and might interfere with the cluster operations. Please make sure to follow these recommendations to prevent future interventions. When you are done, please remove this annotation. See also https://github.com/gardener/gardener/blob/master/docs/usage/shoot_status.md#constraints for further information.
      The following modifications have been made:
      - timeoutSeconds of webhook "validation.webhook.serverless.kyma-project.io" was set to 15
...
```

here is the line from the gardener's code base which returns this error:
https://github.com/gardener/gardener/blob/8ead4a3d7b30e67bd8f4c6a1041c9cb45fbe195b/pkg/operation/care/constraints.go#L271

weird thing is that this problem occurs only on the Azure clusters :)
