### ISSUE TITLE
Expose Outbound IP address info HA kyma clusters

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#15451]
**Description**

Outbound IP addresses of Kyma clusters should be discoverable for end users. Options:
- request exposing outbound IPs as a Gardener feature: [Expose NAT gateway IP in the shoot cluster](https://github.com/gardener/gardener-extension-provider-azure/issues/606) (similar to: https://github.com/gardener/gardener/issues/3873)
- provide a tutorial/script or kyma CLI/Dashboard feature to obtain outbound IPs
- provide control-plane controller that publishes outbound IPs as a managed resource (only if it can't be done in Gardener)

**Reasons**
Some services exposed with public IP require well known stable IP allowlist for security reasons. The outbound IP addresses of managed Kyma clusters (based on Gardener) are not exposed to end users. Right now users are asked to create a ticket and they get list of IPs with the manual process. It should be automated.

**Attachments**

Related gardener issue that could solve the problem:
- https://github.com/gardener/gardener/issues/3873

---
<details>
    <summary>:warning: Funnel process - do not remove!</summary>
    </br>

Name|Value
:--- | :---
theme | Enterprise-grade
business value | 10
technical value | 0
user value | 10
open-source value | 0
effort | 
requested by | 
</details>

**Comment by pbochynski** [comment]
Blocked by: https://github.com/gardener/gardener-extension-provider-azure/issues/606

**Comment by pbochynski** [comment]
As the feature in Gardenes is still not implemented, and we get many questions how to get cluster egress IPs, I decided to create a simple kubernetes operator that can retrieve all the IPs assigned to Kubernetes nodes. It works for any Kubernetes cluster. The list is updated when new nodes are added to the cluster (if there is a new IP). In case of SAP Kyma Runtime it is enough to fetch the IP list only once as Kyma uses NAT gateways with stable IPs.
Source code: https://github.com/pbochynski/cluster-ip
Tutorial: https://killercoda.com/kyma-project/scenario/cluster-ip

**Comment by tobiscr** [comment]
If we have any chance to retrieve hte public IP from Gardener, we could cover this part in KIM. 

@ebensom  - do you have any recommendation / idea how KIM could figure out in an easy way which public IP is used b the LB?

I would have following options in mind:
* We get the IPs from hyperscaler directly (from security point challenging as KIM would require READ permissions for each account)
* We can get it from SKR cluster (haven't yet checked how good that wold work , e.g. either by checking information on service-instance level or using [external webservices](https://linuxconfig.org/how-to-use-curl-to-get-public-ip-address) to get the IP)
* We again ping Gardener to reopen [the previous request](https://github.com/gardener/gardener/issues/3873) and to provide this information on Shoot level

**Comment by pbochynski** [comment]
Yes, it is still required. Moreover, we would need a central component to report external IPs to some systems that can evaluate access policy. I would rather directly get IPs from cloud provider API by KIM. You can do it the same way as Cloud Manager.

**Comment by tobiscr** [comment]
I'm a bit scared to enable KIM to have access to all Hyperscaler accounts in Kyma. This would required per Hyperscaler dedicated credentials (read-only - best would be to have only read-access to IP relevant resources).

I'll get in touch with @ngrkajac for further details.

**Comment by tobiscr** [comment]
After alignment with @tmilos77 , we agreed to handover this EPIC to @kyma-project/phoenix team as their controller in KCP is already interacting with hyperscalers.

**Comment by marsteg** [comment]
Could the info also be taken from shoot.status.networking.egressCIDRs (from the gardener shoot object) and applied into the shoot? might be easier than taking it from the Hyperscaler.

**Comment by tobiscr** [comment]
> Could the info also be taken from shoot.status.networking.egressCIDRs (from the gardener shoot object) and applied into the shoot? might be easier than taking it from the Hyperscaler.

I've checked one of the new created Shoot-clusters in our DEV landscape.. seems this information is not per default provided:

```
status:
  conditions:
    - type: APIServerAvailable
      message: All webhooks are properly configured.
      ...
  gardener:
    id: ...
    name: garden...zz
    version: v1.114.2
  hibernated: false
  lastOperation:
    description: Shoot cluster has been successfully reconciled.
    lastUpdateTime: '2025-03-19T08:39:50Z'
    progress: 100
    state: Succeeded
    type: Reconcile
  observedGeneration: 140
  seedName: gcp-ha-us2
  technicalID: shoot--kyma-dev--a2f3c8f
  uid: 3...b6
  clusterIdentity: >-
    shoot--kyma-dev--a2f...6-sap-landscape-canary
  advertisedAddresses:
    - name: external
      url: https://api.....dev.kyma.ondemand.com
    - name: internal
      url: https://api.....kyma-dev.internal.canary.k8s.ondemand.com
    - name: service-account-issuer
      url: https://api.....kyma-dev.internal.canary.k8s.ondemand.com
  lastMaintenance:
    description: >-
      All maintenance operations successful. Control Plane: Updated Kubernetes
      version from "1.31.4" to "1.31.5". Reason: Automatic update of Kubernetes
      version configured
    triggeredTime: '2025-03-07T07:19:50Z'
    state: Succeeded
  networking: {}
```
