### ISSUE TITLE
[Telemetry Operator] Exclusion of containers enables system namespace inclusion

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15490]
**Description**
Assume a pipeline configuration like that:
```yaml
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: cls-application-logs
spec:
  input:
    application:
      containers:
        exclude:
          - istio-proxy
...
```

then the expected behaviour according to documentation is that system namespaces are getting ignored (default behaviour for namespace selection stays untouched). In fact, that setting enables the streaming of logs for system namespaces.
