### ISSUE TITLE
Bearer token based authentication for LogPipeline HTTP Output

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15766]
**Description**
The current http output does not support custom headers, especially not for Authorization needs. That is a common feature used for integration with providers like for example https://www.axiom.co/docs/send-data/fluent-bit.
However, the token is provided by a secret usually not being in the right format so that it can be consumed as a header value (the Bearer prefix needs to be added). So instead of adding plain support for custom headers, first a dedicated support for tokens should be provided.

Secret rotation must be supported.

```
apiVersion: telemetry.kyma-project.io/v1alpha1
kind: LogPipeline
metadata:
  name: logpipeline-http-sample
spec:
  output:
    http:
      host:
        value: icke.com
      token:
        type: Bearer
        value: hardcodedToken
        valueFrom:
          secretKeyRef:
            name: mySecret
            namespace: myNamespace
            key: token
```

Criterias:
- Bearer tokens can be specified for authentication
- Tokens can be rotated
- Tokens can be stored in secrets

**Reasons**

**Attachments**
