### ISSUE TITLE
SAP Btp Operator service auditlog always inprogress

### ISSUE THREAD

**Issue by VinceVega7** [kyma-project/kyma#15777]
**Description**

Hi,

I am following the instructions to create a service binding on top of kyma following their instructions here:

https://kyma-project.io/docs/kyma/latest/03-tutorials/00-service-management/smgt-01-deploy-service/#documentation-content

Once I have logged into btp and created the service manager instance and key to obtain the creds.
When I create the service binding:

apiVersion: services.cloud.sap.com/v1alpha1
kind: ServiceInstance
metadata:
  name: btp-audit-log-instance
  namespace: default
spec:
  serviceOfferingName: auditlog-api
  servicePlanName: default
  externalName: btp-audit-log-instance
It is always inprogress and the describe shows the following:

kubectl get serviceinstances.services.cloud.sap.com btp-audit-log-instance -o yaml
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
creationTimestamp: "2022-10-11T20:14:43Z"
deletionGracePeriodSeconds: 0
deletionTimestamp: "2022-10-11T20:16:19Z"
finalizers:

services.cloud.sap.com/sap-btp-finalizer
generation: 2
name: btp-audit-log-instance
namespace: default
resourceVersion: "3228395"
uid: 3a77ca4b-28bf-4791-ba3b-9435f549ef23
spec:
externalName: btp-audit-log-instance
serviceOfferingName: auditlog-api
servicePlanName: default
userInfo:
groups:
system:masters
system:authenticated
uid: system:cluster-admin
username: system:cluster-admin
status:
conditions:
lastTransitionTime: "2022-10-11T20:14:43Z"
message: 'Error sending request GET /v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27btp-audit-log-instance%27+and+context%2Fclusterid+eq+%27da74f3ea-d914-4fa9-b531-e9e275b6c83e%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27btp-audit-log-instance%27:
Get "/v1/service_instances?attach_last_operations=true&fieldQuery=name+eq+%27btp-audit-log-instance%27+and+context%2Fclusterid+eq+%27da74f3ea-d914-4fa9-b531-e9e275b6c83e%27+and+context%2Fnamespace+eq+%27default%27&labelQuery=_k8sname+eq+%27btp-audit-log-instance%27":
unsupported protocol scheme ""'
observedGeneration: 1
reason: InProgress
status: "False"
type: Succeeded
lastTransitionTime: "2022-10-11T20:14:43Z"
message: ""
reason: NotProvisioned
status: "False"
type: Ready
observedGeneration: 1
ready: "False"
I compared the kyma version to sap operator version and I also tried v1 , but same issue.
The url is cut but that is not in my control.
fyi. this is being done in azure.

**Expected result**

The serviceinstance should be Ready

**Actual result**

The serviceinstance is always InProgress

**Steps to reproduce**

See above your doc.

**Comment by PK85** [comment]
hello @VinceVega7 

thanks for reporting that cause since https://github.com/SAP/sap-btp-service-operator/tree/v0.2.3 they changes input param name. Please use:

correct:
```
... --set manager.secret.sm_url=...
```
wrong:
```
... --set manager.secret.url=...
```

@IwonaLanger please adjust https://kyma-project.io/docs/kyma/latest/03-tutorials/00-service-management/smgt-01-deploy-service#documentation-content point nr 3, and send me to review.

Cheers, Piotr

**Comment by PK85** [comment]
After above adjustment:
```
kubectl get serviceinstances.services.cloud.sap.com btp-audit-log-instance -oyaml

...
status:
  conditions:
  - lastTransitionTime: "2022-10-12T10:10:48Z"
    message: ServiceInstance provisioned successfully
    observedGeneration: 1
    reason: Created
    status: "True"
    type: Succeeded
  - lastTransitionTime: "2022-10-12T10:10:48Z"
    message: ""
    reason: Provisioned
    status: "True"
    type: Ready
  instanceID: 526ce546-0bb9-4b86-ab3d-b178cc0887e0
  observedGeneration: 1
  ready: "True"
```
