### ISSUE TITLE
Basic Auth support for TracePipeline

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#15829]
**Description**

For the minimal integration scenario, support for basic auth is required.

Proposed API:
```yaml
kind: TracePipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
 otlp:
      protocol: grpc #grpc | http
      endpoint: 
          value: "myserver.local:55690"
          valueFrom:
            secretKeyRef:
                name: my-config
                namespace: default
                key: "endpoint"
      authentication:
        basic:
          username:
            value: "user"
            valueFrom:
              secretKeyRef:
                  name: my-config
                  namespace: default
                  key: "username"
          password:
            value: "my-insecure-password"
            valueFrom:
              secretKeyRef:
                  name: my-config
                  namespace: default
                  key: "password"
```
**Criterias**
- Enable configuration of basic auth secrets for OTLP outputs in a TracePipeline
- Secrets should stay secret via secrets, so plain text values and references to secrets needs to be supported as input for user and password
- OTLP endpoints are usually co-located with the credentials in the same secret, so it must be possible to reference the OTLP endpoint from the same secret
- Have unit tests assuring that the otel-collector config is generated proper
- Assure that the CRD has proper in-line documentation and potential constraints defined

**Reasons**
The SAP internal tooling requires basic auth as way of authentication, so that is a minimal viable feature needed

**Attachments**
