### ISSUE TITLE
Istio Telemetry does not work

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#15875]
**Description**

**Expected result**

Tracing sample rate is adjusted by Telemetry CR.

**Actual result**

Using Telemetry from istio stops tracing at all.

**Steps to reproduce**

1 Add a telemetry CR like

```
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: namespace-override
  namespace: myns
spec:
  tracing:
        userId:
          header:
            defaultValue: unknown
            name: x-user
      randomSamplingPercentage: 100
```

2) Check Jaeger,

**Troubleshooting**

I guess the problem is like https://github.com/istio/istio/issues/35750#issuecomment-1165988761

A possibile solution would be to name the extension provider and not use this provider for default configuration.
