### ISSUE TITLE
Delete PSP from Eventing components for k8s 1.25

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#15919]
**Description**

Since PSP will be removed with k8s 1.25, remove it from following kyma components:
- Eventing controller
- Event-publisher-proxy
- NATS
- KMC

More info: https://github.com/kyma-project/kyma/issues/15897

**Comment by marcobebway** [comment]
The following security context config is applied for all Eventing Pods/Containers:

```yaml
  podSecurityContext:
    fsGroup: 10001
    runAsUser: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
    sysctls:
      - name: kernel.shm_rmid_forced
        value: ''
      - name: net.ipv4.ip_local_port_range
        value: ''
      - name: net.ipv4.ip_unprivileged_port_start
        value: ''
      - name: net.ipv4.tcp_syncookies
        value: ''
      - name: net.ipv4.ping_group_range
        value: ''
```

```yaml
  containerSecurityContext:
    privileged: false
    allowPrivilegeEscalation: false
    runAsNonRoot: true
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
    seLinuxOptions:
      type: container_t
    procMount: default
```

**Comment by marcobebway** [comment]
The following security context config is applied for all KMC Pods/Containers:

```yaml
podSecurityContext:
  fsGroup: 10001
  runAsUser: 10001
  runAsGroup: 10001
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

```yaml
containerSecurityContext:
  privileged: false
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop:
      - ALL
    add:
      - NET_BIND_SERVICE
  seLinuxOptions:
    type: container_t
  procMount: default
```
