### ISSUE TITLE
Apply security context  to the function workloads

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#15923]
**Description**

Review the Pod/Job templates for function managed workloads with regards to the [recommended security features](https://github.com/kyma-project/community/blob/main/concepts/psp-replacement/baseline-pod-spec.yaml) so that they will be admitted for namespaces with baseline restriction level enforced

**Reasons**

Previous investigation has shown that function workloads ( build job and function pod ) would be admitted if the `baseline` restriction level is applied on the namespace. Lets check if we the workloads do have all the recommended features set.

**Comment by anoipm** [comment]
**manual test**

create cluster: gcp with kubernetes 1.23.13 (piona-15923-6)

in terminal:
export KUBECONFIG=/Users/I567085/Downloads/kubeconfig--wookiee--piona-15923-6.yaml
kubectl create namespace piona
kubectl label namespace piona pod-security.kubernetes.io/enforce=baseline
kyma deploy --source PR-16014
kyma init function --namespace piona
kyma apply function
kubectl get pods -n piona

build pod contains:
```
...
spec:
  containers:
  - args:
    ...
    securityContext:
      capabilities:
        add:
        - CHOWN
        - FOWNER
        - SETGID
        - DAC_OVERRIDE
        drop:
        - ALL
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: false
    ...
  ...
  securityContext:
    runAsGroup: 0
    runAsUser: 0
    seccompProfile:
      type: RuntimeDefault
  ...
```

function pod contains:
```
...
spec:
  containers:
  - env:
    ...
    securityContext:
      capabilities:
        drop:
        - ALL
      privileged: false
      procMount: Default
      readOnlyRootFilesystem: true
    ...
  ...
  securityContext:
    runAsGroup: 10001
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault
  ...
  volumes:
  - emptyDir:
      sizeLimit: 100Mi
    name: tmp-dir
...
```

Pod's yamls are compared with [baseline-pod-spec](https://github.com/kyma-project/community/blob/main/concepts/psp-replacement/baseline-pod-spec.yaml).

For build pod I see some uncompliances (will be explained):
- we use root user and group,
- we set `readOnlyRootFilesystem` to `false`.
