### ISSUE TITLE
Service binding: hide service instances if Service Class or given Service Plan has bindable attribute set to false

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#1596]
**Description**

As a developer I don't like to see service instances that are marked as not bindable.

**Expected result**

They are not displayed.

**Actual result**

They are displayed.

**Steps to reproduce**

Use Service Class that represents Events only (from Remote environment). Create:
```
apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: RemoteEnvironment
metadata:
  name: ec-prod
spec:
  accessLabel: access-label-1
  description: "EC description"

  # list of services
  services:
    # mandatory, unique ID
    - id: "ac031e8c-9aa4-4cb7-8999-0d358726ffaa"               # required, uuid, immutable
      # required, MUST only contain lowercase characters, numbers and hyphens (no spaces)
      # MUST be unique across all services. MUST be a non-empty string.
      name: "promotions-ac031e8c"
      # required, mapped to metadata.displayName, used by catalog UI
      displayName: "Promotions"
      # required, mapped to description, used by catalog UI
      description: "Short desc for Promotions APIs"
      # required, mapped to metadata.longDescription, used by catalog UI
      longDescription: "Long description for Promotions APIs"
      # mandatory, maps to metadata.providerDisplayName, provider name in catalog UI
      providerDisplayName: "HakunaMatata"

      # mapped to tags, not required
      tags:
      - occ
      - promotions
      labels:
        connected-app: "ec-prod"
      # Entries defines, what can be enabled by activation (instantiating and/or binding) of the service
      entries:
      - type: Events
```

**Troubleshooting**
