### ISSUE TITLE
Prepwork for v1alpha2 subscription busola extensibility implementation [TB: 3 days]

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16056]
**Description**

As part of the new subscription CRD implementation, we need to make sure that eventing users on busola can create/view subscriptions both in the v1alpha1 version and v1alpha2 version. We would also like to make sure that we are in control of this feature. To learn more about the extensibility feature of busola, we will timebox this issue to gather as much details and information as possible so that we can continue to work on [this](https://github.com/kyma-project/kyma/issues/15586) issue. 

More information can be found [here](https://github.com/kyma-project/busola/tree/main/docs/extensibility). Related pull request can be found [here](https://github.com/kyma-project/busola/pull/1912).

**Questions to be answered:**

- How to create extensions and persist them on busola for all users?
- How to support creation/update of subscriptions in both versions: v1alpha1 and v1alpha2?

**Attachments**

**Comment by mfaizanse** [comment]
Busola extension configMap for Subscription v1alpha2 CRD: 

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: subscriptions-v1alpha2
  namespace: kube-public
  labels:
    app.kubernetes.io/name: subscriptions-v1alpha1
    busola.io/extension: resource
    busola.io/extension-version: '0.5'
data:
  general: |-
    resource:
      kind: Subscription
      group: eventing.kyma-project.io
      version: v1alpha2
    name: Subscriptions v1alpha2
    category: Configuration
    scope: namespace
    description: '{{[Subscription](https://kyma-project.io/docs/kyma/latest/05-technical-reference/00-custom-resources/evnt-01-subscription#documentation-content)}} is used to subscribe to events.'
    urlPath: subscriptions-v1alpha2
  details: |-
    header: 
      - name: status.conditions.status
        source: 'status.ready = false ? "error" : "ready"'
        widget: Badge
        description: status.conditions.message
      - name: spec.typeMatching
        source: spec.typeMatching
      - name: spec.source
        source: spec.source
      - name: spec.sink
        source: spec.sink
      - source: spec.sink
        widget: ResourceLink
        name: spec.sink.controlledBy
        resource:
          name: '$substringBefore($substringAfter(spec.sink, "http://"), ".")'
          namespace: $root.metadata.namespace
          kind: "'Service'"
    body: 
      - source: status.conditions
        widget: Table
        name: status.conditions
        children:
          - source: 'status.ready = false ? "error" : "ready"'
            name: status.type
            widget: Badge
            description: status.conditions.message
          - source: '$item.status'
            name: status.conditions.status
          - source: '$item.reason'
            name: status.conditions.reason
          - source: '$readableTimestamp($item.lastTransitionTime)'
            name: status.conditions.lastTransitionTime
      - name: spec.types
        source: spec.types
        widget: Table
        children:
          - name: Type
            search: true
            source: '$item'
            sort: false
      - widget: EventList
        filter: "$matchEvents($$, $root.kind, $root.metadata.name)"
        name: events
        defaultType: NORMAL
        hideInvolvedObjects: true
  form: |-
    - path: spec.sink
      name: spec.sink
      simple: true
      inputInfo: inputInfo.sink
      placeholder: placeholder.sink
    - path: spec.typeMatching
      simple: true
      enum:
        - standard
        - exact
      required: true
    - path: spec.source
      simple: true
      required: false
    - path: spec.types
      simple: true
      widget: SimpleList
      children:
        - path: '[]'
      defaultExpanded: true
  list: |-
    - name: status.conditions.status
      source: 'status.ready = false ? "error" : "ready"'
      widget: Badge
      description: status.conditions.message
  translations: |-
    en:
      inputInfo.sink: Sink structure, 'http://{SERVICE}.{NAMESPACE}.svc.cluster.local'
      inputInfo.eventType: Event Type structure, 'sap.kyma.custom.{APP}.{EVENT.NAME}.{VERSION}'
      events: Events
      placeholder.eventType: Enter the event type, for example, sap.kyma.custom.test-app.order.cancelled.v1
      placeholder.sink: Enter the sink, for example, http://service.default.svc.cluster.local
      spec.filters: Filters
      spec.filter.eventType: Event Type
      spec.filter.eventSource: Event Source
      spec.filter.event.property: Property
      spec.filter.event.type: Type
      spec.filter.event.value: Value
      spec.types: Types
      spec.source: Source
      spec.typeMatching: Type Matching
      spec.sink: Sink
      spec.sink.controlledBy: Controlled By
      status.cleanEventTypes: Event Types
      status.conditions: Condidtions
      status.conditions.lastTransitionTime: Last Transition
      status.conditions.reason: Reason
      status.conditions.status: Status
      status.type: Type

```
