### ISSUE TITLE
Support other ways of authentication of Grafana

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16254]
**Description**

The in-cluster Grafana stack is secured by an oauth2-proxy running in front of grafana, all requests to grafana must go through the proxy. Traffic coming from other proxies are rejected by an Istio authorization policy. With that, other ways of doing the authentication (for example using a custom SAP approuter and the SAP xsuaa integration) are not supported.

Goal: Provide a way so that users can manage the clients which are allowed to access Grafana

**Reasons**
It is good to run secure by default, but also assure a level of flexibility.

**Attachments**
 An example would be to run the SAP specific approunter, having it configured to the kyma local grafana instance. You could follow this [example](https://github.com/SAP-samples/kyma-runtime-extension-samples/tree/main/standalone-approuter) and then customize it with these additions:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-destinations
data:
  destinations: >-
    [
        {
          "name": "grafana",
          "url": "http://monitoring-grafana.kyma-system.svc.cluster.local",
          "forwardAuthToken": false
        }
    ]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: expose-grafana-config
data:
  xs-app.json: |-
    {
        "authenticationMethod": "route",
        "sessionTimeout": 10,
        "routes": [
            {
                "source": "^/(.*)$",
                "destination": "grafana",
                "target": "$1",
                "authenticationType": "xsuaa"
            }
        ]
    }
```
Then all is in place but the actual call will fail with a 403 RBAC access denied

**Comment by a-thaler** [comment]
The grafana instance is secured by a Istio AuthorizationRole allowing requests only by the serviceaccount used by the related ouath2-proxy instance. That will assure that intruders cannot access the metrics/logs via the grafana API in an easy way.

To allow access for additional accounts, you can add additional policies to the kyma-system namespace. So assuming that you use the SAP approuter running in namespace "my-namespace", and you assigned an individual serviceaccount with name "my-account", then the following policy will enable incoming traffic from the router:

```yaml
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: grafana-addition
  namespace: kyma-system
spec:
  action: ALLOW
  rules:
  - from:
    - source:
        principals:
        - cluster.local/ns/my-namespace/sa/my-account
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
```
