### ISSUE TITLE
serverless.kyma-project.io/v1alpha1 Function could not be saved anymore

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#16333]
**Description**

we have a existing Function which mounts a secret as a ENV Value

```
spec:
  env:
    - name: PRIVATE_KEY
      valueFrom:
        secretKeyRef:
          key:  tls.key
          name: my-secret-name
```

With the current 2.9.1 Release it couldn't be edited anymore.  It seems like there is a Validator for serverless.kyma-project.io/v1alpha2 which does  not expect a secret mountet as a env.
