### ISSUE TITLE
Runtime debuggability of telemetry-operator

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16435]
**Description**
Have a way to change operator settings (mainly related to reconcilation) at runtime without getting reconciled like for disabling reconcilation or changing log levels.
For that, we need a dynamic configuration option with some new features for improving operations.

**Criterias**
- At runtime I can pass a config file with settings
- I can add/remove settings at any time without getting the operator restarted
- I can pause reconcilation for Trace/LogPipeline
  - With that I can manipulate the otel-collector log level directly
    ```
    service:
      telemetry:
        logs:
          level: info #info | debug
    ```
  - With that I can manipulate the verbosity of the logging exporter
    ```
    exporters:  
      logging:
         verbosity: basic # basic | normal | detailed
    ```
