### ISSUE TITLE
Please add required_scope to apirules.gateway.crd.yaml schema

### ISSUE THREAD

**Issue by akucharska** [kyma-project/kyma#16509]
**Description**
Please add `required_scope` to apirules.gateway.crd.yaml schema in similar way as this:

```
jwks_urls:
  type: array
  items:
    type: string
    pattern: ^(https://|file://).*$
trusted_issuers:
  type: array
  items:
    type: string
    pattern: ^(https://|file://).*$
```

**Reasons**
We have other fields: `jwks_urls` and `trusted_issuers` specified in spec.rules.accessStrategies.config but not `required_scope`.
It would be helpful from UI perspective to have every field that is used in configuration specified in schema, cause we use schema to prepare forms.

**Attachments**
