### ISSUE TITLE
verify `server-side-apply` behaviour

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#16519]
Verify behaviour of the new controller in case a CRD was applied using server-side-apply.
See: https://github.com/kyma-project/api-gateway/issues/50

**Comment by raypinto** [comment]
I performed the following steps:

- Install kyma enabling the new version of the CRD
- Create subscription with the old (v1alpha1) version using the below command and yaml
  - `kubectl apply --server-side -f eventing_v1alpha1_subscription.yaml`

<details>
  <summary>Click here for the yaml</summary>
    ```yaml
    apiVersion: eventing.kyma-project.io/v1alpha1
    kind: Subscription
    metadata:
      name: test-noapp1
      namespace: tunas-testing
    spec:
      filter:
        filters:
          - eventSource:
              property: source
              type: exact
              value: "noapp"
            eventType:
              property: type
              type: exact
              value: sap.kyma.custom.noapp.order.created.v1
          - eventSource:
              property: source
              type: exact
              value: "noapp"
            eventType:
              property: type
              type: exact
              value: sap.kyma.custom.noapp.order.created.v2
      protocol: ""
      protocolsettings: {}
      sink: http://test.tunas-testing.svc.cluster.local
    ```
</details>

- Apply the same subscription with the new (v1alpha2) version using the below command and yaml
  - `kubectl apply --server-side -f eventing_v1alpha2_subscription.yaml`

<details>
  <summary>Click here for the yaml</summary>
    ```yaml
    apiVersion: eventing.kyma-project.io/v1alpha2
    kind: Subscription
    metadata:
      name: test-noapp1
      namespace: tunas-testing
    spec:
      sink: http://test.tunas-testing.svc.cluster.local
      typeMatching: exact
      source: "kyma"
      types:
        - sap.kyma.custom.noapp.order.created.v1
        - sap.kyma.custom.noapp.order.created.v3
    ```
</details>

It was applied successfully without any problems or issues. I also tried the same by using a different event type and the subscription was updated successfully.
