### ISSUE TITLE
[Telemetry Traces] Filter system traces by default

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16514]
**Description**
Having istio trace reporting enabled, by default the kyma-system components are reporting spans repeatedly. That spans are not relevant for any business use case and also not for kyma operations.
For now, let's filter them out hardcoded till there is a better understanding how the API desin will look like.

**Criterias**
- Filter out traces for fluent-bit -> loki communication
- Filter out traces for prometheus and vm_promscrape scraping (reported by the destination potentially)
- Filter out traces targetting the telemetry-otel service (maybe test once more if the span reporting uses a dedicated traceID independent from the initial e2e request chain, if so we can be sure to filter it out)
- document filtering in limitation section
- assure that additional resource consumption is acceptable

**Implementation Idea**
Use the filterprocessor with OTTL. Try to be as specific as possible to not have false positives, include namespace info were possible.
```yaml
    filter:
      traces:
        span:
          - '(attributes["http.method"] == "GET") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Ingress") and (IsMatch(attributes["http.url"], ".+/metrics") == true)'
          - '(attributes["http.method"] == "GET") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Ingress") and (IsMatch(attributes["http.url"], ".+/healthz(/.*)?") == true)'
          - '(attributes["http.method"] == "GET") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Ingress") and (attributes["user_agent"] == "vm_promscrape")'
          - '(attributes["http.method"] == "POST") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Egress") and (IsMatch(attributes["http.url"], "http(s)?:\\/\\/telemetry-trace-collector\\.kyma-system(\\..*)?:(4318|4317).*") == true)'
          - '(attributes["http.method"] == "POST") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Ingress") and (resource.attributes["service.name"] == "loki.kyma-system")'
          - '(attributes["http.method"] == "POST") and (attributes["component"] == "proxy") and (attributes["OperationName"] == "Egress") and (resource.attributes["service.name"] == "telemetry-fluent-bit.kyma-system")'
 ```
