### ISSUE TITLE
[Telemetry Tracing] Custom header support for tracepipeline otlp output

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#16554]
**Description**

Typical integration scenarios based on [native OTLP](https://opentelemetry.io/vendors/) like for [Dynatrace integration](https://www.dynatrace.com/support/help/extend-dynatrace/opentelemetry/opentelemetry-traces/opentelemetry-ingest) will require some sort of authentication typically solved via custom headers. While a more [convenient API](https://github.com/kyma-project/kyma/issues/16258) for "Authorization" header can be achieved, the basic support for custom headers is the base for all.

Goal of this story is to add an API to support custom headers in the OTLP output with the support of secret management.

Proposed API:
```yaml
kind: TracePipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
 otlp:
      protocol: grpc #grpc | http
      endpoint: 
          value: "myserver.local:55690"
          valueFrom:
            secretKeyRef:
                name: my-config
                namespace: default
                key: "endpoint"
      headers:
         - name: key1
           value: myValue
           valueFrom:
              secretKeyRef:
                  name: my-config
                  namespace: default
                  key: "myHeaderValue"
      
```
**Criterias**
- Enable configuration of custom headers for OTLP outputs in a TracePipeline so that it will work with a Dynatrace setup
- Secrets should stay secret via secrets, so plain text values and references to secrets needs to be supported as input for user and password
- OTLP endpoints are usually co-located with the credentials in the same secret, so it must be possible to reference the OTLP endpoint from the same secret
- Have unit tests assuring that the otel-collector config is generated proper
- Assure that the CRD has proper in-line documentation and potential constraints defined
- Adjust documentation

**Reasons**
It will broaden the supported vendors. Dynatrace, Elastic and Splunk as an example will be supported

**Attachments**
