### ISSUE TITLE
SKR Subscription is not working for source different than "noapp"

### ISSUE THREAD

**Issue by muralov** [kyma-project/kyma#16591]
**Description**
No event is received by a function if a source is different than `noapp`. As a result, commerce mock tests are not working for SKR.

**Expected result**

there should be events received by the sink

**Actual result**

no event is received by a function if a source different than `noapp` source

**Steps to reproduce**

1. Install Kyma on SKR with new CRD enabled by following the [doc](https://github.tools.sap/kyma/documentation/blob/main/how-to-guides/provisioning-skr.md). Here is the sample [PR](https://github.com/kyma-project/kyma/pull/16571) that with new CRDs.
2. Create a function named `test` that prints event content:
```
module.exports = { 
   main: function (event, context) {
      console.log(event.data);
   }
}
```
3. Create the following subscription:
```
cat << EOF | kubectl apply -f -                                                                                                                                                                                                                                                                       ─╯
apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
  annotations: {}
  namespace: test
spec:
  typeMatching: standard
  types:
    - order.created.v3
  sink: http://test.test.svc.cluster.local
  source: mp-test-newcrd
EOF
```
4. Port-forward the Eventing Publisher Proxy
```
kubectl -n kyma-system port-forward svc/eventing-event-publisher-proxy  8081:80
```
5. Send a CE event:
```
curl -v -X POST \                                                                                                                 
    -H "Content-Type: application/cloudevents+json" \
    -H "X-B3-Sampled: 1" \
    -H "traceparent: 2c81e6d2858553e622353a1fb01a3cc5" \
    --data @<(<<EOF
    {
        "specversion": "1.0",
        "source": "mp-test-newcrd",
        "type": "order.created.v3",
        "eventtypeversion": "v1",
        "id": "A234-1234-1234",
        "data" : "{\"foo\":\"bar-v1alpha2\"}",
        "datacontenttype":"application/json"
    }
EOF
    ) \
    http://localhost:8081/publish
```
6. Watch the logs of a function pod and no event should be received by the function

**Comment by mfaizanse** [comment]
I tested the in-cluster on OSS cluster using this [PR](https://github.com/kyma-project/kyma/pull/16594) and it worked for me.

```
cat << EOF | kubectl apply -f -
apiVersion: eventing.kyma-project.io/v1alpha2
kind: Subscription
metadata:
  name: test
  labels:
    app.kubernetes.io/name: test
  annotations: {}
  namespace: tunas-testing
spec:
  typeMatching: standard
  types:
    - order.created.v3
  sink: http://test.tunas-testing.svc.cluster.local
  source: mp-test-newcrd
EOF
```

```
curl -v -X POST \
    -H "Content-Type: application/cloudevents+json" \
    -H "X-B3-Sampled: 1" \
    -H "traceparent: 2c81e6d2858553e622353a1fb01a3cc5" \
    --data @<(<<EOF
    {
        "specversion": "1.0",
        "source": "mp-test-newcrd",
        "type": "order.created.v3",
        "eventtypeversion": "v1",
        "id": "A234-1234-1234",
        "data" : "{\"foo\":\"bar-v1alpha2\"}",
        "datacontenttype":"application/json"
    }
EOF
    ) \
    http://localhost:8081/publish
```
