### ISSUE TITLE
Update the cli to use the new subscription CRD while creating functions

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#16631]
**Description**

The cli currently creates subscription CR with `v1alpha1` api version and it is hardcoded [here](https://github.com/kyma-project/hydroform/blob/8cd1c2a4c268ab0a0a6605aa9c44c33c6a679bdc/function/pkg/resources/unstructured/subscription.go#L13). We need to update this to use `v1alpha2` if the new subscription CRD is enabled.

In addition, the spec types [here](https://github.com/kyma-project/hydroform/blob/8cd1c2a4c268ab0a0a6605aa9c44c33c6a679bdc/function/pkg/resources/types/subscription.go) also need to be updated.

**Reasons**

**Attachments**

**Comment by k15r** [comment]
- [ ] add support for new v1alpha2 subscription to hydroform with the new specification for eventing subscriptions
- [ ] detect which crd version is used in target cluster and install correct version of subscription
- [ ] update cli to use updated hydroform
- [ ] check other projects that use hydroform (if there are any)

**Comment by kwiatekus** [comment]
Hi @k15r @muralov 

In order not to break the compatibility for users who would apply the legacy config, we'd need to introduce versioning of the config.yaml schema.
@kyma-project/otters  have it already partially there but we'd need to finalise it.

There must be sconversion webhook in place I assume to make sure previous version of subscription CRD api will work for the depreciation grace period

My idea is that thanks to the versioning of the config.yaml and the conversion webhook we can ensure legacy content will still work (in such case hydroform would apply v1alpha1 subscriptions )
```yaml
name: event-receiver
namespace: default
runtime: nodejs16
source:
   sourceType: inline
subscriptions:
   - name: event-receiver
     protocol: ""
     filer:
        filters:
           - eventSource:
               property: source
               type: exact
               value: ""
            eventType:
               property: type
               type: exact
               value: sap.kyma.custom.acme.payload.sanitised.v1
```
And for new version hydroform would apply the v1alpha2 subscription version

```yaml
name: event-receiver
namespace: default
runtime: nodejs16
source:
   sourceType: inline
subscriptions:
  - name: event-receiver
     sink: http://test.tunas-testing.svc.cluster.local/
	source: ""
	typeMatching: exact
	types:
	- sap.kyma.custom.noapp.order.created.v1
	- sap.kyma.custom.test-app.order.created.v1
```
@kyma-project/otters would be happy to contribute to this topic next week
