### ISSUE TITLE
[BUG] Kyma 2.10.1 Application Connector not working as expected

### ISSUE THREAD

**Issue by rufreakde** [kyma-project/kyma#16864]
**Description**

We upgraded our kyma version to 10.1 and now our application connector is not routing through to our destinations.

### Example calls from within a cluster pod:
```bash
~/App $ wget 'http://central-application-gateway.kyma-system:8080/pld-proxy/product-designer'
Connecting to central-application-gateway.kyma-system:8080 (100.105.127.23:8080)
wget: error getting response: Connection reset by peer
~/App $ wget 'http://central-application-gateway.kyma-system:8081/pld-proxy/product-designer'
Connecting to central-application-gateway.kyma-system:8081 (100.105.127.23:8081)
wget: error getting response: Connection reset by peer
~/App $ wget 'http://central-application-gateway.kyma-system:8082/pld-proxy/product-designer'
Connecting to central-application-gateway.kyma-system:8082 (100.105.127.23:8082)
wget: error getting response: Connection reset by peer
```

Deployment of applications was success in kyma-system namespace:
![Screenshot 2023-02-22 at 11 30 47](https://user-images.githubusercontent.com/28104368/220594373-80bbbbbc-c41a-48e5-ba7f-b10c127b4307.png)

here is an example of on of our 2 applications:
```yaml
---
apiVersion: applicationconnector.kyma-project.io/v1alpha1
kind: Application
metadata:
  name: pld-proxy
  namespace: kyma-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  services:
    - id: <id>
      name: product-designer
      displayName: "product-designer"
      description: <desc>
      providerDisplayName: <xxx>
      entries:
        - credentials:
            secretName: pld-proxy
            authenticationUrl: <not changed worked before>
            type: OAuth
          targetUrl: <not changed worked before>
          type: API
```
example secret
```yaml
Name:         pld-proxy
Namespace:    kyma-system
Labels:       <none>

Type:  Opaque

Data
====
clientSecret:  XXX
clientId:      YYY
```

Kubernetes 1.24.9
**Expected result**

API calls being routed authenticated through

**Actual result**
```bash
~/App $ wget 'http://central-application-gateway.kyma-system:8082/pld-proxy/product-designer'
Connecting to central-application-gateway.kyma-system:8082 (100.105.127.23:8082)
wget: error getting response: Connection reset by peer
```

**Steps to reproduce**
install kyma 1.10.1 deploy application with secret `execute wget '<path>'`

**Troubleshooting**
