### ISSUE TITLE
Kyma API Rule exposed cannot be opened in browser due to invalid certificate presented.

### ISSUE THREAD

**Issue by dragosnutu** [kyma-project/kyma#16871]
**Description**

Exposing API through the gateway and trying to access it through browser seems that it does not work because of maybe invalid certificate.

**Expected result**

Expose service through API Rules and being able to access it through browser even if the https certificate is a self signed one

**Actual result**

Endpoint cannot be accessed within browser because it is blocked.
See: 
![image](https://user-images.githubusercontent.com/48376420/220625871-ff6ff1fd-7821-4193-8a28-62544e8570ec.png)
![image](https://user-images.githubusercontent.com/48376420/220627255-e920b053-d9b8-4057-a573-165e6a0fb64e.png)

**Steps to reproduce**

1. Install kyma locally.
2. Deploy function or microservice.
3. Create API Rule. Something like this:
```yaml
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  labels:
    app: commerce-mock
  name: commerce-mock
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: commerce-mock
    port: 10000
    host: commerce
  rules:
    - path: /.*
      methods: ["GET","POST","PUT","DELETE","HEAD"]
      accessStrategies:
        - handler: allow
 ```

**Troubleshooting**

I did not followed any steps to solve this issue, but I guess there might be some documentation about how to create your self signed certificates locally that might work.
