### ISSUE TITLE
scopes are not supported with JWT access strategies with kyma busola API rule editor

### ISSUE THREAD

**Issue by ptesny** [kyma-project/kyma#17122]
Just try to add a scope with a JWT strategy...using a kyma busola API rule editor:

1. you can only do it manually in the yaml editor (yaml tab)
2. once you validate the API rule the scope will be taken into account
3. go back to the API rule editor; switch to yaml tab; ad the scope will not be there anymore
4. if you edit anything else in this API rule or just the hit update button you will lose the scopes....

For instance:

```
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: "{{ .Values.services.srv.name }}-{{ .Release.Namespace }}"
spec:
  gateway: {{ .Values.gateway }}
  host: "{{ .Values.services.srv.name }}-{{ .Release.Namespace }}.{{ .Values.clusterDomain }}"
  rules:
    - accessStrategies:
        - config:
            jwks_urls:
              - https://<tenant>.authentication.<region>.hana.ondemand.com/token_keys
            trusted_issuers:
              - https://<tenant>.authentication.<region>.hana.ondemand.com/oauth/token
            required_scope:
              - openid        
          handler: jwt
      methods:
        - GET
        - PUT
        - DELETE
        - POST
        - PATCH
        - HEAD
      path: /.*
  service:
    name: {{ .Values.services.srv.name }}
    port: {{ .Values.services.srv.port }}
```
