### ISSUE TITLE
[Telemetry Manager] Reflect state of managed component in module status

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17158]
**Description**
At the moment the status of the telemetry module is static, but it should reflect the module health which is mainly dependent on the health of the subsequent components and about the active endpoints it is offering.
Please prepare an API Design which will cover these.

**Proposal**
```yaml
status:
  status: "Ready"
  endpoints:
    traces:
      grpc: "http://telemetry-otlp-traces...:4317"
      http: "..."
  conditions:
    - type: TraceComponentsHealthy
       status: `true`
       reason: TraceGatewayNotReady
       message: "..."
    - type: MetricComponentsHealthy
       status: `false`
       reason: MetricGatewayCrashloop
       message: "..."
    - type: LogComponentsHealthy
       status: `true`
       reason: FluentBitRunning
       message: "..."
```

**Criterias**
- The module status is reflecting the overall module health by aggregating the health (pods, service, etc.) of the subsequent components (fluentbit/otel-collectors) in the status conditions
  - A detailed status indicates which sub-components are active
- If tracing is active, the public otlp-trace endpoint is reported (in a way that it can be used as is for configuring an exporter)
- Provide a matrix on components and possible states as part of the documentation
- Understand the behaviour of the lifecycle-manager when the module has a negative status, will it constantly apply resources to the manager

As a nice example have a look at https://github.com/kyma-project/btp-manager/blob/main/docs/contributor/02-10-operations.md
