### ISSUE TITLE
CRDs from kube-prometheus-stack are overwritten by kyma

### ISSUE THREAD

**Issue by johgoe** [kyma-project/kyma#17214]
**Description**

Because of the change of strategy change in kyma, we are now maintain our own version of kube-prometheus-stack, which is already newer than the one provided by kyma. After patching kyma the installation was broken.

**Expected result**

Modules which are not enabled in kyma should not override CRDs

**Actual result**

CRDs of kube-prometheus-stack are downgraded to kyma version.

**Steps to reproduce**

Install kyma update 2.12.1 on a kubernetes cluster which already has a newer version of kube-prometheus-stack.

Call `kyma deploy -c components.yaml --source=2.12.1 -p production` with a component.yaml like
```
---
defaultNamespace: kyma-system
prerequisites:
  - name: "cluster-essentials"
  - name: "istio"
    namespace: "istio-system"
  #- name: "certificates"
  #  namespace: "istio-system"
components:
  - name: "istio-resources"
#  - name: "logging"
  - name: "telemetry"
#  - name: "tracing"
# - name: "monitoring"
...
```

**Troubleshooting**

It seems that the installation of CRDs applies all https://github.com/kyma-project/kyma/tree/main/installation/resources/crds and does not take care about the component.yaml. This is a major problem, for components which should be maintained by customers in future, caused by the deprecation in kyma project.

Partial Log of kyma deploy -v: [kyma.log](https://github.com/kyma-project/kyma/files/11113496/kyma.log)
