### ISSUE TITLE
A subscription with duplicate event types crashes the eventing-controller

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#17277]
**Description**
This issue happens, when there exists a `v1alpha1` subscription with duplicate event filters in kyma v.2.11.x and then cluster is upgraded to latest version with `v1alpha2` subscription enabled.

In kyma v2.12 onwards we do not allow user to create a subscription with duplicate event types (using validation webhook).

**Steps to reproduce:**
1. Provision a kyma v2.11.2 cluster.
2. Create a subscription:
```
cat << EOF | kubectl apply -f -
apiVersion: eventing.kyma-project.io/v1alpha1
kind: Subscription
metadata:
  name: test-noapp
  namespace: tunas-testing
spec:
  filter:
    filters:
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
    - eventSource:
        property: source
        type: exact
        value: ""
      eventType:
        property: type
        type: exact
        value: sap.kyma.custom.noapp.order.created.v1
  protocol: ""
  protocolsettings: {}
  sink: http://test.tunas-testing.svc.cluster.local
EOF
```
3. Upgrade the cluster to kyma v2.12.1.
4. The eventing-controller will crash.
