### ISSUE TITLE
[Telemetry] Annotation based scraping support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17373]
**Description**
As part of https://github.com/kyma-project/kyma/issues/13079 the MVP should not only contain the initial metrics gateway setup but should already support scraping custom metrics from applications. This story should implement a basic setup.

The initial API should similar to this:

```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input: # Metrics will be received via OTLP to the gateway always. Additionally you can enable different inputs to send additional metrics to the gateway. Metrics are selected based on labels
    application: # activates app-scraper by annotation
      enabled: true
      namespaces: # maps to filterprocessor
        include: []
        exclude: []
        system: true # enables system namespaces for scraping as well
      runtime: # (container runtime) activates cadvisor scraping (kubeletreceiver)
        enabled: true
      istio: # activates istio scraping. Filter by `destination_service_namespace` or `destination_workload_namespace` if namespaces are limited
        enabled: true
```

Having one pipeline which enables the application input, will trigger the deployment of a new agent running as daemonset. That new agent will run the following receivers:
- prometheusreceiver/app: annotation based scraping of the custom application endpoints running on that node
- prometheusreceiver/istio: annotation based scraping of the istio endpoint running on the node
- kubeletreceiver: determine kubelet metrics for the node

The resource.service.name attribute should be set to the service name determined from the metrics attributes. For the kubeletreceiver, the kubeletreceiver most probably needs to use a constant name for now.

As the service name should be configurable via annotation as well, we might introduce a custom annotation instead of using the default "prometheus.io" annotations, or supporting both?

```
telemetry.kyma-project.io/metrics-scrape=true
telemetry.kyma-project.io/metrics-port=1234
telemetry.kyma-project.io/service-name=icke
````

As multiple pipelines could use a different scrape config regarding namespaces, all namespaces should be scraped always and filtered in the gateway. To indicate that a metric is sourced by a specific agent, an additional resource attribute `kyma.source=prometheusreceiver/app` should be enriched per receiver/agent, then the namespace filtering can happen on base of that attribute and potentially removed again.

**Reasons**

**Attachments**
