### ISSUE TITLE
Test Contract between serverelss and api-gateway

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#17506]
**Description**
Kubernetes resources produced by serverless must satisfy API-gateway label selectors so that  when istio and api-gateway are installed, user may add a sidecar to the function pod and expose its API.

**Comment by strekm** [comment]
from api-gateway perspective it is important that k8s service has properly configured selector. api-gateway controller discovers selector on a service being exposed and secured and uses it to configure Istio resources. we do not require specific selectors.

**Comment by kwiatekus** [comment]
When a function is deployed we need to verify if the related k8s service has labelSelectors configured and this selector is matching labels defined at the function runtime pod.

I.e
svc
```yaml
kind: Service
apiVersion: v1
metadata:
...
spec:
  selector:
    serverless.kyma-project.io/function-name: serene-youth
    serverless.kyma-project.io/managed-by: function-controller
    serverless.kyma-project.io/resource: deployment
    serverless.kyma-project.io/uuid: 6250dfe2-71c9-4b9d-9b77-775ce5da8394
```

pod
```
kind: Pod
apiVersion: v1
metadata:
  labels:
...
    serverless.kyma-project.io/function-name: serene-youth
    serverless.kyma-project.io/managed-by: function-controller
    serverless.kyma-project.io/resource: deployment
    serverless.kyma-project.io/uuid: 6250dfe2-71c9-4b9d-9b77-775ce5da8394
```
