### ISSUE TITLE
Rate limiting

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#17572]
**Description**
Provide a simple way to enable rate-limiting using EnvoyFilters. Consider extending APIRule or introducing a new custom resource.

**Reasons**
Envoy supports two kinds of rate limiting: global and local. Global rate limiting uses a global gRPC rate limiting service to provide rate limiting for the entire mesh. Local rate limiting is used to limit the rate of requests per service instance. Local rate limiting can be used in conjunction with global rate limiting to reduce the load on the global rate limiting service.

This [task description from istio documentation](https://istio.io/latest/docs/tasks/policy-enforcement/rate-limit/) contains example envoy filter configurations to enable rate limiting. It can be useful for more advanced users but can be overwhelming for beginners. 

**Scope**
The minimum scope is a local rate limit. Global rate limit requires a central shared rate limit service to ensure that regardless of the number of instances the global rate limit is not exceeded. Generic rate limit service is provided by the [Envoy project](https://github.com/envoyproxy/ratelimit), it uses Redis as a storage.

**Comment by alperdedeoglu** [comment]
With envoy filter configuration below, I was able to apply a rate limiting rule based on tenant specific url, to istio-ingress gateway.

### Scenario Description
Each tenant has specific url to access the multitenant application, see the example below:
**Tenant url**: tenant1.application.com

**Token Bucket Algorithm Details**: 
 - Maximum number of tokens in the bucket : 10
 - Number of token to be filled into bucket : 10
 - Token fill interval: 60 seconds 

Which means; sample tenant might send 10 ( request / minute ) * number of *istio-gateway* pod instance.

### Relevant Envoy Filter Configuration
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: filter-local-ratelimit-ping-pong
  namespace: susaas
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
    - applyTo: HTTP_FILTER
      match:
        context: GATEWAY
        listener:
          filterChain:
            filter:
              name: "envoy.filters.network.http_connection_manager"
      patch:
        operation: INSERT_BEFORE
        value:
          name: envoy.filters.http.local_ratelimit
          typed_config:
            "@type": type.googleapis.com/udpa.type.v1.TypedStruct
            type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
            value:
              stat_prefix: http_local_rate_limiter
    - applyTo: VIRTUAL_HOST
      match:
        context: GATEWAY
        routeConfiguration:
          vhost:
            name: "tenant1.application.com:443"
            route:
              action: ANY
      patch:
        operation: MERGE
        value:
          typed_per_filter_config:
            envoy.filters.http.local_ratelimit:
              "@type": type.googleapis.com/udpa.type.v1.TypedStruct
              type_url: type.googleapis.com/envoy.extensions.filters.http.local_ratelimit.v3.LocalRateLimit
              value:
                stat_prefix: http_local_rate_limiter
                token_bucket:
                  max_tokens: 10
                  tokens_per_fill: 10
                  fill_interval: 60s
                filter_enabled:
                  runtime_key: local_rate_limit_enabled
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                filter_enforced:
                  runtime_key: local_rate_limit_enforced
                  default_value:
                    numerator: 100
                    denominator: HUNDRED
                response_headers_to_add:
                  - append: false
                    header:
                      key: x-local-rate-limit
                      value: 'true'
```
## Result
With this envoy filter, I was able to apply a primitive rate limiting configuration on istio gateway context.
