### ISSUE TITLE
Cannot deploy Function due to Running Status unknown

### ISSUE THREAD

**Issue by johanneseschrig** [kyma-project/kyma#17734]
**Description**

We are running a self managed Kyma on Gardener with the following versions:

```
Kyma CLI version: 2.15.0
Kyma cluster version: 2.15.0
Client Version: v1.27.3
Server Version: v1.25.10
```

Possibly due to a Kyma upgrade, we are having trouble deploying our git-sourced node Function via Helm, which was working fine before. Deploying the function manually via the UI and pasting the git-sourced code inline seems to work though. Even with Helm deploy, our Function is being built and the pod is spinning up, with our applications debug console.log.

**Expected result**

Function is deployed successfully and corresponding APIRule is accessible.

**Actual result**

Function conditions hang with Running status Unknown:

```
  conditions:
    - lastTransitionTime: '2023-06-23T15:14:46Z'
      message: Deployment ... created
      reason: DeploymentCreated
      status: Unknown
      type: Running
    - lastTransitionTime: '2023-06-23T15:14:45Z'
      message: Job ... finished
      reason: JobFinished
      status: 'True'
      type: BuildReady
    - lastTransitionTime: '2023-06-23T15:14:28Z'
      message: Sources ... updated
      reason: SourceUpdated
      status: 'True'
      type: ConfigurationReady
```

Accessing the APIRule gives a 503 with no healthy upstream.

**Steps to reproduce**

Deploy a Function via helm chart with git-source and corresponding APIRule.

**Troubleshooting**

Manually deploy in-line
different node runtimes (14, 16, 18)
different branch names

**Comment by ptesny** [comment]
@dbadura , can you have look please ?

**Comment by pPrecel** [comment]
Please, add more info about the git-sourced Function you've mentioned in the ticket (spec, status, deploy, deploy logs)

**Comment by UnchartedBull** [comment]
Helm Chart that's being used for deployment:

```
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
  name: <name
  creationTimestamp: null
  labels:
    <helm-labels>
spec:
  source:
    gitRepository:
      url: <url-to-git>
      auth:
        type: basic
        secretName: <secret-name>
      reference: main
      baseDir: /
  runtime: nodejs14
  env:
    <env-vars>
---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: <name>
  creationTimestamp: null
  labels:
     <helm-labels>
spec:
  host: <host>
  service:
    name: <name>
    port: 80
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  rules:
    - accessStrategies:
        - config: { }
          handler: allow
      methods:
        - GET
        - POST
        - HEAD
      path: /.*
```

The function itself is super simple. Just a `handler.js` with no dependencies (so a package.json with no dependencies as well). As mentioned above the pod with the function inside starts fine and the `handler.js` is definitely invoked. It just seems like the APIRule isn't being attached properly / responded to from the `server.js`. For every API call we get "No Healthy Upstream" as a response. The exact same code works on other landscapes though.

I wasn't able to find any more of the deployment logs. Helm just says that everything deployed fine and then the usual Kyma functions process starts (build pod comes up and goes back down and then the executor pod comes up with no errors). It's just that the function never get's available and is always stuck in the Deploying state.
