### ISSUE TITLE
Initial metric agent and pod scraping support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17828]
**Description**
Implement a first increment of https://github.com/kyma-project/kyma/issues/17373 by focusing on prometheus scraping for annotation placed on pods

The initial API should be similar to:
```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input:
    application:
      prometheus:
        enabled: true # triggers agent deployment and activates pod-scraping by annotation
```

- Resulting service.name should be cleared so that the gateway can enrich it later
- All namespaces should be scraped for now so that the gateway can filter out later
- The input type needs to be set as an internal resource or metric attribute so that the gateway can filter based on that later

**Criterias**
- As a user
    - I can enable scraping of custom and system workloads by pod annotations so that the metrics of the pods will be delivered to the configured backend
    - I can disable scraping by setting the enabled flag to false
    - I can activate scraping for non-istiofied workload for now
    - I will not find any dummy serviceName, as it will be not defined in case it is unknown
- As an operator
  - I don't need to worry about the number of pods to be scraped as the agent setup is scalable
 
**Reasons**

**Attachments**

https://github.com/kyma-project/telemetry-manager/pull/250

**Comment by a-thaler** [comment]
Still to do:
- e2e test

**Comment by a-thaler** [comment]
I did more investigations on the annotation-based scraping. In a scrape config you can check an annotation for presence or a specific value, but you cannot use an annotation value as a matcher for other label sources.
The service discovery will return you a target for every container-port mapping + containers without port, see https://prometheus.io/docs/prometheus/latest/configuration/configuration/#pod

The logic will take all that targets discovered for a pod and statically replace the target address with the configured port. As all the targets for the pod will use the same address, prometheus is smart and calling only the first target.

Most prominent effect is that the container label in the scraped metric might be wrong. I observed that for example the init-validation container was returned.

Conclusion:
- If you have multiple containers exposing multiple ports the container label might be wrong
- We can reduce the likelihood of this situation by:
   - removing containers without port
      ```
            - action: keep
              source_labels:
              - __meta_kubernetes_pod_container_port_number
              regex: (\d+)
      ```
   - removing init-containers
     ```
            - action: drop
              source_labels:
              - __meta_kubernetes_pod_container_init
              regex: (true)
     ```
   - removing the istio-proxy container
      ```
            - action: drop
              source_labels:
              - __meta_kubernetes_pod_container_name
              regex: (istio-proxy)
     ```
 - We need to document that known problem
