### ISSUE TITLE
Metric agent supports kublet metrics for pod and container

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17830]
**Description**
Implement a first increment of https://github.com/kyma-project/kyma/issues/17373 by focusing on kublet metrics for pods and containers

The initial API should be similar to:
```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input:
    application:
      runtime:
        enabled: true # triggers agent deployment and activates the kubletreceiver
```

- Resulting service.name should be cleared so that the gateway can enrich it later
- All namespaces should be scraped for now so that the gateway can filter out later
- the input type needs to be set as internal resource or metric attribute so that the gateway can filter based on that later

**Criterias**
- As a user
    - I can enable container and pod metrics of custom and system workload, so that the metrics of the pods will be delivered to the configured backend
    - I can disable the retrival by setting the enabled flag to false
    - I will not find any dummy serviceName, as it will be not defined in case it is unknown
    - I can rely on compatibility of the metrics in further release, as all supported metrics and the related attributes are covered in tests, so that a version update of the kubletreceiver will not result in changed metrics/attributes
  
**Reasons**

**Attachments**
