### ISSUE TITLE
Istio-proxy scraping support

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#17887]
**Description**
Implement an increment of https://github.com/kyma-project/kyma/issues/17373 by focusing on istio scraping

The initial API should be similar to:
```YAML
kind: MetricPipeline
apiVersion: telemetry.kyma-project.io/v1alpha1
metadata:
  name: myPipeline
spec:
  input:
    application:
      istio:
        enabled: true # triggers agent deployment and activates istio-proxy scraping
```

- Resulting service.name should be cleared so that the gateway can enrich it later
- All namespaces should be scraped for now so that the gateway can filter out later
- The input type needs to be set as an internal resource or metric attribute so that the gateway can filter based on that later

**Criterias**
- As a user
    - I can enable scraping of istio-proxies running with workloads so that the metrics of the pods will be delivered to the configured backend
    - I can disable scraping by setting the enabled flag to false
    - I will not find any dummy serviceName, as it will be not defined in case it is unknown
- As an operator
  - I don't need to worry about the number of pods to be scraped as the agent setup is scalable
 
**Reasons**

**Attachments**

https://github.com/kyma-project/telemetry-manager/pull/250
