### ISSUE TITLE
Default Presets are not taken into account when creating function

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#18027]
**Expected behaviour**

**When** creating a simple "hello world" function w/o runtime or build-time resource configuration

```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
    creationTimestamp: null
    labels:
        app.kubernetes.io/name: function
    name: function
    namespace: default
spec:
    runtime: nodejs18
    source:
        inline:
            dependencies: |-
                {
                  "name": "function-eloquent-maciej8",
                  "version": "0.0.1",
                  "dependencies": {}
                }
            source: |-
                module.exports = {
                    main: function (event, context) {
                        return 'Hello Serverless'
                    }
                }

```

**and** the serverless is configured to apply a given default presets:

```bash
kubectl get cm -n kyma-system serverless-webhook-envs -oyaml | grep WEBHOOK_DEFAULTING_FUNCTION_RESOURCES_DEFAULT_PRESET
  WEBHOOK_DEFAULTING_FUNCTION_RESOURCES_DEFAULT_PRESET: S
```

**Then** defaulting webhook logic should apply resource configuration according to configured default preset ("S")

**Actual behaviour**

In the scenario described the defaulting logic sets the runtime resources that correspond to "L" preset and doesnt fill in the profile field:

Have:
```yaml
spec:
  resourceConfiguration:
    function:
      resources:
        limits:
          cpu: 800m
          memory: 1Gi
        requests:
          cpu: 400m
          memory: 512Mi
```

Want:
```yaml
spec:
  resourceConfiguration:
    function:
      profile: S
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
```
