### ISSUE TITLE
Manual scaling for trace and metric gateway

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#18212]
**Description**
The current gateway setup is limited to a maximal throughput. If that is not sufficient, data will be started to refused. To support larger setups, scaling options are required. The simplest form is to have an API allowing to configure a fixed amount of instances. The API should be designed to support auto-scaling options as well.

**API Proposal**
Telemetry CR
```yaml
trace:
  gateway:
    scaling:
      strategy: constant
      replicas: 5
metric:
  gateway:
    scaling:
      strategy: auto
      min: 2
      max: 5
```

**Criterias**
- As a user I can fix the amount of replicas manually via an API
- The API is well documented and outlines the limitations related to my settings
- The API can be extended with auto scaling options
- Env tests are assuring that no regression can happen to the new functionality

**Reasons**
A limited troughput will prevent adoption for larger setups

**Attachments**
