### ISSUE TITLE
Failed to update the Kyma Function - error

### ISSUE THREAD

**Issue by I046495** [kyma-project/kyma#18479]
Hi,
We have a Kyma environment in canary named oppskymasaas. We have created some functions inside this instance spread across some different namespaces. We have been able to expose those functions using API rules etc. From last week, we are not able to update any of the function and get below error:

**Failed to update the Function: Function.serverless.kyma-project.io "first-function" is invalid: spec.resourceConfiguration.function: Invalid value: "object": Use profile or resources.**

**Expected result**

We expect to update the Kyma function after making some changes to it. 

**Actual result**

Throws above error instead.

**Steps to reproduce**

Going to any namespace inside our kyma instance and try to change any function, one such example is:
https://dashboard.stage.kyma.cloud.sap/cluster/shoot--kyma-stage--c-5fe9320/namespaces/i046495/functions/first-function

kubeconfigURL: 
https://kyma-env-broker.cp.stage.kyma.cloud.sap/kubeconfig/10E6DE20-3909-46F6-ABD9-110BACFB4BB1

Please also let me know if you need any other information from my side. Thanks.

**Comment by ptesny** [comment]
Can you paste the function manifest ? Thank you

**Comment by ptesny** [comment]
just use function profiles to define the resources required

```
spec:
............................
  scaleConfig:
    maxReplicas: 3
    minReplicas: 1
  resourceConfiguration:
    function:
      profile: XS
```

**Comment by ptesny** [comment]
@pPrecel , It seems the description of function profiles is missing from kyma documentation ?
https://kyma-project.io/#/serverless-manager/user/00-20-configure-serverless?id=overview

**Comment by ptesny** [comment]
OK the profiles are described in a different part of kyma documentation, namely here: https://kyma-project.io/#/serverless-manager/user/technical-reference/07-80-available-presets?id=build-jobs-resources

@I046495 , please refer to the above link and pick a function profile that suites your needs

**Comment by pPrecel** [comment]
@ptesny you sent a link to the `Serverless` CR docs, not the `Function` docs. Look here pls
https://kyma-project.io/#/serverless-manager/user/resources/06-10-function-cr

**Comment by pPrecel** [comment]
Available profile presets are described [here](https://kyma-project.io/#/serverless-manager/user/technical-reference/07-80-available-presets)

**Comment by pPrecel** [comment]
Ok, the problem is caused because you use the `profile` and the `resource` fields at the same time. Please remove one of these fields. Examples:

```
resourceConfiguration:
    function:
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
```

or

```
resourceConfiguration:
    function:
      profile: XS
```

The last sentence from the error log says `Use profile or resources.`

Can you please change it and say if it helps?
