### ISSUE TITLE
Migrate `kyma provision gardener` to using kubectl against gardener seed cluster

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#18674]
**Description**

Update docs and shell scripts which use `kyma provision gardener` command.
Migrate from deprecated cli command into applying shoot manifests directly ([docs](https://gardener.cloud/docs/guides/administer-shoots/create-delete-shoot/))
 - [occurences](https://github.com/search?q=org%3Akyma-project%20%22provision%20gardener%22&type=code)

Do not enforce shoot parameters if they are not required. Let gardener defaulting mechanism default values that are not provided (i.e k8s version)
 
**Reasons**
kyma cli commands to provision k8s clusters are deprecated and will be removed from kyma cli. Those not be used.
[Decision](https://github.com/kyma-project/community/issues/872)
https://github.com/kyma-project/cli/issues/2051

**Comment by halamix2** [comment]
Minimal configs:

<details>
<summary>GCP</summary>

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: test
spec:
  secretBindingName: secretName
  cloudProfileName: gcp
  region: europe-west1
  purpose: evaluation
  provider:
    type: gcp
    infrastructureConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        workers: 10.250.0.0/16
    controlPlaneConfig:
      apiVersion: gcp.provider.extensions.gardener.cloud/v1alpha1
      kind: ControlPlaneConfig
      zone:  europe-west1-b
    workers:
    - name: cpu-worker
      minimum: 1
      maximum: 2
      machine:
        type: n1-standard-4
      volume:
        type: pd-standard
        size: 20Gi
      zones:
        - europe-west1-b
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
```
</details>

<details>
<summary>AWS</summary>

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: test
spec:
  secretBindingName: secretName
  cloudProfileName: aws
  region: eu-west-1
  purpose: evaluation
  provider:
    type: aws
    infrastructureConfig:
      apiVersion: aws.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vpc:
          cidr: 10.250.0.0/16
        zones:
          - name: eu-west-1b
            internal: 10.250.112.0/22
            public: 10.250.96.0/22
            workers: 10.250.0.0/19
    workers:
    - name: cpu-worker
      minimum: 1
      maximum: 2
      machine:
        type: m5.large
      volume:
        type: gp2
        size: 20Gi
      zones:
        - eu-west-1b
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
```
</details>

<details>
<summary>Azure</summary>

```yaml
apiVersion: core.gardener.cloud/v1beta1
kind: Shoot
metadata:
  name: test
spec:
  secretBindingName: secretName
  cloudProfileName: az
  region: westeurope
  purpose: evaluation
  provider:
    type: azure
    infrastructureConfig:
      apiVersion: azure.provider.extensions.gardener.cloud/v1alpha1
      kind: InfrastructureConfig
      networks:
        vnet:
          cidr: 10.250.0.0/16
        workers: 10.250.0.0/19
    workers:
    - name: cpu-worker
      minimum: 1
      maximum: 2
      machine:
        type: Standard_A4_v2
      volume:
        type: Standard_LRS
        size: 20Gi
  networking:
    type: calico
    pods: 100.96.0.0/11
    nodes: 10.250.0.0/16
    services: 100.64.0.0/13
```
</details>
