### ISSUE TITLE
Make module images localizable

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma#18798]
### Description

Based on the [decision record](https://github.com/kyma-project/lifecycle-manager/issues/1587) here. 

To ensure the Kyma Lifecycle Manager (KLM) can replace localized module images during deployment, all required images must be listed in the Module Operator Deployment Kubernetes resource. Images are categorized into two groups:

- module operator images: All the images listed in module manifest as container images.
- module managed images: Images deployed by certain module managers during runtime, for example, btp-manager will deploy [sap-btp-service-operator](https://github.com/kyma-project/btp-manager/blob/a59f2cd89943b286af167db55a6a1cfe1e360170/module-resources/apply/deployment.yml#L55), for this kind of usages, each image must be provided in module Deployment as a dedicated container env value.

Example:
```
kind: Deployment
metadata:
  name: btp-manager-controller-manager
  namespace: kyma-system
spec:
  template:
    spec:
      containers:
      - image: europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.2.9
        env:
        - name: sap-btp-service-operator
          value: "europe-docker.pkg.dev/kyma-project/prod/external/sap-btp-service-operator/controller:v0.6.4"
```

All images (module operator images and module managed images) must be published and signed in the central image registry: `europe-docker.pkg.dev/kyma-project/prod`

### Reasons

Allow the module images to be localized by KLM when the module is running in a restricted environment without access to public internet.

### Acceptance Criteria

- [ ] Each image used by the module must be published in the central image registry: `europe-docker.pkg.dev/kyma-project/prod`.
  - [ ] this includes 3rd party images
  - [ ] **if currently other registries than `europe-docker.pkg.dev/kyma-project/prod` are used, state them in a comment in this ticket**
- [ ] Ensure that the module operator image uses the same version as the OCM. https://github.com/kyma-project/modulectl/issues/260
- [ ] For module operator images, reference them as module Deployment container images.
  - i.e. `deployment.spec.template.spec.containers[].image`
  - i.e. `deployment.spec.template.spec.initContainers[].image`
- [ ] For module-managed images, reference them as module Deployment container env variables.
  - i.e. `deployment.spec.template.spec.containers[].env[]`
  - also include images for `initContainers`
- [ ] When deploying module-managed images, the localized value from the env variable must be used.

### Module Tracking

> see `kyma/restricted-markets/issues/20`

- [x] API Gateway
- [x] Istio
- [x] BTP Operator
- [x] Serverless
- [x] Telemetry - ETA: 05.08.25
- [x] Keda
- [ ] Connectivity Proxy
- [x] Transparent Proxy
- [x] Eventing (created ticket late due to misconception that there is no backend on NS2 so far)
- [x] KIM Snatch (created ticket late due to kim-snatch not listed in the transferred modules section)
- [x] Cloud Manager (created ticket late due to cloud manager not listed in the transferred modules section)
- [x] to be confirmed
  - [x] ~CAP Operator~ out of scope for NS2?
  - [x] ~CF API~ out of scope for NS2?
  - [x] ~Zero Trust Identity Service~ out of scope for NS2?
  - [x] ~NATS~ out of scope for NS2?
  - [x] ~Warden~ out of scope for NS2?
  - [x] ~Docker registry~ out of scope for NS2?
  - [x] ~Application Connector~ out of scope for NS2?
