### ISSUE TITLE
Kubeless controller does not remove labels

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#2137]
**Description**

The Kubeless controller does not propagate changes in a Function resources to a Deployment in a proper way. Removing labels does not work. 
It seems the problem is a merge patch performed by the Kubeless controller, see:
(https://github.com/kubeless/kubeless/blob/master/pkg/utils/kubelessutil.go#L702)

**Expected result**

After applying new version of a Function with removed a label - it must be removed from the Deployment.

**Actual result**

Removing labels from the Function does not change the Deployment.

**Steps to reproduce**

Steps to reproduce:
1. Create a function with defined labels:
```yaml
...
spec:
  ...
  deployment:
    spec:
      template:
        metadata:
          labels:
            lab1: abc
            lab2: def
```
2. Check lables in the deployment
```bash
> kubectl get deployment func-name -o jsonpath="{.spec.template.metadata.labels}{'\n'}"
```
3. Apply changes to the Function (remove one label):
```yaml
...
spec:
   ...
  deployment:
    spec:
      template:
        metadata:
          labels:
            lab1: abc
```
4. Check the deployment - there are still two labels
