### ISSUE TITLE
Communication between a K8S Service and Istio virtual service is broken

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2363]
**Description**
While implementing a Publish served by Knative, it was discovered that a Publish service (a plain K8S service with Istio sidecar) cannot connect to Istio virtual service which represents a Knative eventing channel.

The flow is as below:
```
publish app (k8s deployment + istio side car ) ----> k8s service (channel) ---> istio virtual service (channel) ---> dispatcher service ---> dispatcher pod
```
e.g.
```
publish app --> foo-channel.svc.cluster.local --> foo-channel (Istio Virtual service) --> nats-dispatcher.knative-eventing.svc.cluster.local
```
error is : 

```
Route not found nats-dispatcher.knative-eventing.svc.cluster.local
```

>Note: **The same flow works on vanila K8s + Knative**.
This points to a possible discrepancy with Istio installation in Kyma

Please refer https://github.com/kyma-project/community/blob/master/sig-and-wg/wg-knative/assets/event-types.svg and https://github.com/kyma-project/community/blob/master/sig-and-wg/wg-knative/assets/publish-api.svg for details.

**Comment by radufa** [comment]
Findings:
1. After installation of Kyma/Knative the "dispatcher" Knative eventing service was running without Istio sidecar. See in: https://github.com/knative/eventing/blob/master/config/provisioners/in-memory-channel/in-memory-channel.yaml
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: in-memory-channel-dispatcher
  namespace: knative-eventing
spec:
  replicas: 1
  selector:
    matchLabels: &labels
      clusterChannelProvisioner: in-memory-channel
      role: dispatcher
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels: *labels
spec:
....
```
