### ISSUE TITLE
Introduce kyma-developer role

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#2557]
**Description**
There is a need for a role that is powerful enough to do developer's tasks like deploy service or lambda, see the logs, monitor, upgrade and delete. This role should be granted only to some namespaces (like qa, test, prod, default). The role should not give cluster scope permissions or be granted in system namespaces (e.g. kube-system, kyma-system, istio-system, kyma-integration, kyma-installer). 
The permissions included in kyma-developer role should contain:
- all standard namespaced kubernetes resources (copy them from edit role),
- all namespaces resources introduced by kyma components (e.g. apis.gateway.kyma-project.io)
- all verbs (create, delete, deletecollection, get, list, patch, update, watch).

**Reasons**
Currently, we define only kyma-admin and kyma-view roles. First is too powerful, the second is insufficient for developers.

**Proposal**
There is a built-in `edit` role. Consider reusing that role and grant it to developers in respective namespaces. 
To make a developer role more manageable consider using `aggregationRule` and compose that role from other smaller roles created per domain.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyma-developer
aggregationRule:
  clusterRoleSelectors:
  - matchLabels:
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
```

**Related issues**:
- Code PR https://github.com/kyma-project/kyma/pull/2782
- Prowjob PR https://github.com/kyma-project/test-infra/pull/647
