### ISSUE TITLE
Mixer doesn't provide necessary attributes to evaluate rbac rules

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#2623]
After defining istio RBAC rules for authorization a service to evaluate e.g. some claims from JWT token, service is not more reachable due to HTTP 403 with istio proxy result 'enforced denied'. This happening also with defining service accounts and evaluate via istio RBAC.

I can see from istio Pilot logs envoy filters are created successfully after deploying RBAC rules but istio proxy logs shown non of the attributes provided with call to service to evaluate rules.

Reproducible with creating simple istio RBAC ServiceRole like
```
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRole
metadata:
  name: my-service-role
  namespace: mynamespace
spec:
  rules:
  - services: ["myservicename"]
    methods: ["*"]

---
apiVersion: rbac.istio.io/v1alpha1
kind: ServiceRoleBinding
metadata:
  name: bind-my-service-role
  namespace: mynamespace
spec:
  subjects:
  - properties:
      request.auth.claims[email]: "*@sap.com"
  roleRef:
    kind: ServiceRole
    name: my-service-role
---
apiVersion: rbac.istio.io/v1alpha1
kind: RbacConfig
metadata:
  name: default
spec:
  mode: ON_WITH_INCLUSION
  inclusion:
    services: ["myservicename"]
```

here is the logs from istio proxy of service
```
'x-istio-attributes', 'CnNlcnZpY2USLBIqbG9nZ2luZy1sb2tpLmt5bWEtc3lzdGVtLnN2Yy5jbHVzdGVyLmxvY2FsCj8KCnNvdXJjZS51aWQSMRIva3ViZXJuZXRlczovL2xvZ2dpbmctcHJvbXRhaWwta25qcXAua3ltYS1zeXN0Z'
'sec-istio-authn-payload', ''
, dynamicMetadata: filter_metadata {
  key: "istio_authn"
  value {
  }
}

[2019-02-05 16:41:21.728][20][debug][rbac] external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:78] shadow denied
[2019-02-05 16:41:21.728][20][debug][rbac] external/envoy/source/extensions/filters/http/rbac/rbac_filter.cc:112] enforced denied
```
as log shown there is no attribute names and values for "istio_authn" provided

**Comment by piotrmsc** [comment]
I have talked with @kwiatekus and it will be done in the next release. In the meantime, @hisarbalik  did you create Autn policy as well in the set up?

**Comment by hisarbalik** [comment]
> I have talked with @kwiatekus and it will be done in the next release. In the meantime, @hisarbalik did you create Autn policy as well in the set up?
 
Policies are already created but disabled for now until we fix issue with mixer.  Currently service not exposed.

**Comment by Demonsthere** [comment]
Hi, 
I have been trying to reproduce this problem, and sadly I am unable to. 
I have tried by creating a simple app from our [examples](https://kyma-project.io/docs/root/kyma/#examples-examples), and expose it as an API in the console (in a custom, kyma managed namespace).
Afterwards I have applied the configuration you supplied and tried to curl the exposed application. 
Current results:

- `200` when accessing an unprotected API
- `401` when accessing a protected API

I was unable to get a `403`. Can you supply more context and information?

**Comment by Demonsthere** [comment]
Update:
After some thorough research, we have found that the [RbacConfig](https://istio.io/docs/reference/config/authorization/istio.rbac.v1alpha1/#RbacConfig) in istio is global, meaning only one instance of it can present in the srvice-mesh at any present time. 
As it turns out, we in kyma have a default configuration in place, which is created during the installation procedure, and as it is created as the first one, Yours is simply ignored. 

I have tested the provided scenario and found out it works, however you need some additional configuration in the form of [Authentication Policy](https://istio.io/docs/reference/config/istio.authentication.v1alpha1/#Policy) and a modification to the existing RbacConfig. 

```yaml
# updated existing RbacConfig
---
apiVersion: rbac.istio.io/v1alpha1
kind: RbacConfig
metadata:
  name: default
  namespace: kyma-system
spec:
  inclusion:
    services:
      - core-ui-api.kyma-system.svc.cluster.local
    namespaces:
      - default
  mode: ON_WITH_INCLUSION

# The policy to allow JWT usage
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: jwt
  namespace: default
spec:
  targets:
  - name: productpage
    ports:
    - number: 9000
  origins:
  - jwt:
      issuer: "https://dex.kyma.local"
      audiences:
      - "productpage"
      jwksUri: "http://dex-service.kyma-system.svc.cluster.local:5556/keys"
  principalBinding: USE_ORIGIN

```
