### ISSUE TITLE
Publish API is broken when installed with Knative

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2797]
**Steps to reproduce**
* Start Kyma with `--knative` feature flag
* Follow steps until [setting up Node port](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario#node-port)
* Create a channel manually in `kyma-system`
```yaml
apiVersion: eventing.knative.dev/v1alpha1
kind: Channel
metadata:
  name: sample-external-solution-order-created-v1
spec:
  provisioner:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: ClusterChannelProvisioner
    name: natss
```
* [Publish the event](https://github.com/kyma-incubator/examples/tree/master/kyma-local-e2e-scenario#publish-the-event)

**Expected Result**
The event gets successfully published

**Actual result**
The API returns error 500

```
$echo '{"event-type" : "order-created", "event-type-version" : "v1", "event-time" : "2018-05-02T22:08:41+00:00", "data" : {"orderCode" : "1234"}}'|http POST https://gateway.kyma.local:${NODE_PORT}/sample-external-solution/v1/events --cert=generated.pem --verify=no

HTTP/1.1 500 Internal Server Error
Connection: keep-alive
Content-Length: 123
Content-Type: application/json
Date: Tue, 19 Feb 2019 13:04:52 GMT
Server: nginx/1.15.3
Strict-Transport-Security: max-age=15724800; includeSubDomains
x-envoy-decorator-operation: sample-external-solution-event-service-external-api.kyma-integration.svc.cluster.local:8081/*
x-envoy-upstream-service-time: 30

{
    "message": "Some unexpected internal error occurred, please contact support.",
    "status": 500,
    "type": "internal_server_error"
}
```

Publish logs
```
2019/02/19 13:04:52 ERROR: GetChannel(): geting channel: channels.eventing.knative.dev "order-created" not found
2019/02/19 13:04:52 cannot find the knative channel 'order-created' in namespace 'kyma-system'
2019/02/19 13:04:52 publish cloud-event failed: &{500 internal_server_error Some unexpected internal error occurred, please contact support.  []}
```

The reason seems to be the implementation does not derive the channel name using source id (application identifier), event type, and event type version
https://github.com/kyma-project/kyma/blob/master/components/event-bus/cmd/event-bus-publish-knative/handlers/publish.go#L97

This is correctly encoded in the previous version
https://github.com/kyma-project/kyma/blob/master/components/event-bus/cmd/event-bus-publish/handlers/handlers.go#L179

Another missing piece is to add escape characters as was done previously.

**Comment by marcobebway** [comment]
The [knative-eventing-adoption](https://github.com/abbi-gaurav/community/blob/51c4822c32ac19de7a6587c636576e1423fd2782/sig-and-wg/wg-knative/knative-eventing-adoption.md) document has to change also, because it maps the event-type to the channel-name without taking into consideration the source-id or the event-type-version.

**Comment by abbi-gaurav** [comment]
Updated the doc https://github.com/kyma-project/community/pull/220

**Comment by marcobebway** [comment]
This is done. The channel name consists of the **source-id**, **event-type** and **event-type-version**. In order to avoid channel naming collisions, we applied the naming convention described [here](https://github.com/kyma-project/kyma/blob/7e6b2c9b1a857c54b1e2f9d1e71f9370bafa427b/components/event-bus/cmd/event-bus-publish-knative/handlers/publish.go#L154).

> Note: It is the responsibility of the channel creator to create knative channels following the channel naming convention mentioned [here](https://github.com/kyma-project/kyma/blob/7e6b2c9b1a857c54b1e2f9d1e71f9370bafa427b/components/event-bus/cmd/event-bus-publish-knative/handlers/publish.go#L154).

Verified the fix locally on minikube with the following setup:

* Create an application from the kyma console UI called **sample-external-solution**.

* Create a channel manually following the naming convention mentioned above:
  ```yaml
  apiVersion: eventing.knative.dev/v1alpha1
  kind: Channel
  metadata:
    name: sample--external--solution-order-dot-created-v1
    namespace: kyma-system
  spec:
    provisioner:
      apiVersion: eventing.knative.dev/v1alpha1
      kind: ClusterChannelProvisioner
      name: in-memory-channel
  ```

* Use port-forward to send requests to the created application event-service pod. 

* Send publish request:
  ```bash
  $ curl -i -H "Content-Type:application/json" -X POST http://localhost:8081/sample-external-solution/v1/events -d '{"event-type": "order.created", "event-type-version": "v1", "event-time": 
  "2018-11-02T22:08:41+00:00", "data": {"event":{"customer":{"customerID": "1234", "uid": 
  "name@mail.com"}}}}'
  HTTP/1.1 200 OK
  Content-Type: application/json
  Date: Wed, 20 Feb 2019 18:52:30 GMT
  Content-Length: 52

  {"event-id":"fae61418-4a94-408d-80ea-1b5486e5229c"}
  ```

* Check the knative-publish application logs
  ```bash
  2019/02/21 16:31:25 publish success to the knative channel 'sample--external--solution-order-dot-created-v1' in namespace 'kyma-system'
  ```
