### ISSUE TITLE
Add the settings field to the MF and CMF CRDs

### ISSUE THREAD

**Issue by dariadomagala** [kyma-project/kyma#2848]
Add the `settings` field to the Custom Resource Definitions of Micro Frontend and Cluster Microfrontend. Settings should optional and should be an object for each navigation node, with custom fields.
Add documentation to Kyma.

Example of CMF with settings field:

```
apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
  name: applicationsmicrofrontend
  labels:
    app:  applicationsmicrofrontend
spec:
  displayName: Applications
  version: v1
  category: Integration
  placement: cluster
  viewBaseUrl: 'https://console.{{ js .Values.global.domainName }}/consoleapp.html#'
  navigationNodes:
    - label: Applications
      navigationPath: apps
      viewUrl: '/home/settings/apps'
      order: 1
      settings:
        readOnly: {{ js .Values.XYZ.applicationManagementDisabled }}
    - label: Application Details
      navigationPath: apps/details
      viewUrl: '/home/settings/apps'
    - label: Application Details
      navigationPath: apps/details/:name
      viewUrl: '/home/settings/apps/:name'
      settings:
        readOnly: {{ js .Values.XYZ.applicationManagementDisabled }}
```
