### ISSUE TITLE
Update service catalog to newer version than 0.1.41

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#2902]
AC:
- update Service Catalog to newer version than  0.1.41
- run test for service catalog, from https://github.com/kyma-incubator/service-catalog-tester.
- if update done adjust a name of the ticket to the given version, and create a new one for the next sprint
- see kubernetes-incubator/service-catalog#2577 , In case the PR (kubernetes-incubator/service-catalog#2576) is merged, we can use newer (currently it is 0.4) version of bundles repo (simplified Azure Broker)

**Comment by piotrmiskiewicz** [comment]
see https://github.com/kubernetes-incubator/service-catalog/pull/2577

**Comment by polskikiel** [comment]
Please add to the release notes the information about the documentation migrated into bundles

**Comment by piotrmiskiewicz** [comment]
provisioning GCP broker without the secret makes the broker:
```
status:
  asyncOpInProgress: true
  conditions:
  - lastTransitionTime: "2019-04-25T12:41:12Z"
    message: The instance is being deprovisioned asynchronously
    reason: Deprovisioning
    status: "False"
    type: Ready
  - lastTransitionTime: "2019-04-25T12:49:44Z"
    message: 'Provision call failed: provisioning failed on error: while installing
      helm release: while installing release from chart with name [hb-gcp-service-broker-default-685ab67d-6757-11e9-82fb]
      in namespace [qa]: rpc error: code = Unknown desc = Job failed: BackoffLimitExceeded'
    reason: ProvisionCallFailed
    status: "True"
    type: Failed
  - lastTransitionTime: "2019-04-25T12:49:44Z"
    message: 'Provision call failed: provisioning failed on error: while installing
      helm release: while installing release from chart with name [hb-gcp-service-broker-default-685ab67d-6757-11e9-82fb]
      in namespace [qa]: rpc error: code = Unknown desc = Job failed: BackoffLimitExceeded'
    reason: ProvisionCallFailed
    status: "True"
    type: OrphanMitigation
```
