### ISSUE TITLE
failed to connect to istio when deployed on GKE using kyma installer

### ISSUE THREAD

**Issue by mikosa** [kyma-project/kyma#3079]
I followed the instruction and installed kyma successfuly as described in the instructions.
But there is a networking issue not allowing connection to istiogateway through the load balancer.

istio-ingressgateway log shows:
```
[2019-03-08 17:04:00.821][62][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:111] cm init: initializing secondary clusters
[2019-03-08 17:04:00.826][62][info][upstream] external/envoy/source/common/upstream/cluster_manager_impl.cc:134] cm init: all clusters initialized
[2019-03-08 17:04:00.826][62][info][main] external/envoy/source/server/server.cc:401] all clusters initialized. initializing init manager
[2019-03-08 17:04:00.836][62][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Failed to load private key from /etc/istio/ingressgateway-certs/tls.key
[2019-03-08 17:04:00.836][62][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: Failed to load private key from /etc/istio/ingressgateway-certs/tls.key
[2019-03-08 17:04:00.836][62][info][config] external/envoy/source/server/listener_manager_impl.cc:908] all dependencies initialized. starting workers
[2019-03-08 17:04:26.356][62][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Failed to load private key from /etc/istio/ingressgateway-certs/tls.key
[2019-03-08 17:04:26.356][62][warning][config] bazel-out/k8-opt/bin/external/envoy/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener 0.0.0.0_443: Failed to load private key from /etc/istio/ingressgateway-certs/tls.key
[2019-03-08 17:05:00.832][62][info][main] external/envoy/source/server/drain_manager_impl.cc:63] shutting down parent after drain
[2019-03-08 17:09:35.610][62][warning][upstream] external/envoy/source/common/config/grpc_mux_impl.cc:223] gRPC config for type.googleapis.com/envoy.api.v2.Listener update rejected: Error adding/updating listener 0.0.0.0_443: Failed to load private key from /etc/istio/ingressgateway-certs/tls.key
```

When I kubectl exec to istio-gateway, I can find the tls.key and cert in the correct folder and well decrypted (not in base64)

Istio proxy shows no errors in logs

my-kyma.yaml shows the following:
```
apiVersion: v1
kind: Namespace
metadata:
  name: kyma-installer
  labels:
    istio-injection: disabled
---
apiVersion: v1
kind: LimitRange
metadata:
  name: kyma-default
  namespace: kyma-installer
spec:
  limits:
  - max:
      memory: 1024Mi # Maximum memory that a container can request
    default:
      # If a container does not specify memory limit, this default value will be applied.
      # If a container tries to allocate more memory, container will be OOM killed.
      memory: 96Mi
    defaultRequest:
      # If a container does not specify memory request, this default value will be applied.
      # The scheduler considers this value when scheduling a container to a node.
      # If a node has not enough memory, such pod will not be created.
      memory: 32Mi
    type: Container
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: installations.installer.kyma-project.io
spec:
  group: installer.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Installation
    singular: installation
    plural: installations
    shortNames: ['installation']
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: releases.release.kyma-project.io
spec:
  group: release.kyma-project.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Release
    singular: release
    plural: releases
    shortNames: ['release']
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kyma-installer
  namespace: kyma-installer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kyma-installer
  namespace: kyma-installer
spec:
  template:
    metadata:
      labels:
        name: kyma-installer
    spec:
      serviceAccountName: kyma-installer
      containers:
      - name: kyma-installer-container
        image: eu.gcr.io/kyma-project/kyma-installer:0.7.0
        imagePullPolicy: IfNotPresent
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kyma-installer-reader
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kyma-installer
subjects:
- kind: ServiceAccount
  name: kyma-installer
  namespace: kyma-installer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyma-installer-reader
---
apiVersion: "installer.kyma-project.io/v1alpha1"
kind: Installation
metadata:
  name: kyma-installation
  finalizers:
    - finalizer.installer.kyma-project.io
spec:
  version: "0.0.1"
  url: ""
  components: 
    - name: "cluster-essentials"
      namespace: "kyma-system"
    - name: "istio"
      namespace: "istio-system"
    - name: "knative"
      namespace: "istio-system" # KNative comes with namespaces hardcoded so this one is only for installer
    - name: "istio-kyma-patch"
      namespace: "istio-system"
    - name: "prometheus-operator"
      namespace: "kyma-system"
    - name: "dex"
      namespace: "kyma-system"
    - name: "service-catalog"
      namespace: "kyma-system"
    - name: "service-catalog-addons"
      namespace: "kyma-system"
    - name: "helm-broker"
      namespace: "kyma-system"
    - name: "nats-streaming"
      namespace: "natss"
    - name: "assetstore"
      namespace: "kyma-system"
    - name: "core"
      namespace: "kyma-system"
    - name: "event-bus"
      namespace: "kyma-system"
    - name: "application-connector"
      namespace: "kyma-system"
    - name: "ark"
      namespace: "heptio-ark"
    - name: "logging"
      namespace: "kyma-system"
    - name: "jaeger"
      namespace: "kyma-system"
    - name: "monitoring"
      namespace: "kyma-system"
---

---
apiVersion: v1
kind: Secret
metadata:
  name: application-connector-certificate-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
type: Opaque
data:
  global.applicationConnectorCa: ""
  global.applicationConnectorCaKey: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-certificate-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
data:
  global.tlsCrt: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZMekNDQkJlZ0F3SUJBZ0lUQVBvNUg3MzlSR3M5dDJQZXgvMHd0ajRzTWpBTkJna3Foa2lHOXcwQkFRc0YKQURBaU1TQXdIZ1lEVlFRRERCZEdZV3RsSUV4RklFbHVkR1Z5YldWa2FXRjBaU0JZTVRBZUZ3MHhPVEF6TURneApOREEzTkRsYUZ3MHhPVEEyTURZeE5EQTNORGxhTUJZeEZEQVNCZ05WQkFNVEMyOXNhV0poZEc4dVkyOXRNSUlCCklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFwdldUN3kxM1NGZEtNeitHYk9wZHJVN28KMk41VGxXRlhSWGRWTnI2citScFNiTmxnYzVyMjJTbWJuOTRhVnY1dzNNU09aY212RWZORFBURkhWZEc3eUJrcwo2SlpzZTYwang3SW5UOGlCVTZvc3FzeDBhRXRnRTByVG03VnFtSWo4RHRwMitvYVhtY3hZTEsrKzB2R2lsbVI4CnNhUTBHemp6Z2hINnZ5cVJVcEI4Nnp1ZkJQQnplWEZZd2JobldiUEdHNFV1MVQxNUJqUlF2cFRjeVpRUXJaeE8KeDN6b2h5OVJTdGZwK1NDY0hkbUhPWUFHU1lRN3U4UTRzTTIxempyY0pUTW0wSnI5NGRwVWdVZW1LK09IN3FqdApFcXBxeE9od3VXMFVOU0FUUG45SkRkK2VRWUk4c004TjJCU0F5eEtFSVVlSXJqeXgxNWx1QjZVaGJncUxld0lECkFRQUJvNElDYURDQ0FtUXdEZ1lEVlIwUEFRSC9CQVFEQWdXZ01CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUIKQmdnckJnRUZCUWNEQWpBTUJnTlZIUk1CQWY4RUFqQUFNQjBHQTFVZERnUVdCQlRpbnBPc2paR2tpbTBLTnpNZQpwRmNFLzBFNjJUQWZCZ05WSFNNRUdEQVdnQlRBekFOR3VWZ2d6Rnh5Y1BQaExzc2dwdlZvT2pCM0JnZ3JCZ0VGCkJRY0JBUVJyTUdrd01nWUlLd1lCQlFVSE1BR0dKbWgwZEhBNkx5OXZZM053TG5OMFp5MXBiblF0ZURFdWJHVjAKYzJWdVkzSjVjSFF1YjNKbk1ETUdDQ3NHQVFVRkJ6QUNoaWRvZEhSd09pOHZZMlZ5ZEM1emRHY3RhVzUwTFhneApMbXhsZEhObGJtTnllWEIwTG05eVp5OHdGZ1lEVlIwUkJBOHdEWUlMYjJ4cFltRjBieTVqYjIwd1RBWURWUjBnCkJFVXdRekFJQmdabmdRd0JBZ0V3TndZTEt3WUJCQUdDM3hNQkFRRXdLREFtQmdnckJnRUZCUWNDQVJZYWFIUjAKY0RvdkwyTndjeTVzWlhSelpXNWpjbmx3ZEM1dmNtY3dnZ0VFQmdvckJnRUVBZFo1QWdRQ0JJSDFCSUh5QVBBQQpkZ0RkbVRUOHBlY2tnTWxXYUgyQk5Ka0lTYkpKOTdWcDJNZThxejljd2ZOdVpBQUFBV2xkMkpaRUFBQUVBd0JICk1FVUNJUURwWlZMeFhMVGxsUWRmdnNPY1REUWFBaUdIYVlCYVd2cHp2QUhmWm1HVkNBSWdkd0VWNEx6VDBMWnkKRC8xWWVsVEtKNnkvVVFJR2hUOWtpby93VjJOQkYrd0FkZ0FXNkduQjBaWHExOFA0bHhyajhIWUI5NHpodHAweApxRklZdG9OL01hZ1ZDQUFBQVdsZDJKWmtBQUFFQXdCSE1FVUNJUURiUVZmRFhFYmNDYmNHTWlBbWwzKzYzNHI5CnFqUmtzZDZxUlF3dDlaTEd6QUlnVTJZKzdGa2xack43ZGtpUkdsUDVmV0RCQyt6ZlNUUXp0VWpvc1N3L0hCa3cKRFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUhXdnJhZEVUL2dteXdxUVFNLzFqWkZrdGNRQ05OSVBGZjVaaGI5eQpmaUZmVHJvOUlLcUY2WElsNXc5K1NuQ1BXY1E0N3VKWGRhc1dPekErNHRsdlhkUUZvYnNTUVNoZ1FaTUtPS0hZCmNYdmw5L25FdCtoU2RLSTZ6OXlWSlA3K2h6eEhyZjJYd09WTzJmZkVacVZJZ0s3Vm5PZjFQV2d2b2RlaE4zancKa1I4THRjbnNGclphYkdkUlZ3UUNkdlIvSitYZlV6Qlo5dDFWSkcxQThrb3RITCtZQXJqN1dCRXR3VVBwbzFyVAo4dktGdmlFSHhFcEZhd2dvbUlKL014ODRXQzAxRWRTS3ZUWUJQazMwTVRLOWVnczVRVUM1Vi9zdktBZ1N1N0FXCmt4SUNvcTl1dWhtNGo5T3JsTFZmUGdLcE0yN3g5NkFjNElCYVhMQ0diMjAxK3RnPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCgo="
  global.tlsKey: "LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcFFJQkFBS0NBUUVBeFlML2hwN3Y4ODVZdWlzS0pvbk5lWEk0d2U1OHJwTTM0eE5LZkExc1d4OVdFczQ1CkNFdnZodkRlUU9lQkVTOGh5emlEWDd6alZTMnduTkpPVVFzNXRtai8wS2dZS1ByNk1iME9JSitGcWEwelhWdUEKdjdudHRpb2c4c2FkZ3lLNHBhb1F0QVUrdHFGbmp0NmRnR2xvWjRndThwbzVMNDdTaEpXeXBQQUJMcGZwakZpUgo0Mkc4QmVVeFdLRU5DcGxaMGREU1ZsNDFlNFJkZGN1Wm9xYWdONTNWTzUzZjBHV3pXNWYwSktjWWlsa2JPbHRlCmo3R0xVSGZDQXFNMXpWSnlERWFKMXRzYzFXNVhyNXBQTW5KclN0cWI0aFErY1g5L1R1clZUWWlMWmJ1NGloM2sKRnBmeUhkNHNTUlNmbXlxNHNYMm1hcXp3Z29VbXowZ1B3a3VRUVFJREFRQUJBb0lCQVFDUzZyK0I5c1hNV0NoZAp5dGdSRko0WUFXUEF0ZEplMVRsVUdxeGtIR1FHWUFmWmt6YVBPbFRnemxpMGRML245V1F3MDBlOXRqWnZ6TDI3CjJSL1NYd1E5OEZxaGJmZ1N1NlhSeTZ3dmpobVJ2amtmNzRtVWxBd0RYZEVHWmNFU280Z3dDcEhFSnNhZ2VPMGMKTS9GNmJHM3gzVFgyMWN0RjJmbzBEMXBFSUJidy9WVlZzdkhjMmpEUUZqcDhOMnM5NGhpZE0rdTVpbWt3R2p5VQpoMTNuVUZrUGgzQmE0VjE4TmY5NVY4bk1UYnQ0N0ZxcVA5VFQ3bGlLYlZaMWIwai9kNlJWRnRzVkhpRFJjTHpSCkRKay9xUnNrYmxvNkdJRWNDZHRhcXJtQWRxTGZjMjVhWDJObE5TaWFheGtNL3MzWXhiRlZ2c2dpR0V4Rm5DdHkKeU1BUzRlREZBb0dCQU03Yk5YSnZkU3laN0NOQTFRbVUyNjA3WGVEQ1RBaXpHUUVwTWt2VElmY0JrcW9OUmp1RgplNVdLWmxoeVFlYlc1S3BqRk80ZndwbHVYUUlYeFJGcngzOUh5L211bmdkTDNFK0c1L3RnTHdvY0t1L216dlh5ClRoblZpWU5tbXpmTjZtcjVLYUcrSDJQRGErcHF6MnY3ZnViaG5ETGRQKzVKNGQyWTV2OE1xemZUQW9HQkFQUnYKZGp2UkQvdU5PczRBcmtuS1NyRS8xY1BEU25DVFhNTnFyekNCR1E3Ymp6ODZxZUJwcTF2WVJCcFVFU21lOUU4ZApBdEVRWmpEaFRUb0V5am9BbHBkNU53REtCRjZVeTRSNTZ1dUxDci9xSkhtYVExd3Z6Q0JqclAzWGtqNmlZR1RXCkR2d1ZpS2NPM1Zpdlh2U09oeDMzSTdMRG1pWFBkZTlIQVFkU2FYOGJBb0dCQUx4TFBqT1UwWXh2OEV1RzBHV1EKWXdjbGF5Y1V0akdWRmNYQXdrL1RPSytuZHVIa2czSGE1OHdQMTJuYlY3SFJHd1VlZkFibVVqVm9DTEhIQVZRQwpUKzdFWkNBN213MzVOK29NVzA2dkZ5S1UwV0RmTUxVZ2c0ZHdvV1JER2plSjhVQyszZTZsS2QyZUhiV2MxSUx1CncyMVhJT0FNRmczS294Y2IvK2xhbHVDUkFvR0JBSTczMHJQUjZBTTk2N01wK3NiMkp4SGRRRzZyL3hJeFh3UjkKbGRKTThCY2NuSUJqRTVGS3ZRdVBSdVlQWGFwMmFuY0xoT1k3TFVwUnZSVytUM24xZGg5S3FyMHZhN2JXV09NMwpYQXhBMnh5OUduQjFwZ2g1Zkc5RlhaMXJSUUtWZnNQNzMrL1p1SC9kMWVGVlViakExSTdXU203NHNXU0VIM3JBCmtQMXpXbmtaQW9HQUp1MFQ5bmdrWWJOdnpVUStXYW5UZUdlRlBNcU1nRC82NVNIU1lORlpwc09pVVdxQktFeGUKVmlOV3J2ckwyVVN3NWZraEZkajRGSS9LMFc4R2VYSFBHMGd4MmpuUjRrMGdOMzBVSkN5YWM1bTNsbG51aWFpNwp1L0tzbjliWDdELzd2YWt0YnBoVksxUGFXcmtDcTFWT0p4MHdCbUhzYitoakI1WFplRzJTWm5JPQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQoK"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: installation-config-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
data:
  global.domainName: "olibato.com"
  global.applicationConnectorDomainName: ""
  global.loadBalancerIP: ""
  global.etcdBackup.containerName: ""
  global.etcdBackup.enabled: ""
  nginx-ingress.controller.service.loadBalancerIP: ""
  cluster-users.users.adminGroup: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: monitoring
data:
  global.alertTools.credentials.slack.apiurl: ""
  global.alertTools.credentials.slack.channel: ""
  global.alertTools.credentials.victorOps.routingkey: ""
  global.alertTools.credentials.victorOps.apikey: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: connector-service-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: application-connector
data:
  connector-service.tests.skipSslVerify: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
data:
  gateways.istio-ingressgateway.loadBalancerIP: ""
  global.proxy.excludeIPRanges: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: knative-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: knative
data:
  knative.domainName: "olibato.com"
```

gcloud cloud DNS well formed:
```
*.olibato.com. | A | 60 | 35.202.19.77 |  
gateway.olibato.com. | A | 60 | 35.222.101.82
```

I also checked the ingress load balancer created; it is fine and has the 443 port open (and several other ports are open too)

Please help me!!
