### ISSUE TITLE
Function is not updated when their ServiceBindingUsage is deleted

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#310]
Confirm these statements before you submit the issue:

- [x] I have searched open and closed issues for duplicates.
- [x] I have read the contributing guidelines.
---

**Description**
When we are applying the ServiceBindingUsage to kubeless Function we are modifying Function spec by adding new label under deployment obj
```yaml
  spec:
    checksum: ""
    deployment:
      metadata:
        creationTimestamp: null
      spec:
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
            labels:
              use-72032fc1-7548-11e8-bde1-0684dced7ab6: "17753"
```
and thanks to that the kubless restart the function and add new labels for created pods.

When we are deleting ServiceBindingUsage then we are also removing such label from Function 
```yaml
  spec:
    checksum: ""
    deployment:
      metadata:
        creationTimestamp: null
      spec:
        strategy: {}
        template:
          metadata:
            creationTimestamp: null
          spec:
            containers: null
```

but Kubeless controller in such case does not restart the pods so they still have a label and secrets injected.

**Expected result**
Kubeless controller restarts the pods when labels section is removed from **spec.deployment.metadata.labels**

**Actual result**
Kubeless controller does not restart the pods when labels section is removed from **spec.deployment.metadata.labels** so they still have a label and secrets injected.

We need to check how exactly the kubless controller works and fix it or report issue for them

AC:
- validate if issue is in BUC or in kubeless controller (assign ticket to serverless team)

**Comment by piotrmiskiewicz** [comment]
The problem is the Kubeless controller implementation. I've done simple test, create a function:
```
spec:
  deployment:
    spec:
      template:
        metadata:
          labels:
            lab1: abc
            lab2: def
```

then update the function without one label:
```
spec:
  deployment:
    spec:
      template:
        metadata:
          labels:
            lab1: abc
```
Then execute the following command like:
``` kubectl get deployment redis-client -n qa -o jsonpath="{.spec.template.metadata.labels}{'\n'}"```
The deployment still contains both labels. This is because of the Kubeless controller performs a merge patch (https://github.com/kubeless/kubeless/blob/master/pkg/utils/kubelessutil.go#L702).
Such operation merges labels of existing deployment with labels from the new one. Such operation does not remove any item from the list.
This is the reason of the problem - label is not removed from the list, Pod still contains label added by the BUC.
