### ISSUE TITLE
Loki promtail doesn't detect kubeless lambda function pods

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#3217]
Loki promtail agent doesn't detect lambda function pods for logging. 

Current promtail scrape config drop all pods which not labeled with app, since all kubeless lambda functions using label function instead of app are dropped from log tail process.

Promtail scrape config should updated be with new job definition for kubeless lambda function pods

Example:
```
- job_name: kubernetes-pods-function
        kubernetes_sd_configs:
        - role: pod
        relabel_configs:
        - source_labels:
          - __meta_kubernetes_pod_node_name
          target_label: __host__
        - action: drop
          regex: ^$
          source_labels:
          - __meta_kubernetes_pod_label_function
        - action: replace
          replacement: $1
          separator: /
          source_labels:
          - __meta_kubernetes_namespace
          - __meta_kubernetes_pod_label_function
          target_label: job
        - action: replace
          source_labels:
          - __meta_kubernetes_namespace
          target_label: namespace
        - action: replace
          source_labels:
          - __meta_kubernetes_pod_name
          target_label: instance
        - action: replace
          source_labels:
          - __meta_kubernetes_container_name
          target_label: container_name
        - action: labelmap
          regex: __meta_kubernetes_pod_label_(.+)
        - replacement: /var/log/pods/$1/0.log
          separator: /
          source_labels:
          - __meta_kubernetes_pod_uid
          - __meta_kubernetes_pod_container_name
          target_label: __path__
```
