### ISSUE TITLE
Installation doc indicates kubernetes-dashboard deployed out of the box

### ISSUE THREAD

**Issue by ArthurPerry** [kyma-project/kyma#3288]
**Description**
[Installation doc](https://kyma-project.io/docs/root/kyma/#installation-install-kyma-locally-from-the-release-access-the-kubernetes-dashboard) indicates kubernetes-dashboard deployed out of the box.  Please update this to explain that the dashboard is removed as of v0.8.0 but also include steps to deploy it, based on [Kubernetes Dashboard](https://github.com/kubernetes/dashboard)

`kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/v1.10.1/src/deploy/recommended/kubernetes-dashboard.yaml`

Also would be nice to grant dashboard access to admin@kyma.cx user but I haven't figured out how to do this yet.  Creating a new service account  and granting it access works.  (***not called admin-user*** - doing so impacts the kyma-system admin-user making it impossible to log into the kyma console.)
``` 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dashboard-user
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: dashboard-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: dashboard-user
  namespace: kube-system
```
