### ISSUE TITLE
Helm Broker creates Service Class documentation from add-ons

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#3358]
**Description**

Store bundle's documentation in bundle itself via the Headless CMS functionality.

**Reasons**

We don't want to store bundle documentation in kyma itself, as it is right now.

**AC**
- Not estimated in that story (all bundles docs moved to respective bundles (https://github.com/kyma-project/kyma/issues/3577))
- helm-broker uploads bundle documentation as ClusterDocsTopic during repository registration
- that solution must support documentation registration from bundle but with external resources (md, swagger, asyncAPI specs), see details in the `technical details section`
- HB removes given ClusterDocsTopic when repository URL is deregistered
- helm-broker pass repository URL parameter to given bundle (Could be used in helm-chart of the given bundle to upload documentation for given namespace by DocsTopic for example Azure Service Classess documentation)
- ~using ClusterDocsTopic and DocsTopis only if those CRDs exists~
- show refactoring on our Redis bundle

**Technical Details**
- about AC: `documentation registration from bundle but with external resources`, see how it can be realized: https://github.com/PK85/add-ons/blob/master/addons/slack-connector-0.1.0/docs/cluster-docs-topic.yaml . And HB will take that CR and install, of course in case documentation is provided in a bundle itself, HB need to adjust URLs to bundleRespository what was registered to HB with given bundle.

See, dependency:
- https://github.com/kyma-project/console/issues/666
- https://github.com/kyma-project/kyma/pull/3292/files

**Comment by derberg** [comment]
When you will work on defining new CRs, you can take docs to another level, in theory somethign like that should work:

```
apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  name: {Text-Analytics-Service-Class-Id}
  labels:
    cms.kyma-project.io/view-context: service-catalog
spec:
  sources:
    - type: markdown
      name: markdown-files
      mode: package
      url: https://github.com/kyma-project/kyma/archive/master.zip
      filter: /docs/service-brokers/azure-broker-service-classes/azure-textanalytics/docs
    - type openapi
      name: openapi-swagger-file
      mode: single
      url: https://westus.dev.cognitive.microsoft.com/docs/services/TextAnalytics.V2.0/export?DocumentFormat=Swagger&ApiName=Text%20Analytics%20API%20(v2.0)
```
