### ISSUE TITLE
Support overriding array entry by Installer

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#3634]
**Description**

I had a case, where I created a ConfigMap with overrides for `groups` entry. Unfortunately, the `groups` entry is an array and installer right now does not have any support for that.

Overrides are done by ConfigMaps data which are `map[string]string`. In installer, it is also read as [`map[string]string`](https://github.com/kyma-project/kyma/blob/master/components/installer/pkg/overrides/config-reader.go#L25-L26)

Then such overrides are propagated to Helm Chart and in values.yaml instead of 
```yaml
bindings:
  kymaAdmin:
    groups: ['kyma-project:cluster-access']
```
we have
```yaml
bindings:
  kymaAdmin:
    groups: "['kyma-project:cluster-access']"
```
which causing error: `range can't iterate over ['kyma-project:cluster-access']` 

How this can be achieved by the installer? 

### Possible solution

Installer should have its own CRD instead of using the ConfigMap. 

E.g.
```yaml
kind: InstallerOverride
metadata:
  name: custom-overrides
  namespace: kyma-system
spec:
  bindings:
  kymaAdmin:
    groups: ['kyma-project:cluster-access']
```

Thanks to that you can simply copy all the spec body and use it for helm overrides. What's more user will have the YAML syntax and formatting support of of the box and you will support all cases that helm does
