### ISSUE TITLE
Create documentation about using the DocsTopic in helm-broker

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#3719]
**Description**

We need to document the way how user can provide the documentation for bundle and wrapped Helm Chart.

in https://github.com/kyma-project/kyma/blob/master/docs/helm-broker/docs/03-01-create-bundles.md document that:
- In the `docs`  directory, you should place documentation for the bundle and wrapped Helm chart. The directory layout is up to "user" but provides the best practices.
	```
	sample-bundle/
	  ├── meta.yaml                             # [REQUIRED] A file which contains metadata information about this bundle
	  ├── chart/                                # [REQUIRED] A directory which contains a Helm chart that installs your Kubernetes resources
	  │    └── {chart-name}/                    # [REQUIRED] A Helm chart directory
	  │         └── ....                        # [REQUIRED] Helm chart files   
	  ├── plans/                                # [REQUIRED] A directory which contains the possible plans for an installed chart
	  │    ├── example-enterprise               # [REQUIRED] A directory which contains files for a specific plan
	  │    │   ├── meta.yaml                    # [REQUIRED] A file which contains metadata information about this plan
	  │    │   ├── bind.yaml                    # A file which contains information required to bind this plan
	  │    │   ├── create-instance-schema.json  # JSON schema definitions for creating a ServiceInstance
	  │    │   ├── bind-instance-schema.json    # JSON schema definitions for binding a ServiceInstance
	  │    │   ├── update-instance-schema.json  # JSON schema definitions for updating a ServiceInstance
	  │    │   └── values.yaml                  # Default configuration values in this plan for a chart defined in the `chart` directory
	  │    └── ....
	  │
	  └── docs/                                 # A directory which contains a documentation for this bundle
	       ├── meta.yaml                        # A file which contains metadata information about documentation for this bundle
	       ├── {assets}                         # Files with documentation and assets
	       └── ....
	```
- document the `meta.yaml` file which holds information on how documentation should be uploaded
  ```yaml
	docs:
	  - template: # template describes the ClusterDocsTopic that will be created.
	      displayName: "Doc for redis bundle"
	      description: "Overall documentation"
	      sources:
	        - type: markdown
	          name: markdown-files
	          mode: package
	          url: abc.pl # If not provided then Helm broker will inject the full repository URL for this bundle
	          filter: /docs/bundles
  ```
  for now, we support only one entry under docs array. For now we only created the ClusterDocsTopic because in Kyma the Helm Broker is installed as ClusterServiceBroker (by default)
- document that you can define in you wrapped Helm Chart the ClusterDocTopic/DocTopic. It's required when provisioning action for given bundle will generate new classes which will be visible in Service Catalog and you want to provide documentation for them

The Cluster Doc Topic is documented here: https://kyma-project.io/docs/components/headless-cms/#custom-resource-clusterdocstopic

The Wookiee team does not have any overall documentation of how the ClusterDocsTopic or DocTopic working in Kyma. In our documentation, we should only mention overall idea and create an issue for them to created detailed documentation about the process of uploading documentation for ClusterServiceClass and ServiceClass. In this issue mention that after all, they should add to our documentation statement "Find more information `[here](<link_to_detailed_docs>)`"

**AC:**
- strategy for providing documentation both for bundle and bundle Helm Chart is well documented
