### ISSUE TITLE
Add support for DocsTopic in case of registering new repository in Helm Broker

### ISSUE THREAD

**Issue by mszostok** [kyma-project/kyma#3721]
**Description**
Bundle has new `/docs` folder. In docs folder we have `meta.yaml` file with such spec:
```yaml
docs:
  - template: # template describes the ClusterDocsTopic that will be created.
      displayName: "Doc for postgres v9.6"
      description: "Overall documentation"
      sources:
        - type: markdown
          name: markdown-files
          mode: package
          url: https://github.com/kyma-project/kyma/archive/master.zip # when url is not provided then the bundler repository url is used e.g. https://github.com/kyma-project/bundles/releases/download/latest/azure-service-broker-0.0.1.tgz
          filter: /docs/service-brokers/azure-broker-service-classes/azure-textanalytics/docs
```

Right now we are supporting only one entry under `docs` array. Helm broker creates ClusterDocsTopic with given template during repository registration.

Fields under `template` are the same as we have under ClusterDocsTopic. 

Add label to created ClusterDocsTopic which will say that this resource was created by Helm Broker

### Tech details
Deserialize fields under `template` using struct provided by ClusterDocsTopic.

AC:
- helm-broker uploads bundle documentation as ClusterDocsTopic during repository registration
- that solution must support documentation registration from bundle but with external resources (md, swagger, asyncAPI specs)
- HB removes given ClusterDocsTopic when repository URL is deregistered
- show refactoring on our Redis bundle
