### ISSUE TITLE
Api-controller does not update policies under specific conditions

### ISSUE THREAD

**Issue by kubadz** [kyma-project/kyma#3827]
**Description**

Api-controller does not properly handle update scenario in which `spec.authentication` field is deleted and in the same time `spec.authenticationEnabled` is changed.

The following steps should be performed in minikube environment, as the `issuer` field in the sample Api contains domain adjusted for local installation. Alternatively, domain names can be adjusted to those in a cluster environment.

**Expected result**

Update of the Api CR is successfully handled and Policies are properly updated/created/deleted if necessary. 

**Actual result**

Api-controller returns errors and causes problems with handling Policies.

**Steps to reproduce**

There are many possible scenarios, but I will describe two example scenarios which are failing. 
Note: We do not need to create an actual service, which will be exposed by the Api, as the Api-controller creates proper resources (VirtualServices, Policies) for Api regardless of the existence of services being exposed.

1) First scenario

Create an Api with `spec.authentication` specified and without `spec.authenticationEnabled`, for example:
```
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: hello
spec:
  authentication:
    - type: JWT
      jwt:
        jwksUri: http://not-dex.kyma-system.svc.cluster.local:5556/keys
        issuer: https://not-dex.kyma.local
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080
```
that will make Api-controller successfully create a Policy CR with authentication settings from `spec.authentication` field. It is important to notice that we are not using the same `jwksUri` and `issuer` as the default configuration provided to api-controller. 
We can check that the Policy has been created by listing policies:
 ```
>kc get policies

# output:
# NAME      AGE
# hello     15s
```
or by checking Api-controller logs, which should output:
```
time="2019-04-24T10:24:00Z" level=info msg="Creating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://not-dex.kyma.local, JwksUri: http://not-dex.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T10:24:00Z" level=info msg="Authentication policy default/hello ver:  created."
time="2019-04-24T10:24:00Z" level=info msg="Authentication creation finished for: default/hello ver: 53231"
```
As the next step apply the Api without `spec.authentication` defined and with `spec.authenticationEnabled` field set to `true`:
```
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: hello
spec:
  authenticationEnabled: true
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080
```
That should make api-controller check if Policy needs the update and perform the update, as new (default) authentication specification is different than created in previous step. The Api-controller perform the update successfully what can be seen in api-controller logs:
```
time="2019-04-24T10:30:42Z" level=info msg="Updating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T10:30:42Z" level=info msg="Authentication policy updated: {Namespace: default, Name: hello, UID: 13307a28-667b-11e9-8048-2edd894abcef, Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T10:30:42Z" level=info msg="Authentication updated for: default/hello ver: 54894"
```
What is wrong here is that Api-controller tries to perform update twice, even that it skips it the second time.
```
time="2019-04-24T10:30:42Z" level=info msg="Authentication enabled. Trying to create or update authentication policy with: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T10:30:42Z" level=info msg="Update skipped: authentication policy has not changed."
time="2019-04-24T10:30:42Z" level=info msg="Authentication updated for: default/hello ver: 54896"
```
That leads to a serious problem.
After the next update in which any field related to created Policy changes (e.g. `spec.service.*`, `spec.authenticationEnabled`) Api-controller returns errors and doesn't update policy. Api-controller also "forgets" about the created policy in some cases, and doesn't delete them after the Api is deleted.
You can check that by applying again the first configuration, or by manually editing `spec.service.name` using `kubectl edit api hello`. After that you can check the logs from Api-controller, which should look like this:
```
time="2019-04-24T11:08:17Z" level=info msg="Authentication enabled. Trying to create or update authentication policy with: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: yellow}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T11:08:17Z" level=info msg="Updating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: yellow}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T11:08:17Z" level=error msg="[Error '99ceaaac-0a8f-473c-8ac9-f69ac09a833b']: Operation cannot be fulfilled on policies.authentication.istio.io \"hello\": the object has been modified; please apply your changes to the latest version and try again"
time="2019-04-24T11:08:17Z" level=error msg="Error while updating Authentication for: default/hello ver: 64227. Root cause: error while updating authentication policy (error code = '99ceaaac-0a8f-473c-8ac9-f69ac09a833b')"
```
The error will be repeated a few times.
We can also check that Api-controller is no longer able to delete the Policy:
```
kubectl delete api hello
```
Then in Api-controller logs we can see that Policy is not deleted:
```
time="2019-04-24T11:12:06Z" level=info msg="Deleting: default/hello ver: 65144"
time="2019-04-24T11:12:06Z" level=info msg="Delete skipped: no authentication policy to delete."
```
fetching policy with kubectl confirms that:
```
>kc get policies

# output:
# NAME      AGE
# hello     50m
```

2) Second scenario

In contrary to the first scenario, here we can see the errors just after the first update of the Api.

Create an Api with `spec.authentication` specified and with `spec.authenticationEnabled` set to false, for example:
```
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: hello
spec:
  authenticationEnabled: false
  authentication:
    - type: JWT
      jwt:
        jwksUri: http://not-dex.kyma-system.svc.cluster.local:5556/keys
        issuer: https://not-dex.kyma.local
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080
```
Because the `authenticationEnabled` is set to `false`, the Policy will not be created, even that we specified authentication settings. We can check that there are no logs in Api-controller like:
```
time="2019-04-24T10:24:00Z" level=info msg="Creating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://not-dex.kyma.local, JwksUri: http://not-dex.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T10:24:00Z" level=info msg="Authentication policy default/hello ver:  created."
t
```
also listing policies with kubectl returns `No resources found.`.
As the next step apply the Api without `spec.authentication` defined and with `spec.authenticationEnabled` field set to `true`:
```
apiVersion: gateway.kyma-project.io/v1alpha2
kind: Api
metadata:
  name: hello
spec:
  authenticationEnabled: true
  hostname: hello.kyma.local
  service:
    name: hello
    port: 8080
```
That would make Api-controller create the Policy:
```
time="2019-04-24T11:25:32Z" level=info msg="Creating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T11:25:32Z" level=info msg="Authentication policy default/hello ver:  created."
time="2019-04-24T11:25:32Z" level=info msg="Authentication policy created: {Name: hello, Version: 68419, Uid: abe0ec02-6683-11e9-8048-2edd894abcef}"
```
and will instantly process that Api again and create the Policy again, what will lead to errors:
```
time="2019-04-24T11:25:32Z" level=info msg="Authentication enabled. Trying to create or update authentication policy with: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T11:25:32Z" level=info msg="Authentication policy does not exist. Creating..."
time="2019-04-24T11:25:32Z" level=info msg="Creating authentication policy: {Namespace: default, Name: hello, UID: , Spec: {Targets: [{Name: hello}], PrincipalBinding: USE_ORIGIN, Origins: [{Jwt: {Issuer: https://dex.kyma.local, JwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys}}]}}"
time="2019-04-24T11:25:32Z" level=error msg="[Error 'bc76c4be-fdaa-4c56-9f59-8f540661a409']: policies.authentication.istio.io \"hello\" already exists"
time="2019-04-24T11:25:32Z" level=error msg="[Error 'e929ac09-1504-4eb5-924d-8d5d15cc0ffa']: error while creating authentication policy (error code = 'bc76c4be-fdaa-4c56-9f59-8f540661a409')"
time="2019-04-24T11:25:32Z" level=error msg="Error while updating Authentication for: default/hello ver: 68420. Root cause: error while creating authentication policy (can not create a new one) (error code = 'e929ac09-1504-4eb5-924d-8d5d15cc0ffa')"
```
Like in the first scenario Api-controller is no longer able to delete the policy it created.

**Troubleshooting**
