### ISSUE TITLE
Provide a simple tutorial/example how to add new documentation topics in the content view

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3837]
**Description**

- provide a simple tutorial/example how to add new documentation topics in the content view. Can be based on https://github.com/kyma-project/website/pull/254/files#diff-85ab10c276d11142b62fa3a054b00cc4R68 but also remember to explain the part about metadata, what metadata is supported in UI, link to our guidelines, content strategy and templates
- improve internal instructions and https://github.com/kyma-project/community/blob/master/guidelines/add-new-component-docs.md with new flow of loading docs

**Reasons**

With the introduction of Headless CMS we have to do some cleanup in minio and solve issues that could not be solved with the previous solution.

**Comment by derberg** [comment]
Example scenario:

cat <<EOF | kubectl apply -f -
apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  name: istio-security
  labels:
    cms.kyma-project.io/view-context: docs-ui
    cms.kyma-project.io/order: "1"
    cms.kyma-project.io/group-name: istio
spec:
  displayName: "Security"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/istio/istio.io/archive/master.zip
      filter: content/docs/concepts/security
EOF



cat <<EOF | kubectl apply -f -
apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  labels:
    cms.kyma-project.io/view-context: docs-ui
    cms.kyma-project.io/group-name: prometheus
    cms.kyma-project.io/order: "2"
  name: prometheus-concepts
spec:
  displayName: "Concepts"
  description: "Some docs about Prometheus concepts"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/prometheus/docs/archive/master.zip
      filter: content/docs/concepts
---
apiVersion: cms.kyma-project.io/v1alpha1
kind: ClusterDocsTopic
metadata:
  labels:
    cms.kyma-project.io/view-context: docs-ui
    cms.kyma-project.io/group-name: prometheus
    cms.kyma-project.io/order: "1"
  name: prometheus-guides
spec:
  displayName: "Guides"
  description: "Some docs about Prometheus guides"
  sources:
    - type: markdown
      name: docs
      mode: package
      url: https://github.com/prometheus/docs/archive/master.zip
      filter: content/docs/guides
EOF

# get all docs topics and see if they are all in Ready state
kubectl get clusterdocstopics
## get status of the asset created by one of the docs topics
kubectl get clusterasset -o yaml -l cms.kyma-project.io/docs-topic=istio-security
## notice the status subresource, if Ready, there are links to documentation
```
status:
    assetRef:
      baseUrl: https://minio.kyma.local/cms-public-1b745incmh3u2-1b745inemsqj4/istio-security-docs-markdown-1b75gro4l4sfk
      files:
      - name: istio.io-master/content/docs/concepts/security/architecture.svg
      - name: istio.io-master/content/docs/concepts/security/auth.svg
      - name: istio.io-master/content/docs/concepts/security/authn.svg
      - name: istio.io-master/content/docs/concepts/security/authz.svg
      - metadata:
          aliases:
          - /docs/concepts/network-and-auth/auth.html
          - /docs/concepts/security/authn-policy/
          - /docs/concepts/security/mutual-tls/
          - /docs/concepts/security/rbac/
          - /docs/concepts/security/mutual-tls.html
          description: Describes Istio's authorization and authentication functionality.
          keywords:
          - security
          - authentication
          - authorization
          - rbac
          - access-control
          title: Security
          weight: 30
        name: istio.io-master/content/docs/concepts/security/index.md
      - name: istio.io-master/content/docs/concepts/security/node_agent.svg
      - name: istio.io-master/content/docs/concepts/security/overview.svg
```
