### ISSUE TITLE
Function sizes and env variables in knative compatible CRD 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#3965]
**Description**

Function sizes and env variables in knative compatible CRD does not work at the moment. The following functionality needs to be introduced:
- Adding/Updating env variables for functions inturn for ksvcs
- Adding/Updating function sizes for functions inturn for ksvcs
 ```
apiVersion: runtime.kyma-project.io/v1alpha1
kind: Function
metadata:
  labels:
    foo: bar
  name: sample
  selfLink: /apis/runtime.kyma-project.io/v1alpha1/namespaces/default/functions/sample
spec:
  **env:
  - name: foo
    value: bar**
  function: |
    module.exports = {
        main: function(event, context) {
          return 'HelloWorld'
        }
      }
  functionContentType: plaintext
  runtime: nodejs8
  **size: L**
```
