### ISSUE TITLE
Support for metadata on a source level in HeadlessCMS custom resources

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#3989]
**Description**

- Make sure proper support for it is in DocsTopic and ClusterDocsTopic 
- Do we need explicit support in AssetStore? Makes more sense to have it in Asset CR but we need to talk if `annotations` is better than `spec`
- Proper documentation/tutorial/example
- Support in Kyma Console UI Backend
- Support in the markdown rendering components in Kyma:
  - Agree on contract, what keys can be provided in metadata
  - Document them and support in UI

**Reasons**

Users must be able to specify some additional, custom metadata for a specific source of content. Later, the presentation layer can read this metadata and react properly. For example, it could be:
```
sources:
    - type: markdown
      name: markdown-slack
      mode: single
      url: https://raw.githubusercontent.com/slackapi/slack-api-specs/master/README.md
      metadata: 
        disableRelativeLinks: true
        disableAbsoluteLinks: true
        disableHTML: true
```
