### ISSUE TITLE
Create configuration document for Monitoring

### ISSUE THREAD

**Issue by kazydek** [kyma-project/kyma#4080]
**Description**

Create configuration documents for the **Monitoring** component. 
These documents should list and describe configurable parameters from `values.yaml` files of these charts and their sub-charts:

- [`monitoring`](https://github.com/kyma-project/kyma/tree/master/resources/monitoring)
- [`prometheus-operator`](https://github.com/kyma-project/kyma/tree/master/resources/prometheus-operator)

>**NOTE:** Every chart and sub-chart should be described in a separate document.

Make sure you:
- Create the documents based on the existing [template](https://github.com/kyma-project/community/blob/master/guidelines/templates/resources/configuration.md).
- Rely on the already created configuration documents for the [Asset Store](https://kyma-project.io/docs/master/components/asset-store/#configuration-configuration).

**Reasons**

Have a set of configuration documents that describe values from the Monitoring `values.yaml` files you can override.

**Attachments**
It relates to the epic #4028.

**Comment by a-thaler** [comment]
Alerting notification can be configured by this:
```
global:
  alertTools:
    credentials:
      slack:
        apiurl: ""
        channel: ""
      victorOps:
        routingkey: ""
        apikey: ""
```

Grafana options:
```
users:
  default:
    theme: "light" (out of "dark" or "light")
```

prometheus options:
```
retention: 6h
storageSpec:
  volumeClaimTemplate:
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
```
