### ISSUE TITLE
Application Broker migration deletes main service

### ISSUE THREAD

**Issue by polskikiel** [kyma-project/kyma#4209]
**Description**

If the application broker restart when migration was already done, the migration process will delete the main service for application brokers causing them to fail to respond on every call.

That can happen on the `kyma 1.1` cluster.

**Workaround**

If the service `application-broker` in the namespace `kyma-integration` doesn't exist and your application-brokers have `ErrorFetchingCatalog` status or the ServiceInstance provision call fails with the error: `The provision call failed and will be retried: Error communicating with broker for provisioning`.
You can restore that service manually from the following `yaml` file: 
```
apiVersion: v1
kind: Service
metadata:
  name: application-broker
  namespace: kyma-integration
  annotations:
    auth.istio.io/80: NONE
  labels:
    app: application-broker
    release: application-connector
spec:
  type: NodePort
  ports:
  - name: http-app-broker
    nodePort: 31319
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: application-broker
    release: application-connector
```

Then resync your failed application brokers and they should work again.

**Fix**

The issue was already fixed by this PR: https://github.com/kyma-project/kyma/pull/4193
The fix will be introduced in the `kyma 1.2` release.
