### ISSUE TITLE
Weird formatting in config map dex-config

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#4278]
**Description**

When I try to edit the `dex-config` ConfigMap using `kubectl edit configmaps -n kyma-system dex-config` the data contents are formatted weird:
```
apiVersion: v1
data:
  config.yaml: "issuer: https://dex.vmk100a.cluster.extend.cx.cloud.sap\n# extending
    it to 15days because apparently Istio does not handle ID token validation properly\nexpiry:\n
    \ idTokens: 8h\n  signingKeys: 720h\n  \nstorage:\n  type: kubernetes\n  config:\n
    \   inCluster: true\nlogger:\n  level: \"info\"\n  format: \"text\"\nweb:\n  http:
    0.0.0.0:5556\nconnectors:\n  - type: saml\n    id: sci\n    name: SAP CI\n    config:\n
...
```

**Expected result**

```
apiVersion: v1
data:
  config.yaml: |
    issuer: https://dex.kubecon.kyma.pro
    # extending it to 15days because apparently Istio does not handle ID token validation properly
    expiry:
      idTokens: 8h
      signingKeys: 720h
    storage:
      type: kubernetes
      config:
        inCluster: true
```

**Workaround**
You have to delete trailing spaces from the fragment:
`signingKeys: 720h\n  \nstorage:` (it should be: `signingKeys: 720h\n\nstorage:`). When you save it without those spaces formatting comes back to normal.

The problem is introduced by templating that inserts `expiry` section from values. Maybe the simple solution would be to have separate values for `idTokens` and `signingKeys`.
