### ISSUE TITLE
Cluster users test doesn't work

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#4640]
**Description**

During work on #4438 cluster user test should start failing cause configurations-generator is not available anymore. The test uses variables injected by kubernetes to the test containers (`${CONFIGURATIONS_GENERATOR_SERVICE_HOST}:${CONFIGURATIONS_GENERATOR_SERVICE_PORT_HTTP}`). These variables are not available anymore. The test calls configurations-generator to get kubeconfig and then export it to a KUBECONFIG variable. Output of this call is empty and a file with kubeconfig is not created. Probably kubectl defaults to container kubeconfig and that's the reason why the test passes. 

**Expected result**

Test should fail

**Actual result**

Test passes

**Steps to reproduce**

- install kyma
- execute following configuration to trigger the failing test:
```
echo 'apiVersion: testing.kyma-project.io/v1alpha1
kind: ClusterTestSuite
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: api-ctrl-suite
spec:
  maxRetries: 1
  concurrency: 1
  selectors:
    matchNames:
      - name: cluster-users-test
        namespace: kyma-system' | kc apply -f -
```
