### ISSUE TITLE
Navigation node for Kiali in console

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#4762]
**Description**
Kiali will be enabled by default and a proper link should be available in the admin section of the console. Still it should not be shown if the customer decides to not enable it (kiali.enabled=false flag in istio helm chart)

See also microfronend CR for grafana link: https://github.com/kyma-project/kyma/blob/master/resources/monitoring/charts/grafana/templates/stats-metrics-microfrontend.yaml

```
apiVersion: "ui.kyma-project.io/v1alpha1"
kind: ClusterMicroFrontend
metadata:
 name: kialimicrofrontend
 labels:
  app: kialimicrofrontend
spec:
 displayName: Kiali Hmhmhmh
 version: v1
 category: Diagnostics
 placement: cluster
 viewBaseUrl: https://kiali-hostname.{{ js .Values.global.ingress.domainName }}
 navigationNodes:
  - label: Kiali Hmhmhm
   navigationPath: ''
   viewUrl: ''
   externalLink: https://kiali-hostname.{{ js .Values.global.ingress.domainName }}
   order: 3
```

**Reasons**
Easiness of access to observability tools

Part of https://github.com/kyma-project/kyma/issues/4168
