### ISSUE TITLE
Catalog UI fails in binding when I configure 

### ISSUE THREAD

**Issue by derberg** [kyma-project/kyma#4880]
**Description**

- fix issue in UI so the UI is resilient and doesn't fail if there is an internal error coming from backend
- ask for usageKind and bindable resources in one query, one POST call, now it is separate
- fix console backend service so it doesn't throw not meaningful error and I do not have to go to logs to understand what is actually happening and why something doesn't work
- update documentation with missing part that I mentioned below, some tutorial should be created, Job can be a role model here. I would also check why it is so complicated after all, why those resources cannot by default have access to all default workloads
- maybe Job and other k8s workloads should have UsageKinds configured by default

**Expected result**

I create new UsageKind pointing to some workload and all suddenly in UI I can bind my service instance to it.
<img width="658" alt="Screen Shot 2019-07-11 at 18 57 54" src="https://user-images.githubusercontent.com/6995927/61069998-debd7880-a40d-11e9-920c-7af92c2a8d2e.png">

**Actual result**

After creating UsageKind for Job the UI no longer is able to list bindable resources in the UI
<img width="679" alt="Screen Shot 2019-07-11 at 19 01 05" src="https://user-images.githubusercontent.com/6995927/61070202-62776500-a40e-11e9-9b55-a24f49349f43.png">

**Steps to reproduce**

1. you create an instance of some service, like `Test bundle`
2. you create a usagekind
```
cat <<EOF | kubectl create -f -
apiVersion: servicecatalog.kyma-project.io/v1alpha1
kind: UsageKind
metadata:
   name: jobjob
spec:
   displayName: Job
   resource:
     group: batch
     kind: job
     version: v1
   labelsPath: spec.template.metadata.labels
EOF
```
3. In instance view you go to the instance of the `Test bundle` and try to bind it. The wizard endlessly shows a spinner and is not able to load any resources that user is allowed to bind to
4. You might think it is because there are no Jobs :) nope, create a job if you want and it still fails
```
cat <<EOF | kubectl create -f -
apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
      - name: pi
        image: perl
        command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4
EOF
```
5. Trying to query in the graphiql
```
query {
 usageKinds{
  name
  displayName
} 
  bindableResources(namespace:"default"){
    kind
    resources {
      name
    }
  }
}
```
returns
```
{
  "errors": [
    {
      "message": "internal error [namespace: \"default\"]",
      "path": [
        "bindableResources"
      ]
    }
  ],
  "data": null
}
```
6. the logs of the backend service show that problem is in the RBAC settings
```
E0711 11:42:00.736960       1 bindableresources_resolver.go:33] while listing Bindable Resources for Usage Kind in namespace `default`: while listing target resources: while listing target resources: jobs.batch is forbidden: User "system:serviceaccount:kyma-system:core-console-backend-service" cannot list resource "jobs" in API group "batch" in the namespace "default"
```

**Troubleshooting**

The core of the issue is that there is some hidden knowledge about RBAC here https://github.com/kyma-project/kyma/blob/7cacbc23728d59fb589482afe2059eee5797b61d/components/service-binding-usage-controller/docs/usage-kind.md#rbac-settings

To make it really work you have to additionally do below, not only create UsageKind:
1. `k edit clusterrole service-catalog-addons-service-binding-usage-controller`
2. add this config
```
- apiGroups: 
  - batch
  resources: 
  - jobs
  verbs:
  - get
  - update
```
3. `k edit clusterrole core-console-backend-service`
4. add this config
```
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
```
5. I finally have success
<img width="658" alt="Screen Shot 2019-07-11 at 18 57 54" src="https://user-images.githubusercontent.com/6995927/61069998-debd7880-a40d-11e9-920c-7af92c2a8d2e.png">
