### ISSUE TITLE
Helm-Broker fetching addons fails

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#4998]
**Description**

Helm Broker looks for archived addons using the following pattern:

${addonName}-${addonVersion}.tgz

but should

${entryName}-${addonVersion}.tgz

for given index yaml file:
```
apiVersion: v1
entries:
  entryName:
    - name: addonName
      description: "description"
      version: 0.0.1
```

**Steps to reproduce**

add an URL for addons: https://storage.googleapis.com/faros-int-base-xf-bundles/index.yaml

The pahse of the ClusterAddonConfiguration is Failed but should be Ready

see: provider.go, method LoadCompleteBundle

**AC**:
- entryKey + version pair must be the name of the addon file 
- entryKey + version pair must be unique in given index.yaml
- name is just a displayName
- include all above information in our documnetation in kyma-project.io
