### ISSUE TITLE
Oauth2 API Gateway

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#5084]
**Description**

We have developed oathkeeper maester and now it is possible to define access rules using CRs. Now it's time to plug it in the API Gateway. The goal is to allow users specify access rules when they expose their API and select "secure".

In the first iteration we will create brand new **API Gateway controller** which will have new CRD. New CRD should have AuthN configuration and Authz configuration. 
Controller should work as follows:

## High lvl overview

API Gateway should allow to: 

1. Expose entire service using virtual service
2. Expose and secure entire service with JWT authentication (Virtual Service + istio policy)
3. Expose service with JWT authentication on selected paths (Virtual Service + oathkeeper access rule)
4. Expose service with JWT authentication including scopes on paths (Virtual Service + AR)
5. Expose and secure entire service with JWT authentication including scopes  (Virtual Service + AR)
6. Expose service with JWT authentication but with path whitelisting(excluding) (Virtual Service + istio policy)

7. Expose service and secure with Oatuh2 scopes (client credentials grant supported) - Virtual Service + Access Rule
8. Expose service and secure with Oauth2 scopes on paths - Virtual Service + Access rule 

All scenarios that require Access Rule should have ```authorizer``` set to **allow**.
Controller should set owner reference for all created resources: virtual service, policy, access rule to allow easier garbe collection using k8s.

In order to have service secured on paths (inclusion or exclusion), we can create VirtualService that will route to service **or** oathkeeper depending on the request path.

Example : 

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-proxy
  namespace: kyma-system
spec:
  gateways:
  - kyma-gateway
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - match: 
    - uri:
        exact: /headers
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000   
  - route:
    - destination:
        host: ory-oathkeeper-proxy
        port:
          number: 4455
```

In this example, we are moving requests on endpoint ```/headers``` to httpbin and rest of the traffic to oathkeeper proxy.

## Custom Resource Definition

We have to build this controller from scratch which means we have to define new CRD.
CRD should be simple meaning we should avoid taking 1:1 copy of access rule CRD and old API.
What should CRD describe is a way to expose external service, for example, wikipedia.org.
But external service exposure implementation is out of scope for this iteration/release. 

Task for CRD #5228

### Additional thoughts
IF AuthZ && AuthN -> create access rule with authenticator and authorizer + virtual service with destination pointing do oathkeeper
If AuthN -> Create Istio policy, **do not** create access rule, create virtual service pointing do service defined in CR
If AuthZ -> Create access rule with authorizer, **do not** istio policy, create virtual service with the destination set to oathkeeper

|  AuthZ 	| AuthN   	| VS  	| AR AuthN   	| AR AuthZ  	| Istio Policy  	|
|---	|---	|---	|---	|---	|---	|
|   provided	| provided  	|  create for service 	|   create	| create  	|skip	|
|   provided	|  **not** provided 	|  create for oathkeeper 	|  skip 	| create  	|skip	|
|   **not** provided	|   **not** provided  	|  create for service 	|   skip	|   skip	|skip	|
|   **not** provided 	|  provided 	| create for service  	|  skip 	| skip  	|create	|

**create for service** - Expose service under hostname
**create for oathkeeper** - Expose oathkeeper under given hostname and create AR pointing to given service
**AR AuthZ** - Means Access Rules authorizer
**AR AuthN** - Means Access Rules authenticator

New API Gateway controller should allow excluding path like old one does as well.

## Out of scope for this release
1.  UI and GraphQL queries in `console-backend-service` 
2. UI in the console
3. Exposing external service

**Reasons**
Enable oath2 in Kyma, old api controller will be still in place but in next releases it will be deprecated and then removed.

**Attachments**

**Comment by Demonsthere** [comment]
**Scenario 2:** Expose and secure entire service with JWT authentication (Virtual Service + istio policy)

Basing on the [httpbin example](https://github.com/kyma-incubator/examples/tree/master/ory-hydra/scenarios/client-credentials).

Required manifests:
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-httpbin-proxy
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
    - match:
      - uri:
        regex: /.*
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
---
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: httpbin-httpbin-proxy
  namespace: default
spec:
  origins:
  - jwt:
      issuer: https://dex.kyma.local
      jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
  targets:
  - name: httpbin
```

**Comment by strekm** [comment]
1. Expose entire service using virtual service

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-passthrough
  namespace: kyma-system
spec:
  gateways:
  - kyma-gateway
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF
```

**Comment by Demonsthere** [comment]
**Scenario 3:**
Expose service with JWT authentication on selected paths (Virtual Service + oathkeeper access rule)
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-httpbin-proxy
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - match:
    - uri:
        exact: /cookies
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-path
  namespace: default
spec:
  description: httpbin access with "read" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.kyma.local/cookies
  authenticators:
    - handler: jwt
      config:
        trusted_issuers:
        - https://dex.kyma.local
  authorizer:
    handler: deny
```

**Comment by Demonsthere** [comment]
**Scenario 4:**
Expose service with JWT authentication including scopes on paths (Virtual Service + AR)
```yaml
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-httpbin-proxy
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - match:
    - uri:
        exact: /cookies
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
---
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-path
  namespace: default
spec:
  description: httpbin access with "read" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.kyma.local/cookies
  authenticators:
    - handler: jwt
      config:
        trusted_issuers:
        - https://dex.kyma.local
        required_scope: 
        - write
  authorizer:
    handler: allow
```

**Comment by strekm** [comment]
5. Expose and secure entire service with JWT authentication including scopes (Virtual Service + AR)

```
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-proxy
  namespace: kyma-system
spec:
  gateways:
  - kyma-gateway
  hosts:
  - httpbin-proxy.$DOMAIN
  http:
  - match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: ory-oathkeeper-proxy
        port:
          number: 4455
EOF

---

cat <<EOF | kubectl apply -f -
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-jwt-scopes
  namespace: default
spec:
  description: httpbin access with "write" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.$DOMAIN/<.*>
  authenticators:
    - handler: jwt
      config:
        required_scope: ["write"]
        trusted_issuers:
        - https://dex.kyma.local
  authorizer:
    handler: allow
EOF
```

6. Expose service with JWT authentication but with path whitelisting(excluding) (Virtual Service + istio policy)

```
cat << EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-jwt-exclude
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      allowOrigin:
      - '*'
    match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF
---
cat <<EOF | kubectl apply -f -
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: httpbin-jwt-exclude
  namespace: default
spec:
  origins:
  - jwt:
      issuer: https://dex.kyma.local
      jwksUri: http://dex-service.kyma-system.svc.cluster.local:5556/keys
      trigger_rules:
      - excluded_paths:
      - exact: /headers
  peers:
  - mtls: {}
  principalBinding: USE_ORIGIN
  targets:
  - name: httpbin
EOF
```

7. Expose service and secure with Oatuh2 scopes (client credentials grant supported) - Virtual Service + Access Rule

```
cat <<EOF | kubectl apply -f -
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-image-jpeg
  namespace: default
spec:
  description: httpbin access with "write" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.$DOMAIN/<.*>
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope: ["write"]
  authorizer:
    handler: allow
EOF
---
cat <<EOF | kubectl apply -f -
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-jwt-exclude
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      allowOrigin:
      - '*'
    match:
    - uri:
        regex: /.*
    route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF
```

8. Expose service and secure with Oauth2 scopes on paths - Virtual Service + Access rule

```
cat <<EOF | kubectl apply -f -
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin-httpbin-proxy
  namespace: default
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin-proxy.kyma.local
  http:
  - match:
    - uri:
        exact: /cookies
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
  - match:
    - uri:
        exact: /image/jpeg
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455
  - route:
    - destination:
        host: httpbin.default.svc.cluster.local
        port:
          number: 8000
EOF
---
cat <<EOF | kubectl apply -f -
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-cookies
  namespace: default
spec:
  description: httpbin access with "write" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.$DOMAIN/cookies
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope: ["cookies"]
  authorizer:
    handler: allow
EOF
---
cat <<EOF | kubectl apply -f -
apiVersion: oathkeeper.ory.sh/v1alpha1
kind: Rule
metadata:
  name: httpbin-image-jpeg
  namespace: default
spec:
  description: httpbin access with "write" scope
  upstream:
    url: http://httpbin.default.svc.cluster.local:8000
  match:
    methods: ["GET"]
    url: <http|https>://httpbin-proxy.$DOMAIN/image/jpeg
  authenticators:
    - handler: oauth2_introspection
      config:
        required_scope: ["jpeg"]
  authorizer:
    handler: allow
EOF
```
