### ISSUE TITLE
Application Event Service Ignores maxRequestSize Override

### ISSUE THREAD

**Issue by toddnelson-sap** [kyma-project/kyma#5442]
**Description**

Sending a message of 65Kb size results in a 413 Request Body Too Large error even after setting the maxRequestSize to 108Kb in the Application Event Service Deployment. 

Kyma version 1.3
Kubernetes version v1.12.9-gke.7
Cluster: konduit-dev-4 us-west1-a GCP

**Expected result**

Message successfully delivered.

**Actual result**
Received Error Message

```
=========================
HTTP response:
status=
413 Payload Too Large
headers=
content-length: 82
content-type: application/json
date: Tue, 27 Aug 2019 17:25:25 GMT
server: istio-envoy
x-envoy-upstream-service-time: 7

body=
{"status":413,"type":"request_body_too_large","message":"Request body too large"}

<<<<<<<<<<<<<<<<<<<<<<<<<
```

**Steps to reproduce**

Edit the Application Event Service deployment to increase the maxRequestSize setting:
```kubectl edit deployment commerce-benchmark-event-service -n kyma-integration```

Change the maxRequestSize from the default 65536 to 110000:
```
    spec:
      containers:
      - args:
        - /eventservice
        - --externalAPIPort=8081
        - --eventsTargetURL=http://event-bus-publish.kyma-system.svc.cluster.local:8080/v1/events
        - --maxRequestSize=110000
        - --requestTimeout=10
        - --requestLogging=true
        - --sourceId=commerce-benchmark
        image: eu.gcr.io/kyma-project/event-service:1.3.0
        imagePullPolicy: IfNotPresent
```
Send a message to the Kyma gateway for this application with a message body of 68Kb.

**Troubleshooting**

Looked at:
https://github.com/kyma-project/kyma/blob/master/components/event-service/internal/externalapi/v1/eventshandler.go

Pod startup showed the value as expected (110000):
```
commerce-benchmark-event-service-58b5f56dc6-zbxvx commerce-benchmark-event-service time="2019-08-27T17:24:52Z" level=info msg="Starting event-service"
commerce-benchmark-event-service-58b5f56dc6-zbxvx commerce-benchmark-event-service time="2019-08-27T17:24:52Z" level=info msg="Options: --externalAPIPort=8081 --eventsTargetURL=http://event-bus-publish.kyma-system.svc.cluster.local:8080/v1/events --requestTimeout=10 --sourceId=commerce-benchmark --requestLogging=true --maxRequestSize=110000"```
