### ISSUE TITLE
JWT issuer must be e-mail or url

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#553]
**Description**

Dear Colleagues,

as already discussed with Piotr, when securing an API Kyma (through the underlying Istio) requires the JWT issuer to match URL / E-Mail specification. Anything else will error out with Origin authentication failed. (https://istio.io/docs/reference/config/istio.authentication.v1alpha1/)

To test this you can use https://hub.docker.com/r/andy008/jwt_issuer/ to generate JWT tokes to your liking.

Cheers

Andreas

**Expected result**

all issuers that are configured and matched by the token shall be accepted (also those not matching uri/e-mail format)

**Actual result**

Only issuers matching uri/e-mail format are working

**Steps to reproduce**

Secure API, create issuer andreas, cretae matching jwt, call api

**Troubleshooting**

Create issuer matching uri/e-mail format are working

**Comment by pbochynski** [comment]
Verify if the authentication policy can handle issuer different than URI/email. If not, create istio issue for that.

**Comment by piotrmsc** [comment]
AuthenticationPolicy does not accept issuers in a different format than in URI or email format which is compliant with OIDC.
Little background: JWT specification allows the issuer claim `iss` to be string or URI (https://tools.ietf.org/html/draft-ietf-oauth-json-web-token-32#section-4.1.1). However, OIDC discovery requires the issuer to be URI with https scheme (https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderMetadata) and to match with the issuer claim.
Why does istio support the issuer in the email format as well? Simply because OIDC specification mentions it in the compatibility with Google OIDC (https://openid.net/specs/openid-connect-core-1_0.html#GoogleIss).

**Comment by akrausesap** [comment]
Can we then add a validation regex on the API and IDP Preset? Then we make it more simple.

**Comment by piotrmsc** [comment]
Yes, ofc. Issue created https://github.com/kyma-project/kyma/issues/1156

**Comment by piotrmsc** [comment]
@akrausesap I was able to create an api with issuer "issuer" and authentication works.
My sample api 
```
---
apiVersion: gateway.kyma.cx/v1alpha2
kind: Api
metadata:  
  labels:
    example: http-db-service
  name: http-db-service
spec:
  authentication:
  - type: JWT
    jwt:
      issuer: "issuer"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.0/security/tools/jwt/samples/jwks.json"
  hostname: http-db-service.kyma.local
  service:
    name: http-db-service
    port: 8017
```

I have issued a token using script mentioned in https://istio.io/help/ops/security/end-user-auth/
