### ISSUE TITLE
Remodel api-gateway CR to support many authn

### ISSUE THREAD

**Issue by strekm** [kyma-project/kyma#5583]
After brainstorming and consulting with Compass team there's a need to support more than one authenticator. Also it is a good time to refactor it too.

```
apiVersion: gateway.kyma-project.io/v2alpha1
kind: Gate
metadata:
  name: oauth
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    host: httpbin.kyma.local
    name: httpbin
    port: 8000
  authn:
    - name: OAUTH
      config:
        bar: foo
    - name: JWT
      config:
        foo: bar
  paths:
  - path: /headers
    scopes: [read]
    methods: [GET]
  - path: /images
    scopes: [write]
    methods: [POST]
  mutators: []
```
