### ISSUE TITLE
Istio RBAC rules does not work for brokers as expected

### ISSUE THREAD

**Issue by piotrmiskiewicz** [kyma-project/kyma#5694]
**Description**
The istio RBAC rules sometimes does not block a call to the broker, which makes the test TestBrokerHasIstioRbacAuthorizationRules failing.

**Expected result**

Only Service catalog controller manager is able to call Helm-Broker.

**Actual result**

Sometimes a testing Pod is able to call the Helm-Broker

**Steps to reproduce**

Edit core testdefinition, enable istio rbac tests by setting env BROKER_ISTIO_RBAC_ENABLED to "true":
```
kubectl edit testdefinition core -n kyma-system
```
Run the test:
```
cat <<EOF | kubectl apply -f -
apiVersion: testing.kyma-project.io/v1alpha1
kind: ClusterTestSuite
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: acceptance-test
spec:
  maxRetries: 1
  concurrency: 1
  selectors:
      matchNames:
      - name: core
        namespace: kyma-system
EOF
```

3. You can watch logs:
```
kubectl logs -f -n kyma-system oct-tp-acceptance-test-core-0 tests
```
4. If you want to run again, first remove cluster test suite:
```
kubectl delete clustertestsuite acceptance-test
```
5. If you want to see istio config dump, you can edit the testdefinition resource and change `http` to `https` protocol for one of the broker.

Please make sure the [PR](https://github.com/kyma-project/kyma/pull/5668) is merged. If not, provide RBAC rule for exec operation and add POD_NAME env, see changes (test.yaml, rbac.yaml, values.yaml) https://github.com/kyma-project/kyma/pull/5668/files#diff-d8ba24b2f2cf8d7a61782ba8fd6f0b92

**Troubleshooting**

The test is not failing always, you need to try few times.
