### ISSUE TITLE
POC : GitOps support for serverless

### ISSUE THREAD

**Issue by devguyio** [kyma-project/kyma#5752]
**Description**

Propose a solution for GitOps support for serverless.

**Requirements**
* Function code could be versioned at GIT (possibility to provide a source code should be preserved)
* Function version can be fixed to specific  repo URL, branch and commit hash (optional)
* In case commit hash is not fixed, function is rebuild and restarted on every commit to the branch
* support for private repositories  - include a mechanism to reference a secret that is necessary to access private repos
* gitops configuration in Function CR only - exclude UI for the sake of MVP 
* support multiple functions in one repo

**Comment by Abd4llA** [comment]
@akrausesap do you have any ideas in mind?

**Comment by montaro** [comment]
@Abd4llA Do you have input from the customers and the stakeholders in terms of features to add here, please?

**Comment by michal-hudy** [comment]
I think we should create GitOps not only for Functions, but for Kyma at all. Functions should support git repositories as the source, but this is separate functionality.

Description edited

**Comment by michal-hudy** [comment]
> In case commit hash is not fixed, function is rebuild and restarted on every commit to the branch

Do we plan to monitor a repository? It will be pull or push? If pull then we are independent from the platform (GitHub, GitLab, GCP Source, etc.) but if it will be a push then we will need to have support for webhooks. Yes, we can use some ready solutions for that, but it needs to be investigated.

**Comment by michal-hudy** [comment]
For POC scope private repositories are also supported, or only public?

**Comment by michal-hudy** [comment]
Another thing 😄 Does the repository will contain `Dockerfile` and `Function` CR?

**Comment by kwiatekus** [comment]
> Do we plan to monitor a repository? It will be pull or push? If pull then we are independent from the platform (GitHub, GitLab, GCP Source, etc.) but if it will be a push then we will need to have support for webhooks. Yes, we can use some ready solutions for that, but it needs to be investigated.

I'd start with easiest for the sake of the POC - pull.

**Comment by kwiatekus** [comment]
> For POC scope private repositories are also supported, or only public? What about authentication?

Excelent point. I will add it to the the requirements

**Comment by kwiatekus** [comment]
> Another thing 😄 Does the repository will contain `Dockerfile` and `Function` CR?
I imagine the code + dockerfile.
In the POC I'd leave the Function CR out

**Comment by kwiatekus** [comment]
Investigate how addons are fetched form git. 
Maybe we could reuse the same mechanisms for git communication

**Comment by michal-hudy** [comment]
Ok, here is how I see it:

As for now, we have 3 _phases_ when Function CR is processed:
   - Configuration - creates a `ConfigMap` with source code and dependencies
   - Building - creates a `Job` that builds a Docker image. `ConfigMap` with source code and dependencies is attached to pod as a volume
   - Deploying - creates `Deployment`, `HPA` and `Service`

The MVP for GitOps has an impact on `Configuration` and `Building` phases as they are responsible for creating a Docker image - MVP is only for keeping source code, dependencies, and Dockerfile in repositories, GitOps for Function CR will be a part of another more generic GitOps for Kyma.

The first thing that needs to have a support of Git repositories is Function CR. It needs to be extended (I think it should be version `v1alpha2`) by fields that are referencing repository. For the purpose of this document let's extend it like that (just an example):

   ```yaml
   spec:
     repository:
       url: https://github.com/kyma-project/kyma.git # Also other formats, like ssh
       baseDir: function1/                           # Base directory for Function code
       dockerfile: Dockerfile                        # Relative path to Dockerfile in repository
       baseRef: master                               # Branch
       baseSHA: abcde1234567890                      # Revision
       repoPullSecret: kyma-github-secret            # Secret with credentials to the repository if needed
      ...
    status:
      version: abcde12                               # Short SHA of latest processed revision
      ...
   ```

Ok, as Function CR is extended with all needed information, now we can focus on how it is processed.

The `configuration` phase can be skipped, as `ConfigMap` with source code is not needed.

If the `baseSHA` is not set, then the controller fetches the latest revision for a branch. Such revision is passed to `Job` together with other repository related information. Also, `baseSHA` if stored in `status.version` for information about the latest processed revision. With every reconcile of Function CR controller is checking if there is a newer revision in the referenced branch (if `baseSHA` not set, or other repository related information are changed) than processed in the job and is creating a new `Job` if needed.

Regarding the `Job`. When it is working with git repositories it will require additional sidecar. Such sidecar will pull a proper referenced revision from the repository. When the container responsible for building an image is executed it will use a `Dockerfile` from a repository, not this one defined in a runtime. Also, it needs to be in a proper context that also is passed to the container (proper directory inside the repository)

**Comment by michal-hudy** [comment]
In the future, the user should also be able to define a resources needed for building a Docker image. Also, logs from a git init container should be displayed in the UI 😄

**Comment by m00g3n** [comment]
Just a couple of notes after brain-storming with @pPrecel:

- the overall architecture

![image](https://user-images.githubusercontent.com/45931826/85543736-9f863880-b61a-11ea-9748-73bfce7e3e5d.png)

- a new `Repository` CRD (draft)

```yaml
apiVersion: kyma-project.io/v1alpha1
kind: GitRepository
metadata:
 name: kyma-repo
spec:
  url: https://github.com/kyma-project/kyma
  branch: sample-refactor
  baseDir: components/function-controller/config/samples
  dockerfile: sample.dockerfile
  commit: cc9f1af36206427622862bb62bc3c715ca4592eb
  repoPullSecret: kyma-github-secret
``` 

- new `Function` CRD version (draft)
```yaml
apiVersion: serverless.kyma-project.io/v1alpha2
kind: Function
metadata:
 name: sample-with-dep
 labels:
   foo: bar
spec:
  type: git
  source: kyma-repo
  baseDir: components/function-controller/config/samples
  dockerfile: components/function-controller/deployment/sample.dockerfile
  commit: cc9f1af36206427622862bb62bc3c715ca4592eb
```

**Comment by michal-hudy** [comment]
@m00g3n  I think that `repository` should contain `commit`, `dockerfile` and `baseDir` as they are strictly related to the `function`. Repository CR should only contain the necessary information for accessing the repository (too many repository words :P). So function should reference repository as a source, and in function, spec should be defined `dockerfile` and `baseDir`. Take in mind that the repository may contain many functions and many `dockerfiles`.

**Comment by m00g3n** [comment]
Sorry it's a `copy/paste` error that I've didn't notice (in original it was `strikethrough`)

**Comment by johnkbarrow** [comment]
Really like this concept. I see it could definitely be used with microservices as well as Functions - at the moment, we don't make it easy to deploy microservices - there is little in the UI to help, and the developer must supply their own Deployment, Service and APIRule yaml. A Microservices CRD and controller could automate all of this, using the Repository CRD.

**Comment by aerfio** [comment]
As for the mechanism that is responsible for checking changes in observed repo -> have a look at `git ls-remote` and it's equivalent in `gi-git` library 
![image](https://user-images.githubusercontent.com/17271979/86445052-04741980-bd12-11ea-846e-42a47d03d22b.png)

**Comment by pPrecel** [comment]
### Results from me and @m00g3n : 
The proposed solution from us is included and divided into two PRs.
[The first one](https://github.com/kyma-project/kyma/pull/8924) contains all changes concerning the `gitops` logic based on the library `go-git` (checking the latest commit from a branch, cloning a repository from git + init container that can clone and inject repository to the building job).
[The second one](https://github.com/kyma-project/kyma/pull/8929) contains the new (upgraded) Function CRD, upgrades the `serverless-manager-controller` to handle new fields in Function CR, building function image with the source from git, and creating deployment with this image.

### How it works now?
1. Run the `kyma` on the gke cluster from [the second PR](https://github.com/kyma-project/kyma/pull/8929)
2. Apply the `Function CR` via the `kubectl`. Example below:
```
apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: newone
spec:
  source: "https://github.com/pPrecel/public-gitops"
  baseDir: "/"
  type: git
  branch: "master"
  dockerfile: "deploy/Dockerfile"
```
> NOTE: now gitops Function should has `type: git` to inform function-controller that function should be fetched and built from a git repository. the `baseDir` is not used now but in the future, it can be used as information where the `function-controller` should search for changes or it can be used as a path for the `build job` to locate sources of a handler (simplifying, the `build job` now works like `docker build -f $dockerfile .` command but it can work something like `docker build -f $dockerfile $baseDir`), but this is just an idea how it can works. The last parameter is the `branch` name (function-controller should fetch the last commit from the given branch and search for changes) or the `commit` hash (function-controller should fetch repository from the given commit hash)

3. Apply secret with the credentials to the repository. Example:
```
apiVersion: v1
data:
  username: ""
  password: ""
kind: Secret
metadata:
  name: newone
type: Opaque
```

> NOTE: now every function` with the `type: git` in the spec` should has the `secret` (in the same namespace and with the same name as the `Function CD`).

Now every change pushed to the repository on the given branch or every change of the `Function CR` triggers the re-build of the function from the new commit hash.

### To improve:
This is only a POC so here are a lot of things that we can improve. For example:
- code refactor
- update all not working  and add more integration [tests](http://peter.bourgon.org/go-in-production/#testing-and-validation)
- update the `serverless-webhook`
- add new CRD (`GitRepository` proposed [here](https://github.com/kyma-project/kyma/issues/5752#issuecomment-648755268))
- the Secret should not be required for public repositories
- think how the `baseDir` should work
- think about excluding the `branch` from the `status`
- check the whole scenario on all platforms (gke, azure, gardener), because on the `gardener`, deployments couldn't pull the function image from the docker-registry. Given error:
```
Failed to pull image "registry.mw-0004.kyma-dev.shoot.canary.k8s-hana.ondemand.com/testme-newone:75366d282fe529a292140a7ac2ed5f6248dca3e7f650c90190725edcebc8ffa5": rpc error: code = Unknown desc = Error response from daemon: Get "https://registry.mw-0004.kyma-dev.shoot.canary.k8s-hana.ondemand.com/v2/": dial tcp: lookup registry.mw-0004.kyma-dev.shoot.canary.k8s-hana.ondemand.com: no such host
```
