### ISSUE TITLE
Updated Lambda UI to create a Trigger for Lambdas

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6151]
**Description**

In order to start introducing the new Knative eventing mesh, Lambda UI needs to create a [knative `Trigger` ](https://knative.dev/docs/eventing/broker-trigger/#trigger) against the default `Broker` alongside the Kyma `Subscription` it currently creates. 

![knative_brokers_co_exist_arch](https://user-images.githubusercontent.com/1930204/68677580-a31df100-055c-11ea-9b05-9a32c7830e3e.png)

**Details**

- When Lambdas are created, it is expected that there's a [default broker](https://knative.dev/docs/eventing/broker-trigger/#broker) running in that namespace that gets created at the same time the `EventActivation` object gets created. This behavior is added in #6148 
- The Lambda UI needs to create a [knative `Trigger` ](https://knative.dev/docs/eventing/broker-trigger/#trigger) object with the proper filter that looks as follows
 - Delete trigger if event subscription is deleted

```yaml
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: my-lambda-function # 1. same as lambda name
spec:
  broker: default # this should always stay the same
  filter:
    attributes:
      type: order.deliverysent # 2. the event type (check the screenshot below)
      source: commerce # 3. the external solution name (check the screenshot below)
      eventtypeversion: v1 # 4. the event type version (check the screenshot below)
  subscriber:
    uri: http://my-lambda-function.my-namespace:8080/ # 5. the uri of the function
```

The Lambda UI needs to change the fields 1, 2, 3, 4 and 5 as in the comment. The three fields in the filter `type`, `source` and `eventtypeversion` correspond to the following attributes of the event

![Screen Shot 2019-11-12 at 15 28 23](https://user-images.githubusercontent.com/1930204/68680339-cac38800-0561-11ea-9e7d-d3916dda952d.png)

**Note**
1. In order to test the changes before #6148 is merged, just manually add the label `knative-eventing-injection=enabled` to the namespace so that the default broker gets created and then test your changes.
2. We will work on a feature branch, so merge the changes against the feature branch.

**AC**

1. The Lambda UI behaves as described above.
1. The old behavior is still preserved. 
1. The new behavior is tested .
1. Documentations are updated.
