### ISSUE TITLE
Support kubernetes secrets for lambdas

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#6392]
**Description**
To have better security, all keys/passwords/confidential data should be stored as k8s secrets in lambdas. Currently, only config maps are supported.

**Comment by michal-hudy** [comment]
As far as I know, ConfigMaps are also not supported. We should rather create a "generic" injector that will handle SBU, Secrets, and ConfigMaps. @PK85 I think your help is needed 😄

**Comment by kwiatekus** [comment]
First a concept is needed for an universal binding mechanism that is decoupled from service catalog
https://github.com/kyma-project/kyma/issues/9402

**Comment by kwiatekus** [comment]
This is already possible to inject ENVs from configmaps and secrets into your function.
Config map example documented here
https://kyma-project.io/docs/master/components/serverless/#configuration-environment-variables-define-environment-variables-in-a-config-map

Analogically you can reference value from secret:
```

apiVersion: serverless.kyma-project.io/v1alpha1
kind: Function
metadata:
  name: hello
  namespace: default
spec:
  type: git
  runtime: nodejs12
  source:my-repo
  reference: master
  baseDir: /
  env:
    - name: MY_ENV
      valueFrom:
        secretKeyRef:
          name: hello-secret
          key: text

```
