### ISSUE TITLE
PoC of running a knative broker with Kafka Channel

### ISSUE THREAD

**Issue by Abd4llA** [kyma-project/kyma#6659]
**Description**

To get an understanding and feeling of how the [Kafka Channel](https://github.com/kyma-incubator/knative-kafka/) works, we need to run a PoC of running a Knative Broker using that Kafka Channel. Some desired findings are:

1. How do we connect and configure Azure Event Hubs?
1. How do the traces and metrics look like compared to NATSS Channel?
1. Any obvious missing features or other issues that would block the Knative Eventing mesh feature?

**AC**

1. PoC is done with the results documented in this issue.

**Comment by Abd4llA** [comment]
Attaching the script to be used
[provision-eventhub-namespace.sh.zip](https://github.com/kyma-project/kyma/files/4018725/provision-eventhub-namespace.sh.zip)

**Comment by travis-minke-sap** [comment]
I've made some enhancements to the script mentioned above which should remove the need to manually change the two instances of "konduit-dev" resource group.  It's not been through QA yet but I tested it once and it seems good.  Please use this version instead...

[provision-eventhub-namespace.sh.gz](https://github.com/kyma-project/kyma/files/4032809/provision-eventhub-namespace.sh.gz)

...also feel free to holler if you have any knative-kafka questions ; )

**Comment by anishj0shi** [comment]
# Knative Eventing POC with Azure Event Hub

### Prerequisites

* Kubernetes (*kubectl*) CLI
* Azure (*az*) CLI
* jq CLI
* base64 CLI 
* Knative 0.10
* [Prometheus Operator](https://github.com/coreos/prometheus-operator)
* Helm 2.16.x

### Install Prometheus Operator
Knative Clusters are not enhaced with the prometheus operator, so you'd need this operator up and running in your cluster. Simply run the following commands to install prometheus operator:
```
go get https://github.com/coreos/prometheus-operator
cd $GOPATH/src/github.com/coreos/prometheus-operator
kubectl apply -f bundle.yaml
```

### Install kafka Channel Controller
Clone the kafka channel repository from https://github.com/kyma-incubator/knative-kafka 

Edit file **resources/knative-kafka/values.yaml** and change the property value for key `environment.kafkaProvider` to `azure` and `global.runtime.namespace` to `knative-eventing`

Initialise tiller by performing.
```
helm init
```

Install kafka Chart 
```
helm install --tls -n knative-kafka ./knative-kafka
```

### Provision Azure Event Hub Namespace
(Script provided by Konduit)
This script creates an Azure Event hub Namespace in a `ResourceGroup` specified in `initializeConfiguration`.
Once this script is executed, a Secret is injected to the runtime namespace which is used by the kafka channel controller to create azure event-hub kafka channels.

```shell
#!/bin/bash
# Exit Script Upon Any Non Zero Return
set -e

# Uncomment To Debug (Verbose!)
# set -x

# Current Script Name
SCRIPT_NAME=$(basename "$0")


#
# Global Variables
#
KUBERNETES_CONTEXT=""
AZURE_SUBSCRIPTION=""
EVENTHUB_NAMESPACE_RESOURCE_GROUP=""
EVENTHUB_NAMESPACE_NAME=""
EVENTHUB_NAMESPACE_MIN_THROUGHPUT_UNITS=2 # Must be greater than zero and less than maximum value!
EVENTHUB_NAMESPACE_MAX_THROUGHPUT_UNITS=4 # Must be greater than minimum value and less than 20!
EVENTHUB_NAMESPACE_LOCATION=""
EVENTHUB_NAMESPACE_SHARED_ACCESS_KEY="RootManageSharedAccessKey"
CLUSTER_EVENTHUB_NAMESPACE_INDEX=""
CLUSTER_EVENTHUB_NAMESPACE_COUNT=""
SUBSCRIPTION_EVENTHUB_NAMESPACE_COUNT=""

K8S_SECRET_NAME=""
K8S_SECRET_NAMESPACE="knative-eventing"
K8S_SECRET_USERNAME="\$ConnectionString"
K8S_SECRET_BROKER=""
K8S_SECRET_PASSWORD=""

KAFKA_BROKER_PORT="9093"
KAFKA_CHANNEL_CONTROLLER_NAME=""
KAFKA_CHANNEL_CONTROLLER_NAMESPACE="knative-eventing"
KAFKA_CHANNEL_CONTROLLER_APP_LABEL="knative-kafka-channel-controller"


#
# Script Boilerplate
#

# Print Usage Information Message
printUsage() {
  echo ""
  echo "USAGE:"
  echo ""
  echo "  ${SCRIPT_NAME} [ -h ]"
  echo ""
  echo "DESCRIPTION:"
  echo ""
  echo "  Creates a new Azure EventHubs Namespace and binds it to the current Kubernets Kyma/Konduit cluster."
  echo ""
  echo "OPTIONS:"
  echo ""
  echo "  -h  Print this help information."
  echo ""
  echo "EXAMPLES:"
  echo ""
  echo "    # Provision A New EventHubs Namespace For The Current K8S Cluster"
  echo "    ${SCRIPT_NAME}"
  echo ""
}


#
# Utility Functions To Make The Actual Cmd Line Calls
#

# Get K8S Current Context
cmdCurrentKubernetesContext() {
  kubectl config current-context | cut -c 1-15
}


# Get The Azure K8S Cluster's Location
# NOT USED IN THIS POC
cmdAzureKubernetesClusterLocation() {
  az aks show -o json --name ${KUBERNETES_CONTEXT} --resource-group konduit-dev | jq -r ".location"
}


# Get The Azure K8S Cluster's ResourceGroup
# NOT USED IN THIS POC
cmdAzureKubernetesClusterResourceGroup() {
  az aks show -o json --name ${KUBERNETES_CONTEXT} --resource-group konduit-dev | jq -r ".resourceGroup"
}


# Get Azure Subscription Name
cmdAzureAccountName() {
  az account show -o json | jq -r ".name"
}


# Count The Number Of EventHub Namespaces In The Azure Subscription
cmdSubscriptionEventHubNamespaceCount() {
  az eventhubs namespace list -o json | \
    jq -r ".[].id" | \
    wc -l | \
    sed -e 's/^[ \t]*//'
}


# Count The Number Of EventHub Namespaces In The Azure Subscription Associated With The Current Cluster
cmdClusterEventHubNamespaceCount() {
  az eventhubs namespace list -o json | jq -r ".[].name" | \
    grep -c "${KUBERNETES_CONTEXT}-" | \
    { grep -v grep || true; }
}


# List All Namespaces In The Resource Group For The K8S Context, Parse Out Name Suffix & Select Largest Numeric Value
cmdLargestNamespaceIndex() {
  az eventhubs namespace list -o json --resource-group ${EVENTHUB_NAMESPACE_RESOURCE_GROUP} | \
    jq -r ".[].name" | \
    grep "${KUBERNETES_CONTEXT}-" | \
    { grep -v grep || true; } | \
    sed -e "s/${KUBERNETES_CONTEXT}-//" | \
    sort -rn | \
    head -1
}


# Get The Name Of The Kafka Channel Controller Pod In The K8S Cluster
cmdKafkaChannelControllerPodName() {
  kubectl get pods -n ${KAFKA_CHANNEL_CONTROLLER_NAMESPACE} -l app=${KAFKA_CHANNEL_CONTROLLER_APP_LABEL} --no-headers=true --template '{{range .items}}{{.metadata.name}}{{"\n"}}{{end}}'
}


# Create The Azure EventHubs Namespace Based On Global Configuration
cmdCreateEventHubNamespace() {
  az eventhubs namespace create \
    --name "${EVENTHUB_NAMESPACE_NAME}" \
    --resource-group "${EVENTHUB_NAMESPACE_RESOURCE_GROUP}" \
    --location "${EVENTHUB_NAMESPACE_LOCATION}" \
    --sku standard \
    --enable-kafka true \
    --enable-auto-inflate true \
    --capacity "${EVENTHUB_NAMESPACE_MIN_THROUGHPUT_UNITS}" \
    --maximum-throughput-units "${EVENTHUB_NAMESPACE_MAX_THROUGHPUT_UNITS}" \
    --output none
}


# Get The Azure EventHub Namespace Authorization Keys' PrimaryConnectionString
cmdNamespacePrimaryConnectionString() {
  az eventhubs namespace authorization-rule keys list \
    -o json \
    --resource-group "${EVENTHUB_NAMESPACE_RESOURCE_GROUP}" \
    --namespace-name "${EVENTHUB_NAMESPACE_NAME}" \
    --name "${EVENTHUB_NAMESPACE_SHARED_ACCESS_KEY}" | \
    jq -r ".primaryConnectionString"
}


# Create The EventHub Namespace Secret In The K8S Cluster
cmdCreateventHubNamespaceSecret() {

  local encodedBroker=$(echo -n "${K8S_SECRET_BROKER}" | base64)
  local encodedNamespace=$(echo -n "${EVENTHUB_NAMESPACE_NAME}" | base64)
  local encodedPassword=$(echo -n "${K8S_SECRET_PASSWORD}" | base64)
  local encodedUsername=$(echo -n "${K8S_SECRET_USERNAME}" | base64)

cat <<EOF | kubectl create -f - > /dev/null 2>&1
apiVersion: v1
data:
  brokers: ${encodedBroker}
  namespace: ${encodedNamespace}
  password: ${encodedPassword}
  username: ${encodedUsername}
kind: Secret
metadata:
  name: ${K8S_SECRET_NAME}
  namespace: ${K8S_SECRET_NAMESPACE}
  labels:
    knativekafka.kyma-project.io/kafka-secret: "true"
type: Opaque
EOF
}


# Delete The Kafka Channel Controller Pod In The K8S Cluster
cmdDeleteKafkaChannelControllerPod() {
  kubectl delete pod -n ${KAFKA_CHANNEL_CONTROLLER_NAMESPACE} ${KAFKA_CHANNEL_CONTROLLER_NAME}
}


# Check That The Kafka Channel Controller Pod Is Running
cmdCheckKafkaChannelControllerPodRunningState() {
  kubectl get pods -n ${KAFKA_CHANNEL_CONTROLLER_NAMESPACE} -l app=${KAFKA_CHANNEL_CONTROLLER_APP_LABEL} --no-headers=true | grep -c "2/2"
}


#
# Main Algorithm Step Implementations
#

# Verify The Expected Dependencies Are Present On $PATH
verifyPathDependencies() {

  if ! [[ -x "$(command -v az)" ]]; then
    echo ""
    echo "Executable 'az' Not Found On \$PATH - Exiting"
    echo ""
    exit 1
  fi

  if ! [[ -x "$(command -v kubectl)" ]]; then
    echo ""
    echo "Executable 'kubectl' Not Found On \$PATH - Exiting"
    echo ""
    exit 1
  fi

  if ! [[ -x "$(command -v jq)" ]]; then
    echo ""
    echo "Executable 'jq' Not Found On \$PATH - Exiting"
    echo ""
    exit 1
  fi

  if ! [[ -x "$(command -v base64)" ]]; then
    echo ""
    echo "Executable 'base64' Not Found On \$PATH - Exiting"
    echo ""
    exit 1
  fi

}


# Initialize The Current User's Azure Subscription & Kubernetes Context
initializeConfiguration() {

  echo ""
  echo "Loading Azure Subscription & Kubernetes Cluster Configuration..."

  KUBERNETES_CONTEXT=$(cmdCurrentKubernetesContext)

  AZURE_SUBSCRIPTION=$(cmdAzureAccountName)
  EVENTHUB_NAMESPACE_LOCATION="westeurope"
  EVENTHUB_NAMESPACE_RESOURCE_GROUP="DefaultResourceGroup-WEU"
  SUBSCRIPTION_EVENTHUB_NAMESPACE_COUNT=$(cmdSubscriptionEventHubNamespaceCount)
  CLUSTER_EVENTHUB_NAMESPACE_COUNT=$(cmdClusterEventHubNamespaceCount)
  CLUSTER_EVENTHUB_NAMESPACE_INDEX=$(cmdLargestNamespaceIndex)
  EVENTHUB_NAMESPACE_NAME="aj-test-$((CLUSTER_EVENTHUB_NAMESPACE_INDEX+1))"

  K8S_SECRET_NAME=${EVENTHUB_NAMESPACE_NAME}

  KAFKA_CHANNEL_CONTROLLER_NAME=$(cmdKafkaChannelControllerPodName)
}


# Validate The Previously Initalized Configuration
validateConfiguration() {

  # Validate The Namespaces Aren't ALL Already In Use
  if [[ ${SUBSCRIPTION_EVENTHUB_NAMESPACE_COUNT} -gt 99 ]]; then
    echo ""
    echo "All of the Azure Subscription's 100 Namespaces have been allocated - Exiting!"
    echo ""
    exit 1
  fi

}


# Confirm The User's Desire To Provision A New EventHub Namespace For Their Current Azure/K8S Context
confirmConfiguration() {

  # Log The Configuration Summary
  echo ""
  echo "The following configuration will be used to provision the new EventHub Namespace - review for correctness before continuing!"
  echo ""
  echo "                              Azure Subscription    :  ${AZURE_SUBSCRIPTION}"
  echo "                              Azure Resource Group  :  ${EVENTHUB_NAMESPACE_RESOURCE_GROUP}"
  echo ""
  echo "           Total EventHub Namespace Count           :  ${SUBSCRIPTION_EVENTHUB_NAMESPACE_COUNT}"
  echo "         Cluster EventHub Namespace Count           :  ${CLUSTER_EVENTHUB_NAMESPACE_COUNT}"
  echo "             New EventHub Namespace Name            :  ${EVENTHUB_NAMESPACE_NAME}"
  echo "             New EventHub Namespace Location        :  ${EVENTHUB_NAMESPACE_LOCATION}"
  echo "             New EventHub Namespace Throughput Min  :  ${EVENTHUB_NAMESPACE_MIN_THROUGHPUT_UNITS}"
  echo "             New EventHub Namespace Throughput Max  :  ${EVENTHUB_NAMESPACE_MAX_THROUGHPUT_UNITS}"
  echo ""
  echo "                       Kubernetes Context           :  ${KUBERNETES_CONTEXT}"
  echo "                       Kubernetes Secret Name       :  ${EVENTHUB_NAMESPACE_NAME}"
  echo "                       Kubernetes Secret Namespace  :  ${K8S_SECRET_NAMESPACE}"
  echo ""
  echo "            Kafka Channel Controller Pod Name       :  ${KAFKA_CHANNEL_CONTROLLER_NAME}"
  echo "            Kafka Channel Controller Pod Namespace  :  ${KAFKA_CHANNEL_CONTROLLER_NAMESPACE}"
  echo ""

  # Prompt User To Be Sure They Want To Continue
  # read -rp "Type 'yes' to continue: " CONTINUE
  # if [[ ${CONTINUE} != "yes" ]]; then
  #   echo ""
  #   echo "Exiting - No changes have been made to either the Azure Subscription or the Kubernetes Cluster."
  #   echo ""
  #   exit 1
  # fi

}


# Create The EventHub Namespace Based On User's Current Azure / K8S Context
createEventHubNamespace() {

  # Execute The Azure EventHubs Namespace Creation Command & Handle The Results
  echo ""
  echo "Creating New EventHubs Namespace... (takes several minutes - be patient :)"
  echo ""
  if [[ $(cmdCreateEventHubNamespace) -eq 0 ]]; then
    sleep 2
    echo "Successfully Created New EventHub Namespace!"
  else
    echo "Failed To Create New EventHub Namespace - Exiting!"
    echo ""
    exit 1
  fi
}


# Load The EventHub Namespace's Authorization Key Information Into Global Variables
loadAuthorizationKey() {

   # Get The New EventHub Namespace's PrimaryConnectionString
  echo ""
  echo "Loading The New EventHub Namespace's Authorization Key..."
  local primaryConnectionString=""
  primaryConnectionString=$(cmdNamespacePrimaryConnectionString)

  # Populate The Kubernetes Secret Broker / Password Values
  K8S_SECRET_BROKER=$(echo "${primaryConnectionString}" | sed -e "s/^Endpoint=.*sb:\/\/\(.*\)\/;.*$/\1:${KAFKA_BROKER_PORT}/")
  K8S_SECRET_PASSWORD=${primaryConnectionString}
}


# Create The EventHub Namespace Secret In The K8s Cluster (Contains The EventHub Namespace Auth Keys)
createK8SSecret() {

  echo ""
  echo "Creating Kubernetes Secret For The New EventHub Namespace..."
  echo ""
  if [[ $(cmdCreateventHubNamespaceSecret) -eq 0 ]]; then
    sleep 2
    echo "Successfully Created Kubernetes Secret For EventHub Namespace!"
  else
    echo "Failed To Create Kubernetes Secret For EventHub Namespace - Exiting!"
    echo ""
    exit 1
  fi
}


# Delete (Restart) The Kafka Channel Controller To Force A Reload Of The EventHub Namespace Cache
deleteControllerPod() {

  echo ""
  echo "Deleting (Restarting) The Kafka Channel Controller Pod To Force Load Of New EventHub Namespace Configuration..."
  echo ""
  local result=$(cmdDeleteKafkaChannelControllerPod)

  # shellcheck disable=SC2181
  if [[ $? -eq 0 ]]; then
    sleep 5 # Pause Briefly To Let Deletion Happen (Will be waiting for startup anyway so no hurry at this point.)
    echo "Successfully Deleted (Restarted) Kafka Channel Controller Pod!"
  else
    echo "Failed To Delete (Restart) Kafka Channel Controller Pod - Exiting!"
    echo ""
    exit 1
  fi
}

# Wait For The Kafka Channel Controller Pod To Start
waitForControllerPod() {

  echo ""
  echo "Waiting For The Kafka Channel Controller Pod To Start..."
  echo ""
  while [[ $(cmdCheckKafkaChannelControllerPodRunningState) -eq 0 ]]
  do
    sleep 5
  done
  echo "Successfully Verified Kafka Channel Controller Pod Is Running!"
  echo ""
}


#
# Main Script Execution
#

# Parse Any Command Line Options
while getopts ":h" opt; do
  case ${opt} in
    h)
      printUsage
      exit 0
      ;;
    \?)
      echo "ERROR: Invalid option: -$OPTARG" >&2
      printUsage >&2
      exit 1
      ;;
    :)
      echo "ERROR: Option -$OPTARG requires an argument." >&2
      printUsage >&2
      exit 1
      ;;
  esac
done

# Verify The Environment Contains The Expected Dependencies (az, kubectl, jq, etc.)
verifyPathDependencies

# Initialize The User's Current Configuration (Azure / K8S / etc)
initializeConfiguration

# Validate The User's Current Configuration (Azure / K8S / etc)
validateConfiguration

# Confirm User's Intention To Provision New EventHub Namespace
confirmConfiguration

# Create The New Azure EventHubs Namespace
createEventHubNamespace

# Lookup The New Azure EventHub Namespace's Authorization Key
loadAuthorizationKey

# Create K8S Secret For EventHub Namespace
createK8SSecret

# Delete (Restart) The Kafka Channel Controller Pod
deleteControllerPod

# Wait For The Kafka Channel Controller Pod To Start
waitForControllerPod

# Exit Successfully
exit 0


```

### Knative ConfigMap Update
The default-ch-webhhok configmap needs to be updated to set the default channel to `KafkaChannel `

```
⇒  k get cm -n knative-eventing default-ch-webhook -oyaml
apiVersion: v1
data:
  default-ch-config: |
    clusterDefault:
      apiVersion: knativekafka.kyma-project.io/v1alpha1
      kind: KafkaChannel
kind: ConfigMap
metadata:
  name: default-ch-webhook
  namespace: knative-eventing

```

### Create a Knative Channel
```
apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: my-channel
```

```
kubectl get kafkachannels.knativekafka.kyma-project.io
NAMESPACE   NAME                  READY   REASON   HOSTNAME                                                AGE
default     my-channel            True             my-channel-channel.default.svc.cluster.local            4d3h
```

### Create a Knative Subscription
```
apiVersion: messaging.knative.dev/v1alpha1
kind: Subscription
metadata:
  name: test-sub
spec:
  channel:
    apiVersion: messaging.knative.dev/v1alpha1
    kind: Channel
    name: my-channel
  reply: {}
  subscriber:
    uri: http://hello-display.default
```

```
kubectl get subscriptions.messaging.knative.dev
NAME                                                            READY   REASON                                AGE
test-sub                                                        True                                          28h
```

### Known Issues
Currently the kafka channel controller doesn't work as expected with Knative Brokers and Triggers, due to the way channel controller handles subscriber reference Issue raised: https://github.com/kyma-incubator/knative-kafka/issues/29

### Inference
Secret labeled with `    knativekafka.kyma-project.io/kafka-secret: "true"` needs to be present in the runtime namespace. and once this secret is changed the controller has to be restarted. This secret is created based on the connection string which can be obtained via `az` cli by executing:
```
az eventhubs namespace authorization-rule keys list \
    -o json \
    --resource-group "${EVENTHUB_NAMESPACE_RESOURCE_GROUP}" \
    --namespace-name "${EVENTHUB_NAMESPACE_NAME}" \
    --name "${EVENTHUB_NAMESPACE_SHARED_ACCESS_KEY}" | \
    jq -r ".primaryConnectionString"
    
```

**Comment by nachtmaar** [comment]
Works for me. A few small comments:

- [ ] `go get https://github.com/coreos/prometheus-operator` is based on imports path => should be `go get github.com/coreos/prometheus-operator`
- [ ] global.runtime.namespace => you mean global.namespace.eventing ? it is already set to knative-eventing
- [ ] `helm install --tls -n knative-kafka ./knative-kafka` => run it from within `knative-kafka/resources` directory
- [ ] `go get https://github.com/coreos/prometheus-operator` => `go get github.com/coreos/prometheus-operator`
- [ ] for channel and subscription, having a ready command in cat << EOF manner would be nice, like this

```bash
cat << EOF | kubectl apply -f -
apiVersion: messaging.knative.dev/v1alpha1
kind: Channel
metadata:
  name: my-channel
EOF
```

same for subscription

- [ ] service hellp-display is not provided but used in subscription, add a link to knative page or show how to deploy the service
- [ ] a curl example on how to send to the channel would be great

**Comment by sayanh** [comment]
In order to get the knative-kafka work with a broker, a trigger and a subscriber ksvc, following are my observations:
- GKE clusters should not be installed with Istio as an addon. But istio should be installed as in [here](https://knative.dev/docs/install/installing-istio/#installing-istio-with-sidecar-injection) and also configure cluster local gateway
```
helm template --namespace=istio-system \
  --set sidecarInjectorWebhook.enabled=true \
  --set sidecarInjectorWebhook.enableNamespacesByDefault=true \
  --set global.proxy.autoInject=disabled \
  --set global.disablePolicyChecks=true \
  --set prometheus.enabled=false \
  `# Disable mixer prometheus adapter to remove istio default metrics.` \
  --set mixer.adapters.prometheus.enabled=false \
  `# Disable mixer policy check, since in our template we set no policy.` \
  --set global.disablePolicyChecks=true \
  --set gateways.istio-ingressgateway.autoscaleMin=1 \
  --set gateways.istio-ingressgateway.autoscaleMax=2 \
  --set gateways.istio-ingressgateway.resources.requests.cpu=500m \
  --set gateways.istio-ingressgateway.resources.requests.memory=256Mi \
  `# Enable SDS in the gateway to allow dynamically configuring TLS of gateway.` \
  --set gateways.istio-ingressgateway.sds.enabled=true \
  `# More pilot replicas for better scale` \
  --set pilot.autoscaleMin=2 \
  `# Set pilot trace sampling to 100%` \
  --set pilot.traceSampling=100 \
  install/kubernetes/helm/istio \
  > ./istio.yaml

  kubectl apply -f istio.yaml
```

- Configure a cluster local gateway:
```
# Add the extra gateway.
helm template --namespace=istio-system \
  --set gateways.custom-gateway.autoscaleMin=1 \
  --set gateways.custom-gateway.autoscaleMax=2 \
  --set gateways.custom-gateway.cpu.targetAverageUtilization=60 \
  --set gateways.custom-gateway.labels.app='cluster-local-gateway' \
  --set gateways.custom-gateway.labels.istio='cluster-local-gateway' \
  --set gateways.custom-gateway.type='ClusterIP' \
  --set gateways.istio-ingressgateway.enabled=false \
  --set gateways.istio-egressgateway.enabled=false \
  --set gateways.istio-ilbgateway.enabled=false \
  install/kubernetes/helm/istio \
  -f install/kubernetes/helm/istio/example-values/values-istio-gateways.yaml \
  | sed -e "s/custom-gateway/cluster-local-gateway/g" -e "s/customgateway/clusterlocalgateway/g" \
  > ./istio-local-gateway.yaml

kubectl apply -f istio-local-gateway.yaml
```

- Create a namespace with istio-injection=enabled
```
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2020-01-22T10:04:26Z"
  labels:
    istio-injection: enabled
    knative-eventing-injection: enabled
  name: test
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

- Create a broker in ns `test`
```
kubectl label ns test knative-eventing-injection=enabled --overwrite
```

- Create a subscriber ksvc
```
cat << EOF | kubectl apply -n test -f -  
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  labels:
    serving.knative.dev/visibility: cluster-local
  name: event-display
  namespace: test
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containerConcurrency: 0
      containers:
      - image: gcr.io/knative-releases/github.com/knative/eventing-sources/cmd/event_display
        name: user-container
        readinessProbe:
          successThreshold: 1
          tcpSocket:
            port: 0
        resources: {}
      timeoutSeconds: 300
  traffic:
  - latestRevision: true
    percent: 100
EOF
```
- Create a trigger
```
cat << EOF | kubectl apply -n test -f -  
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  generation: 1
  labels:
    eventing.knative.dev/broker: default
  name: heartbeat
  namespace: test
spec:
  broker: default
  filter:
    sourceAndType:
      type: dev.knative.eventing.samples.heartbeat
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1alpha1
      kind: Service
      name: event-display
EOF
```
- Create a container source
```
cat << EOF | kubectl -n test apply -f - 
apiVersion: sources.eventing.knative.dev/v1alpha1
kind: ContainerSource
metadata:
  name: test-heartbeats
  namespace: test
spec:
  sink:
    apiVersion: eventing.knative.dev/v1alpha1
    kind: Broker
    name: default
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - args:
        - --period=1
        env:
        - name: POD_NAME
          value: mypod
        - name: POD_NAMESPACE
          value: event-test
        image: docker.io/shazra/heartbeats-007104604b758f52b70a5535e662802b@sha256:cba3dce56cdcd090d430b90ee6ebdb770469cbd966b0306e55dd8bf0b7f46f34
        name: heartbeats
        resources: {}
EOF
```
