### ISSUE TITLE
Compass migrator-job template not handling case of managedGCP PostgreSQL

### ISSUE THREAD

**Issue by JackCheng01** [kyma-project/kyma#6713]
**Description**

Compass migrator-job template not handling case of managedGCP PostgreSQL

**Reasons**

The migrator job for compass will fail due to not able to connect to database.
As both director and provisioner deployments are utilising cloudsql-proxy from google. 
We might align with them and add  cloudsql-proxy container in our job definition

**Attachments**
We might add below container and volumes definition to [migrator job template](https://github.com/kyma-project/kyma/blob/967e65ed5098d46d05bf2d585e3d1a5b67879f4e/resources/compass/templates/migrator-job.yaml#L21)
```yaml
        {{if eq .Values.global.database.embedded.enabled false}}
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          command:
          - /bin/sh
          args:
          - -c
          - '/cloud_sql_proxy -instances={{ .Values.global.database.managedGCP.instanceConnectionName }}=tcp:5432 -credential_file=/secrets/cloudsql-instance-credentials/credentials.json & sleep 30; exit'
          volumeMounts:
            - name: cloudsql-instance-credentials
              mountPath: /secrets/cloudsql-instance-credentials
              readOnly: true
          {{- with .Values.deployment.securityContext }}
          securityContext:
{{ toYaml . | indent 12 }}
          {{- end }}
          {{end}}

...

      {{if eq .Values.global.database.embedded.enabled false}}
      volumes:
        - name: cloudsql-instance-credentials
          secret:
            secretName: cloudsql-instance-credentials
      {{end}}
```
