### ISSUE TITLE
Unable to expose API with the same path and http method sensitive scopes

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#6830]
**Description**
When exposing an api like the one below, a validation error is produced:

```
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: httpbin
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: my-httpbin
    port: 80
    host: httpbin.mycluster.com
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["read"]
    - path: /.*
      methods: ["POST"]
      accessStrategies:
        - handler: oauth2_introspection
          config:
            required_scope: ["write"]
```
The corresponding validation error is: `Validation error: Attribute “.spec.rules”: multiple rules defined for the same path`.

This should not be the case. Also this is not based on the known ory limitation: https://github.com/ory/oathkeeper/issues/157

**Expected result**

It is expected that the following resources are created in the background:

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: httpbin
spec:
  gateways:
  - kyma-gateway.kyma-system.svc.cluster.local
  hosts:
  - httpbin.mycluster.com
  http:
  - corsPolicy:
      allowHeaders:
      - Authorization
      - Content-Type
      - '*'
      allowMethods:
      - GET
      - POST
      - PUT
      - DELETE
      allowOrigin:
      - '*'
    route:
    - destination:
        host: ory-oathkeeper-proxy.kyma-system.svc.cluster.local
        port:
          number: 4455

---
  apiVersion: oathkeeper.ory.sh/v1alpha1
  kind: Rule
  metadata:
    name: httpbin-read
  spec:
    authenticators:
    - config:
        required_scope:
        - read
      handler: oauth2_introspection
    authorizer:
      handler: allow
    match:
      methods:
      - GET
      url: <http|https>://httpbin.mycluster.com</.*>
    upstream:
      url: http://my-httpbin.apiv2.svc.cluster.local:80

---
  apiVersion: oathkeeper.ory.sh/v1alpha1
  kind: Rule
  metadata:
    name: httpbin-write
  spec:
    authenticators:
    - config:
        required_scope:
        - write
      handler: oauth2_introspection
    authorizer:
      handler: allow
    match:
      methods:
      - POST
      url: <http|https>://httpbin.mycluster.com</.*>
    upstream:
      url: http://my-httpbin.apiv2.svc.cluster.local:80
```

**Actual result**

A validation error is created:`Validation error: Attribute “.spec.rules”: multiple rules defined for the same path`.

**Steps to reproduce**
Apply above API Definition.

**Troubleshooting**

Manual editing of Rule and Virtualservice
