### ISSUE TITLE
Support JWT Tokens in Ory Hydra Token Issuer

### ISSUE THREAD

**Issue by akrausesap** [kyma-project/kyma#6832]
**Description**

By default Ory Hydra issues opaque OAuth2 tokens. however it supports also JWT Tokens: https://www.ory.sh/docs/hydra/advanced#json-web-tokens
https://www.ory.sh/docs/hydra/configuration

This can be achieved by changing the standard config map as follows:

```
apiVersion: v1
data:
  config.yaml: |
    dsn: memory
    secrets: {}
    serve:
      admin:
        port: 4445
      public:
        port: 4444
      tls:
        allow_termination_from:
        - 10.0.0.0/8
        - 172.16.0.0/12
        - 192.168.0.0/16
    urls:
      self: {}
    strategies:
      access_token: jwt
kind: ConfigMap
metadata:
  name: ory-hydra
  namespace: kyma-system
```

Those tokens can then be validated also by the v1 api which is by default used in the lambda runtime and also helps to share tokens across environments.

**Reasons**

Those tokens can then be validated also by the v1 api which is by default used in the lambda runtime and also helps to share tokens across environments.

**Attachments**

N/A
