### ISSUE TITLE
Prometheus missing kubelet metrics on AKS

### ISSUE THREAD

**Issue by toddnelson-sap** [kyma-project/kyma#6846]
**Description**
After installing Kyma 1.9, Prometheus is up and running and available in the "Stats & Metics" link in the Kyma console UI. Browsing the Grafana / Prometheus UI for the "Kubernetes Pods" resources shows the expected page. When you query for a pod, however, the "current" metrics for the pod are missing, including Memory, CPU, and Network. 

Cloud Provider: Azure 
Kyma version: 1.9
kubectl version:
```Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.8", GitCommit:"1da9875156ba0ad48e7d09a5d00e41489507f592", GitTreeState:"clean", BuildDate:"2019-11-14T05:19:20Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}```

**Expected result**

Current Pod metics for Memory, CPU, and Network are **visible** in the Grafana / Prometheus user interface.

**Actual result**

Current Pod metics for Memory, CPU, and Network are **missing** in the Grafana / Prometheus user interface.

**Steps to reproduce**

 * Log into Kyma 1.9 console 
  * https://console.dev2.agogos.ml
 * Click on link for "Stats & Metics" in the main Kyma menu
  * opens https://grafana.dev2.agogos.ml/
 * Click "Home", "Kubernetes / Pods"
 * Query for a pod: 
  * datasource: Prometheus
  * Namespace: kyma-system
  * Pod: almost any pod will do, for example: logging-promtrail-9sn7t
 * The UI shows Requested and Limit settings for Memory and CPU, but is missing Current metrics for Memory, CPU and Network

**Troubleshooting**

There's an error reported from Prometheus about a missing config file. I don't know if this is related to the above issue or not.

```kubectl describe pod -n kyma-system prometheus-monitoring-prometheus-0```

```    State:       Running
      Started:   Thu, 09 Jan 2020 17:37:26 -0700
    Last State:  Terminated
      Reason:    Error
      Message:    caller=main.go:657 msg="Starting TSDB ..."
level=info ts=2020-01-10T00:37:20.080Z caller=web.go:450 component=web msg="Start listening for connections" address=0.0.0.0:9090
level=info ts=2020-01-10T00:37:20.085Z caller=head.go:514 component=tsdb msg="replaying WAL, this may take awhile"
level=info ts=2020-01-10T00:37:20.085Z caller=head.go:562 component=tsdb msg="WAL segment loaded" segment=0 maxSegment=0
level=info ts=2020-01-10T00:37:20.086Z caller=main.go:672 fs_type=EXT4_SUPER_MAGIC
level=info ts=2020-01-10T00:37:20.086Z caller=main.go:673 msg="TSDB started"
level=info ts=2020-01-10T00:37:20.086Z caller=main.go:743 msg="Loading configuration file" filename=/etc/prometheus/config_out/prometheus.env.yaml
level=info ts=2020-01-10T00:37:20.086Z caller=main.go:526 msg="Stopping scrape discovery manager..."
level=info ts=2020-01-10T00:37:20.086Z caller=main.go:540 msg="Stopping notify discovery manager..."
level=info ts=2020-01-10T00:37:20.087Z caller=main.go:522 msg="Scrape discovery manager stopped"
level=info ts=2020-01-10T00:37:20.087Z caller=main.go:562 msg="Stopping scrape manager..."
level=info ts=2020-01-10T00:37:20.087Z caller=manager.go:814 component="rule manager" msg="Stopping rule manager..."
level=info ts=2020-01-10T00:37:20.087Z caller=main.go:556 msg="Scrape manager stopped"
level=info ts=2020-01-10T00:37:20.087Z caller=manager.go:820 component="rule manager" msg="Rule manager stopped"
level=info ts=2020-01-10T00:37:20.087Z caller=main.go:536 msg="Notify discovery manager stopped"
level=info ts=2020-01-10T00:37:20.096Z caller=notifier.go:602 component=notifier msg="Stopping notification manager..."
level=info ts=2020-01-10T00:37:20.096Z caller=main.go:727 msg="Notifier manager stopped"
level=error ts=2020-01-10T00:37:20.096Z caller=main.go:736 err="error loading config from \"/etc/prometheus/config_out/prometheus.env.yaml\": couldn't load configuration (--config.file=\"/etc/prometheus/config_out/prometheus.env.yaml\"): open /etc/prometheus/config_out/prometheus.env.yaml: no such file or directory"```

**Comment by toddnelson-sap** [comment]
![Screen Shot 2020-01-13 at 10 42 52 AM](https://user-images.githubusercontent.com/54596897/72282059-18f41680-35f9-11ea-94e3-83e7de57cfeb.png)

**Comment by hisarbalik** [comment]
Current monitoring deployment can't scrape metrics from kubelet on AKS, we are testing a patch to solve problem on AKS deployments

**Comment by a-thaler** [comment]
The consequence is that exactly these kind of metrics like cpu/memory are missing. All other metrics should work well. That problem is specific to AKS.

**Comment by codmleep** [comment]
@a-thaler will this fix be included in a 1.9 patch or with the 1.10 release?

**Comment by hisarbalik** [comment]
Fix will be delivered with next release, as a workaround please use following patch for service monitor kubelet exporter ```monitoring-kubelet```

to edit service monitor instance execute following command
``` kubectl edit servicemonitors.monitoring.coreos.com -n kyma-system monitoring-kubelet```

instance configuration should look like below

```
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: monitoring-kubelet
    chart: monitoring-8.3.3
    heritage: Tiller
    release: monitoring
  name: monitoring-kubelet
  namespace: kyma-system
  resourceVersion: "41599"
spec:
  endpoints:
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    port: http-metrics
    scheme: http
  - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    honorLabels: true
    path: /metrics/cadvisor
    port: http-metrics
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
    - kube-system
  selector:
    matchLabels:
      k8s-app: kubelet
```

**Comment by toddnelson-sap** [comment]
This patched worked successfully on our Kyma 1.9 instance on AKS. After applying the patch I see Prometheus memory and cpu pod metrics in Grafana, yay! Thanks so much for your help!

**Comment by suleymanakbas91** [comment]
Monitoring integration tests are failing on nightly aks because of this issue.

**Comment by hisarbalik** [comment]
** Description **
Kubelet deployment configuration vary depending on managed kubernetes deployment, this issue occurs on Microsoft AKS, prometheus can't scrape metrics from kubelet with an error HTTP 401. 

Following patch will solve this issue on Microsoft AKS deployments

Step 1: Delete existing ServiceMonitor instance with following command

```kubectl delete servicemonitors.monitoring.coreos.com monitoring-kubelet -n kyma-system```

Step 2: Apply new ServiceMonitor deployment for AKS with following command
```
cat <<EOF | kubectl apply -f -
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: monitoring-kubelet
    chart: monitoring-8.3.3
    heritage: Tiller
    release: monitoring
  name: monitoring-kubelet
  namespace: kyma-system
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      port: http-metrics
      scheme: http
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      honorLabels: true
      path: /metrics/cadvisor
      port: http-metrics
      scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    matchNames:
      - kube-system
   selector:
     matchLabels:
       k8s-app: kubelet
EOF
```
