### ISSUE TITLE
Monitoring CoreDNS exporter not working on AKS and Gardener with Azure

### ISSUE THREAD

**Issue by hisarbalik** [kyma-project/kyma#7093]
**Description**
Monitoring CoreDNS exporter down on AKS and Gardener Azure cluster deployment

**Expected result**
Current metics for core-dns are visible in the Grafana / Prometheus user interface.

**Actual result**
Current metics for core-dns are missing in the Grafana / Prometheus user interface.

**Comment by hisarbalik** [comment]
** Description **
Core-DNS service instance on Azure using different port setting than other providers, default deployment of service definition will not work on Azure deployment and exporter can't scrape metrics from service.

Following patch will solve problem on Azure deployements

Step 1: Delete existing service instance
```kubectl delete service monitoring-coredns -n kube-system```

Step 2: Apply new service deployment with following command
```
cat <<EOF | kubectl apply -f -
apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitoring-coredns
    chart: monitoring-8.3.3
    heritage: Tiller
    jobLabel: coredns
    release: monitoring
  name: monitoring-coredns
  namespace: kube-system
spec:
  clusterIP: None
  ports:
    - name: http-metrics
      port: 9153
      protocol: TCP
      targetPort: 9153
  selector:
    k8s-app: kube-dns
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
EOF
```
