### ISSUE TITLE
Trigger lambdas by event

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#7216]
**Description**

It should be possible to trigger lambdas by events, so functions need to support registration to brokers.
For now, base Event lists on EventActivation CR, as a new solution is not ready yet.

AC:
 - Trigger CR that points to default broker is created
 - The filter is defined in Trigger CR
 - Trigger supported in UI
 - Tutorial with steps on how to create trigger CR (kubectl)
 - List of available events in UI
 - Events trigger lambda 😄 

Decide if Trigger CR should be treated as a new domain in CBS or not.

**Reasons**

Lambdas connected to Event Mesh

**Attachments**

https://knative.dev/docs/eventing/broker-trigger/

**Comment by michal-hudy** [comment]
Take a look at this note: https://github.com/kyma-project/console/issues/956#issuecomment-536672006

**Comment by michal-hudy** [comment]
Sample trigger CR:
```yaml
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: test-trigger
  namespace: serverless
spec:
  broker: default
  filter:
    attributes:
      type: bo.interaction.created # Event name
      eventtypeversion: v1 # Event version
      source: mock # Application name
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: test-lambda # Lambda name
```
