### ISSUE TITLE
Support for Gardener based Certificate Renewal

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#7222]
**Description**
With https://github.com/kyma-project/kyma/issues/6647 Kyma added support for domains managed by Gardener. For that, the xip-patch logic got adjusted to generate a certificate for the default shoot cluster domain, in case no custom domain is configured. The generated certificate gets copied to the standard domain overrides.

The gardener certificate extension will re-generate the certificate on its own in case of expiration. Unfortunately, the Kyma logic is copying the certificate once instead of directly using the generated secret. With that, any re-generation is not getting recognized and the used certificate will expire.

Goal: Use the single secret generated by the gardener certificate extension for the istio ingress gateway directly, so that a re-generation gets active immediately without any action.

To have a stable secret in the istio-system namespace just specify the requested secret name in the related resource:
```
apiVersion: cert.gardener.cloud/v1alpha1
kind: Certificate
metadata:
  name: kyma-cert
  namespace: istio-system
spec:
  commonName: "*.${DOMAIN}"
  secretName: "${secret_name}"
```

**Reasons**
Certificates will expire, Kyma should provide a convenient way to circumvent that

**Attachments**
