### ISSUE TITLE
Override returns an error for istio-kyma-patch Pod 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#7249]
**Description**
After adding an override for Istio settings, the installation fails,  `istio-kyma-patch` pod returns an error.

Tested locally on Minikube.
I applied the following override to change the value for trace sampling. The override was added at runtime with the Kyma installation update triggered afterwards.

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  kyma_istio_control_plane: |-
    apiVersion: install.istio.io/v1alpha2
    kind: IstioControlPlane
    spec:
      trafficManagement:
        components:
          pilot:
            enabled: true
            k8s:
              env:
              - name: PILOT_TRACE_SAMPLING
                value: "60"
```

**Expected result**

Override is applied, Kyma updated, value is changed. 

**Actual result**

istio-kyma-patch pod returns an error:

```
istio-kyma-patch-56gwq                   0/1     Error     0          2m15s
istio-kyma-patch-sdjpj                   0/1     Error     0          114s
```
```
mTLS must be "STRICT"
```

**Steps to reproduce**

1. Create an override + apply it
2. Trigger installation update
