### ISSUE TITLE
Development Profile Istio Proxy Memory Too Low

### ISSUE THREAD

**Issue by toddnelson-sap** [kyma-project/kyma#7432]
**Description**

With Kyma 1.10 we see that default Istio proxy sidecar memory was reduced by half. Kyma 1.9 had 64Mi request/128Mi max memory for the default Istio sidecar. With Kyma 1.10 the default sidecar memory is 32Mi/64Mi. We have many Kyma pods that fail with istio-proxy OOMKilled errors: core-console-backend, jaeger, helm-broker, ory-oathkeeper, etc. This makes Kyma 1.10 not stable for us.

Kyma version 1.10.0
Kubernetes: 1.14.8
Hyperscaler: Azure
Cluster Name: konduit-dev-5
Cluster Size: D4v3; 3 nodes each with 4 vCPU, 16GB memory

**Expected result**

Important Kyma pods like core-console-backend, etc, run without repeated OOMKilled restarts.

**Actual result**

Many Kyma pods that fail with istio-proxy OOMKilled errors: core-console-backend, jaeger, helm-broker, ory-oathkeeper, etc. This makes Kyma 1.10 not stable for us.

**Steps to reproduce**

Install Kyma with the default (development) Service Mesh profile. 
See: https://kyma-project.io/docs/components/service-mesh/#configuration-service-mesh-production-profile

This results in istio-proxy sidecars with the following resource settings:

Resource | Setting
------------ | -------------
CPU Requests | 20m
CPU Limits | 200m
Memory Requests | 32Mi
Memory Limits | 64Mi

**Troubleshooting**

Setting to the production profile also crashes the cluster. 

Resource | Setting
------------ | -------------
CPU Requests | 300m
CPU Limits | 500m
Memory Requests | 128Mi
Memory Limits | 1024Mi

There is not enough CPU on a 3 node D4v3 cluster to schedule all the pods, and so pods fail to come up with:
```
FailedScheduling      No nodes are available that match all of the following predicates:: Insufficient cpu (3).
```

Setting to the Kyma 1.9 istio proxy settings allows the cluster to run successfully. 

Resource | Setting
------------ | -------------
CPU Requests | 10m
CPU Limits | 100m
Memory Requests | 64Mi
Memory Limits | 128Mi

Made these settings with a Kyma installer override:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  global.proxy.resources.requests.cpu: "10m"
  global.proxy.resources.limits.cpu: "100m"
  global.proxy.resources.requests.memory: "64Mi"
  global.proxy.resources.limits.memory: "128Mi"
```
