### ISSUE TITLE
Tiller 2.16 Fails on CRD with Integer Validation

### ISSUE THREAD

**Issue by toddnelson-sap** [kyma-project/kyma#7433]
**Description**

Kyma 1.10 depends on Tiller v2.16.1. There is a bug in this version of Tiller that fails to load the
Konduit Dataflow CRD. Specifically, it results in ```cannot convert int64 to float64```. This is because of this bug in Tiller: https://github.com/helm/helm/issues/5806

**Environment**
Kyma version 1.10.0
Kubernetes: 1.14.8
Hyperscaler: Azure
Cluster Name: konduit-dev-5

**Expected result**

CustomResourceDefinitions with integer validation load successfully from Helm charts. 

**Actual result**

CustomResourceDefinitions with integer validation fail to load from Helm charts.

```
Error during install/update:  Details: Helm install error: rpc error: code = Unknown desc = unable to convert to 
CRD type: unable to convert unstructured object to apiextensions.k8s.io/v1beta1, Kind=CustomResourceDefinition: 
cannot convert int64 to float64
```

**Steps to reproduce**

Try to create a CustomResourceDefinition with integer field validation:

```
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
...
spec:
...
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            retryInterval:
              format: int64
              maximum: 60000
              minimum: 100
              type: integer
          type: object
        status:
          type: object
  version: v1alpha1
...
```

**Troubleshooting**

Until the above mentioned Tiller bug is fixed, one way to fix is to down-rev tiller. Download the Kyma tiller yaml and patch it. Set the Tiller version to 2.13.1, the most recent version without the bug.
```
curl -L https://raw.githubusercontent.com/kyma-project/kyma/$KYMA_VERSION/installation/resources/tiller.yaml --output tiller.yaml
# patch tiller version:
sed -i '' 's/tiller:v2.16.1/tiller:v2.13.1/' tiller.yaml
```
Apply Tiller:
```
kubectl apply -f tiller.yaml
```
