### ISSUE TITLE
Add documentation for Trigger CR 

### ISSUE THREAD

**Issue by bszwarc** [kyma-project/kyma#7498]
**Description**

Although we use Trigger implementation provided by Knative, we should document it in the Kyma context, especially including the attributes. Also, add information about the `default` Broker to the architecture.
Sample trigger CR:

```
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: test-trigger
  namespace: serverless
spec:
  broker: default
  filter:
    attributes:
      type: bo.interaction.created # Event name
      eventtypeversion: v1 # Event version
      source: mock # Application name
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: test-lambda # Lambda name
```
**Reasons**
Kyma-specific elements/configs should be documented. 

This doc can serve as point fo reference in #7216
