### ISSUE TITLE
Install ServiceEntry inside Knative-Eventing-Kafka chart

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#7507]
**Description**

With `knative-eventing-kafka` on gke and kafka being hosted on azure kafka channels do not work.

**Expected result**

Events get sent

**Actual result**

Events do not get sent:

the `kantive-kafka-channel`s logs show:

```
{"level":"warn","ts":"2020-03-09T08:40:10.404Z","caller":"producer/producer.go:142","msg":"Kafka Error","error":"sasl_ssl://nachtmaar-test-2.servicebus.windows.net:9093/bootstrap: SSL handshake failed: SSL transport error: Connection reset by peer (after 120ms in state CONNECT)"}
```

**Fix**
Install a ServiceEntry for azure:

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: azure-eventhubs
  namespace: kyma-system
spec:
  hosts:
  - '*.servicebus.windows.net'
  location: MESH_EXTERNAL
  ports:
  - name: kafka
    number: 9093
    protocol: HTTPS
  - name: https
    number: 443
    protocol: HTTPS
```

**AC**
- Add a Troubleshooting Guide which addresses this problem and provides user to add the *ServiceEntry* CR if they face this issue.
