### ISSUE TITLE
API rules list all service versions created with kantive service which can be confusing for customers

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#7670]
### Steps
* Create a Knative service

```YAML
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  labels:
    serving.knative.dev/visibility: cluster-local
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
      - image: gabbi/helloworld-go:latest
        env:
        - name: TARGET
          value: "Gooo"
```

* Create an API rule.
* One will see multiple services
<img width="1333" alt="Screenshot 2020-03-18 at 10 45 01" src="https://user-images.githubusercontent.com/4436741/76947990-bbd15580-6906-11ea-89d6-1629d7f896f7.png">
