### ISSUE TITLE
dex override of admin password only possible with ConfigMap

### ISSUE THREAD

**Issue by tehcyx** [kyma-project/kyma#7829]
**Description**
I tried overriding the admin password with a secret and the installation was hanging at the dex component until I deleted the cluster and the same thing worked with a ConfigMap instead. (kyma 1.10)

From the dex pod in kyma-system I got the following log:
```shell
k --kubeconfig=kconfig.yaml -n kyma-system logs dex-b9695bfc7-bvftn -c dex       
error parse config file /etc/dex/cfg/config.yaml: error unmarshaling JSON: no password hash provided
```

My Secret looked like this:
```yaml
apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: dex-user-override
    namespace: kyma-installer
    labels:
        installer: overrides
        component: dex
        kyma-project.io/installation: ""
data:
    adminPassword: {{ .Values.kyma.dex.adminPassword | b64enc | default ( randAlphaNum 12 | b64enc ) }}
```

which was filled correctly on the cluster with a randomly generated secret: `VnZDQ0NwV0sxanBa`

From the installer logs I could read this:
```shell
---------------------------
2020/03/27 19:26:17 Get Kyma Sources
2020/03/27 19:26:17 Kyma sources available locally.
2020/03/27 19:26:17 Get Kyma Sources...DONE
2020/03/27 19:26:17 Overrides used for installation of component dex
2020/03/27 19:26:17 
 global:
  adminPassword: VvCCCpWK1jpZ
```
which was the base64 decoded password of the randomly generated one, so it actually was passed all the way through.

When I took the above secret and turned it into a configmap:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
    name: dex-user-override
    namespace: kyma-installer
    labels:
        installer: overrides
        component: dex
        kyma-project.io/installation: ""
data:
    adminPassword: {{ .Values.kyma.dex.adminPassword | b64enc | default ( randAlphaNum 12 | b64enc ) }}
```
It worked immediately. If I understand the [documentation](https://kyma-project.io/docs/#configuration-helm-overrides-for-kyma-installation-overrides-examples) correctly the Secret should also work:
> For overrides that the system should keep in Secrets, just define a Secret object instead of a ConfigMap with the same key and a base64-encoded value. Be sure to label the Secret.

**Expected result**
Secret should be overriden like it is with the ConfigMap

**Actual result**
dex installation fails

**Steps to reproduce**
Use a secret override for the admin password
