### ISSUE TITLE
[kyma-installer] fails to install proper helm package

### ISSUE THREAD

**Issue by fhivemind** [kyma-project/kyma#7983]
**Description**

When trying to install a properly packed helm package, `kyma-installer` fails to locate the Chart.yaml and other chart related files.

Properly packed helm package follows the guidelines of Helm chart packing.

> A chart is organized as a collection of files inside of a directory. The directory name is the name of the chart (without versioning information). Thus, a chart describing WordPress would be stored in the wordpress/ directory.

**Expected result**

Kyma-installer should successfully perform installation of the package

**Actual result**

Kyma-installer throws `fail to locate the Chart.yaml`

**Steps to reproduce**

```yaml
- name: "wordpress"
  namespace: "kyma-system"
  source:
    url: https://kubernetes-charts.storage.googleapis.com/wordpress-1.0.0.tgz
```

**Troubleshooting**

Kyma-installer expects that the helm chart doesn't have a parent folder `package-name`, and instead has as a parent the contents of the package (chart related files such as Chart.yaml) which makes it fail.
