### ISSUE TITLE
Console backend should not depend on rafter config map

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#8034]
**Description**
Console backing can't be installed before rafter config map is created:
```
       - name: APP_RAFTER_ADDRESS
            valueFrom:
              configMapKeyRef:
                name: rafter-minio-envs
                key: APP_UPLOAD_ENDPOINT_WITH_PORT
          - name: APP_RAFTER_SECURE
            valueFrom:
              configMapKeyRef:
                name: rafter-minio-envs
                key: APP_UPLOAD_SECURE
  ```

**Expected result**
Service can be installed in parallel with rafter (or even without rafter)
