### ISSUE TITLE
istioctl displays CONFLICT for services without sidecar

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#8284]
**Description**

in the current istio setup we apply a meshwide default for services to enforce mtls by setting 
```yaml
mtls:
  mode: STRICT
```

This also applies to services that are not part of the mesh (e.g. api-server (kubernetes.default.svc))

in case of the api-server a destination-rule exists in istio-system

```yaml
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
  name: api-server
  namespace: istio-system
spec:
  host: kubernetes.default.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        connectTimeout: 30s
    tls:
      mode: DISABLE
```

This destination rule is required to allow communication with kubernetes api-server as it is not part of the mesh.

if one uses `istioctl authn tls-check` to check the mtls settings for any pod this leads to the output similar to 
```shell
$ istioctl authn tls-check -n kyma-integration varkes-event-service-5dbcb95769-pmnkb
HOST:PORT                                         STATUS       SERVER         CLIENT          AUTHN POLICY                                                            DESTINATION RULE
kubernetes.default.svc.cluster.local:443          CONFLICT     STRICT         DISABLE          /default                                                                istio-system/api-server
```

Even though it reports a conflict the communication works fine.

**Expected result**

Status should be reported as `OK`

**Actual result**

Status is `CONFLICT`

**Fix**
Create a policy similar to this
```yaml
apiVersion: authentication.istio.io/v1alpha1
kind: Policy
metadata:
  name: api-server
  namespace: default
spec:
  peers:
  - mtls:
      mode: PERMISSIVE
  targets:
  - name: kubernetes
```

for every service that is not part of the mesh (no sidecar injected)
