### ISSUE TITLE
Function controller  doesn't always update the conditions

### ISSUE THREAD

**Issue by magicmatatjahu** [kyma-project/kyma#8331]
**Description**

As in title. Example conditions:

```yaml
status:
  conditions:
  - lastTransitionTime: "2020-04-30T08:42:29Z"
    message: Function test-fn is ready
    reason: ServiceReady
    status: "True"
    type: Running
  - lastTransitionTime: "2020-04-30T08:42:09Z"
    message: Job test-fn-build-jz2p7 created
    reason: JobCreated
    status: Unknown
    type: BuildReady
  - lastTransitionTime: "2020-04-30T08:42:08Z"
    message: ConfigMap test-fn-fv8kw updated
    reason: ConfigMapUpdated
    status: "True"
    type: ConfigurationReady
```

And Job conditions:

```yaml
  status:
    completionTime: "2020-04-30T08:42:21Z"
    conditions:
    - lastProbeTime: "2020-04-30T08:42:21Z"
      lastTransitionTime: "2020-04-30T08:42:21Z"
      status: "True"
      type: Complete
    startTime: "2020-04-30T08:42:09Z"
    succeeded: 1
```

As we can see, we have Unknown status on Job condition, but Job has Completed status.
