### ISSUE TITLE
Clean Application Operator and Runtime Agent charts up

### ISSUE THREAD

**Issue by franpog859** [kyma-project/kyma#8718]
**Description**

After the migration to Helm 3 we can prune all Tiller occurrences from the charts. This is a good opportunity to just clean the charts too. Follow the pattern proposed in [this PR](https://github.com/kyma-project/kyma/pull/8594/files) and make Application Operator charts located in `components/application-operator/charts/` and Compass Runtime Agent charts located in `resources/compass-runtime-agent/` consistent!

This is a follow up issue for [this one](https://github.com/kyma-project/kyma/issues/8577)

**Reasons**

It's good to match the best practices!

**Attachments**

In most cases the change will consist in pruning Tiller from charts and adding these lines to `metadata` of the resource:
```
labels:
  release: {{ .Release.Name }}
  helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
  app.kubernetes.io/name: {{ template "name" . }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
  app.kubernetes.io/instance: {{ .Release.Name }}
```
