### ISSUE TITLE
[POC] kyma installation with helm-operator

### ISSUE THREAD

**Issue by piotrmsc** [kyma-project/kyma#8746]
**Description**

As we are currently thinking about how the future installation/upgrade of kyma should look like https://github.com/kyma-project/kyma/issues/8664 and given the requirements we have (in that issue as well) I found [helm-operator](https://github.com/fluxcd/helm-operator) as an interesting alternative for current kyma-operator. 

Goal of this POC is simple : 

- Kyma installed using helm operator (helm3 under the hood)
- Checked if all requirements from #8664 are met, any missing parts are described. Results will be used for further discussion.

**Reasons**

Given the nature of kyma - integrating existing components like istio, service-catalog, knative,kiali,prometheus, etc plus ours like application gateway we need to have a common way of installing and managing components. Currently, some of the components might have operators implemented or CLI like prometheus and istio, however, we still need one common way to apply this configuration into the cluster and manage it there. 

In my opinion, independently from what will be used to install and orchestrate our applications (cli/operator anything else) helm3 will be a good option as a common interface/ data medium.
Helm itself had issues and we struggled with it but mostly we hit problems related to tiller. 
There are +/- of using helm, but also helm is widely used across k8s and having, for example, helm-operator would be an easy way of kyma users to add any helm compliant component (it can still use cli in that chart, doesn't actually matter).

**Attachments**

**Comment by mszostok** [comment]
### Findings 

0. HelmRelease does not create a namespace for chart installation. Need to be created up front.

1. When using the HelmRelease the underlying chart installs are infinitely retried, with no configurability, check [this issue](https://github.com/fluxcd/helm-operator/issues/388) for more info. 

2. Upgrades support configurability of retries through the HelmRelease's spec fields.
    ```yaml
    spec:
      rollback:
        enable: true
        retry: true
        maxRetries: 5
    ```
    The problem is that the it needs to be set for each HelmRelease. We need to come up with some concept to have a common base for all HelmRelase CRs. (kustomize, own bash script, sed, etc.).

3. HelmRelease which points to the git repos are not cached across namespace.

    ```yaml
    spec:
      chart:
        git: git@github.com:org/repo
        ref: master
        path: charts/podinfo
    ```

   Each one will be mirrored with such index:
    ```go
    hr = HelmRelease CR
    fmt.Sprintf("%s/%s/%s", hr.GetNamespace(), hr.Spec.GitChartSource.SecretRef.Name, hr.Spec.GitURL)
    ```
    Git additionally adds:
    > when a change is detected in Git under the .chart.path, a release will be scheduled for an upgrade

    In Kyma context that is not an expected behavior. Probably is a good approach for MPS but not for SKR unless we will have a separate repo per client.
    
    There is an alternative a Helm repository that is globally cached. Problem is that we will need to build and push all Kyma charts to some repo e.g. GCS.
    ```yaml
    spec:
      chart:
        repository: https://stefanprodan.github.io/podinfo
        name: podinfo
        version: 3.2.0
    ```
