### ISSUE TITLE
Installation hangs when using own-domain (minikube)

### ISSUE THREAD

**Issue by pauls-z** [kyma-project/kyma#8757]
**Description**
Installing kyma on minikube using custom domain & ssl certs hangs up on application-connector.

`kyma install --domain kyma.dev --tlsKey <bas64 key> --tlsCert <bas64 cert>`

**Expected result**

Kyma should install succesfully and accessible through custom domain.

**Actual result**

Installation hangs up on application-connector.

**Steps to reproduce**

1. Provision minikube 
`kyma provision minikube`
2. Run install with custom domain, tlsKey, tlsCert. Using self-signed certificate below:
```
kyma install --domain kyma.dev --tlsKey LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tDQpNSUlFdmdJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLZ3dnZ1NrQWdFQUFvSUJBUURFQUdtQ2JEcGRXZ1k0DQpyT3FtNGRvZHMwMjkxczZPT1VRYnBiNXdyeGxMWEdTUEV0anJQcUlMV3ROYmtFcWdDaDNZZEk3dDA2Zkw2SER0DQpRU1hWU3dONFVrMWNkS3NudXRFL3hxT0drQkpkZHJLbExQMElZbU5JWC9pSHBMUkVad0ZUZ2EraWd6NWhWbTNJDQpDVkhiVnVDVHVtLy8yNFdTQzhwSEVCZ3dhZVhja21ZTFZCQlBxcjlZWEFMY2dGTHVaamg3OVFmcWRIY1UrUmJHDQpRdW56d2xRY210Nnpwd1ErelRBd2EralljR1J0S0FiZGNiU29vTWFqM2pxYzBUMzdieXNURHlmdlJxYURqek9EDQpzZk5acVA1VGxxTzFTell0YWVvcE1vc0txWG9TZUg4K1VDZVpyczZXQjdXYjREdzZtaHhxYlRheFZOMjhMOHRrDQorM3cxNzJDakFnTUJBQUVDZ2dFQkFMUFlpUGZpcFI5WlpwSUVvSCttaDRSdkxXdC9PaU1vaXNVdnJYSXFTUFJzDQpmOTBFZDBSTVFWWlg3YzU3dE8zcXVuNE9YY1ArVFY1K0YzaXNLYkh3VmV2RzRUTnYza2pqVS9QSUtlNWtMbVhTDQpiNU8rbHlObFhDSmg1V05aand1ZzFJZXlYTjJxdmNlRkRkRGFOR0VsODRXNk1lQzhwbkJmSHlsYnJFWm9OVUhRDQorekxyTUpxbHJiYmNPR0N4a2hGRWpsUFowTmtXcEZrYlhTOWZBYmNiK2FudXZjZGJLMVhPaXVNcFREVUJCNVo5DQpVYWNHNDJwNUtnTGZNc3lOdGFGekpFckk3NVgzTXFBK0JJYi8vaHMwdnY2d1V2eU10dld6MGRONGZhM2VwNWV1DQpacjJIWi9KUU9QNGhPUit4cWVmTzFuQXJLQkloQ3Fvb1ltd1dxaTNiVHRrQ2dZRUE4bVRoZ25YWE1zbVdLbk5zDQo3YmhLYjhKdmowYktjcjVib0ltZ3pyS1M5SkZiOElJUkM1RDRrLzRaVU16NXRUem5zZDVtU0xEbldNR09jV01mDQp0Q2YyaStGVCtialY1YXAwWGxaOHlrajhTaDZnV0hJMFdpWHYrMUJqNGlsUUxxM2lPVkExdGFORjVFbzZUdGI5DQpDUytuV0lOVSswRkhFc0ZkV3RwekJGaTdISzBDZ1lFQXp3RGpQY05TZXlwTEJla2JvQlZVbjBlN3FUZWtoeGQwDQpNbGlQRk1kelgyWks1Zm9qTVc5RHZReSttVlJDUVhvUzZJVWFMdlpKaDVSa3JtVGN5enMxZUwyRUZXMmx0R2d2DQo0NmFPMlNtNmJIWFh6M1FtTlZocjZHdjE3MWlvRXY5eWR3cEh4TE5ERmQ3Q3A4ejhRaUM4dDFrNWcxamovVG12DQpyWkt3ZFVwalRJOENnWUVBa0d3YkVTZzFPRVZ6KzRjYWQraytNS2lnMzdWR0dtZmhJQjNnZWtkYjEreGo0MEViDQo5dEJCeTZ1eVdicEhiZjBENzY2Yk11UjBjeVdnUVY3V0hQbFNwTFYwMjIyTnhIRnpOR0pEcUNNa2J1VWdsSkkzDQpMeDg3aFhtNGlhQWo3aXdjaGhtTVp0VUpaNlB5YWRjZW5NS1A2dVVWVlQ3bm9mMGtLbVhOOGVFTVcyRUNnWUE2DQpPQVd4V1QzWlpndXpuZHduS2RpaTg0blVEZEk0TEdDQnlHWjFjYU1CTWNQZTZucjdiRStnMi9TL0t2TjNkdDNhDQpoNVRWb0c4TnNxNmVYYis3YU91aENhd2NXcnBBQXcxMCtXTXpzSWk5K0dhNThmRE5FQkZKVFJQZVBSRUlScy9xDQpxdm1FV09hRlFDRi9FQ2ZpY1ZLaVBuWHVleEdrSnBWQ08vOWsvWWJ3QVFLQmdCYTB2L2xUU3dXRmRvU1MrY2pTDQpmWjVTZU40SWhGaGZXL0djNkNxeklsUC80dEJYczJ4WGRvWHN1NkZuRnJJUUM0MzZQbGxhNGpycmZmbU9NZWxoDQovZi9TUmpMcmo3blVMeVFqRGdlZTErMWYrTHJ4cW03YWhxdTl5aUwzMk1OUjRmd2F1UkFuUzlmMDNDbktuOTA4DQpnMkczM29IdlNMclNmeTdPR2lxakVHb1YNCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0NCg== --tlsCert LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tDQpNSUlEUmpDQ0FpNmdBd0lCQWdJVUY4MitndHlTVEJreGU1L3AwU2xGd1JNY1BwMHdEUVlKS29aSWh2Y05BUUVMDQpCUUF3SWpFVE1CRUdBMVVFQXd3S0tpNXJlVzFoTG1SbGRqRUxNQWtHQTFVRUJoTUNWVk13SGhjTk1qQXdOakE0DQpNakUxTlRBNVdoY05NekF3TmpBMk1qRTFOVEE1V2pBaU1STXdFUVlEVlFRRERBb3FMbXQ1YldFdVpHVjJNUXN3DQpDUVlEVlFRR0V3SlZVekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNUUFhWUpzDQpPbDFhQmppczZxYmgyaDJ6VGIzV3pvNDVSQnVsdm5DdkdVdGNaSThTMk9zK29ndGEwMXVRU3FBS0hkaDBqdTNUDQpwOHZvY08xQkpkVkxBM2hTVFZ4MHF5ZTYwVC9HbzRhUUVsMTJzcVVzL1FoaVkwaGYrSWVrdEVSbkFWT0JyNktEDQpQbUZXYmNnSlVkdFc0Sk82Yi8vYmhaSUx5a2NRR0RCcDVkeVNaZ3RVRUUrcXYxaGNBdHlBVXU1bU9IdjFCK3AwDQpkeFQ1RnNaQzZmUENWQnlhM3JPbkJEN05NREJyNk5od1pHMG9CdDF4dEtpZ3hxUGVPcHpSUGZ0dkt4TVBKKzlHDQpwb09QTTRPeDgxbW8vbE9XbzdWTE5pMXA2aWt5aXdxcGVoSjRmejVRSjVtdXpwWUh0WnZnUERxYUhHcHROckZVDQozYnd2eTJUN2ZEWHZZS01DQXdFQUFhTjBNSEl3SFFZRFZSME9CQllFRkxId1VrVWtjVW9BSWFYMCtVUjE1Z1dlDQpBNk40TUI4R0ExVWRJd1FZTUJhQUZMSHdVa1VrY1VvQUlhWDArVVIxNWdXZUE2TjRNQTRHQTFVZER3RUIvd1FFDQpBd0lGb0RBZ0JnTlZIU1VCQWY4RUZqQVVCZ2dyQmdFRkJRY0RBUVlJS3dZQkJRVUhBd0l3RFFZSktvWklodmNODQpBUUVMQlFBRGdnRUJBR2t3bDlQN0gwYmFtSzArNEdESS94dVRPckVFZVJHSlJ1V2V1OWVWdFZKN3RMRlQxOGlnDQpueTJpUW9IZURvWTRhbjNRb0lNOXo2U2xCOWkyZlM0WEkvUzVvc2hLQzBQNW9BTUxFRnR6SE8yOW1XcmdoNlZ6DQphMlMwN0c0N1gwMkRYb0V4b09XL0p6ei9XNHJ5SWN4V3BNRUhmRnQ5eXk2OFlBdG1vWU43SnlrMHpRTlp5bWFDDQpDQSs2MjM5SThVUU1UUjB4cEdPUzdGSzV6WlhOZ0M3amQ2eWpGK09kaWN3b1hKZlBvVEhEaENTMWRJQkVaUERiDQpSNVZUZXNNY205THJXd2NJQ2IralVZRGcxdVcybEVzdC9BckNkOEZlTGhxVUhHeldUZkpSZG1iQ0JmRG5DSnNXDQpKcFdzZWJZN0xKbWlzaitwcnZsT3FEUTBHRnViOCtadFBLUT0NCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0NCg==
```

3. Wait for it to hang-up

**Troubleshooting**

Installer logs show 
```
2020/06/09 05:58:59 install component application-connector
2020/06/09 05:58:59 ---------------------------
2020/06/09 05:58:59 Get Kyma Sources
2020/06/09 05:58:59 Kyma sources available locally.
2020/06/09 05:58:59 Get Kyma Sources...DONE
```

`kyma describe node` show that the cpu is 100% used ` cpu        4010m (100%)`

Created file overrides.yaml file and added istio overrides with reduced resources:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: istio-overrides
  namespace: kyma-installer
  labels:
    installer: overrides
    component: istio
    kyma-project.io/installation: ""
data:
  pilot.resources.limits.memory: 1024Mi
  pilot.resources.limits.cpu: 500m
  pilot.resources.requests.memory: 512Mi
  pilot.resources.requests.cpu: 150m
  pilot.autoscaleEnabled: "false"

  mixer.policy.resources.limits.memory: 2048Mi
  mixer.policy.resources.limits.cpu: 500m
  mixer.policy.resources.requests.memory: 512Mi
  mixer.policy.resources.requests.cpu: 100m

  mixer.telemetry.resources.limits.memory: 2048Mi
  mixer.telemetry.resources.limits.cpu: 500m
  mixer.telemetry.resources.requests.memory: 512Mi
  mixer.telemetry.resources.requests.cpu: 100m
  mixer.loadshedding.mode: disabled

  mixer.policy.autoscaleEnabled: "false"
  mixer.telemetry.autoscaleEnabled: "false"
```

then re-run the installation with additional installer parameter `--override override.yaml` and installation succeeded
