### ISSUE TITLE
Remove .value for overwrites for Serverles chart

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#9006]
**Description**

Following the [documentation](https://kyma-project.io/docs/components/serverless#configuration-serverless-chart) we can overwrite the default values for the chart.

**Expected result**

For configuring we should have something like this
```
  serverless:
    enabled: true
    namespace: "kyma-system"
    overrides: 
      containers.manager.envs.buildRequestsCPU: "100m"
      containers.manager.envs.buildRequestsMemory: "200Mi"
      containers.manager.envs.buildLimitsCPU: "200m"
      containers.manager.envs.buildLimitsMemory: "400Mi"
```

**Actual result**

We need to add `.value` to be able to change those values
```
  serverless:
    enabled: true
    namespace: "kyma-system"
    overrides: 
      containers.manager.envs.buildRequestsCPU.value: "100m"
      containers.manager.envs.buildRequestsMemory.value: "200Mi"
      containers.manager.envs.buildLimitsCPU.value: "200m"
      containers.manager.envs.buildLimitsMemory.value: "400Mi"
```
