### ISSUE TITLE
POC Kyma Binding

### ISSUE THREAD

**Issue by PK85** [kyma-project/kyma#9402]
**Description**
POC about new credential binding mechanism. We'd like to decouple Kyma bindings from Service Catalog domain (currently ServiceBindingUsage) and make them lightweight and simple. 

More or less new CRD _from_ and _to_ sections must be configurable from type point of view. Section _to_ could be reused from SBU. The _from_ section in the first iteration must support secrets, and config maps could be added in the next iterations.

**Reasons**
Current credential binding into application is implemented with help of ServiceBindingUsage CRD. This is tightly coupled with service catalog domain and cannot be used without it. 

**AC**
- check if we have any alternatives to podpreset
- allow user to declare which secret will be injected into function and into deployment 
- allow to adjust environment variables keys (mappings). Design solution.
- create full-blown doc about that feature
- part of the kyma-project organization, kyma repository. Give a possibility to install "bindings" chart only. 
- check if we can removed podpreset CRD from kyma (if any component use it as well)

**Naming**
- api group name: bindings.kyma-project.io
- CRD: bindings.kyma-project.io/Bindings
- CRD: bindings.kyma-project.io/TargetKind

Binding proposal:
```
apiVersion: bindings.kyma-project.io/v1alpha1
kind: Binding
metadata:
 name: deploy-redis-client
spec:
 source:
   kind: secret
   name: redis-instance-credential
 target:
   kind: deployment
   name: redis-client
```

TargetKind proposal:
```
apiVersion: bindings.kyma-project.io/v1alpha1
kind: TargetKind
metadata:
   name: deployment
spec:
   displayName: Deployment
   resource:
     group: apps
     kind: deployment
     version: v1
   labelsPath: spec.template.metadata.labels
```

**Links**
- https://github.com/knative/pkg/tree/master/apis/duck (https://www.youtube.com/watch?v=kldVg63Utuw)

**Comment by crabtree** [comment]
Maybe also worth checking: https://github.com/IBM/composable

**Comment by jasiu001** [comment]
Existing solutions that combine Secret/ConfigMap with other resources:
**1) Knative duck [link](https://github.com/knative/pkg/tree/master/apis/duck)**
- the project is still being developed (last commit a few days ago) but still in the alpha stage
- presentation showed on "kubecon" presents only example with knative service
- very poor documentation, lack of examples. There is no proof it could be used with Secret and could be useful in binding case
- knative functioanlity is already used in Kyma with whole resources include `sinkbindings.sources.knative.dev` and `sinkbindings.sources.eventing.knative.dev`

**2) IBM/composable [link](https://github.com/IBM/composable)**
- alpha stage
- last commit was made in February 2020
- support secret and config map
- well documented with examples
- during installation according to documentation error occurs
```
unable to recognize "/tmp/ibm-composable/composable-master/releases/latest/005_deployment.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
```
(to fix it deployment version need to be changed from "extensions/v1beta1" to "app/v1"
- the library allows creating a template of resource (e.g. deployment) with values which refer to not existing Secrets (or CMs). The Deployment will not be created until the required secret will not show up. For example, let's consider the following Composable template with Deployment, assume Secret "credentials" doesn't exist:
```yaml
apiVersion: ibmcloud.ibm.com/v1alpha1
kind: Composable
metadata:
  name: test-deploy
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: sandbox
    spec:
      selector:
        matchLabels:
          app: sandbox
      replicas: 1
      template:
        metadata:
          labels:
            app: sandbox
          annotations:
            sidecar.istio.io/inject: "false"
        spec:
          containers:
            - name: sandbox
              image: yauritux/busybox-curl
              command: ['sh', '-c', 'sleep 10000']
              env:
                - name: SOME_VALUE
                  value:
                    getValueFrom:
                      kind: Secret
                      name: credentials
                      namespace: default
                      path: '{.data.password}'
                      format-transformers:
                      - "Base64ToString"
```
the Deployment will not be created after we create Secret
```
kubectl create secret generic credentials --from-literal=password='super_secret_password'
```
the Composable will detect this and deployment will be created
- injected sensitive data are visible (not coded)
- the library does not inject data from the Secret, injected data must be previously declared in the template (e.g. Deployment)

**3) stakater/Reloader [link](https://github.com/stakater/Reloader)**
- 1,6k stars on Github, last commmit few days ago
- support secret and config map
- well documented
- easy installation by helm
```
helm repo add stakater https://stakater.github.io/stakater-charts
helm repo update
helm install stakater/reloader --generate-name
```
- library watches Secrets and Config Maps and reloads resources connected with Secret/ConfigMap if they changed
- exmaple:
    - create empty secret
        ```
        kubectl create secret generic sandbox-secret
        ```
    - add Deployment
        ```yaml
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: sandbox
          annotations:
            reloader.stakater.com/auto: "true"
        spec:
          selector:
            matchLabels:
              app: sandbox
          replicas: 1
          template:
            metadata:
              labels:
                app: sandbox
              annotations:
                sidecar.istio.io/inject: "false"
            spec:
              containers:
                - name: sandbox
                  image: yauritux/busybox-curl
                  command: ['sh', '-c', 'sleep 10000']

                  envFrom:
                    - secretRef:
                        name: sandbox-secret
        ```
    - update Secret (by removing and create new one with fields)
        ```
        kubectl delete secret sandbox-secret; kubectl create secret generic sandbox-secret --from-literal=PASSWORD='super_secret_password'
        ```
    - library detects changes and will reload Pods with new values
- documentation suggested Secret not have to exist before applying Deployment, and annotation will add Secret to the resource after creation, unfortunately, it doesn't work this way, Secret has to exist before and Deployment has to have declared fields from Secret.

**Conclusion**
None of the solutions found fit our case. All presented solutions operate on injection of values from Secret/ConfigMap, however, these fields must be previously declared in the injected resources. The dominant solution is still PodPreset.
