### ISSUE TITLE
Separate flags for specifying resource profile, target platform, network, and certificate handling

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9442]
**Description**
1. Do not use isLocalEnv flag for host aliases. Use: global.minikubeIP instead
Bad example:
```      
      {{ if .Values.global.isLocalEnv }}
      hostAliases:
        - ip: {{ .Values.global.minikubeIP }}
          hostnames:
            - "dex.{{ .Values.global.ingress.domainName }}"
            - "minio.{{ .Values.global.ingress.domainName }}"
      {{ end }}
```
2. Do not use isLocalEnv for setting CPU/memory requests and limits:
Bad example:
```
{{ if .Values.global.isLocalEnv }}
{{tpl (.Files.Get "files/kyma_minikube_istio_control_plane.yaml" | printf "%s" | indent 4) .}}
{{ else }}
{{tpl (.Files.Get "files/kyma_cluster_istio_control_plane.yaml" | printf "%s" | indent 4) .}}
{{ end }}
```
3. Provide a way to specify low resource profile for not minikube deployment. See [installing demo profile](https://istio.io/v1.4/docs/setup/getting-started/#install) in istio as a good example.

**Reasons**

Kyma charts assume that isLocalEnv flag means low resource profile and minikube networking. But it is not true. There are several use cases that should be possible to apply:
1. Local cluster without minikube (k3s or kind) 
2. Regular cluster (GKE, AKS or Gardener) with minimal resource consumption profile
3. Gardener cluster with own domain (own certificate issuer)
4. Local cluster with monitoring enabled

etc.

** Links **
The issue is a result of the agreement from [WG Installation](https://docs.google.com/document/d/19lM_wDLXRV-8rQQ7ZxFtasr6kgGRCwUm0kJaAK3NNik/edit) on 21st July 2020
