### ISSUE TITLE
Optimize observability setup for evaluation profile

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#9689]
**Description**
in regards to https://github.com/kyma-project/kyma/issues/9673 the observability stack should be optimized in the evaluation profile to provide full feature-richness with lowest price.

AC: for all observability components:
- reduce retention times as much as possible
- remove any persistence
- lower memory and cpu so that it might crash with workloads more than 10 but also recovers
- Decide on a profile implementation mechanism with all the teams.
- Implement the chosen mechanism for the observability charts (either on the charts directly or as extra resource).

**Reasons**
EVakkuation must be cheap

**Attachments**

**Comment by clebs** [comment]
### Findings for Monitoring minimal setup:
The minimal viable setup is as follows:
```yaml
  limits:
    cpu: 600m
    memory: 1500Mi
  requests:
    cpu: 150m
    memory: 1000Mi
...
retention: 2h
retentionSize: 1GB
grafana.persistence.enabled: "false"
```

The profile during 2h of stress test was:
![Screenshot 2020-10-19 at 17 29 54](https://user-images.githubusercontent.com/1059661/96476211-3663aa00-1235-11eb-9abb-3e27dba49a5e.png)

From that we can see that the current profile is the minimum viable since there is a spike at start that comes close to the limits. Should we make it less, prometheus would endlessly restart.

**Comment by clebs** [comment]
### Findings for Tracing

The minimal viable setup is as follows:
```yaml
jaeger-operator:
resources:
  limits:
    cpu: 50m
    memory: 100Mi
  requests:
    cpu: 10m
    memory: 40Mi
(...)
jaeger:
  resources:
      limits:
        cpu: 50m
        memory: 60Mi
      requests:
        cpu: 10m
        memory: 40Mi
  storage:
      type: memory
      options:
        (...)
        memory:
          max-traces: 10000
kcproxy:
  resources:
    limits:
      cpu: 50m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 5Mi
```

With this setup, jaeger was stable during 4h running the stress tests generating traces and querying with a limit of 1000 traces. This should be more than enough for a trial.

**Comment by clebs** [comment]
### Findings for Logging
The minimal viable setup is as follows:
```yaml
loki:
  resources:
    limits:
      cpu: 100m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  persistence:
    enabled: false

(...)

fluentbit:
  resources:
    limits:
      cpu: 50m
      memory: 80Mi
    requests:
      cpu: 20m
      memory: 40Mi
```
Loki hits the memory limit after a while when running the stress tests, but after discussing with @hisarbalik, we estimated that the normal usage is far below the pressure that stress tests put the system under:
![Screenshot 2020-10-21 at 14 14 18](https://user-images.githubusercontent.com/1059661/96746571-9b4f0980-13c7-11eb-9625-8cd1ac2043c7.png)

For fluentbit, memory usage is very stable and with this setup more than enough. The CPU usage spikes sometimes when doing very big queries. The effect of CPU throttling on the query is barely noticeable:
![Screenshot 2020-10-21 at 14 13 53](https://user-images.githubusercontent.com/1059661/96746818-dcdfb480-13c7-11eb-94a5-47d7a0682f12.png)

**Comment by clebs** [comment]
### Findings for Kiali
The minimal viable setup is as follows:
```yaml
kiali:
resources:
  limits:
    cpu: 50m
    memory: 70Mi
  requests:
    cpu: 10m
    memory: 20Mi
(...)
operator:
  resources:
    limits:
      cpu: 25m
      memory: 20Mi
    requests:
      cpu: 10m
      memory: 5Mi
(...)
kcproxy:
  resources:
    limits:
      cpu: 600m
      memory: 250Mi
    requests:
      cpu: 20m
      memory: 50Mi
```
For the kiali operator the default settings have not changed since they already have a setup that can't be reduced further. As seen in the evaluation, the operator is already utilizing all resources when using the Kiali UI:
![Screenshot 2020-10-26 at 14 03 49](https://user-images.githubusercontent.com/1059661/97176451-416a8d00-1795-11eb-916e-606e716f5c64.png)

The Kiali CR can be reduced on CPU but not on memory:
![Screenshot 2020-10-26 at 14 05 58](https://user-images.githubusercontent.com/1059661/97177085-37955980-1796-11eb-9808-224738662d1b.png)

Kiali Proxy is very stable and its CPU can also be reduced significantly, memory can't be reduced since it already is close to the limit:
![Screenshot 2020-10-26 at 14 04 27](https://user-images.githubusercontent.com/1059661/97178447-c787d300-1797-11eb-8424-2ba9b759d9c3.png)
