### ISSUE TITLE
Evaluation profile for Istio

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#9759]
**Description**

Support [evaluation profile](#9673) in istio component. Limit request CPU to 10m. I tested istio installation with such settings:
```
istioctl manifest apply --set profile=demo -f config-istio.yaml
```
The config-istio.yaml:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  addonComponents:
    grafana:
      enabled: false
    istiocoredns:
      enabled: false
    kiali:
      enabled: false
    prometheus:
      enabled: false
    tracing:
      enabled: false
  components:
    citadel:
      enabled: false
    cni:
      enabled: false
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    galley:
      enabled: false
```

**Reasons**

Default profile allocates too much CPU and memory for evaluation purpose.

**Attachments**
