### ISSUE TITLE
UAA-activator - lack of Secret during the launch of Job

### ISSUE THREAD

**Issue by jasiu001** [kyma-project/kyma#9782]
**Description**
`uaa-activator` chart (Kyma resource) consist of a few elements, the core element is Job which requires the Secrets to work correctly. In some cases Helm during installation chart installs Job, Job is running but Secret does not exist yet.

**Expected result**
Job is only launched when the Secret from chart exists. 

Find out what are the best practices for Helm to ensure the existence of the Secret for Job that it requires. One of the solution could be mounted Secret to the template Pod in the Job.

**Actual result**
The job which requires Secret is launched despite Secret doesn't exist yet.

**Steps to reproduce**
The case was in a cluster with limited resources. Difficult to reproduce.

**Comment by crabtree** [comment]
We can also include a simple init container that checks if the secret exists. This is doable as the ServiceAccount bound to that Pod already has access rights to get secret.

Example:
```yaml
...
initContainers:
  image: docker-image-with-kubectl
  command: ["sh", "-c"]
  args: ["until kubectl get secret secret-name; do echo waiting for secret; done; echo secret found!"]
...
```
