### ISSUE TITLE
Enable providing multiple services with paths in apirules.

### ISSUE THREAD

**Issue by valentinvieriu** [kyma-project/kyma#9936]
**Description**

We should have the possibility to have a single hostname and multiple paths mapped to various k8s services.
Example:

```yml
apiVersion: networking.k8s.io/v1
kind: APIRule
metadata:
  name: coolapp-ingress-wildcard-host
spec:
  rules:
  - host: "coolapp.bar.com"
    http:
      paths:
      - pathType: Prefix
        path: "/api"
        backend:
          service:
            name: customApiService
            port:
              number: 80
      - pathType: Prefix
        path: "/login"
        backend:
          service:
            name: loginService
            port:
              number: 80
      - pathType: Prefix
        path: "/.*"
        backend:
          service:
            name: staticWebsiteService
            port:
              number: 80
```

**Acceptance criteria**

- [x] [POC] expose multiple svc under same virtual host](https://github.com/kyma-project/kyma/issues/14421)
- [x] [api-gateway implementation](https://github.com/kyma-incubator/api-gateway/issues/140)
- [x] [documentation](https://github.com/kyma-project/kyma/issues/14882)
- [x] [tutorial explaining configuration scenarios](https://github.com/kyma-project/kyma/issues/14887)
- [x] [Kyma Dashboard reflecting changes](https://github.com/kyma-project/busola/issues/1767)
- [x] release notes
- [x] [automated test](https://github.com/kyma-project/kyma/issues/14890)

**Reasons**

For Single Page Applications, this will be a very simple way to consume services, without worrying about CORS overhead and also about how to pass the API endpoints as configurations to the SPA.
This is also a good practice that is used by other vendors like Firebase, and Vercel to expose and consume serverless functions to the SPA
