### ISSUE TITLE
Performance Test RoundTrip

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#9997]
**Description**

collect performance metrics for our BEB based eventing in skr

**Reason**
As a kyma user i want to get some rough estimate how many events i am able to send to and process on a managed kyma cluster.

**Acceptance Criteria**
- [ ] Workload connected to BEB using webhook and secured using oauth
- [ ] event generation can be done on a developers machine (optional)
- [x] documented: number of applications, webhooks, number of events / sec

Ready to be implemented as soon as BEB RestAPI team allows us to run those tests

**Comment by marcobebway** [comment]
### Description

Performance evaluation for Kyma Eventing with NATS as a messaging backend was done in four phases:


1. Tune the Eventing and Load-Test-Suite container resources to sustain the load.
2. Measure how the current implementation will perform under load.
3. Fix OMM errors and crashes.
4. Measure after applying the fixes.
---

#### 1. Tune the Eventing and Load-Test-Suite container resources to sustain the load

**istio-proxy**

```yaml
resources:
  limits:
    cpu: 300m
    memory: 1024Mi
  requests:
    cpu: 200m
    memory: 512Mi
```

**nats-controller**

```yaml
containers:
  - name: nats-controller
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
```

**nats-publisher**

```yaml
containers:
  - name: event-publisher-nats
    resources:
      limits:
        cpu: 300m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 256Mi
```

**nats-server**

```yaml
containers:
  - name: nats
    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 250m
        memory: 256Mi
```

---

#### 2. Measure how the current implementation will perform under load

Despite of scaling the NATS publisher horizontally, it was eventually killed with OMM errors. And as a result of that, a lot of messages were failed to be sent. In addition, a lot of messages were failed to be delivered, which also means that the NATS controller (dispatcher) cannot perform well under load.

Sending 75 Events per second for 60 seconds:

- nats-controller (1 replica)
- nats-publisher (1 replica)
- nats-server (1 replica)

Sending 150 Events per second for 60 seconds:

- nats-controller (1 replica)
- nats-publisher (2 replica)
- nats-server (1 replica)

Sending 250 Events per second for 60 seconds:

- nats-controller (1 replica)
- nats-publisher (3 replica)
- nats-server (1 replica)

---

#### 3. Fix OMM errors and crashes

- [NATS publisher fixes](https://github.com/kyma-project/kyma/pull/10723)
- [NATS controller/dispatcher fixes](https://github.com/kyma-project/kyma/pull/10729)

---

#### 4. Measure after applying the fixes

The OMM errors were fixed for the NATS Publisher and it was not crashing anymore. Also the NATS controller (dispatcher) was able to deliver more messages from NATS server to subscribers.

> Note: we did not scale the NATS Publisher nor the controller (dispatcher).

Sending 200 Events per second for 60 seconds:

- nats-controller (1 replica)
- nats-publisher (1 replica)
- nats-server (1 replica)

Sending 400 Events per second for 60 seconds:

- nats-controller (1 replica)
- nats-publisher (1 replica)
- nats-server (1 replica)

With the same setup as above, we ran the Load-Test-Suite for 10 hours with 400 Events per second. Although the NATS Publisher and Dispatcher did not crash, but there was a lot of messages lost. Since a lot of factors can contribute to this, we decided to investigate this more thoroughly later.

---

#### Future work

- We need to profile the Eventing components and act on the results.
- Make the Load-Test-Suite to be more resilient.
